-- Db_Membership: 20 tables. Generated by vendor/_tools/export.mjs from sys.* catalog (SQL Server dialect).

-- rows: 20200
CREATE TABLE [dbo].[Mem_ActiveCode] (
  [ApplicationId] nvarchar(256) NULL,
  [ActiveCode] varchar(50) NOT NULL,
  [BeginActivityDate] datetime NULL,
  [EndActivityDate] datetime NULL,
  [IsOpen] int NULL,
  [Company] varchar(50) NULL,
  CONSTRAINT [PK_Mem_ActiveCode] PRIMARY KEY CLUSTERED ([ActiveCode])
);

-- rows: 6
CREATE TABLE [dbo].[Mem_Application] (
  [ApplicationName] nvarchar(256) NULL,
  [LowerApplicationName] nvarchar(256) NULL,
  [ApplicationId] nvarchar(20) NOT NULL,
  [Description] nvarchar(256) NULL,
  [IsOpen] bit NULL CONSTRAINT [DF_Mem_Application_IsOpen] DEFAULT (0),
  CONSTRAINT [PK_MEM_APPLICATION] PRIMARY KEY CLUSTERED ([ApplicationId])
);

-- rows: 6
CREATE TABLE [dbo].[Mem_Application_Sub] (
  [id] int IDENTITY(1,1) NOT NULL,
  [ApplicationId] nvarchar(50) NULL,
  [SubName] nvarchar(256) NULL,
  [SubId] nvarchar(50) NULL,
  [IsOpen] bit NULL,
  [Description] nvarchar(50) NULL
);

-- rows: 3
CREATE TABLE [dbo].[Mem_Code] (
  [id] int IDENTITY(1,1) NOT NULL,
  [code] varchar(50) NOT NULL,
  [codenumber] bigint NULL,
  [info] varchar(50) NULL
);

-- rows: 117
CREATE TABLE [dbo].[Mem_Module] (
  [Id] int IDENTITY(1,1) NOT NULL,
  [ApplicationId] nvarchar(20) NULL,
  [ModuleId] int NOT NULL,
  [ModuleName] varchar(256) NULL,
  [ParModuleId] int NULL,
  [AddTime] datetime NULL CONSTRAINT [DF_Mem_Module_AddTime] DEFAULT (getdate()),
  [Description] nvarchar(256) NULL,
  CONSTRAINT [PK_MEM_MODULE] PRIMARY KEY CLUSTERED ([ModuleId])
);

-- rows: 0
CREATE TABLE [dbo].[Mem_Paths] (
  [ApplicationId] nvarchar(20) NULL,
  [PathId] nvarchar(256) NOT NULL,
  [Path] nvarchar(256) NULL,
  [LoweredPath] nvarchar(256) NULL,
  CONSTRAINT [PK_MEM_PATHS] PRIMARY KEY CLUSTERED ([PathId])
);

-- rows: 0
CREATE TABLE [dbo].[Mem_ResetPwd] (
  [UserId] int NOT NULL,
  [SaleEntry] uniqueidentifier NULL,
  [GetTime] datetime NULL CONSTRAINT [DF_Mem_ResetPwd_GetTime] DEFAULT (getdate()),
  [IsActived] bit NULL CONSTRAINT [DF_Mem_ResetPwd_IsActived] DEFAULT ((0)),
  [ApplicationId] int NULL
);

-- rows: 153
CREATE TABLE [dbo].[Mem_Right] (
  [Id] int IDENTITY(1,1) NOT NULL,
  [ApplicationId] nvarchar(256) NULL,
  [ModuleId] int NULL,
  [RightsName] varchar(256) NULL,
  [RightsId] int NULL,
  [RightsDes] varchar(256) NULL,
  [AddTime] datetime NULL CONSTRAINT [DF_Mem_Right_AddTime] DEFAULT (getdate())
);

-- rows: 12
CREATE TABLE [dbo].[Mem_Roles] (
  [ApplicationId] nvarchar(50) NULL,
  [RoleId] int NULL,
  [RoleName] nvarchar(256) NULL,
  [LowerRoleName] nvarchar(256) NULL,
  [Description] nvarchar(256) NULL
);

-- rows: 6
CREATE TABLE [dbo].[Mem_UserInfo] (
  [ApplicationId] nvarchar(20) NULL,
  [UserId] nvarchar(256) NULL,
  [Password] nvarchar(128) NULL,
  [PasswordFormat] int NULL,
  [PasswordSalt] nvarchar(128) NULL,
  [MobilePIN] nvarchar(16) NULL,
  [Email] nvarchar(256) NULL,
  [LowerEmail] nvarchar(256) NULL,
  [PasswordQuestion] nvarchar(256) NULL,
  [PasswordAnswer] nvarchar(128) NULL,
  [IsApproved] bit NULL,
  [IsLockedOut] bit NULL,
  [CreateDate] datetime NULL,
  [LastLoginDate] datetime NULL,
  [LastPasswordChangeDate] datetime NULL,
  [LastLockoutDate] datetime NULL,
  [FailedPasswordAttemptCount] int NULL,
  [FailedPasswordAttemptWindowStart] datetime NULL,
  [FailedPasswordAnswerAttemptCount] int NULL,
  [FailedPasswordAnswerAttemptWindowstart] datetime NULL,
  [Comment] ntext NULL,
  [UserSex] bit NULL
);

-- rows: 0
CREATE TABLE [dbo].[Mem_UserRight] (
  [Id] int IDENTITY(1,1) NOT NULL,
  [ApplicationId] nvarchar(256) NULL,
  [UserID] varchar(256) NULL,
  [RightsId] int NULL,
  [AddTime] datetime NULL
);

-- rows: 6
CREATE TABLE [dbo].[Mem_Users] (
  [ApplicationId] nvarchar(20) NULL,
  [UserId] nvarchar(256) NULL,
  [UserName] nvarchar(256) NULL,
  [LowerName] nvarchar(256) NULL,
  [MobileAlias] nvarchar(200) NULL,
  [IsAnonymous] bit NULL,
  [LastActivityDate] datetime NULL,
  [LoginTime] int NULL
);

-- rows: 3
CREATE TABLE [dbo].[Mem_Users_Save] (
  [id] int IDENTITY(1,1) NOT NULL,
  [User_Type] varchar(50) NULL
);

-- rows: 0
CREATE TABLE [dbo].[Mem_UsersInRoles] (
  [UserID] int NULL,
  [RoleID] int NULL
);

-- rows: 2694
CREATE TABLE [dbo].[Pay_Card] (
  [id] int IDENTITY(1,1) NOT NULL,
  [CardId] varchar(20) NULL,
  [IsValues] int NULL,
  [IsOpen] int NULL,
  [MustMoney] numeric(18,0) NULL,
  [GamePoint] int NULL,
  [ApplicationId] varchar(10) NULL,
  [CardPassword] varchar(20) NULL,
  [BeginDay] datetime NULL,
  [EndDay] datetime NULL,
  [OrderId] varchar(20) NULL,
  [PayId] varchar(50) NULL,
  [PayDateTime] datetime NOT NULL CONSTRAINT [DF_Pay_Card_PayDateTime] DEFAULT (getdate())
);
CREATE UNIQUE NONCLUSTERED INDEX [IX_Pay_Card] ON [dbo].[Pay_Card] ([CardId]);

-- rows: 0
CREATE TABLE [dbo].[Pay_Exchange] (
  [Id] int NULL,
  [OrderId] varchar(100) NULL,
  [UserId] varchar(50) NULL,
  [LastMoney] int NULL,
  [OutPoint] int NULL,
  [ResultPoint] int NULL,
  [EnterIp] varchar(50) NULL,
  [EnterTime] datetime NULL,
  [EnterServer] varchar(50) NULL,
  [EnterUserId] varchar(50) NULL,
  [Remark] varchar(200) NULL
);

-- rows: 0
CREATE TABLE [dbo].[Pay_History] (
  [Id] int NULL,
  [Order_Id] varchar(20) NULL,
  [Money] numeric(18,2) NULL,
  [User_Id] varchar(50) NULL,
  [Enter_Ip] varchar(20) NULL,
  [Enter_Time] datetime NULL,
  [Pay_Info] varchar(100) NULL
);

-- rows: 45
CREATE TABLE [dbo].[Pay_Info] (
  [id] int IDENTITY(1,1) NOT NULL,
  [OrderId] varchar(20) NOT NULL,
  [OrderNumbers] int NULL,
  [OrderMoney] numeric(18,0) NULL,
  [PayUserId] varchar(50) NULL,
  [EnterIp] varchar(50) NULL,
  [EnterDate] datetime NULL,
  [BuyInfo] varchar(200) NULL,
  [IsPass] int NULL,
  [UserId] varchar(50) NULL,
  [LastDateTime] datetime NULL,
  [PayWay] varchar(20) NULL,
  CONSTRAINT [PK_Pay_Info] PRIMARY KEY CLUSTERED ([OrderId])
);

-- rows: 0
CREATE TABLE [dbo].[Pay_Select] (
  [id] int NULL,
  [PaywayId] varchar(20) NULL,
  [PayName] varchar(200) NULL,
  [IsOpen] bit NULL
);

-- rows: 4
CREATE TABLE [dbo].[Pay_Way] (
  [Id] int IDENTITY(1,1) NOT NULL,
  [WayId] varchar(10) NULL,
  [WayName] varchar(20) NULL,
  [IsOpen] bit NULL CONSTRAINT [DF_Pay_Way_IsOpen] DEFAULT (1)
);

-- Foreign keys
ALTER TABLE [dbo].[Mem_Paths] ADD CONSTRAINT [FK_MEM_PATH_主从表_MEM_APPL] FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[Mem_Application] ([ApplicationId]) ON DELETE NO ACTION ON UPDATE NO ACTION;
