-- Project_Player34: 73 tables. Generated by vendor/_tools/export.mjs from sys.* catalog (SQL Server dialect).

-- rows: 0
CREATE TABLE [dbo].[AASInfo] (
  [UserID] int NOT NULL,
  [Name] nvarchar(50) NOT NULL,
  [IDNumber] nvarchar(50) NOT NULL,
  [State] int NOT NULL,
  CONSTRAINT [PK_AASInfo] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[AchievementData] (
  [UserID] int NOT NULL,
  [AchievementID] int NOT NULL,
  [IsComplete] bit NOT NULL,
  [CompletedDate] datetime NOT NULL,
  CONSTRAINT [PK_AchievementData] PRIMARY KEY CLUSTERED ([UserID], [AchievementID])
);

-- rows: 0
CREATE TABLE [dbo].[Active_Number] (
  [AwardID] nvarchar(50) NOT NULL,
  [ActiveID] int NOT NULL,
  [PullDown] bit NOT NULL CONSTRAINT [DF_Active_Number_PullDown] DEFAULT ((0)),
  [GetDate] datetime NOT NULL CONSTRAINT [DF_Active_Number_GetDate] DEFAULT (getdate()),
  [UserID] int NOT NULL CONSTRAINT [DF_Active_Number_UserID] DEFAULT ((0)),
  [Mark] int NOT NULL CONSTRAINT [DF_Active_Number_Mark] DEFAULT ((0)),
  [GetByBot] bit NULL,
  CONSTRAINT [PK_Active_Number] PRIMARY KEY CLUSTERED ([AwardID])
);

-- rows: 0
CREATE TABLE [dbo].[AdoptPetList] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [PetID] int NOT NULL CONSTRAINT [DF_AdoptPetList_PetID] DEFAULT ((0)),
  [TemplateID] int NOT NULL CONSTRAINT [DF_AdoptPetList_TemplateID] DEFAULT ((0)),
  [Name] nvarchar(2000) NULL,
  [UserID] int NOT NULL CONSTRAINT [DF_AdoptPetList_UserID] DEFAULT ((0)),
  [Attack] int NOT NULL CONSTRAINT [DF_AdoptPetList_Attack] DEFAULT ((0)),
  [Defence] int NOT NULL CONSTRAINT [DF_AdoptPetList_Defence] DEFAULT ((0)),
  [Luck] int NOT NULL CONSTRAINT [DF_AdoptPetList_Luck] DEFAULT ((0)),
  [Agility] int NOT NULL CONSTRAINT [DF_AdoptPetList_Agility] DEFAULT ((0)),
  [Blood] int NOT NULL CONSTRAINT [DF_AdoptPetList_Blood] DEFAULT ((0)),
  [Damage] int NOT NULL CONSTRAINT [DF_AdoptPetList_Damage] DEFAULT ((0)),
  [Guard] int NOT NULL CONSTRAINT [DF_AdoptPetList_Guard] DEFAULT ((0)),
  [AttackGrow] int NOT NULL CONSTRAINT [DF_AdoptPetList_AttackGrow] DEFAULT ((0)),
  [DefenceGrow] int NOT NULL CONSTRAINT [DF_AdoptPetList_DefenceGrow] DEFAULT ((0)),
  [LuckGrow] int NOT NULL CONSTRAINT [DF_AdoptPetList_LuckGrow] DEFAULT ((0)),
  [AgilityGrow] int NOT NULL CONSTRAINT [DF_AdoptPetList_AgilityGrow] DEFAULT ((0)),
  [BloodGrow] int NOT NULL CONSTRAINT [DF_AdoptPetList_BloodGrow] DEFAULT ((0)),
  [DamageGrow] int NOT NULL CONSTRAINT [DF_AdoptPetList_DamageGrow] DEFAULT ((0)),
  [GuardGrow] int NOT NULL CONSTRAINT [DF_AdoptPetList_GuardGrow] DEFAULT ((0)),
  [Level] int NOT NULL CONSTRAINT [DF_AdoptPetList_Level] DEFAULT ((1)),
  [GP] int NOT NULL CONSTRAINT [DF_AdoptPetList_GP] DEFAULT ((0)),
  [MaxGP] int NOT NULL CONSTRAINT [DF_AdoptPetList_MaxGP] DEFAULT ((0)),
  [Hunger] int NOT NULL CONSTRAINT [DF_AdoptPetList_Hunger] DEFAULT ((10000)),
  [PetHappyStar] int NOT NULL CONSTRAINT [DF_AdoptPetList_PetHappyStar] DEFAULT ((3)),
  [MP] int NOT NULL CONSTRAINT [DF_AdoptPetList_MP] DEFAULT ((0)),
  [IsEquip] bit NOT NULL CONSTRAINT [DF_AdoptPetList_IsEquip] DEFAULT ((0)),
  [Place] int NOT NULL CONSTRAINT [DF_AdoptPetList_Place] DEFAULT ((-1)),
  [IsExit] bit NOT NULL CONSTRAINT [DF_AdoptPetList_IsExit] DEFAULT ((1)),
  [IsUse] bit NOT NULL CONSTRAINT [DF_AdoptPetList_IsUse] DEFAULT ((0)),
  [Skill] nvarchar(50) NOT NULL CONSTRAINT [DF_AdoptPetList_Skill] DEFAULT (''),
  [SkillEquip] nvarchar(50) NOT NULL CONSTRAINT [DF_AdoptPetList_SkillEquip] DEFAULT (''),
  CONSTRAINT [PK_Sys_AdoptPetList] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Auction] (
  [AuctionID] int IDENTITY(1,1) NOT NULL,
  [Name] nvarchar(50) NOT NULL,
  [Category] int NOT NULL,
  [AuctioneerID] int NOT NULL,
  [AuctioneerName] nvarchar(50) NOT NULL,
  [ItemID] int NOT NULL,
  [PayType] int NOT NULL,
  [Price] int NOT NULL,
  [Rise] int NOT NULL,
  [Mouthful] int NOT NULL,
  [BeginDate] datetime NOT NULL,
  [ValidDate] int NOT NULL,
  [BuyerID] int NOT NULL,
  [BuyerName] nvarchar(50) NOT NULL,
  [IsExist] bit NOT NULL,
  [TemplateID] int NOT NULL CONSTRAINT [DF_Auction_TemplateID] DEFAULT ((0)),
  [Random] int NOT NULL CONSTRAINT [DF_Auction_Random] DEFAULT ((0)),
  [goodsCount] int NULL CONSTRAINT [DF_Auction_goodsCount] DEFAULT ((0)),
  CONSTRAINT [PK_Auction] PRIMARY KEY CLUSTERED ([AuctionID])
);

-- rows: 0
CREATE TABLE [dbo].[Bag_Init] (
  [ID] int NOT NULL,
  [Sex] int NOT NULL CONSTRAINT [DF_Bag_Init_Sex] DEFAULT ((2)),
  [TemplateID] int NOT NULL,
  [Count] int NOT NULL CONSTRAINT [DF_Bag_Init_Count] DEFAULT ((1)),
  [ValidDate] int NOT NULL CONSTRAINT [DF_Bag_Init_ValidDate] DEFAULT ((0)),
  [StrengthenLevel] int NOT NULL CONSTRAINT [DF_Bag_Init_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_Bag_Init_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_Bag_Init_DefendCompose] DEFAULT ((0)),
  [LuckCompose] int NOT NULL CONSTRAINT [DF_Bag_Init_LuckCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL CONSTRAINT [DF_Bag_Init_AgilityCompose] DEFAULT ((0)),
  [IsBinds] bit NOT NULL CONSTRAINT [DF_Bag_Init_IsBinds] DEFAULT ((0)),
  [BagType] int NOT NULL CONSTRAINT [DF_Bag_Init_BagType] DEFAULT ((-1)),
  [place] int NOT NULL CONSTRAINT [DF_Bag_Init_place] DEFAULT ((-1)),
  CONSTRAINT [PK_Bag_Init] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Charge_Money] (
  [ChargeID] varchar(50) NOT NULL,
  [UserName] nvarchar(200) NOT NULL,
  [Money] int NOT NULL,
  [Date] datetime NOT NULL CONSTRAINT [DF_Charge_Money_Date] DEFAULT (getdate()),
  [CanUse] bit NOT NULL,
  [PayWay] nvarchar(200) NOT NULL CONSTRAINT [DF_Charge_Money_PayWay] DEFAULT ((0)),
  [NeedMoney] decimal(10,2) NOT NULL CONSTRAINT [DF_Charge_Money_NeedMoney] DEFAULT ((0)),
  [IP] nvarchar(50) NULL,
  [NickName] nvarchar(200) NULL,
  CONSTRAINT [PK_Charge_Money_1] PRIMARY KEY CLUSTERED ([ChargeID])
);

-- rows: 0
CREATE TABLE [dbo].[ChickActive_Number] (
  [ActiveCode] nvarchar(100) NOT NULL,
  [UserID] int NOT NULL CONSTRAINT [DF_ChickActive_Number_UserID] DEFAULT ((0)),
  [GetDate] datetime NOT NULL CONSTRAINT [DF_ChickActive_Number_GetDate] DEFAULT (getdate()),
  CONSTRAINT [PK_ChickActive_Number] PRIMARY KEY CLUSTERED ([ActiveCode])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia] (
  [ConsortiaID] int IDENTITY(1,1) NOT NULL,
  [ConsortiaName] nvarchar(200) NOT NULL,
  [Honor] int NOT NULL,
  [CreatorID] int NOT NULL,
  [CreatorName] nvarchar(200) NOT NULL,
  [ChairmanID] int NOT NULL,
  [ChairmanName] nvarchar(200) NOT NULL,
  [Description] nvarchar(1000) NULL,
  [Placard] nvarchar(1000) NULL,
  [Level] int NOT NULL,
  [MaxCount] int NOT NULL,
  [CelebCount] int NOT NULL,
  [BuildDate] datetime NOT NULL,
  [Repute] int NOT NULL CONSTRAINT [DF_Consortia_Repute] DEFAULT ((999999999)),
  [Count] int NOT NULL CONSTRAINT [DF_Consortia_Count] DEFAULT ((0)),
  [IP] nvarchar(50) NOT NULL,
  [Port] int NOT NULL,
  [IsExist] bit NOT NULL,
  [Riches] int NOT NULL CONSTRAINT [DF_Consortia_Riches] DEFAULT ((0)),
  [DeductDate] datetime NOT NULL CONSTRAINT [DF_Consortia_DeductDate] DEFAULT (getdate()),
  [WarnDate] datetime NOT NULL CONSTRAINT [DF_Consortia_WarnDate] DEFAULT (getdate()),
  [LastDayRiches] int NOT NULL CONSTRAINT [DF_Consortia_LastDayRiches] DEFAULT ((0)),
  [AddDayRiches] int NOT NULL CONSTRAINT [DF_Consortia_LastAddRiches] DEFAULT ((0)),
  [LastWeekRiches] int NOT NULL CONSTRAINT [DF_Consortia_LastWeekRiches] DEFAULT ((0)),
  [AddWeekRiches] int NOT NULL CONSTRAINT [DF_Consortia_AddWeekRiches] DEFAULT ((0)),
  [LastDayHonor] int NOT NULL CONSTRAINT [DF_Consortia_LastDayHonor] DEFAULT ((0)),
  [AddDayHonor] int NOT NULL CONSTRAINT [DF_Consortia_AddDayHonor] DEFAULT ((0)),
  [LastWeekHonor] int NOT NULL CONSTRAINT [DF_Consortia_LastWeekHonor] DEFAULT ((0)),
  [AddWeekHonor] int NOT NULL CONSTRAINT [DF_Consortia_AddWeekHonor] DEFAULT ((0)),
  [OpenApply] bit NOT NULL CONSTRAINT [DF_Consortia_OpenApply] DEFAULT ((1)),
  [StoreLevel] int NOT NULL CONSTRAINT [DF_Consortia_StoreLevel] DEFAULT ((0)),
  [SmithLevel] int NOT NULL CONSTRAINT [DF_Consortia_SmithLevel] DEFAULT ((0)),
  [ShopLevel] int NOT NULL CONSTRAINT [DF_Consortia_ShopLevel] DEFAULT ((0)),
  [SkillLevel] int NOT NULL CONSTRAINT [DF_Consortia_SkillLevel] DEFAULT ((0)),
  [Rename] bit NOT NULL CONSTRAINT [DF_Consortia_Rename] DEFAULT ((0)),
  [KickDate] datetime NOT NULL CONSTRAINT [DF_Consortia_KickDate] DEFAULT (((2009)-(1))-(1)),
  [KickCount] int NOT NULL CONSTRAINT [DF_Consortia_KickCount] DEFAULT ((0)),
  [FightPower] int NOT NULL CONSTRAINT [DF_Consortia_FightPower] DEFAULT ((0)),
  [BadgeType] int NOT NULL CONSTRAINT [DF_Consortia_BadgeType] DEFAULT ((0)),
  [BadgeName] nvarchar(50) NULL CONSTRAINT [DF_Consortia_BadgeName] DEFAULT (''),
  [BadgeID] int NOT NULL CONSTRAINT [DF_Consortia_BadgeID] DEFAULT ((0)),
  [BadgeBuyTime] nvarchar(50) NULL,
  [ValidDate] int NOT NULL CONSTRAINT [DF_Consortia_ValidDate] DEFAULT ((0)),
  [consortiaPower] int NOT NULL CONSTRAINT [DF_Consortia_consoritiaPower] DEFAULT ((0)),
  [DateOpenTask] datetime NULL CONSTRAINT [DF_Consortia_DateOpenTask] DEFAULT ('2016-07-07'),
  CONSTRAINT [PK_Consortia] PRIMARY KEY CLUSTERED ([ConsortiaID])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Ally] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Consortia1ID] int NOT NULL,
  [Consortia2ID] int NOT NULL,
  [State] int NOT NULL,
  [Date] datetime NOT NULL CONSTRAINT [DF_Consortia_Ally_Date] DEFAULT (getdate()),
  [ValidDate] int NOT NULL,
  [IsExist] bit NOT NULL,
  CONSTRAINT [PK_Consortia_Ally] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Apply_Ally] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Consortia1ID] int NOT NULL,
  [Consortia2ID] int NOT NULL,
  [Date] datetime NOT NULL CONSTRAINT [DF_Consortia_Apply_Ally_Date] DEFAULT (getdate()),
  [Remark] nvarchar(200) NULL,
  [IsExist] bit NOT NULL,
  [State] int NOT NULL CONSTRAINT [DF_Consortia_Apply_Ally_State] DEFAULT ((0)),
  CONSTRAINT [PK_Consortia_Apply_Ally] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Apply_Users] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ConsortiaID] int NOT NULL,
  [ConsortiaName] nvarchar(200) NULL,
  [UserID] int NOT NULL,
  [UserName] nvarchar(200) NOT NULL,
  [ApplyDate] datetime NOT NULL,
  [Remark] nvarchar(200) NULL,
  [IsExist] bit NOT NULL,
  CONSTRAINT [PK_Consortia_Apply] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Boss] (
  [ConsortiaID] int NOT NULL,
  [typeBoss] int NOT NULL,
  [callBossCount] int NOT NULL,
  [BossLevel] int NOT NULL,
  [Blood] int NOT NULL,
  [LastOpenBoss] datetime NOT NULL,
  [BossOpenTime] datetime NOT NULL,
  CONSTRAINT [PK_Consortia_Boss] PRIMARY KEY CLUSTERED ([ConsortiaID])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Boss_Config] (
  [Level] int NOT NULL,
  [NpcID] int NOT NULL,
  [MissionID] int NOT NULL,
  [AwardID] int NOT NULL,
  [CostRich] int NOT NULL,
  [ProlongRich] int NOT NULL,
  [BossLevel] int NOT NULL,
  CONSTRAINT [PK_Consortia_BossConfig] PRIMARY KEY CLUSTERED ([Level])
);

-- rows: 34
CREATE TABLE [dbo].[Consortia_Buff_Temp] (
  [id] int NOT NULL CONSTRAINT [DF_Consortia_Buff_Temp_id] DEFAULT ((0)),
  [name] nvarchar(50) NULL,
  [descript] nvarchar(250) NULL,
  [type] int NOT NULL CONSTRAINT [DF_Consortia_Buff_Temp_type] DEFAULT ((1)),
  [level] int NOT NULL CONSTRAINT [DF_Consortia_Buff_Temp_level] DEFAULT ((1)),
  [value] int NOT NULL CONSTRAINT [DF_Consortia_Buff_Temp_value] DEFAULT ((1)),
  [riches] int NOT NULL CONSTRAINT [DF_Consortia_Buff_Temp_riches] DEFAULT ((0)),
  [metal] int NOT NULL CONSTRAINT [DF_Consortia_Buff_Temp_metal] DEFAULT ((0)),
  [pic] int NOT NULL CONSTRAINT [DF_Consortia_Buff_Temp_pic] DEFAULT ((0)),
  [group] int NOT NULL CONSTRAINT [DF_Consortia_Buff_Temp_group] DEFAULT ((0)),
  CONSTRAINT [PK_Consortia_Buff_Temp] PRIMARY KEY CLUSTERED ([id])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Buffer] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ConsortiaID] int NULL,
  [BufferID] int NULL,
  [IsOpen] bit NULL,
  [BeginDate] datetime NULL,
  [ValidDate] int NULL,
  [Type] int NULL,
  [Value] int NULL,
  CONSTRAINT [PK_Consortia_Buffer] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Duty] (
  [DutyID] int IDENTITY(1,1) NOT NULL,
  [ConsortiaID] int NOT NULL,
  [Level] int NOT NULL,
  [DutyName] nvarchar(200) NOT NULL,
  [Right] int NOT NULL CONSTRAINT [DF_Consortia_Duty_Right] DEFAULT ((0)),
  [IsExist] bit NOT NULL,
  CONSTRAINT [PK_Consortia_Right] PRIMARY KEY CLUSTERED ([DutyID])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Equip_Control] (
  [ConsortiaID] int NOT NULL,
  [Type] int NOT NULL,
  [Level] int NOT NULL,
  [Riches] int NOT NULL,
  [IsExist] bit NOT NULL,
  CONSTRAINT [PK_Consortia_Equip_Control] PRIMARY KEY CLUSTERED ([ConsortiaID], [Type], [Level])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Event] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ConsortiaID] int NOT NULL,
  [Date] datetime NOT NULL,
  [Type] int NOT NULL CONSTRAINT [DF_Consortia_Event_Type] DEFAULT ((0)),
  [NickName] nvarchar(50) NOT NULL,
  [EventValue] int NOT NULL,
  [ManagerName] nvarchar(100) NULL,
  [IsExist] bit NOT NULL,
  [Remark] nvarchar(1000) NOT NULL,
  CONSTRAINT [PK_Consortia_Event] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Invite_Users] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ConsortiaID] int NOT NULL,
  [ConsortiaName] nvarchar(200) NOT NULL,
  [UserID] int NOT NULL,
  [UserName] nvarchar(200) NOT NULL,
  [InviteID] int NOT NULL,
  [InviteName] nvarchar(200) NOT NULL,
  [InviteDate] datetime NOT NULL,
  [Remark] nvarchar(200) NULL,
  [IsExist] bit NOT NULL,
  CONSTRAINT [PK_Consortia_Invite] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 10
CREATE TABLE [dbo].[Consortia_Level] (
  [Level] int NOT NULL,
  [Riches] int NOT NULL,
  [Deduct] int NOT NULL,
  [NeedGold] int NOT NULL,
  [NeedItem] int NOT NULL,
  [Reward] int NOT NULL,
  [Count] int NOT NULL,
  [StoreRiches] int NOT NULL CONSTRAINT [DF_Consortia_Level_StoreRiches] DEFAULT ((100)),
  [SmithRiches] int NOT NULL CONSTRAINT [DF_Consortia_Level_SmithRiches] DEFAULT ((100)),
  [ShopRiches] int NOT NULL CONSTRAINT [DF_Consortia_Level_ShopRiches] DEFAULT ((100)),
  [BufferRiches] int NOT NULL CONSTRAINT [DF_Consortia_Level_BufferRiches] DEFAULT ((0)),
  [KickMax] int NOT NULL CONSTRAINT [DF_Consortia_Level_KickCount] DEFAULT ((10)),
  [BossCount] int NOT NULL CONSTRAINT [DF_Consortia_Level_BossCount] DEFAULT ((0)),
  CONSTRAINT [PK_Consortia_Level] PRIMARY KEY CLUSTERED ([Level])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Task_Info] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ConsortiaID] int NULL,
  [BeginTime] datetime NULL,
  [Contribution] int NULL,
  [Expirience] int NULL,
  [Offer] int NULL,
  [BuffID] int NULL,
  [Level] int NULL,
  [Riches] int NULL,
  [Time] int NULL,
  [ConditionData] nvarchar(max) NULL,
  [RankTable] nvarchar(max) NULL,
  [IsExist] bit NULL CONSTRAINT [DF_Consortia_Task_Info_IsExist] DEFAULT ((1)),
  CONSTRAINT [PK_Consortia_Task_Info] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Consortia_Users] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ConsortiaID] int NOT NULL,
  [UserID] int NOT NULL,
  [UserName] nvarchar(200) NOT NULL,
  [RatifierID] int NULL,
  [RatifierName] nvarchar(200) NULL,
  [DutyID] int NOT NULL,
  [Remark] nvarchar(2000) NULL,
  [IsBanChat] bit NOT NULL CONSTRAINT [DF_Consortia_Users_IsBanChat] DEFAULT ((0)),
  [IsExist] bit NOT NULL,
  CONSTRAINT [PK_Consortia_Users] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[DailyLogList] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL,
  [UserAwardLog] int NOT NULL CONSTRAINT [DF_DailyLogList_UserAwardLog] DEFAULT ((0)),
  [DayLog] nvarchar(2000) NULL CONSTRAINT [DF_DailyLogList_DayLog] DEFAULT (''),
  [LastDate] datetime NOT NULL CONSTRAINT [DF_DailyLogList_LastDate] DEFAULT (CONVERT([datetime],'17530101',(0))),
  CONSTRAINT [PK_DailyLogList] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[DailyRecordInfo] (
  [UserID] int NOT NULL,
  [Type] int NOT NULL,
  [Value] nvarchar(500) NOT NULL
);

-- rows: 4
CREATE TABLE [dbo].[Fight_Rate] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ServerID] int NOT NULL CONSTRAINT [DF_Fight_Change_Rate_ServerID] DEFAULT ((0)),
  [Rate] int NOT NULL CONSTRAINT [DF_Fight_Change_Rate_Rate] DEFAULT ((0)),
  [BeginDay] datetime NOT NULL,
  [EndDay] datetime NOT NULL,
  [BeginTime] datetime NOT NULL,
  [EndTime] datetime NOT NULL,
  [BoyTemplateID] int NOT NULL,
  [GirlTemplateID] int NOT NULL,
  [SelfCue] nvarchar(200) NULL,
  [EnemyCue] nvarchar(200) NULL,
  [Name] nvarchar(50) NULL,
  CONSTRAINT [PK_Fight_Change_Rate] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Fight_Record] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [PlayBegin] datetime NOT NULL,
  [PlayEnd] datetime NOT NULL,
  [ChangeTeam] int NOT NULL,
  [TeamA] nvarchar(50) NULL,
  [TeamB] nvarchar(50) NULL,
  [MapID] int NOT NULL,
  [RoomType] int NOT NULL,
  [FightName] nvarchar(50) NULL,
  [WinTeam] int NOT NULL,
  CONSTRAINT [PK_Fight_Record] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Game_Commands] (
  [UserID] int NOT NULL,
  [Commands] varchar(255) NOT NULL,
  CONSTRAINT [PK_Game_Commands] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 157
CREATE TABLE [dbo].[Item_Fusion] (
  [FusionID] int IDENTITY(1,1) NOT NULL,
  [Item1] int NOT NULL CONSTRAINT [DF_Item_Fusion_Item1] DEFAULT ((0)),
  [Item2] int NOT NULL CONSTRAINT [DF_Item_Fusion_Item2] DEFAULT ((0)),
  [Item3] int NOT NULL CONSTRAINT [DF_Item_Fusion_Item3] DEFAULT ((0)),
  [Item4] int NOT NULL CONSTRAINT [DF_Item_Fusion_Item4] DEFAULT ((0)),
  [Formula] int NOT NULL CONSTRAINT [DF_Item_Fusion_Formula] DEFAULT ((0)),
  [Reward] int NOT NULL CONSTRAINT [DF_Item_Fusion_Reward] DEFAULT ((0)),
  CONSTRAINT [PK_Item_Fusion] PRIMARY KEY CLUSTERED ([FusionID])
);

-- rows: 30
CREATE TABLE [dbo].[Items_Fusion_List] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [TemplateID] int NOT NULL,
  [Show] int NOT NULL,
  [Real] int NOT NULL,
  CONSTRAINT [PK_Items_Fusion_List] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[LuckStarRankInfo] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL CONSTRAINT [DF_LuckStarRankInfo_UserID] DEFAULT ((0)),
  [useStarNum] int NOT NULL CONSTRAINT [DF_LuckStarRankInfo_useStarNum] DEFAULT ((0)),
  [nickName] nvarchar(150) NULL,
  [isVip] int NOT NULL CONSTRAINT [DF_LuckStarRankInfo_isVip] DEFAULT ((0)),
  CONSTRAINT [PK_LuckStarRankInfo] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Marry_Apply] (
  [UserID] int NOT NULL,
  [ApplyUserID] int NOT NULL,
  [ApplyUserName] nvarchar(50) NOT NULL,
  [ApplyType] int NOT NULL,
  [LoveProclamation] nvarchar(300) NULL,
  [ApplyResult] bit NULL,
  [isExist] bit NOT NULL CONSTRAINT [DF_Marry_Apply_isExist] DEFAULT ((1)),
  [isDeal] bit NOT NULL CONSTRAINT [DF_Marry_Apply_isDeal] DEFAULT ((0)),
  [ID] int IDENTITY(1,1) NOT NULL,
  [ApplyDate] datetime NOT NULL CONSTRAINT [DF__Marry_App__Apply__69FBBC1F] DEFAULT (getdate()),
  CONSTRAINT [PK_Marry_Apply] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Marry_Info] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL,
  [IsPublishEquip] bit NOT NULL,
  [Introduction] nvarchar(120) NULL,
  [RegistTime] datetime NOT NULL,
  [IsExist] bit NOT NULL CONSTRAINT [DF_Marry_Info_IsExist] DEFAULT ((1)),
  CONSTRAINT [PK_Marry_Info] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Marry_Room_Info] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Name] nvarchar(50) NOT NULL,
  [PlayerID] int NOT NULL,
  [PlayerName] nvarchar(50) NULL,
  [GroomID] int NOT NULL,
  [GroomName] nvarchar(50) NULL,
  [BrideID] int NOT NULL,
  [BrideName] nvarchar(50) NULL,
  [Pwd] nvarchar(15) NOT NULL,
  [AvailTime] int NOT NULL,
  [MaxCount] int NOT NULL,
  [GuestInvite] bit NOT NULL,
  [MapIndex] int NOT NULL,
  [BeginTime] datetime NOT NULL,
  [BreakTime] datetime NOT NULL,
  [RoomIntroduction] nvarchar(300) NULL,
  [ServerID] int NOT NULL,
  [IsHymeneal] bit NOT NULL,
  [isExist] bit NOT NULL CONSTRAINT [DF_Marry_Room_Info_isExist] DEFAULT ((1)),
  [IsGunsaluteUsed] bit NOT NULL CONSTRAINT [DF_Marry_Room_Info_IsGunsaluteUsed] DEFAULT ((0)),
  CONSTRAINT [PK_Marry_Room_Info] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[New_ChickenBox_Data] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_UserID] DEFAULT ((0)),
  [TemplateID] int NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_TemplateID] DEFAULT ((0)),
  [Count] int NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_Count] DEFAULT ((0)),
  [ValidDate] int NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_ValidDate] DEFAULT ((0)),
  [StrengthenLevel] int NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_DefendCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL,
  [LuckCompose] int NOT NULL,
  [Position] int NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_Position] DEFAULT ((0)),
  [IsSelected] bit NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_IsSeeded] DEFAULT ((0)),
  [IsSeeded] bit NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_IsBinds] DEFAULT ((0)),
  [IsBinds] bit NOT NULL CONSTRAINT [DF_New_ChickenBox_Data_IsBinds_1] DEFAULT ((1)),
  CONSTRAINT [PK_New_ChickenBox_Data] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[QuestData] (
  [UserID] int NOT NULL,
  [QuestID] int NOT NULL,
  [IsComplete] bit NOT NULL,
  [CompletedDate] datetime NULL,
  [Condition1] int NOT NULL CONSTRAINT [DF_QuestData_Condition1] DEFAULT ((0)),
  [Condition2] int NOT NULL CONSTRAINT [DF_QuestData_Condition2] DEFAULT ((0)),
  [Condition3] int NOT NULL CONSTRAINT [DF_QuestData_Condition3] DEFAULT ((0)),
  [Condition4] int NOT NULL CONSTRAINT [DF_QuestData_Condition4] DEFAULT ((0)),
  [IsExist] bit NOT NULL CONSTRAINT [DF_QuestData_IsExist] DEFAULT ((1)),
  [RepeatFinish] int NOT NULL CONSTRAINT [DF_QuestData_RepeatFinish] DEFAULT ((0)),
  [RandDobule] int NOT NULL CONSTRAINT [DF_QuestData_RandDobule] DEFAULT ((1)),
  CONSTRAINT [PK_QuestData] PRIMARY KEY NONCLUSTERED ([UserID], [QuestID])
);

-- rows: 0
CREATE TABLE [dbo].[Rate] (
  [ServerID] int NOT NULL,
  [Rate] decimal(6,2) NOT NULL,
  [BeginDay] datetime NOT NULL,
  [EndDay] datetime NOT NULL,
  [BeginTime] datetime NOT NULL,
  [EndTime] datetime NOT NULL,
  [Type] int NOT NULL CONSTRAINT [DF_Experience_Rate_Type] DEFAULT ((0))
);

-- rows: 0
CREATE TABLE [dbo].[Rename_Consortia] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ConsortiaID] int NOT NULL,
  [ConsortiaName] nvarchar(200) NOT NULL,
  [NickName] nvarchar(200) NOT NULL,
  [Date] datetime NOT NULL,
  [IsExist] bit NOT NULL,
  CONSTRAINT [PK_Rename_Consortia] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Rename_Nick] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL,
  [UserName] nvarchar(200) NOT NULL,
  [NickName] nvarchar(200) NOT NULL,
  [Date] datetime NOT NULL,
  [IsExist] bit NOT NULL,
  [OldNickName] nvarchar(200) NULL,
  CONSTRAINT [PK_Rename_Nick] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 514
CREATE TABLE [dbo].[Server_Config] (
  [ID] int NOT NULL,
  [Name] nvarchar(50) NOT NULL,
  [Value] nvarchar(2000) NOT NULL,
  CONSTRAINT [PK_Server_Config] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 3
CREATE TABLE [dbo].[Server_Event] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Name] nvarchar(200) NOT NULL,
  [Value] nvarchar(500) NULL,
  CONSTRAINT [PK_Server_Event] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 1
CREATE TABLE [dbo].[Server_List] (
  [ID] int NOT NULL,
  [Name] nvarchar(50) NULL,
  [IP] nvarchar(50) NULL,
  [Port] int NULL CONSTRAINT [DF_Server_List_Port] DEFAULT ((0)),
  [State] int NOT NULL CONSTRAINT [DF_Server_List_State] DEFAULT ((0)),
  [Online] int NOT NULL CONSTRAINT [DF_Server_List_Online] DEFAULT ((0)),
  [Total] int NOT NULL CONSTRAINT [DF_Server_List_Total] DEFAULT ((1000)),
  [Room] int NOT NULL CONSTRAINT [DF_Server_List_Room] DEFAULT ((200)),
  [Remark] nvarchar(200) NULL,
  [RSA] nvarchar(1000) NULL,
  [MustLevel] int NOT NULL CONSTRAINT [DF_Server_List_MustLevel] DEFAULT ((0)),
  [LowestLevel] int NOT NULL CONSTRAINT [DF__Server_Li__Lowes__55167929] DEFAULT ((0)),
  [NewerServer] bit NOT NULL CONSTRAINT [DF_Server_List_NewerServer] DEFAULT ((0)),
  [ZoneId] int NOT NULL CONSTRAINT [DF_Server_List_ZoneId] DEFAULT ((1)),
  [ZoneName] nvarchar(50) NOT NULL CONSTRAINT [DF_Server_List_ZoneName] DEFAULT (N'Server S1'),
  CONSTRAINT [PK_Server_List] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Suit_Manager] (
  [UserID] int NULL,
  [Kill_List] nvarchar(200) NULL
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Active_System_Data] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL CONSTRAINT [DF_Sys_Active_System_Data_UserID] DEFAULT ((0)),
  [canOpenCounts] int NOT NULL CONSTRAINT [DF_Sys_Active_System_Data_canOpenCounts] DEFAULT ((5)),
  [canEagleEyeCounts] int NOT NULL CONSTRAINT [DF_Sys_Active_System_Data_canEagleEyeCounts] DEFAULT ((3)),
  [lastFlushTime] datetime NOT NULL CONSTRAINT [DF_Sys_Active_System_Data_lastFlushTime] DEFAULT (getdate()),
  [isShowAll] bit NOT NULL CONSTRAINT [DF_Sys_Active_System_Data_isShowAll] DEFAULT ((1)),
  [ChickActiveData] nvarchar(max) NOT NULL CONSTRAINT [DF_Sys_Active_System_Data_ChickActiveData] DEFAULT (N'0'),
  [LuckystarCoins] int NOT NULL CONSTRAINT [DF_Sys_Active_System_Data_LuckystarCoins] DEFAULT ((0)),
  [ActiveMoney] int NOT NULL CONSTRAINT [DF_Sys_Active_System_Data_ActiveMoney] DEFAULT ((0))
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Eat_Pets] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL CONSTRAINT [DF_Sys_Eat_Pets_UserID] DEFAULT ((0)),
  [weaponExp] int NOT NULL CONSTRAINT [DF_Sys_Eat_Pets_weaponExp] DEFAULT ((0)),
  [weaponLevel] int NOT NULL CONSTRAINT [DF_Sys_Eat_Pets_weaponLevel] DEFAULT ((0)),
  [clothesExp] int NOT NULL CONSTRAINT [DF_Sys_Eat_Pets_clothesExp] DEFAULT ((0)),
  [clothesLevel] int NOT NULL CONSTRAINT [DF_Sys_Eat_Pets_clothesLevel] DEFAULT ((0)),
  [hatExp] int NOT NULL CONSTRAINT [DF_Sys_Eat_Pets_hatExp] DEFAULT ((0)),
  [hatLevel] int NOT NULL CONSTRAINT [DF_Sys_Eat_Pets_hatLevel] DEFAULT ((0))
);

-- rows: 0
CREATE TABLE [dbo].[Sys_User_Farm] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [FarmID] int NOT NULL,
  [PayFieldMoney] nvarchar(50) NULL,
  [PayAutoMoney] nvarchar(50) NULL,
  [AutoPayTime] datetime NOT NULL CONSTRAINT [DF_Sys_User_Farm_AutoPayTime] DEFAULT (getdate()),
  [AutoValidDate] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_AutoValidDate] DEFAULT ((1)),
  [VipLimitLevel] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_VipLimitLevel] DEFAULT ((0)),
  [FarmerName] nvarchar(50) NULL,
  [GainFieldId] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_GainFieldId] DEFAULT ((0)),
  [MatureId] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_MatureId] DEFAULT ((0)),
  [KillCropId] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_KillCropId] DEFAULT ((0)),
  [isAutoId] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_isAutoId] DEFAULT ((0)),
  [isFarmHelper] bit NOT NULL CONSTRAINT [DF_Sys_User_Farm_isFarmHelper] DEFAULT ((0)),
  [buyExpRemainNum] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_buyExpRemainNum] DEFAULT ((20)),
  [isArrange] bit NOT NULL CONSTRAINT [DF_Sys_User_Farm_isArrange] DEFAULT ((0)),
  [FriendCrop] nvarchar(1000) NULL,
  [TreeLevel] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_TreeLevel] DEFAULT ((0)),
  [TreeExp] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_TreeExp] DEFAULT ((0)),
  [LoveScore] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_LoveScore] DEFAULT ((0)),
  [MonsterExp] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_MonsterExp] DEFAULT ((0)),
  [PoultryState] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_PoultryState] DEFAULT ((0)),
  [CountDownTime] datetime NOT NULL CONSTRAINT [DF_Sys_User_Farm_CountDownTime] DEFAULT (getdate()),
  [TreeCostExp] int NOT NULL CONSTRAINT [DF_Sys_User_Farm_TreeCostExp] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_User_Farm] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_User_Field] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [FarmID] int NOT NULL CONSTRAINT [DF_Sys_User_Field_FarmID] DEFAULT ((0)),
  [FieldID] int NOT NULL CONSTRAINT [DF_Sys_User_Field_FieldID] DEFAULT ((0)),
  [SeedID] int NOT NULL CONSTRAINT [DF_Sys_User_Field_SeedID] DEFAULT ((0)),
  [PlantTime] datetime NOT NULL CONSTRAINT [DF_Sys_User_Field_PlantTime] DEFAULT (getdate()),
  [AccelerateTime] int NOT NULL CONSTRAINT [DF_Sys_User_Field_AccelerateTime] DEFAULT ((0)),
  [FieldValidDate] int NOT NULL CONSTRAINT [DF_Sys_User_Field_FieldValidDate] DEFAULT ((0)),
  [PayTime] datetime NOT NULL CONSTRAINT [DF_Sys_User_Field_PayTime] DEFAULT (getdate()),
  [GainCount] int NOT NULL CONSTRAINT [DF_Sys_User_Field_GainCount] DEFAULT ((10)),
  [AutoSeedID] int NOT NULL CONSTRAINT [DF_Sys_User_Field_AutoSeedID] DEFAULT ((0)),
  [AutoFertilizerID] int NOT NULL CONSTRAINT [DF_Sys_User_Field_AutoFertilizerID] DEFAULT ((0)),
  [AutoSeedIDCount] int NOT NULL CONSTRAINT [DF_Sys_User_Field_AutoSeedIDCount] DEFAULT ((0)),
  [AutoFertilizerCount] int NOT NULL CONSTRAINT [DF_Sys_User_Field_AutoFertilizerCount] DEFAULT ((0)),
  [isAutomatic] bit NOT NULL CONSTRAINT [DF_Sys_User_Field_isAutomatic] DEFAULT ((0)),
  [AutomaticTime] datetime NOT NULL CONSTRAINT [DF_Sys_User_Field_AutomaticTime] DEFAULT (getdate()),
  [IsExit] bit NOT NULL CONSTRAINT [DF_Sys_User_Field_IsExit] DEFAULT ((0)),
  [payFieldTime] int NOT NULL CONSTRAINT [DF_Sys_User_Field_payFieldTime] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_User_Field] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_User_Gemstone] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL,
  [FigSpiritId] int NOT NULL CONSTRAINT [DF_Sys_User_Gemstone_FigSpiritId] DEFAULT ((0)),
  [FigSpiritIdValue] nvarchar(50) NOT NULL CONSTRAINT [DF_Sys_User_Gemstone_FigSpiritIdValue] DEFAULT ('0,0,0|0,0,1|0,0,2'),
  [EquipPlace] int NOT NULL CONSTRAINT [DF_Sys_User_Gemstone_EquipPlace] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_User_Gemstone] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_User_Info] (
  [UserID] int NOT NULL,
  [UserEmail] nvarchar(255) NULL,
  [UserPhone] nvarchar(50) NULL,
  [UserOther1] nvarchar(50) NULL,
  [UserOther2] nvarchar(50) NULL,
  [UserOther3] nvarchar(50) NULL,
  CONSTRAINT [PK_Sys_User_Info] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_User_Match_Info] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL,
  [dailyScore] int NOT NULL,
  [dailyWinCount] int NOT NULL,
  [dailyGameCount] int NOT NULL,
  [weeklyScore] int NOT NULL,
  [weeklyRanking] int NOT NULL,
  [weeklyGameCount] int NOT NULL,
  [DailyLeagueFirst] bit NOT NULL CONSTRAINT [DF__Sys_User___Daily__5E4BA8FF] DEFAULT ((0)),
  [DailyLeagueLastScore] int NOT NULL CONSTRAINT [DF__Sys_User___Daily__5F3FCD38] DEFAULT ((0)),
  [addDayPrestge] int NOT NULL CONSTRAINT [DF__Sys_User___addDa__6033F171] DEFAULT ((0)),
  [totalPrestige] int NOT NULL CONSTRAINT [DF__Sys_User___total__612815AA] DEFAULT ((0)),
  [restCount] int NOT NULL CONSTRAINT [DF__Sys_User___restC__621C39E3] DEFAULT ((0)),
  [leagueItemsGet] int NOT NULL CONSTRAINT [DF__Sys_User___leagu__63105E1C] DEFAULT ((0)),
  [leagueGrade] int NOT NULL CONSTRAINT [DF__Sys_User___leagu__64048255] DEFAULT ((0)),
  [eliteScore] int NOT NULL CONSTRAINT [DF__Sys_User___elite__64F8A68E] DEFAULT ((0)),
  [eliteRank] int NOT NULL CONSTRAINT [DF__Sys_User___elite__65ECCAC7] DEFAULT ((0)),
  [WeeklyWinCount] int NOT NULL CONSTRAINT [DF_Sys_User_Match_Info_WeeklyWinCount] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_Users_Math] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_User_Rank] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL CONSTRAINT [DF_Sys_Users_Ranks_UserID] DEFAULT ((0)),
  [UserRank] nvarchar(500) NULL,
  [Attack] int NOT NULL CONSTRAINT [DF_Sys_Users_Ranks_Attack] DEFAULT ((0)),
  [Defence] int NOT NULL CONSTRAINT [DF_Sys_Users_Ranks_Defence] DEFAULT ((0)),
  [Luck] int NOT NULL CONSTRAINT [DF_Sys_Users_Ranks_Luck] DEFAULT ((0)),
  [Agility] int NOT NULL CONSTRAINT [DF_Sys_Users_Ranks_Agility] DEFAULT ((0)),
  [HP] int NOT NULL CONSTRAINT [DF_Sys_Users_Ranks_HP] DEFAULT ((0)),
  [Damage] int NOT NULL CONSTRAINT [DF_Sys_Users_Ranks_Damage] DEFAULT ((0)),
  [Guard] int NOT NULL CONSTRAINT [DF_Sys_Users_Ranks_Guard] DEFAULT ((0)),
  [BeginDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Rank_EndDate] DEFAULT (getdate()),
  [Validate] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Validate] DEFAULT ((0)),
  [IsExit] bit NOT NULL CONSTRAINT [DF_Sys_Users_Rank_IsExit] DEFAULT ((0)),
  [NewTitleID] int NOT NULL CONSTRAINT [DF_Sys_User_Rank_NewTitleID] DEFAULT ((0)),
  [EndDate] datetime NOT NULL CONSTRAINT [DF_Sys_User_Rank_EndDate] DEFAULT (getdate()),
  [Name] nvarchar(500) NULL,
  CONSTRAINT [PK_Sys_Users_Ranks] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_AvatarCollection] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [AvatarID] int NOT NULL,
  [UserID] int NOT NULL,
  [Sex] int NOT NULL,
  [IsActive] bit NOT NULL CONSTRAINT [DF_Sys_Users_AvatarCollection_IsActive] DEFAULT ((0)),
  [Data] nvarchar(500) NULL,
  [TimeStart] datetime NULL CONSTRAINT [DF_Sys_Users_AvatarCollection_TimeStart] DEFAULT (getdate()),
  [TimeEnd] datetime NULL CONSTRAINT [DF_Sys_Users_AvatarCollection_TimeEnd] DEFAULT (getdate()),
  [IsExit] bit NOT NULL CONSTRAINT [DF_Sys_Users_AvatarCollection_IsExit] DEFAULT ((1)),
  CONSTRAINT [PK_Sys_Users_AvatarCollection_1] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Card] (
  [CardID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL,
  [TemplateID] int NOT NULL,
  [Place] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_Place] DEFAULT ((0)),
  [Count] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_Count] DEFAULT ((0)),
  [Attack] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_Attack] DEFAULT ((0)),
  [Defence] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_Defence] DEFAULT ((0)),
  [Agility] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_Agility] DEFAULT ((0)),
  [Luck] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_Luck] DEFAULT ((0)),
  [Guard] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_Guard] DEFAULT ((0)),
  [AttackReset] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_AttackReset] DEFAULT ((0)),
  [DefenceReset] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_DefenceReset] DEFAULT ((0)),
  [AgilityReset] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_AgilityReset] DEFAULT ((0)),
  [LuckReset] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_LuckReset] DEFAULT ((0)),
  [Damage] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_Damage] DEFAULT ((0)),
  [Level] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_Level] DEFAULT ((0)),
  [CardGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Card_CardGP] DEFAULT ((0)),
  [isFirstGet] bit NOT NULL CONSTRAINT [DF_Sys_Users_Card_isFirstGet] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_Users_Card] PRIMARY KEY CLUSTERED ([CardID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_DanhHieu] (
  [Id] int IDENTITY(1,1) NOT NULL,
  [Template] int NULL,
  [UserRank] nvarchar(250) NULL,
  [Attack] int NULL CONSTRAINT [DF_Sys_Users_DanhHieu_Attack] DEFAULT ((0)),
  [Defence] int NULL CONSTRAINT [DF_Sys_Users_DanhHieu_Defence] DEFAULT ((0)),
  [Luck] int NULL,
  [Agility] int NULL CONSTRAINT [DF_Sys_Users_DanhHieu_Agility] DEFAULT ((0)),
  [HP] int NULL CONSTRAINT [DF_Sys_Users_DanhHieu_HP] DEFAULT ((0)),
  [Damage] int NULL CONSTRAINT [DF_Sys_Users_DanhHieu_Damage] DEFAULT ((0)),
  [Guard] int NULL CONSTRAINT [DF_Sys_Users_DanhHieu_Guard] DEFAULT ((0)),
  [Validate] int NULL CONSTRAINT [DF_Sys_Users_DanhHieu_Validate] DEFAULT ((0))
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Detail] (
  [UserID] int IDENTITY(1,1) NOT NULL,
  [UserName] nvarchar(200) NULL,
  [Password] nvarchar(200) NULL,
  [NickName] nvarchar(50) NULL,
  [Date] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Date] DEFAULT (getdate()),
  [IsConsortia] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsConsortia] DEFAULT ((0)),
  [ConsortiaID] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_ConsortiaID] DEFAULT ((0)),
  [Sex] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Sex] DEFAULT ((1)),
  [Win] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Win] DEFAULT ((0)),
  [Total] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Total] DEFAULT ((0)),
  [Escape] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Escape] DEFAULT ((0)),
  [GP] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_GP] DEFAULT ((0)),
  [Honor] nvarchar(50) NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Honor] DEFAULT (N'Guerreiro'),
  [Gold] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Gold] DEFAULT ((0)),
  [Money] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Money] DEFAULT ((0)),
  [MoneyLock] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_MoneyLock] DEFAULT ((0)),
  [Style] nvarchar(200) NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Stype] DEFAULT (N',,,,,,'),
  [Colors] nvarchar(200) NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Colors] DEFAULT (N',,,,,,'),
  [Hide] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Hide] DEFAULT ((1111111111)),
  [Grade] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Grade] DEFAULT ((1)),
  [State] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_State] DEFAULT ((0)),
  [IsFirst] int NOT NULL,
  [Repute] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Repute] DEFAULT ((0)),
  [LastDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastDate] DEFAULT (getdate()),
  [ChargeDate] datetime NULL,
  [ExpendDate] datetime NULL,
  [ActiveIP] nvarchar(50) NULL,
  [ForbidDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_ForbidDate] DEFAULT (getdate()),
  [Skin] nvarchar(50) NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Skin] DEFAULT (''),
  [Offer] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Offer] DEFAULT ((0)),
  [IsExist] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsExist] DEFAULT ((1)),
  [ReputeOffer] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_ReputeOffer] DEFAULT ((0)),
  [LastDateSecond] datetime NULL,
  [LastDateThird] datetime NULL,
  [LoginCount] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LoginCount] DEFAULT ((0)),
  [OnlineTime] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_OnlineTime] DEFAULT ((0)),
  [AntiAddiction] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_AntiAddiction] DEFAULT ((0)),
  [AntiDate] datetime NULL,
  [RichesOffer] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_RichesOffer] DEFAULT ((0)),
  [RichesRob] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_RichesRob] DEFAULT ((0)),
  [UseOffer] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_UseOffer] DEFAULT ((0)),
  [LastDayGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastDayGP] DEFAULT ((0)),
  [AddDayGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_AddDayGP] DEFAULT ((0)),
  [LastWeekGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastWeekGP] DEFAULT ((0)),
  [AddWeekGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_AddWeekGP] DEFAULT ((0)),
  [LastDayOffer] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastDayOffer] DEFAULT ((0)),
  [AddDayOffer] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_AddDayOffer] DEFAULT ((0)),
  [LastWeekOffer] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastWeekOffer] DEFAULT ((0)),
  [AddWeekOffer] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_AddWeekOffer] DEFAULT ((0)),
  [CheckCount] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_CheckCount] DEFAULT ((0)),
  [Site] nvarchar(200) NULL,
  [IsMarried] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsMarried] DEFAULT ((0)),
  [SpouseID] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_SpouseID] DEFAULT ((0)),
  [SpouseName] nvarchar(50) NULL,
  [MarryInfoID] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_MarryInfoID] DEFAULT ((0)),
  [DayLoginCount] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_DayLoginCount] DEFAULT ((0)),
  [ForbidReason] nvarchar(1000) NULL,
  [IsCreatedMarryRoom] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsCreatedMarryRoom] DEFAULT ((0)),
  [PasswordTwo] nvarchar(200) NULL,
  [SelfMarryRoomID] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_SelfMarryRoomID] DEFAULT ((0)),
  [IsGotRing] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsGotRing] DEFAULT ((0)),
  [ServerName] nvarchar(50) NULL,
  [Rename] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Rename] DEFAULT ((0)),
  [Nimbus] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Nimbus_1] DEFAULT ((0)),
  [LastAward] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastAward] DEFAULT (((2009)-(1))-(1)),
  [GiftToken] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_GiftToken] DEFAULT ((0)),
  [QuestSite] varbinary(8000) NOT NULL CONSTRAINT [DF_Sys_Users_Detail_QuestSite] DEFAULT (0x),
  [PvePermission] nvarchar(50) NULL,
  [FightLabPermission] nvarchar(50) NULL CONSTRAINT [DF_Sys_Users_Detail_FightLabPermission] DEFAULT ('10000000000'),
  [FightPower] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_FightPower] DEFAULT ((0)),
  [AnswerSite] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_AnswerSite] DEFAULT ((0)),
  [LastAuncherAward] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastAuncherAward] DEFAULT (((2009)-(1))-(1)),
  [WeaklessGuildProgressStr] nvarchar(max) NOT NULL CONSTRAINT [DF_Sys_Users_Detail_WeaklessGuildProgressStr] DEFAULT (N'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
  [AchievementPoint] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_AchievementPoint] DEFAULT ((0)),
  [IsShowConsortia] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsShowConsortia] DEFAULT ((0)),
  [OptionOnOff] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_OptionOnOff] DEFAULT ((0)),
  [badgeID] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_badgeID] DEFAULT ((0)),
  [IsRecharged] bit NULL CONSTRAINT [DF_Sys_Users_Detail_IsRecharged] DEFAULT ((0)),
  [IsGetAward] bit NULL CONSTRAINT [DF_Sys_Users_Detail_IsGetAward] DEFAULT ((0)),
  [MoneyPlus] int NULL CONSTRAINT [DF_Sys_Users_Detail_MoneyPlus] DEFAULT ((0)),
  [evolutionGrade] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_evolutionGrade] DEFAULT ((0)),
  [evolutionExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_evolutionExp] DEFAULT ((0)),
  [hardCurrency] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_hardCurrency] DEFAULT ((0)),
  [EliteScore] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_EliteScore] DEFAULT ((0)),
  [CanSentMoney] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_CanSentMoney] DEFAULT ((0)),
  [apprenticeshipState] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_apprenticeshipState] DEFAULT ((0)),
  [masterID] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_masterID] DEFAULT ((0)),
  [masterOrApprentices] nvarchar(500) NULL CONSTRAINT [DF_Sys_Users_Detail_masterOrApprentices] DEFAULT (N''),
  [graduatesCount] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_graduatesCount] DEFAULT ((0)),
  [honourOfMaster] nvarchar(500) NULL CONSTRAINT [DF_Sys_Users_Detail_honourOfMaster] DEFAULT (N''),
  [freezesDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_freezesDate] DEFAULT (getdate()),
  [ShopFinallyGottenTime] datetime NULL CONSTRAINT [DF_Sys_Users_Detail_ShopFinallyGottenTime] DEFAULT ('2016-08-07'),
  [charmGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_charmGP] DEFAULT ((0)),
  [Medal] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Medal] DEFAULT ((0)),
  [ChatCount] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_ChatCount] DEFAULT ((0)),
  [SpaPubGoldRoomLimit] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_SpaPubGoldRoomLimit] DEFAULT ((0)),
  [LastSpaDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastSpaDate] DEFAULT (getdate()),
  [IsInSpaPubGoldToday] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsInSpaPubGoldToday] DEFAULT ((0)),
  [IsInSpaPubMoneyToday] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsInSpaPubMoneyToday] DEFAULT ((0)),
  [LastWeekly] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastWeekly] DEFAULT (getdate()),
  [LastWeeklyVersion] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastWeeklyVersion] DEFAULT ((0)),
  [IsOldPlayer] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsOldPlayer] DEFAULT ((0)),
  [Score] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_Score] DEFAULT ((0)),
  [isOldPlayerHasValidEquitAtLogin] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_isOldPlayerHasValidEquitAtLogin] DEFAULT ((0)),
  [badLuckNumber] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_badLuckNumber] DEFAULT ((0)),
  [luckyNum] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_luckyNum] DEFAULT ((0)),
  [lastLuckyNumDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_lastLuckyNumDate] DEFAULT (getdate()),
  [lastLuckNum] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_lastLuckNum] DEFAULT ((0)),
  [NewDay] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_NewDay] DEFAULT (getdate()),
  [BoxGetDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_BoxGetDate] DEFAULT (getdate()),
  [AlreadyGetBox] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_AlreadyGetBox] DEFAULT ((0)),
  [BoxProgression] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_BoxProgression] DEFAULT ((0)),
  [GetBoxLevel] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_GetBoxLevel] DEFAULT ((0)),
  [AddWeekLeagueScore] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_AddWeekLeagueScore] DEFAULT ((0)),
  [WeekLeagueRanking] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_WeekLeagueRanking] DEFAULT ((0)),
  [SpaPubMoneyRoomLimit] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_SpaPubMoneyRoomLimit] DEFAULT ((0)),
  [LastGetEgg] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastGetEgg] DEFAULT (((2009)-(1))-(1)),
  [IsFistGetPet] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsFistGetPet] DEFAULT ((1)),
  [LastRefreshPet] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Detail_LastRefreshPet] DEFAULT (getdate()),
  [petScore] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_petScore] DEFAULT ((0)),
  [accumulativeLoginDays] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_accumulativeLoginDays] DEFAULT ((0)),
  [accumulativeAwardDays] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_accumulativeAwardDays] DEFAULT ((0)),
  [honorId] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_honorId] DEFAULT ((0)),
  [damageScores] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_damageScores] DEFAULT ((0)),
  [totemId] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_totemId_1] DEFAULT ((0)),
  [myHonor] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_myHonor_1] DEFAULT ((0)),
  [MaxBuyHonor] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_MaxBuyHonor_1] DEFAULT ((0)),
  [necklaceExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_necklaceExp] DEFAULT ((0)),
  [necklaceExpAdd] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_necklaceExpAdd] DEFAULT ((0)),
  [GhostEquipList] nvarchar(max) NULL,
  [fineSuitExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_fineSuitExp] DEFAULT ((0)),
  [CountPVP] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_CountPVP] DEFAULT ((1)),
  [IsSMG] bit NOT NULL CONSTRAINT [DF_Sys_Users_Detail_IsSMG] DEFAULT ((0)),
  [FightLimit] int NOT NULL CONSTRAINT [DF_Sys_Users_Detail_FightLimit] DEFAULT ((1)),
  CONSTRAINT [PK_Sys_Users_Detail] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_EventProcess] (
  [UserID] int NOT NULL,
  [ActiveType] int NOT NULL,
  [Conditions] int NOT NULL CONSTRAINT [DF_Sys_Users_EventProcess_Conditions] DEFAULT ((0)),
  [AwardGot] int NOT NULL CONSTRAINT [DF_Sys_Users_EventProcess_AwardGot] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_Users_EventProcess] PRIMARY KEY CLUSTERED ([UserID], [ActiveType])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Extra] (
  [UserID] int NOT NULL,
  [LastTimeHotSpring] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Extra_LastTimeHotSpring] DEFAULT (getdate()),
  [LastFreeTimeHotSpring] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Extra_LastFreeTimeHotSpring] DEFAULT (getdate()),
  [MinHotSpring] int NOT NULL CONSTRAINT [DF_Sys_Users_Extra_MinHotSpring] DEFAULT ((60)),
  [LastTimeConsortiaPower] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Extra_LastTimeConsortiaPower] DEFAULT (getdate()),
  [coupleBossEnterNum] int NOT NULL CONSTRAINT [DF_Sys_Users_Extra_coupleBossEnterNum] DEFAULT ((0)),
  [coupleBossHurt] int NOT NULL CONSTRAINT [DF_Sys_Users_Extra_coupleBossHurt] DEFAULT ((0)),
  [coupleBossBoxNum] int NOT NULL CONSTRAINT [DF_Sys_Users_Extra_coupleBossTakeAward] DEFAULT ((0)),
  [TotalCaddyOpen] int NOT NULL CONSTRAINT [DF_Sys_Users_Extra_TotalCaddyOpen] DEFAULT ((0)),
  [isGetAwardMarry] bit NOT NULL CONSTRAINT [DF_Sys_Users_Extra_isGetAwardMarry] DEFAULT ((0)),
  [isFirstAwardMarry] bit NOT NULL CONSTRAINT [DF_Sys_Users_Extra_isFirstAwardMarry] DEFAULT ((0)),
  [LastGetEgg] datetime NULL,
  [PassWarriorArena] int NOT NULL CONSTRAINT [DF_Sys_Users_Extra_PassWarriorArena] DEFAULT ((0)),
  [LeftRoutteCount] int NULL,
  [LeftRoutteRate] float NULL,
  [FreeSendMailCount] int NOT NULL CONSTRAINT [DF_Sys_Users_Extra_FreeSendMailCount] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_Users_Extra] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Fight] (
  [UserID] int NOT NULL,
  [Attack] int NOT NULL CONSTRAINT [DF_Sys_Users_Fight_Attck] DEFAULT ((0)),
  [Defence] int NOT NULL CONSTRAINT [DF_Sys_Users_Fight_Recovery] DEFAULT ((0)),
  [Luck] int NOT NULL CONSTRAINT [DF_Sys_Users_Fight_Luck] DEFAULT ((0)),
  [Agility] int NOT NULL CONSTRAINT [DF_Sys_Users_Fight_Celerity] DEFAULT ((0)),
  [HP] int NOT NULL CONSTRAINT [DF_Sys_Users_Fight_HP] DEFAULT ((0)),
  [Delay] int NOT NULL CONSTRAINT [DF_Sys_Users_Fight_Delay] DEFAULT ((0)),
  [Honor] nvarchar(200) NULL,
  [Map] nvarchar(50) NULL,
  [Directory] nvarchar(50) NULL,
  [IsExist] bit NOT NULL CONSTRAINT [DF_Sys_Users_Fight_IsExist] DEFAULT ((1)),
  CONSTRAINT [PK_Sys_Users_Fight_1] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Friends] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL,
  [FriendID] int NOT NULL,
  [AddDate] datetime NULL CONSTRAINT [DF_Sys_Users_Friends_AddDate] DEFAULT (getdate()),
  [Remark] nvarchar(200) NULL,
  [IsExist] bit NOT NULL CONSTRAINT [DF_Sys_Users_Friends_IsExist] DEFAULT ((1)),
  [Relation] int NOT NULL CONSTRAINT [DF_Sys_Users_Friends_Relation] DEFAULT ((0)),
  CONSTRAINT [PK_User_Friends] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Gift] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [SenderID] int NOT NULL,
  [ReceiverID] int NOT NULL,
  [TemplateID] int NOT NULL,
  [Count] int NOT NULL,
  [CreateDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Gift_CreateDate] DEFAULT (getdate()),
  [LastUpdate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Gift_LastUpdate] DEFAULT (getdate()),
  CONSTRAINT [PK_Sys_Users_Gift] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Goods] (
  [ItemID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_UserID] DEFAULT ((0)),
  [BagType] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_PageType] DEFAULT ((0)),
  [TemplateID] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_GoodsID] DEFAULT ((0)),
  [Place] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Place] DEFAULT ((100)),
  [Count] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Count] DEFAULT ((1)),
  [IsJudge] bit NOT NULL CONSTRAINT [DF_Sys_Users_Goods_IsJudge] DEFAULT ((1)),
  [Color] nvarchar(50) NULL,
  [IsExist] bit NOT NULL CONSTRAINT [DF_Sys_Users_Goods_IsExist] DEFAULT ((1)),
  [StrengthenLevel] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_StrengthenLevel] DEFAULT ((0)),
  [StrengthenExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_StrengthenExp] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_DefendCompose] DEFAULT ((0)),
  [LuckCompose] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_LcukCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_AgilityCompose] DEFAULT ((0)),
  [Skin] nvarchar(50) NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Skin] DEFAULT (''),
  [IsBinds] bit NOT NULL CONSTRAINT [DF_Sys_Users_Goods_IsBinds] DEFAULT ((0)),
  [IsUsed] bit NOT NULL CONSTRAINT [DF_Sys_Users_Goods_IsUsed] DEFAULT ((0)),
  [BeginDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Goods_BeginDate] DEFAULT (((2008)-(10))-(11)),
  [ValidDate] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_ValidDate] DEFAULT ((10)),
  [RemoveDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Goods_RemoveTime] DEFAULT (getdate()),
  [RemoveType] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_RemoveType] DEFAULT ((0)),
  [Hole1] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole1] DEFAULT ((-1)),
  [Hole2] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole2] DEFAULT ((-1)),
  [Hole3] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole3] DEFAULT ((-1)),
  [Hole4] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole4] DEFAULT ((-1)),
  [Hole5] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole5] DEFAULT ((-1)),
  [Hole6] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole6] DEFAULT ((-1)),
  [Hole5Level] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole5Level] DEFAULT ((0)),
  [Hole5Exp] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole5Exp] DEFAULT ((0)),
  [Hole6Level] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole6Level] DEFAULT ((0)),
  [Hole6Exp] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Hole6Exp] DEFAULT ((0)),
  [StrengthenTimes] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_StrengthenTimes] DEFAULT ((0)),
  [StrengthenRefineryLevel] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_RefineryLevel] DEFAULT ((0)),
  [isGold] bit NOT NULL CONSTRAINT [DF_Sys_Users_Goods_isGold] DEFAULT ((0)),
  [goldValidDate] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_goldValidDate] DEFAULT ((0)),
  [goldBeginTime] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Goods_goldBeginTime] DEFAULT (getdate()),
  [Blood] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_Bloot] DEFAULT ((0)),
  [latentEnergyCurStr] nvarchar(50) NOT NULL CONSTRAINT [DF_Sys_Users_Goods_latentEnergyCurStr] DEFAULT (N'0,0,0,0'),
  [latentEnergyNewStr] nvarchar(50) NOT NULL CONSTRAINT [DF_Sys_Users_Goods_latentEnergyNewStr] DEFAULT (N'0,0,0,0'),
  [latentEnergyEndTime] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Goods_latentEnergyEndTime] DEFAULT (getdate()),
  [curExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Goods_curExp] DEFAULT ((0)),
  [cellLocked] bit NOT NULL CONSTRAINT [DF_Sys_Users_Goods_cellLocked] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_Users_Goods] PRIMARY KEY CLUSTERED ([ItemID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Labyrinth] (
  [UserID] int NOT NULL,
  [myProgress] int NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_myProgress] DEFAULT ((0)),
  [myRanking] int NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_myRanking] DEFAULT ((0)),
  [completeChallenge] bit NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_completeChallenge] DEFAULT ((0)),
  [isDoubleAward] bit NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_isDoubleAward] DEFAULT ((1)),
  [currentFloor] int NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_currentFloor] DEFAULT ((0)),
  [accumulateExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_accumulateExp] DEFAULT ((0)),
  [remainTime] int NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_remainTime] DEFAULT ((0)),
  [currentRemainTime] int NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_currentRemainTime] DEFAULT ((0)),
  [cleanOutAllTime] int NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_cleanOutAllTime] DEFAULT ((0)),
  [cleanOutGold] int NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_cleanOutGold] DEFAULT ((0)),
  [tryAgainComplete] bit NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_tryAgainComplete] DEFAULT ((0)),
  [isInGame] bit NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_isInGame] DEFAULT ((0)),
  [isCleanOut] bit NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_isCleanOut] DEFAULT ((0)),
  [serverMultiplyingPower] bit NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_serverMultiplyingPower] DEFAULT ((0)),
  [LastDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_LastDate] DEFAULT (getdate()),
  [ProcessAward] nvarchar(2000) NOT NULL CONSTRAINT [DF_Sys_Users_Labyrinth_ProcessAward] DEFAULT ((-1)),
  CONSTRAINT [PK_Sys_Users_Labyrinth] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_League] (
  [UserID] int NOT NULL,
  [RankID] int NOT NULL CONSTRAINT [DF_Sys_Users_League_RankID] DEFAULT ((1)),
  [Point] int NOT NULL CONSTRAINT [DF_Sys_Users_League_Point] DEFAULT ((0)),
  [Win] int NOT NULL CONSTRAINT [DF_Sys_Users_League_Win] DEFAULT ((0)),
  [Lose] int NOT NULL CONSTRAINT [DF_Sys_Users_League_Lose] DEFAULT ((0)),
  [IsBanned] bit NOT NULL CONSTRAINT [DF_Sys_Users_League_IsBanned] DEFAULT ((0)),
  [ForbidDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_League_ForbidDate] DEFAULT (getdate()),
  [ForbidReason] nvarchar(500) NOT NULL CONSTRAINT [DF_Sys_Users_League_ForbidReason] DEFAULT (N'Không Có'),
  [ID] int IDENTITY(1,1) NOT NULL,
  CONSTRAINT [PK_Sys_Users_League] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Log] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [UserID] int NOT NULL,
  [UserName] nvarchar(100) NOT NULL,
  [NickName] nvarchar(100) NOT NULL,
  [Type] nvarchar(50) NULL,
  [Content] nvarchar(500) NULL,
  [TimeCreate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Log_TimeCreate] DEFAULT (getdate()),
  CONSTRAINT [PK_Sys_Users_Log] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Order] (
  [UserID] int NOT NULL,
  [Repute] int NOT NULL CONSTRAINT [DF_Sys_User_Order_Repute] DEFAULT ((0)),
  [ReputeOffer] int NOT NULL CONSTRAINT [DF_Sys_User_Order_ReputeOffer] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_Users_Order] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Password] (
  [UserID] int NOT NULL,
  [PasswordQuestion1] nvarchar(50) NULL,
  [PasswordAnswer1] nvarchar(50) NULL,
  [PasswordQuestion2] nvarchar(50) NULL,
  [PasswordAnswer2] nvarchar(50) NULL,
  [LastFindDate] datetime NULL,
  [FailedPasswordAttemptCount] int NULL CONSTRAINT [DF_Sys_Users_Password_FailedPasswordAttemptCount] DEFAULT ((5)),
  CONSTRAINT [PK_Sys_Users_Password] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Pet] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [TemplateID] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_TemplateID] DEFAULT ((0)),
  [Name] nvarchar(2000) NULL,
  [UserID] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_UserID] DEFAULT ((0)),
  [Attack] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Attack] DEFAULT ((0)),
  [Defence] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Defence] DEFAULT ((0)),
  [Luck] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Luck] DEFAULT ((0)),
  [Agility] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Agility] DEFAULT ((0)),
  [Blood] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Blood] DEFAULT ((0)),
  [Damage] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Damage] DEFAULT ((0)),
  [Guard] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Guard] DEFAULT ((0)),
  [AttackGrow] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_AttackGrow] DEFAULT ((0)),
  [DefenceGrow] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_DefenceGrow] DEFAULT ((0)),
  [LuckGrow] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_LuckGrow] DEFAULT ((0)),
  [AgilityGrow] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_AgilityGrow] DEFAULT ((0)),
  [BloodGrow] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_BloodGrow] DEFAULT ((0)),
  [DamageGrow] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_DamageGrow] DEFAULT ((0)),
  [GuardGrow] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_GuardGrow] DEFAULT ((0)),
  [Level] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Level] DEFAULT ((1)),
  [GP] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_GP] DEFAULT ((0)),
  [MaxGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_MaxGP] DEFAULT ((55)),
  [Hunger] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Hunger] DEFAULT ((10000)),
  [PetHappyStar] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_PetHappyStar] DEFAULT ((3)),
  [MP] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_MP] DEFAULT ((0)),
  [IsEquip] bit NOT NULL CONSTRAINT [DF_Sys_Users_Pet_IsEquip] DEFAULT ((0)),
  [Place] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_Place] DEFAULT ((-1)),
  [IsExit] bit NOT NULL CONSTRAINT [DF_Sys_Users_Pet_IsExit] DEFAULT ((0)),
  [Skill] nvarchar(max) NULL,
  [SkillEquip] nvarchar(max) NULL,
  [currentStarExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_currentStarExp] DEFAULT ((0)),
  [breakGrade] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_breakGrade] DEFAULT ((-1)),
  [breakAttack] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_breakAttack] DEFAULT ((0)),
  [breakDefence] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_breakDefence] DEFAULT ((0)),
  [breakAgility] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_breakAgility] DEFAULT ((0)),
  [breakLuck] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_breakLuck] DEFAULT ((0)),
  [breakBlood] int NOT NULL CONSTRAINT [DF_Sys_Users_Pet_breakBlood] DEFAULT ((0)),
  [eQPets] nvarchar(max) NOT NULL CONSTRAINT [DF_Sys_Users_Pet_eQPets] DEFAULT (N'[]'),
  [BaseProp] nvarchar(max) NOT NULL CONSTRAINT [DF_Sys_Users_Pet_BaseProp] DEFAULT (N''),
  CONSTRAINT [PK_Sys_Users_Pet] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Rank_Date] (
  [UserID] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_UserID] DEFAULT ((0)),
  [ConsortiaID] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_ConsortiaID] DEFAULT ((0)),
  [FightPower] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_FightPower] DEFAULT ((0)),
  [PrevFightPower] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_PrevFightPower] DEFAULT ((0)),
  [GP] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_GP] DEFAULT ((0)),
  [PrevGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_PrevGP] DEFAULT ((0)),
  [AchievementPoint] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_AchievementPoint] DEFAULT ((0)),
  [PrevAchievementPoint] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_PrevAchievementPoint] DEFAULT ((0)),
  [charmGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_charmGP] DEFAULT ((0)),
  [PrecharmGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_PrecharmGP] DEFAULT ((0)),
  [LeagueAddWeek] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_LeagueAddWeek] DEFAULT ((0)),
  [PrevLeagueAddWeek] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_PrevLeagueAddWeek] DEFAULT ((0)),
  [ConsortiaFightPower] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_ConsortiaFightPower] DEFAULT ((0)),
  [ConsortiaPrevFightPower] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_ConsortiaPrevFightPower] DEFAULT ((0)),
  [ConsortiaLevel] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_ConsortiaLevel] DEFAULT ((0)),
  [ConsortiaPrevLevel] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_ConsortiaPrevLevel] DEFAULT ((0)),
  [ConsortiaRiches] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_ConsortiaRiches] DEFAULT ((0)),
  [ConsortiaPrevRiches] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_ConsortiaPrevRiches] DEFAULT ((0)),
  [ConsortiacharmGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_ConsortiacharmGP] DEFAULT ((0)),
  [ConsortiaPrevcharmGP] int NOT NULL CONSTRAINT [DF_Sys_Users_Rank_Date_ConsortiaPrecharmGP] DEFAULT ((0))
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Record] (
  [UserID] int NOT NULL,
  [RecordID] int NOT NULL CONSTRAINT [DF_Sys_Users_Record_RecordID] DEFAULT ((0)),
  [Total] int NOT NULL CONSTRAINT [DF_Sys_Users_Record_Total] DEFAULT ((0))
);

-- rows: 0
CREATE TABLE [dbo].[Sys_Users_Texp] (
  [UserID] int NOT NULL,
  [spdTexpExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Texp_spdTexpExp] DEFAULT ((0)),
  [attTexpExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Texp_attTexpExp] DEFAULT ((0)),
  [defTexpExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Texp_defTexpExp] DEFAULT ((0)),
  [hpTexpExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Texp_hpTexpExp] DEFAULT ((0)),
  [lukTexpExp] int NOT NULL CONSTRAINT [DF_Sys_Users_Texp_lukTexpExp] DEFAULT ((0)),
  [texpTaskCount] int NOT NULL CONSTRAINT [DF_Sys_Users_Texp_texpTaskCount] DEFAULT ((0)),
  [texpCount] int NOT NULL CONSTRAINT [DF_Sys_Users_Texp_texpCount] DEFAULT ((0)),
  [texpTaskDate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_Texp_texpTaskDate] DEFAULT (getdate()),
  CONSTRAINT [PK_Sys_Users_Texp] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[Sys_VIP_Info] (
  [UserID] int IDENTITY(1,1) NOT NULL,
  [typeVIP] int NOT NULL CONSTRAINT [DF_Sys_Users_VIP_typeVIP] DEFAULT ((0)),
  [VIPLevel] int NOT NULL CONSTRAINT [DF_Sys_Users_VIP_VIPLevel] DEFAULT ((0)),
  [VIPExp] int NOT NULL CONSTRAINT [DF_Sys_Users_VIP_VIPExp] DEFAULT ((0)),
  [VIPOnlineDays] int NOT NULL CONSTRAINT [DF_Sys_Users_VIP_VIPOnlineDays] DEFAULT ((0)),
  [VIPOfflineDays] int NOT NULL CONSTRAINT [DF_Sys_Users_VIP_VIPOfflineDays] DEFAULT ((0)),
  [VIPExpireDay] datetime NOT NULL CONSTRAINT [DF_Sys_Users_VIP_VIPExpireDay] DEFAULT (getdate()),
  [LastVIPPackTime] datetime NOT NULL CONSTRAINT [DF_Sys_Users_VIP_LastVIPPackTime] DEFAULT (getdate()),
  [VIPLastdate] datetime NOT NULL CONSTRAINT [DF_Sys_Users_VIP_VIPLastdate] DEFAULT (getdate()),
  [VIPNextLevelDaysNeeded] int NOT NULL CONSTRAINT [DF_Sys_Users_VIP_VIPNextLevelDaysNeeded] DEFAULT ((0)),
  [CanTakeVipReward] bit NOT NULL CONSTRAINT [DF_Sys_Users_VIP_CanTakeVipReward] DEFAULT ((0)),
  CONSTRAINT [PK_Sys_Users_VIP] PRIMARY KEY CLUSTERED ([UserID])
);

-- rows: 0
CREATE TABLE [dbo].[User_Buff] (
  [UserID] int NOT NULL,
  [Type] int NOT NULL,
  [Value] int NOT NULL,
  [BeginDate] datetime NOT NULL,
  [ValidDate] int NOT NULL,
  [TemplateID] int NOT NULL CONSTRAINT [DF_User_Buff_TemplateID] DEFAULT ((0)),
  [ValidCount] int NOT NULL CONSTRAINT [DF_User_Buff_ValidCount] DEFAULT ((0)),
  [Data] nvarchar(200) NULL,
  [IsExist] bit NOT NULL,
  CONSTRAINT [PK_User_Buff] PRIMARY KEY CLUSTERED ([UserID], [Type])
);

-- rows: 0
CREATE TABLE [dbo].[User_Messages] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [SenderID] int NOT NULL CONSTRAINT [DF_User_Messages_SenderID] DEFAULT ((0)),
  [Sender] nvarchar(50) NULL,
  [ReceiverID] int NOT NULL CONSTRAINT [DF_User_Messages_ReceiverID] DEFAULT ((0)),
  [Receiver] nvarchar(50) NULL,
  [Title] nvarchar(500) NULL,
  [Content] nvarchar(2000) NULL,
  [SendTime] datetime NOT NULL CONSTRAINT [DF__User_Mess__SendT__1ABEEF0B] DEFAULT (getdate()),
  [IsRead] bit NOT NULL CONSTRAINT [DF__User_Mess__isRea__1BB31344] DEFAULT ((0)),
  [IsDelR] bit NOT NULL CONSTRAINT [DF__User_Mess__isDel__1CA7377D] DEFAULT ((0)),
  [IfDelS] bit NOT NULL CONSTRAINT [DF__User_Mess__ifDel__1D9B5BB6] DEFAULT ((0)),
  [IsDelete] bit NOT NULL CONSTRAINT [DF__User_Mess__isDel__1E8F7FEF] DEFAULT ((0)),
  [Annex1] nvarchar(50) NULL,
  [Annex2] nvarchar(50) NULL,
  [Gold] int NOT NULL CONSTRAINT [DF_User_Messages_Gold] DEFAULT ((0)),
  [Money] int NOT NULL CONSTRAINT [DF_User_Messages_Money] DEFAULT ((0)),
  [IsExist] bit NOT NULL CONSTRAINT [DF_User_Messages_IsExist] DEFAULT ((1)),
  [Type] int NOT NULL CONSTRAINT [DF_User_Messages_Type] DEFAULT ((0)),
  [Remark] nvarchar(200) NULL,
  [ValidDate] int NOT NULL CONSTRAINT [DF_User_Messages_ValidDate] DEFAULT ((240)),
  [Annex1Name] nvarchar(50) NULL,
  [Annex2Name] nvarchar(50) NULL,
  [SendDate] datetime NOT NULL CONSTRAINT [DF_User_Messages_SendDate] DEFAULT (getdate()),
  [Annex3] nvarchar(50) NULL,
  [Annex4] nvarchar(50) NULL,
  [Annex5] nvarchar(50) NULL,
  [Annex3Name] nvarchar(50) NULL,
  [Annex4Name] nvarchar(50) NULL,
  [Annex5Name] nvarchar(50) NULL,
  [AnnexRemark] nvarchar(200) NULL,
  [GiftToken] int NOT NULL CONSTRAINT [DF_User_Messages_GiftToken] DEFAULT ((0)),
  CONSTRAINT [PK_User_Messages] PRIMARY KEY CLUSTERED ([ID])
);

