"""Compare client (AS3) write sequences with server (C#) read sequences per top-level packet code.
Heuristic (branches are flattened on both sides) — use it to find candidates to inspect by hand.

Usage: python compare_formats.py -> out/format-check.md
"""
import json
import os

OUT = os.path.join(os.path.dirname(__file__), "out")
cs = json.load(open(os.path.join(OUT, "client-sends.json"), encoding="utf-8"))
hs = json.load(open(os.path.join(OUT, "handlers.json"), encoding="utf-8"))

CMAP = {"Int": "I", "UnsignedInt": "I", "Byte": "B", "Boolean": "Z", "UTF": "S", "Short": "H", "Double": "D", "Number": "D", "Float": "F", "Bytes": "X", "Date": "T"}
SMAP = {"Int": "I", "Int32": "I", "Byte": "B", "Boolean": "Z", "String": "S", "Short": "H", "Double": "D", "Float": "F", "Bytes": "X", "DateTime": "T", "Long": "L"}


def ctypes(writes):
    return "".join(CMAP.get(w.split("(")[0], "?") for w in writes)


def stypes(reads):
    out = ""
    for r in reads:
        t = r.split(" ")[0].split("(")[0]
        out += SMAP.get(t, "?")
    return out


def main():
    srv = {}
    for h in hs:
        if h["group"] == "client" and h["code"] is not None:
            srv.setdefault(h["code"], []).append(h)
    cli = {}
    for c in cs:
        if c["code"] is not None:
            cli.setdefault(c["code"], []).append(c)
    L = ["# Client write vs server read format check (generated by compare_formats.py)\n",
         "Legend: I=int32 B=byte Z=bool S=UTF string H=int16 D=double T=date X=bytes ?=unknown. "
         "`=` prefix match, `!` mismatch. Sub-dispatched codes (94,129,68,81,102,166,191,249,160...) compare only the first fields.\n",
         "| Code | Server handler | Server reads | Client function | Client writes | Verdict |", "|---|---|---|---|---|---|"]
    only_client = sorted(set(cli) - set(srv))
    only_server = sorted(set(srv) - set(cli))
    for code in sorted(set(cli) & set(srv)):
        for h in srv[code]:
            st = stypes(h["reads"])
            for c in cli[code]:
                ct = ctypes(c["writes"])
                if st == ct:
                    v = "ok"
                elif ct.startswith(st) or st.startswith(ct):
                    v = "= prefix"
                else:
                    v = "! mismatch"
                L.append(f"| {code} | {h['class']} | `{st}` | `{c['func']}` | `{ct}` | {v} |")
    L.append("\n## Codes the client sends but no Game.Server handler is registered (silently dropped)\n")
    for code in only_client:
        fns = ", ".join(f"`{c['func']}`" for c in cli[code])
        L.append(f"- {code}: {fns}")
    L.append("\n## Server handlers never sent by this client build\n")
    for code in only_server:
        L.append(f"- {code}: {', '.join(h['class'] for h in srv[code])}")
    open(os.path.join(OUT, "format-check.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("client-only", len(only_client), "server-only", len(only_server))


if __name__ == "__main__":
    main()
