"""List every *Mgr / *Manager class in the lobby-side projects (plus Game.Logic data
managers that Game.Server boots), with the Bussiness methods each one calls and the
stored procedures those resolve to (via out/bussiness-procs.json).

Usage: python docs/spec/server/tools/extract_managers.py   (run extract_bussiness.py first)
Writes docs/spec/server/tools/out/managers.md
"""
import json
import os
import re
from cslib import read, rel, strip_comments, classes, methods, walk

OUT = os.path.join(os.path.dirname(__file__), "out")
procs = json.load(open(os.path.join(OUT, "bussiness-procs.json"), encoding="utf-8"))
proc_by = {}
for r in procs:
    proc_by.setdefault(f'{r["class"]}.{r["method"]}', []).extend(p for _, p in r["calls"])

DIRS = ["Game.Server", "Bussiness/Managers", "Center.Server", "Game.Logic"]


def buss_calls(body):
    vars_ = {}
    for m in re.finditer(r"\b(\w+Bussiness)\s+(\w+)\s*=\s*new\s+\w+Bussiness\s*\(", body):
        vars_[m.group(2)] = m.group(1)
    for m in re.finditer(r"\b(?:var)\s+(\w+)\s*=\s*new\s+(\w+Bussiness)\s*\(", body):
        vars_[m.group(1)] = m.group(2)
    out = []
    for v, t in vars_.items():
        for m in re.finditer(r"\b" + re.escape(v) + r"\.(\w+)\s*\(", body):
            x = f"{t}.{m.group(1)}"
            if x not in out and m.group(1) != "Dispose":
                out.append(x)
    for m in re.finditer(r"new\s+(\w+Bussiness)\s*\(\s*\)\s*\)?\s*\.(\w+)\s*\(", body):
        x = f"{m.group(1)}.{m.group(2)}"
        if x not in out:
            out.append(x)
    return out


def main():
    lines = ["# Managers -> Bussiness -> stored procedures (generated by extract_managers.py)\n",
             "Methods named Init/Setup/Start/ReLoad/Load* are the boot/reload cache loaders.\n"]
    for f in walk(DIRS):
        src = strip_comments(read(f))
        for attrs, cname, body in classes(src):
            if not re.search(r"(Mgr|Manager)$", cname):
                continue
            ms = list(methods(body))
            if not ms:
                continue
            lines.append(f"\n## {cname} (`{rel(f)}`)\n")
            timers = re.findall(r"new\s+(?:System\.Threading\.|System\.Timers\.)?Timer\s*\(([^;]*)\)", body)
            if timers:
                lines.append("Timers: " + "; ".join(" ".join(t.split()) for t in timers) + "\n")
            lines.append("| Method | Bussiness calls | Stored procedures |")
            lines.append("|---|---|---|")
            for name, rt, params, mb, off in ms:
                bc = buss_calls(mb)
                if not bc and not re.match(r"(Init|Setup|Start|Stop|ReLoad|Reload|Load)", name):
                    continue
                pr = []
                for b in bc:
                    for p in proc_by.get(b, []):
                        if p not in pr:
                            pr.append(p)
                lines.append(f"| `{name}({params})` | {', '.join(bc)} | {', '.join('`'+p+'`' for p in pr)} |")
    with open(os.path.join(OUT, "managers.md"), "w", encoding="utf-8") as fo:
        fo.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
