"""Ground truth for client->server formats: scan the AS3 client source
(vendor/DDTank41/Source Flash/src) for `new PackageOut(CODE)` and the following
writeXxx calls in the same function. Resolves `XxxPackageType.CONST` via all
`public static const NAME:int = N;` declarations.

Usage: python extract_client_sends.py -> out/client-sends.md / .json
"""
import json
import os
import re
from cslib import ROOT

SRC = os.path.join(ROOT, "Source Flash", "src")
OUT = os.path.join(os.path.dirname(__file__), "out")
CONST_RE = re.compile(r"public\s+static\s+const\s+(\w+)\s*:\s*int\s*=\s*(-?\w+)\s*;")
FUNC_RE = re.compile(r"(?:public|private|protected|internal)?\s*(?:static\s+)?function\s+(\w+)\s*\(([^)]*)\)[^{]*\{")
PKG_RE = re.compile(r"new\s+PackageOut\s*\(\s*([\w\.]+)\s*(?:,\s*([^)]*))?\)")
W_RE = re.compile(r"\b(\w+)\.(write(?:Int|Byte|Boolean|UTF|Short|Double|Float|Bytes|UnsignedInt|Date|Number)\w*)\s*\(([^;]*)\)\s*;")


def brace_end(s, i):
    d = 0
    while i < len(s):
        if s[i] == "{":
            d += 1
        elif s[i] == "}":
            d -= 1
            if d == 0:
                return i
        i += 1
    return len(s)


def main():
    consts = {}
    files = []
    for dp, dn, fn in os.walk(SRC):
        for f in fn:
            if f.endswith(".as"):
                p = os.path.join(dp, f)
                files.append(p)
                cls = f[:-3]
                try:
                    s = open(p, encoding="utf-8", errors="replace").read()
                except OSError:
                    continue
                for m in CONST_RE.finditer(s):
                    try:
                        consts[f"{cls}.{m.group(1)}"] = int(m.group(2), 0)
                    except ValueError:
                        pass
    rows = []
    for p in files:
        s = open(p, encoding="utf-8", errors="replace").read()
        if "PackageOut" not in s:
            continue
        for fm in FUNC_RE.finditer(s):
            end = brace_end(s, fm.end() - 1)
            body = s[fm.end():end]
            pm = PKG_RE.search(body)
            if not pm:
                continue
            code_expr = pm.group(1)
            code = consts.get(code_expr)
            if code is None:
                try:
                    code = int(code_expr, 0)
                except ValueError:
                    code = None
            writes = []
            for obj, fn, arg in W_RE.findall(body[pm.end():]):
                a = " ".join(arg.split())
                a = re.sub(r"^(\w+)\.(\w+)$", lambda m: f"{m.group(0)}={consts[m.group(0)]}" if m.group(0) in consts else m.group(0), a)
                writes.append(f"{fn[5:]}({a[:50]})")
            rows.append({"code": code, "expr": code_expr, "func": fm.group(1), "file": os.path.relpath(p, SRC).replace("\\", "/"),
                         "params": " ".join(fm.group(2).split())[:100], "writes": writes})
    rows.sort(key=lambda r: (r["code"] if r["code"] is not None else 99999, r["func"]))
    json.dump(rows, open(os.path.join(OUT, "client-sends.json"), "w", encoding="utf-8"), indent=1)
    L = ["# Client (AS3) -> server sends (generated by extract_client_sends.py)\n",
         "Writes are in source order; branches flattened. `UTF` = writeUTF (u16 length + UTF-8).\n",
         "| Code | Constant | Client function (file) | Writes |", "|---|---|---|---|"]
    for r in rows:
        w = "; ".join(r["writes"]).replace("|", "\\|")
        L.append(f"| {r['code']} | `{r['expr']}` | `{r['func']}` ({r['file']}) | {w} |")
    open(os.path.join(OUT, "client-sends.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(len(rows), "client send functions,", len({r['code'] for r in rows}), "codes")


if __name__ == "__main__":
    main()
