"""Dump config keys:
 - Bussiness/GameProperties.cs  ([ConfigProperty] fields, stored in DB table Server_Config via ServiceBussiness)
 - Game.Server/GameServerConfig.cs, Center.Server/CenterServerConfig.cs, Fighting.Server config ([ConfigProperty] -> app.config appSettings)
 - every ConfigurationManager.AppSettings["X"] read in the lobby projects
 - the shipped App.config appSettings values
Writes docs/spec/server/tools/out/config.md
"""
import os
import re
from cslib import ROOT, read, rel, strip_comments, walk

OUT = os.path.join(os.path.dirname(__file__), "out")
ATTR_RE = re.compile(
    r'\[ConfigProperty(?:Attribute)?\(\s*"(\w+)"\s*,\s*"([^"]*)"\s*,\s*([^\]]*?)\)\]\s*public\s+(?:static\s+)?(?:readonly\s+)?(\w+)\s+(\w+)')


def esc(s):
    return s.replace("|", "\\|").replace("\n", " ")


def main():
    L = ["# Config keys (generated by extract_config.py)\n"]
    for path in ["Bussiness/GameProperties.cs", "Game.Server/GameServerConfig.cs", "Center.Server/CenterServerConfig.cs",
                 "Fighting.Server/FightServerConfig.cs"]:
        full = os.path.join(ROOT, path)
        if not os.path.exists(full):
            continue
        s = read(full)
        L.append(f"\n## `{path}`\n")
        L.append("| Key | C# field | Type | Default | Description (original, often Chinese) |")
        L.append("|---|---|---|---|---|")
        for m in ATTR_RE.finditer(s):
            L.append(f"| `{m.group(1)}` | {m.group(5)} | {m.group(4)} | `{esc(m.group(3).strip())}` | {esc(m.group(2))} |")
    reads = {}
    for f in walk(["Game.Server", "Center.Server", "Center.Service", "Road.Service", "Bussiness", "SqlDataProvider", "Game.Base"]):
        s = strip_comments(read(f))
        for m in re.finditer(r'AppSettings\s*\[\s*"([^"]+)"\s*\]', s):
            reads.setdefault(m.group(1), set()).add(rel(f))
        for m in re.finditer(r'AppSettings\s*\[\s*"([^"]+)"\s*\+', s):
            reads.setdefault(m.group(1) + "*", set()).add(rel(f))
    L.append("\n## Direct `ConfigurationManager.AppSettings[...]` reads\n")
    L.append("| Key | Read in |\n|---|---|")
    for k in sorted(reads, key=str.lower):
        L.append(f"| `{k}` | {', '.join(sorted(reads[k]))} |")
    for cfg in ["Center.Service/App.config", "Road.Service/App.config", "Fighting.Service/App.config"]:
        s = read(os.path.join(ROOT, cfg))
        L.append(f"\n## Shipped `{cfg}` appSettings\n")
        L.append("| Key | Value |\n|---|---|")
        for m in re.finditer(r'<add\s+key="([^"]+)"\s+value="([^"]*)"', s):
            v = m.group(2)
            if m.group(1) in ("conString", "crosszoneString"):
                v = re.sub(r"Password=[^;]*", "Password=***", v)
            if m.group(1) == "PrivateKey":
                v = "<RSAKeyValue>... (1024-bit RSA private key, XML) </RSAKeyValue>"
            L.append(f"| `{m.group(1)}` | `{esc(v)}` |")
        for m in re.finditer(r'(baseAddress|address)="([^"]+)"', s):
            L.append(f"| ({m.group(1)}) | `{m.group(2)}` |")
    with open(os.path.join(OUT, "config.md"), "w", encoding="utf-8") as fo:
        fo.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
