"""List every server->client send helper in Game.Server/Packets/Packets/AbstractPacketLib.cs
(the `client.Out.SendXxx` API) with the packet code(s) it builds and the ordered writes.

Usage: python extract_packetlib.py  -> out/packetlib.md
"""
import json
import os
import re
from cslib import ROOT, read, strip_comments, methods

OUT = os.path.join(os.path.dirname(__file__), "out")
enums = json.load(open(os.path.join(OUT, "enums.json"), encoding="utf-8"))
WRITE_RE = re.compile(r"\b(\w+)\.(Write(?:Int|Byte|Boolean|String|Short|Long|Double|Float|DateTime|Bytes|UShort)?\w*)\s*\(([^;]*)\);")
PKT_RE = re.compile(r"new\s+GSPacketIn\s*\(\s*((?:\(\w+\)\s*)?[\w\.]+)")


def resolve(expr):
    e = re.sub(r"^\((?:byte|int|short)\)\s*", "", expr.strip())
    try:
        return str(int(e, 0))
    except ValueError:
        m = re.match(r"(\w+)\.(\w+)$", e)
        if m and m.group(1) in enums and m.group(2) in enums[m.group(1)]:
            return f"{enums[m.group(1)][m.group(2)]} ({e})"
        return e


def main():
    src = strip_comments(read(os.path.join(ROOT, "Game.Server/Packets/Packets/AbstractPacketLib.cs")))
    lines = ["# Server->client packet builders (generated by extract_packetlib.py)\n",
             "Writes are listed in source order; loops/conditionals are flattened, so treat as a reading aid.\n",
             "| Method | Code(s) | Writes (in order) |", "|---|---|---|"]
    n = 0
    for name, rt, params, body, off in methods(src):
        if not name.startswith("Send") and not name.startswith("send"):
            continue
        codes = sorted({resolve(p) for p in PKT_RE.findall(body)})
        writes = []
        for obj, fn, arg in WRITE_RE.findall(body):
            if fn == "WriteHeader":
                continue
            a = " ".join(arg.split())
            if len(a) > 60:
                a = a[:57] + "..."
            writes.append(f"{fn[5:] or 'Bytes'}({a})")
        n += 1
        w = "; ".join(writes).replace("|", "\\|")
        if len(w) > 1500:
            w = w[:1500] + " …"
        lines.append(f"| `{name}({' '.join(params.split())[:120]})` | {', '.join(codes)} | {w} |")
    with open(os.path.join(OUT, "packetlib.md"), "w", encoding="utf-8") as fo:
        fo.write("\n".join(lines) + "\n")
    print(n, "senders")


if __name__ == "__main__":
    main()
