"""Generate docs/spec/server/03-bussiness-procs.md from out/bussiness-procs.json (+ out/proc-tables.json).
Run extract_bussiness.py and extract_bak_procs.py first.
"""
import json
import os

HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "out")
DOC = os.path.join(HERE, "..", "03-bussiness-procs.md")

rows = json.load(open(os.path.join(OUT, "bussiness-procs.json"), encoding="utf-8"))
tabs = json.load(open(os.path.join(OUT, "proc-tables.json"), encoding="utf-8"))

DB_OF = {
    "BaseBussiness": "Player DB (`conString`, e.g. Project_Player34 / Db_Tank)",
    "BaseCrossBussiness": "Game DB (`crosszoneString`, e.g. Project_Game34)",
}
CLASS_DB = {
    "ActiveBussiness": "game", "AreaBussiness": "game", "MapBussiness": "game", "ProduceBussiness": "game",
    "PveBussiness": "game", "BaseCrossBussiness": "game",
    "ConsortiaBussiness": "player", "CookieInfoBussiness": "player", "ItemRecordBussiness": "player",
    "ManageBussiness": "player", "OrderBussiness": "player", "PlayerBussiness": "player",
    "ServiceBussiness": "player", "UserInfoBussiness": "player", "BaseBussiness": "player",
}

HEADER = """# 03 — Bussiness layer → stored procedures

Generated by `tools/gen_03.py` from the C# sources (`vendor/DDTank41/Bussiness/*.cs`) plus a best-effort
scrape of procedure bodies out of `vendor/DDTank41/Database/*.bak` (`tools/extract_bak_procs.py`).
Re-run: `python tools/extract_bussiness.py && python tools/extract_bak_procs.py && python tools/gen_03.py`.

## How to read this

* Every `XxxBussiness` method opens one SQL connection (`Sql_DbObject`) and calls exactly the procs listed.
  `GetReader` = rowset read, `RunProcedure` = exec (usually checks `@Result` return value; `0` = success unless noted),
  `GetDataTable` = paged admin query (`SP_CustomPage`, dynamic SQL — do **not** port, replace with ORM queries).
* **Two databases.** Classes deriving `BaseBussiness` use `conString` (player DB: users, items, mail, guilds…);
  classes deriving `BaseCrossBussiness` use `crosszoneString` (game/template DB: item templates, shop, quests, drops…).
  In the TS port both become one Postgres database with two schemas (`player`, `game`) — keep the split in naming.
  * player DB: ConsortiaBussiness, CookieInfoBussiness, ItemRecordBussiness, ManageBussiness, OrderBussiness,
    PlayerBussiness, ServiceBussiness, UserInfoBussiness.
  * game DB: ActiveBussiness, AreaBussiness, MapBussiness, ProduceBussiness, PveBussiness.
* "Params" are the `SqlParameter` names in declaration order; `(i=Output|ReturnValue|InputOutput)` marks
  non-input parameters by array index. `Result` ReturnValue codes map to LanguageMgr messages in the method body
  (e.g. `ConsortiaBussiness.*` → `ConsortiaBussiness.*.MsgN` keys) — check the C# method when porting error text.
* "Columns" are every `reader["X"]` read by the method or by the `InitXxx(reader)` helper it calls; these are
  the columns the TS loader must return (case-insensitive in SQL Server, keep exact case in Drizzle).
* "Tables" comes from the .bak scrape; empty = body not recovered (restore the backup to see it). Names with
  odd unicode characters are page-boundary corruption of the scrape (e.g. `Mem_ActiveŃode` = `Mem_ActiveCode`).
* Almost all game-template loaders are `SP_<Table>_All` = `SELECT * FROM <Table>`; the column list below is the
  authoritative schema the server relies on.

## Hot spots / porting notes

* `PlayerBussiness.UpdatePlayer` (SP_Users_Update) passes 86 parameters (most `Sys_Users_Detail` columns) on every save — the
  TS port should persist the `PlayerInfo` row with one UPDATE in the same column set.
* Item persistence: `AddGoods` (SP_Users_Items_Add, returns `@ItemID` output) / `UpdateGoods` (SP_Users_Items_Update)
  on `Sys_Users_Goods`; inventories call these from `SaveToDatabase` for dirty items only. Mail attachments are items
  with `UserID = 0` referenced by `Annex1..5` (= ItemID as string).
* Mail: `SP_Mail_Send` / `SP_Mail_Update` / `SP_Mail_Delete` on `User_Messages`; COD mail = Type 101.
* Auction: `SP_Auction_Add/Update/Delete/Scan` on `Auction`; the scan proc (center timer) settles expired auctions
  and mails results; `Cess` (tax 0.1) is passed in.
* Consortia: almost all permission checks live **inside** the procs (they return `@Result` codes) — they must be
  re-implemented in TS (duty `Right` bitmask in `Consortia_Duty`, levels in `Consortia_Level`).
* `SP_Sys_Update_*` (RankMgr hourly + center) rebuild celebrity/rank tables used by Tank.Request lists.

## Procedure index
See `tools/out/procs-index.md` (proc → callers) and `tools/out/proc-tables.md` (proc → tables/params from .bak).
"""


def esc(s):
    return s.replace("|", "\\|")


def main():
    L = [HEADER]
    cur = None
    for r in rows:
        if r["class"] != cur:
            cur = r["class"]
            db = CLASS_DB.get(cur, "?")
            L.append(f"\n## {cur} — {db} DB (`{r['file']}`)\n")
            L.append("| Method | Kind | Procedure(s) | Params (@) | Result columns read | Tables (.bak) |")
            L.append("|---|---|---|---|---|---|")
        kinds = ", ".join(sorted(set(k for k, _ in r["calls"])))
        procs = list(dict.fromkeys(p for _, p in r["calls"]))
        pr = ", ".join(f"`{p}`" for p in procs)
        params = ", ".join(r["params"])
        if r["directions"]:
            params += " (" + ", ".join(f"{i}={d}" for i, d in r["directions"]) + ")"
        cols = ", ".join(r["columns"])
        t = []
        for p in procs:
            for x in tabs.get(p.strip("[]"), {}).get("tables", []):
                if x not in t:
                    t.append(x)
        L.append(f"| `{esc(r['signature'])}` | {kinds} | {pr} | {esc(params)} | {esc(cols)} | {esc(', '.join(t))} |")
    with open(DOC, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", DOC, len(rows), "methods")


if __name__ == "__main__":
    main()
