"""List LoadFromDatabase/SaveToDatabase (and similar) methods in player-side components with their Bussiness calls/procs.
Usage: python scan_load_save.py -> out/player-persistence.md"""
import json, os, re
from cslib import read, rel, strip_comments, classes, methods, walk
from extract_managers import buss_calls
OUT = os.path.join(os.path.dirname(__file__), "out")
procs = json.load(open(os.path.join(OUT, "bussiness-procs.json"), encoding="utf-8"))
pb = {}
for r in procs:
    pb.setdefault(f'{r["class"]}.{r["method"]}', []).extend(p for _, p in r["calls"])
L = ["# Player-side persistence (generated by scan_load_save.py)\n", "| Class | Method | Bussiness calls | Procs |", "|---|---|---|---|"]
for f in walk(["Game.Server/GameUtils", "Game.Server/Quests", "Game.Server/Achievement", "Game.Server/Buffer", "Game.Server"]):
    if os.path.dirname(f).endswith("Game.Server") and not f.endswith("GamePlayer.cs"):
        continue
    src = strip_comments(read(f))
    for attrs, cname, body in classes(src):
        for name, rt, params, mb, off in methods(body):
            if not re.match(r"(Load|Save|Update|Remove|Add|Clear)\w*", name):
                continue
            bc = buss_calls(mb)
            if not bc:
                continue
            pr = []
            for b in bc:
                for p in pb.get(b, []):
                    if p not in pr:
                        pr.append(p)
            L.append(f"| {cname} | `{name}` | {', '.join(bc)} | {', '.join(pr)} |")
open(os.path.join(OUT, "player-persistence.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
print(len(L) - 3)
