CREATE SCHEMA "app";
--> statement-breakpoint
CREATE TABLE "app"."AccountRoles" (
	"AccountID" integer PRIMARY KEY NOT NULL,
	"role" varchar(16) DEFAULT 'admin' NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."Bots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."Bots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nickname" varchar(40) NOT NULL,
	"sex" varchar(1) DEFAULT 'm' NOT NULL,
	"level" integer DEFAULT 10 NOT NULL,
	"difficulty" varchar(16) DEFAULT 'normal' NOT NULL,
	"weaponTemplateId" integer DEFAULT 7001 NOT NULL,
	"equips" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"guild" varchar(40),
	"enabled" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp (3) DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."LoginSessions" (
	"UserName" varchar(200) NOT NULL,
	"AccountID" integer,
	"WebKey" varchar(64) NOT NULL,
	"GameKey" varchar(64),
	"Site" varchar(64) DEFAULT '' NOT NULL,
	"Count" integer DEFAULT 0 NOT NULL,
	"UserID" integer,
	"CreatedAt" timestamp (3) DEFAULT now() NOT NULL,
	"UpdatedAt" timestamp (3) DEFAULT now() NOT NULL,
	"ExpiresAt" timestamp (3) NOT NULL,
	"GameKeyExpiresAt" timestamp (3),
	"LastIP" varchar(64),
	CONSTRAINT "LoginSessions_pkey" PRIMARY KEY("UserName")
);
--> statement-breakpoint
CREATE TABLE "app"."Logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."Logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"at" timestamp (3) DEFAULT now() NOT NULL,
	"level" varchar(8) DEFAULT 'info' NOT NULL,
	"category" varchar(40) NOT NULL,
	"actor" varchar(200),
	"message" text NOT NULL,
	"data" jsonb
);
--> statement-breakpoint
CREATE TABLE "app"."MailBroadcasts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."MailBroadcasts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sentAt" timestamp (3) DEFAULT now() NOT NULL,
	"subject" varchar(200) NOT NULL,
	"target" varchar(32) NOT NULL,
	"recipients" integer DEFAULT 0 NOT NULL,
	"sentBy" varchar(200),
	"payload" jsonb
);
--> statement-breakpoint
CREATE TABLE "app"."News" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."News_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(200) NOT NULL,
	"summary" text DEFAULT '' NOT NULL,
	"body" text,
	"category" varchar(32) DEFAULT 'news' NOT NULL,
	"cover" text,
	"url" text,
	"publishedAt" timestamp (3) DEFAULT now() NOT NULL,
	"published" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp (3) DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."Settings" (
	"key" varchar(100) PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updatedAt" timestamp (3) DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."Texts" (
	"key" varchar(300) PRIMARY KEY NOT NULL,
	"group" varchar(120) DEFAULT '' NOT NULL,
	"ptBR" text DEFAULT '' NOT NULL,
	"en" text,
	"updatedAt" timestamp (3) DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "IX_Logs_at" ON "app"."Logs" USING btree ("at");--> statement-breakpoint
CREATE INDEX "IX_News_publishedAt" ON "app"."News" USING btree ("publishedAt");