CREATE TABLE IF NOT EXISTS "app"."EventClaims" (
	"UserID" integer NOT NULL,
	"Kind" varchar(32) NOT NULL,
	"Key" varchar(64) NOT NULL,
	"ClaimedAt" timestamp(3) DEFAULT now() NOT NULL,
	CONSTRAINT "EventClaims_pkey" PRIMARY KEY("UserID","Kind","Key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "app"."ScheduledEvents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"kind" varchar(32) NOT NULL,
	"title" text DEFAULT '' NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"weekdays" varchar(20) DEFAULT '0,1,2,3,4,5,6' NOT NULL,
	"startTime" varchar(5) DEFAULT '00:00' NOT NULL,
	"durationMin" integer DEFAULT 60 NOT NULL,
	"startDate" timestamp(3),
	"endDate" timestamp(3),
	"params" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updatedAt" timestamp(3) DEFAULT now() NOT NULL
);
--> statement-breakpoint
INSERT INTO "app"."ScheduledEvents" ("kind","title","enabled","weekdays","startTime","durationMin","params")
SELECT * FROM (VALUES
	('worldboss','Boss mundial (meio-dia)',true,'0,1,2,3,4,5,6','12:00',30,'{"bossHp":20000000,"rankAwards":[{"rank":1,"giftToken":500},{"rank":3,"giftToken":300},{"rank":10,"giftToken":100}]}'::jsonb),
	('worldboss','Boss mundial (noite)',true,'0,1,2,3,4,5,6','20:00',30,'{"bossHp":20000000,"rankAwards":[{"rank":1,"giftToken":500},{"rank":3,"giftToken":300},{"rank":10,"giftToken":100}]}'::jsonb),
	('league','Chiến thần (liga)',true,'6','20:00',60,'{"maxCount":10}'::jsonb),
	('elite','Campeonato de elite',true,'0','20:00',60,'{}'::jsonb),
	('weekly_reset','Reset semanal',true,'1','00:00',1,'{}'::jsonb),
	('double_exp','EXP em dobro (fim de semana)',false,'0,6','00:00',1440,'{"rate":2}'::jsonb),
	('double_gold','Ouro em dobro',false,'5','18:00',240,'{"rate":2}'::jsonb)
) AS v(a,b,c,d,e,f,g) WHERE NOT EXISTS (SELECT 1 FROM "app"."ScheduledEvents");
--> statement-breakpoint
INSERT INTO "game"."Event_Reward_Goods" ("ActivityType","SubActivityType","TemplateId","IsBind","ValidDate","Count")
SELECT * FROM (VALUES (7,1,11024,true,0,5), (7,1,11035,true,0,10), (7,1,11998,true,1,2)) AS v(a,b,c,d,e,f)
WHERE NOT EXISTS (SELECT 1 FROM "game"."Event_Reward_Goods" WHERE "ActivityType" = 7);
