CREATE TABLE "app"."InviteFriends" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."InviteFriends_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"UserID" integer NOT NULL,
	"InvitedNick" varchar(64) NOT NULL,
	"CreatedAt" timestamp (3) DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "InviteFriends_user_idx" ON "app"."InviteFriends" USING btree ("UserID");