import { CalendarDays, Castle, Flag, ListChecks, Map, PackageOpen, ScrollText, ShoppingBag, Skull } from "lucide-react";
import { defineResource } from "@/crud/types";

// Column names below are verbatim from packages/db/src/schema/game.ts so the API can expose the tables directly.

export const shop = defineResource({
  name: "shop",
  table: 'game."Shop"',
  label: { "pt-BR": "Loja", en: "Shop" },
  singular: { "pt-BR": "oferta", en: "offer" },
  description: "Ofertas da loja (Shop): item, tipo de compra, preços por validade e período.",
  icon: ShoppingBag,
  group: "content",
  idField: "ID",
  titleField: "TemplateID",
  defaultSort: "-ID",
  fields: [
    { name: "ID", label: "ID", type: "number", list: true, sortable: true, form: "create", required: true, min: 1 },
    { name: "ShopID", label: "ShopID (aba)", type: "number", required: true, list: true, sortable: true },
    { name: "GroupID", label: "GroupID", type: "number", default: 0 },
    { name: "TemplateID", label: "TemplateID do item", type: "number", required: true, min: 1, list: true, sortable: true },
    { name: "BuyType", label: "BuyType", type: "number", default: 0, list: true, hint: "Tipo de moeda/compra, como no original" },
    { name: "AUnit", label: "AUnit", type: "number", default: 0, list: true, section: "Preços / validade" },
    { name: "BUnit", label: "BUnit", type: "number", default: 0, section: "Preços / validade" },
    { name: "CUnit", label: "CUnit", type: "number", default: 0, section: "Preços / validade" },
    { name: "Beat", label: "Beat (desconto)", type: "number", int: false, default: 1, section: "Preços / validade" },
    { name: "Label", label: "Label", type: "number", default: 0, hint: "Etiqueta (novo/promo…)", section: "Exibição" },
    { name: "Sort", label: "Ordem", type: "number", default: 0, sortable: true, section: "Exibição" },
    { name: "LimitCount", label: "Limite de compras", type: "number", default: -1, section: "Exibição" },
    { name: "LimitGrade", label: "Nível mínimo", type: "number", default: 0, section: "Exibição" },
    { name: "StartDate", label: "Início", type: "datetime", section: "Período" },
    { name: "EndDate", label: "Fim", type: "datetime", section: "Período" },
    { name: "IsContinue", label: "Renovável", type: "boolean", section: "Período" },
    { name: "IsBind", label: "Vinculado", type: "boolean", section: "Período" },
    { name: "IsVouch", label: "Recomendado", type: "boolean", section: "Período" },
    { name: "IsCheap", label: "Promoção", type: "boolean", list: true, section: "Período" },
    { name: "CanBuy", label: "À venda", type: "boolean", default: true, list: true, inlineToggle: true, section: "Período" },
  ],
});

export const quests = defineResource({
  name: "quests",
  table: 'game."Quest"',
  label: { "pt-BR": "Missões", en: "Quests" },
  singular: { "pt-BR": "missão", en: "quest" },
  description: "Missões (Quest). Condições e prêmios ficam em Quest_Condiction e Quest_Goods.",
  icon: ScrollText,
  group: "content",
  idField: "ID",
  titleField: "Title",
  defaultSort: "ID",
  fields: [
    { name: "ID", label: "ID", type: "number", list: true, sortable: true, required: true, form: "create" },
    { name: "QuestID", label: "QuestID (tipo)", type: "number", required: true, list: true, sortable: true, hint: "Categoria da missão, como no original" },
    { name: "Title", label: "Título", type: "text", required: true, list: true, sortable: true, span: 2 },
    { name: "Detail", label: "Detalhe", type: "textarea" },
    { name: "Objective", label: "Objetivo", type: "textarea" },
    { name: "NeedMinLevel", label: "Nível mín.", type: "number", min: 0, max: 100, default: 1, list: true },
    { name: "NeedMaxLevel", label: "Nível máx.", type: "number", min: 0, max: 100, default: 100 },
    { name: "PreQuestID", label: "PreQuestID", type: "text", hint: "IDs separados por vírgula" },
    { name: "NextQuestID", label: "NextQuestID", type: "text" },
    { name: "MapID", label: "MapID", type: "number", default: 0 },
    { name: "CanRepeat", label: "Repetível", type: "boolean", list: true, section: "Repetição" },
    { name: "RepeatInterval", label: "Intervalo", type: "number", default: 1, section: "Repetição" },
    { name: "RepeatMax", label: "Máx. repetições", type: "number", default: 1, section: "Repetição" },
    { name: "TimeMode", label: "Por período", type: "boolean", section: "Repetição" },
    { name: "StartDate", label: "Início", type: "datetime", section: "Repetição" },
    { name: "EndDate", label: "Fim", type: "datetime", section: "Repetição" },
    { name: "RewardGP", label: "EXP (GP)", type: "number", min: 0, default: 0, list: true, section: "Recompensas" },
    { name: "RewardGold", label: "Ouro", type: "number", min: 0, default: 0, section: "Recompensas" },
    { name: "RewardMoney", label: "Cupons", type: "number", min: 0, default: 0, section: "Recompensas" },
    { name: "RewardGiftToken", label: "Medalhas (GiftToken)", type: "number", min: 0, default: 0, section: "Recompensas" },
    { name: "RewardOffer", label: "Mérito", type: "number", min: 0, default: 0, section: "Recompensas" },
    { name: "RewardMedal", label: "Medal", type: "number", min: 0, default: 0, section: "Recompensas" },
    { name: "RewardBuffID", label: "Buff (ID)", type: "number", min: 0, default: 0, section: "Recompensas" },
    { name: "RewardBuffDate", label: "Buff (duração)", type: "number", min: 0, default: 0, section: "Recompensas" },
    { name: "AutoEquip", label: "Equipar prêmio", type: "boolean", section: "Recompensas" },
  ],
});

export const questConditions = defineResource({
  name: "quest-conditions",
  table: 'game."Quest_Condiction"',
  label: { "pt-BR": "Condições de missão", en: "Quest conditions" },
  singular: { "pt-BR": "condição", en: "condition" },
  icon: ListChecks,
  group: "content",
  idField: ["QuestID", "CondictionID"],
  titleField: "CondictionTitle",
  defaultSort: "QuestID",
  fields: [
    { name: "QuestID", label: "QuestID", type: "number", required: true, list: true, sortable: true, form: "create" },
    { name: "CondictionID", label: "CondictionID", type: "number", required: true, list: true, form: "create" },
    { name: "CondictionTitle", label: "Título", type: "text", required: true, list: true, span: 2 },
    { name: "CondictionType", label: "Tipo", type: "number", required: true, list: true },
    { name: "Para1", label: "Para1", type: "number", default: 0, list: true },
    { name: "Para2", label: "Para2", type: "number", default: 0, list: true },
    { name: "isOpitional", label: "Opcional", type: "boolean", list: true },
  ],
});

export const questGoods = defineResource({
  name: "quest-goods",
  table: 'game."Quest_Goods"',
  label: { "pt-BR": "Prêmios de missão", en: "Quest rewards" },
  singular: { "pt-BR": "prêmio", en: "reward" },
  icon: PackageOpen,
  group: "content",
  idField: ["QuestID", "RewardItemID"],
  defaultSort: "QuestID",
  fields: [
    { name: "QuestID", label: "QuestID", type: "number", required: true, list: true, sortable: true, form: "create" },
    { name: "RewardItemID", label: "Item (TemplateID)", type: "number", required: true, list: true, form: "create" },
    { name: "RewardItemCount", label: "Quantidade", type: "number", min: 1, default: 1, list: true },
    { name: "RewardItemValid", label: "Validade (dias)", type: "number", min: 0, default: 0, list: true },
    { name: "IsSelect", label: "Escolha do jogador", type: "boolean", list: true },
    { name: "IsCount", label: "IsCount", type: "boolean" },
    { name: "IsBind", label: "Vinculado", type: "boolean" },
    { name: "StrengthenLevel", label: "Fortalecimento", type: "number", min: 0, default: 0 },
    { name: "AttackCompose", label: "Composição ataque", type: "number", min: 0, default: 0 },
    { name: "DefendCompose", label: "Composição defesa", type: "number", min: 0, default: 0 },
    { name: "AgilityCompose", label: "Composição agilidade", type: "number", min: 0, default: 0 },
    { name: "LuckCompose", label: "Composição sorte", type: "number", min: 0, default: 0 },
  ],
});

export const events = defineResource({
  name: "events",
  table: 'game."Active"',
  label: { "pt-BR": "Eventos", en: "Events" },
  singular: { "pt-BR": "evento", en: "event" },
  icon: CalendarDays,
  group: "content",
  hidden: true, // shown through the custom /events page (calendar + table)
  idField: "ActiveID",
  titleField: "Title",
  defaultSort: "StartDate",
  fields: [
    { name: "ActiveID", label: "ActiveID", type: "number", list: true, sortable: true, required: true, form: "create" },
    { name: "Title", label: "Título", type: "text", required: true, list: true, sortable: true, span: 2 },
    { name: "Type", label: "Type", type: "number", default: 0, list: true },
    { name: "ActiveType", label: "ActiveType", type: "number", default: 0 },
    { name: "IconID", label: "Ícone (IconID)", type: "number", default: 0 },
    { name: "StartDate", label: "Início", type: "datetime", required: true, list: true, sortable: true },
    { name: "EndDate", label: "Fim", type: "datetime", required: true, list: true, sortable: true },
    { name: "Description", label: "Descrição", type: "textarea" },
    { name: "Content", label: "Conteúdo", type: "textarea" },
    { name: "AwardContent", label: "Prêmios (texto)", type: "textarea" },
    { name: "ActionTimeContent", label: "Horário (texto)", type: "text" },
    { name: "HasKey", label: "HasKey", type: "number", default: 0, hint: "Exige código de ativação" },
    { name: "IsOnly", label: "IsOnly", type: "number", default: 0 },
    { name: "IsAdvance", label: "IsAdvance", type: "boolean" },
    { name: "IsShow", label: "Visível", type: "boolean", default: true, list: true, inlineToggle: true },
  ],
});

const scriptHint = "Classe do script de IA (ex.: GameServerScript.AI.Game.XXX)";

export const dungeons = defineResource({
  name: "dungeons",
  table: 'game."Pve_Info"',
  label: { "pt-BR": "Masmorras PvE", en: "PvE dungeons" },
  singular: { "pt-BR": "masmorra", en: "dungeon" },
  description: "Masmorras (Pve_Info): nível, mapas/NPCs e script por dificuldade.",
  icon: Castle,
  group: "content",
  idField: "ID",
  titleField: "Name",
  defaultSort: "Ordering",
  fields: [
    { name: "ID", label: "ID", type: "number", required: true, list: true, sortable: true, form: "create" },
    { name: "Name", label: "Nome", type: "text", required: true, list: true, sortable: true },
    { name: "Type", label: "Type", type: "number", default: 0, list: true },
    { name: "LevelLimits", label: "Nível mínimo", type: "number", min: 0, max: 100, default: 10, list: true, sortable: true },
    { name: "Ordering", label: "Ordem", type: "number", default: 0, sortable: true },
    { name: "Pic", label: "Pic", type: "text" },
    { name: "Description", label: "Descrição", type: "textarea" },
    { name: "AdviceTips", label: "Dicas", type: "text" },
    { name: "BossFightNeedMoney", label: "BossFightNeedMoney", type: "text" },
    { name: "LastFloor", label: "LastFloor", type: "text" },
    { name: "SimpleTemplateIds", label: "Fácil — TemplateIds", type: "text", section: "Fácil" },
    { name: "SimpleGameScript", label: "Fácil — script", type: "text", hint: scriptHint, section: "Fácil" },
    { name: "NormalTemplateIds", label: "Normal — TemplateIds", type: "text", section: "Normal" },
    { name: "NormalGameScript", label: "Normal — script", type: "text", hint: scriptHint, section: "Normal" },
    { name: "HardTemplateIds", label: "Difícil — TemplateIds", type: "text", section: "Difícil" },
    { name: "HardGameScript", label: "Difícil — script", type: "text", hint: scriptHint, section: "Difícil" },
    { name: "TerrorTemplateIds", label: "Herói — TemplateIds", type: "text", section: "Herói" },
    { name: "TerrorGameScript", label: "Herói — script", type: "text", hint: scriptHint, section: "Herói" },
  ],
});

export const missions = defineResource({
  name: "missions",
  table: 'game."Mission_Info"',
  label: { "pt-BR": "Fases PvE", en: "PvE missions" },
  singular: { "pt-BR": "fase", en: "mission" },
  description: "Fases das masmorras (Mission_Info): turnos, script e condições.",
  icon: Flag,
  group: "content",
  idField: "Id",
  titleField: "Name",
  defaultSort: "Id",
  fields: [
    { name: "Id", label: "Id", type: "number", required: true, list: true, sortable: true, form: "create" },
    { name: "Name", label: "Nome", type: "text", required: true, list: true, sortable: true },
    { name: "Title", label: "Título", type: "text", list: true },
    { name: "Script", label: "Script", type: "text", required: true, list: true, hint: "Classe em GameServerScript.AI.Missions", span: 2 },
    { name: "TotalCount", label: "TotalCount", type: "number", default: 0 },
    { name: "TotalTurn", label: "Turnos", type: "number", default: 0, list: true },
    { name: "Delay", label: "Delay", type: "number", default: 0 },
    { name: "IncrementDelay", label: "IncrementDelay", type: "number", default: 0 },
    { name: "TakeCard", label: "Cartas ao vencer", type: "number", default: 0 },
    { name: "TryAgain", label: "Permite tentar de novo", type: "boolean" },
    { name: "TryAgainCost", label: "Custo nova tentativa", type: "number", default: 0 },
    { name: "Success", label: "Condição de vitória", type: "text" },
    { name: "Failure", label: "Condição de derrota", type: "text" },
    { name: "Description", label: "Descrição", type: "textarea" },
  ],
});

export const npcs = defineResource({
  name: "npcs",
  table: 'game."NPC_Info"',
  label: { "pt-BR": "NPCs", en: "NPCs" },
  singular: { "pt-BR": "NPC", en: "NPC" },
  description: "Monstros e chefes do PvE (NPC_Info).",
  icon: Skull,
  group: "content",
  idField: "ID",
  titleField: "Name",
  defaultSort: "ID",
  fields: [
    { name: "ID", label: "ID", type: "number", required: true, list: true, sortable: true, form: "create" },
    { name: "Name", label: "Nome", type: "text", required: true, list: true, sortable: true },
    { name: "Level", label: "Nível", type: "number", default: 1, list: true, sortable: true },
    { name: "Type", label: "Type", type: "number", default: 0 },
    { name: "Camp", label: "Camp", type: "number", default: 0 },
    { name: "Blood", label: "Vida", type: "number", min: 0, list: true, section: "Combate" },
    { name: "Attack", label: "Ataque", type: "number", min: 0, list: true, section: "Combate" },
    { name: "Defence", label: "Defesa", type: "number", min: 0, section: "Combate" },
    { name: "Agility", label: "Agilidade", type: "number", min: 0, section: "Combate" },
    { name: "Lucky", label: "Sorte", type: "number", min: 0, section: "Combate" },
    { name: "BaseDamage", label: "BaseDamage", type: "number", min: 0, section: "Combate" },
    { name: "BaseGuard", label: "BaseGuard", type: "number", min: 0, section: "Combate" },
    { name: "MagicAttack", label: "MagicAttack", type: "number", min: 0, section: "Combate" },
    { name: "MagicDefence", label: "MagicDefence", type: "number", min: 0, section: "Combate" },
    { name: "Experience", label: "EXP", type: "number", min: 0, section: "Combate" },
    { name: "Immunity", label: "Immunity", type: "number", default: 0, section: "Combate" },
    { name: "CurrentBallId", label: "Projétil (BallId)", type: "number", default: 0, section: "Combate" },
    { name: "DropId", label: "DropId", type: "number", default: 0, section: "Drop" },
    { name: "DropRate", label: "DropRate", type: "text", section: "Drop" },
    { name: "MoveMin", label: "MoveMin", type: "number", section: "Movimento" },
    { name: "MoveMax", label: "MoveMax", type: "number", section: "Movimento" },
    { name: "speed", label: "speed", type: "number", section: "Movimento" },
    { name: "Delay", label: "Delay", type: "number", section: "Movimento" },
    { name: "Alert", label: "Alert", type: "number", section: "Movimento" },
    { name: "Range", label: "Range", type: "number", section: "Movimento" },
    { name: "Preserve", label: "Preserve", type: "number", section: "Movimento" },
    { name: "X", label: "X", type: "number", section: "Geometria" },
    { name: "Y", label: "Y", type: "number", section: "Geometria" },
    { name: "Width", label: "Largura", type: "number", section: "Geometria" },
    { name: "Height", label: "Altura", type: "number", section: "Geometria" },
    { name: "FireX", label: "FireX", type: "number", section: "Geometria" },
    { name: "FireY", label: "FireY", type: "number", section: "Geometria" },
    { name: "ModelID", label: "ModelID", type: "text", section: "Recursos" },
    { name: "ResourcesPath", label: "ResourcesPath", type: "text", section: "Recursos" },
    { name: "Script", label: "Script de IA", type: "text", list: true, section: "Recursos", span: 2 },
  ],
});

export const maps = defineResource({
  name: "maps",
  table: 'game."Game_Map"',
  label: { "pt-BR": "Mapas", en: "Maps" },
  singular: { "pt-BR": "mapa", en: "map" },
  description: "Mapas de batalha (Game_Map): dimensões, camadas e música.",
  icon: Map,
  group: "content",
  idField: "ID",
  titleField: "Name",
  defaultSort: "ID",
  fields: [
    { name: "ID", label: "ID", type: "number", required: true, list: true, sortable: true, form: "create" },
    { name: "Name", label: "Nome", type: "text", required: true, list: true, sortable: true },
    { name: "Type", label: "Type", type: "number", default: 0, list: true },
    { name: "Weight", label: "Peso (sorteio)", type: "number", default: 0, list: true },
    { name: "DragIndex", label: "DragIndex", type: "number", default: 0 },
    { name: "PosX", label: "PosX (spawns)", type: "text", span: 2 },
    { name: "ForegroundWidth", label: "Frente — largura", type: "number", section: "Dimensões" },
    { name: "ForegroundHeight", label: "Frente — altura", type: "number", section: "Dimensões" },
    { name: "BackroundWidht", label: "Fundo — largura", type: "number", section: "Dimensões" },
    { name: "BackroundHeight", label: "Fundo — altura", type: "number", section: "Dimensões" },
    { name: "DeadWidth", label: "Zona morta — largura", type: "number", section: "Dimensões" },
    { name: "DeadHeight", label: "Zona morta — altura", type: "number", section: "Dimensões" },
    { name: "Pic", label: "Pic", type: "text", section: "Recursos" },
    { name: "ForePic", label: "ForePic", type: "text", section: "Recursos" },
    { name: "BackPic", label: "BackPic", type: "text", section: "Recursos" },
    { name: "DeadPic", label: "DeadPic", type: "text", section: "Recursos" },
    { name: "BackMusic", label: "Música", type: "text", section: "Recursos" },
    { name: "Description", label: "Descrição", type: "textarea" },
    { name: "Remark", label: "Observação", type: "text" },
  ],
});
