import { Building2, CalendarClock, Crown, ScrollText, UserPlus, Users2 } from "lucide-react";
import { defineResource } from "@/crud/types";

/** player."Consortia" — guilds (Sociedades). Names (chairman/creator) are stored in the row itself. */
export const guilds = defineResource({
  name: "guilds",
  table: 'player."Consortia"',
  label: { "pt-BR": "Sociedades", en: "Guilds" },
  singular: { "pt-BR": "sociedade", en: "guild" },
  description: "Guildas (Consortia): nível, fundos (Riches), prédios, aviso e descrição. Desativar = IsExist falso.",
  icon: Building2,
  group: "players",
  idField: "ConsortiaID",
  titleField: "ConsortiaName",
  defaultSort: "-Level",
  searchPlaceholder: "Nome da sociedade ou líder…",
  capabilities: { create: false, delete: false },
  fields: [
    { name: "ConsortiaID", label: "ID", type: "number", list: true, sortable: true, readOnly: true },
    { name: "ConsortiaName", label: "Nome", type: "text", list: true, sortable: true, required: true },
    { name: "ChairmanName", label: "Líder", type: "text", list: true, readOnly: true },
    { name: "ChairmanID", label: "Líder (UserID)", type: "number", readOnly: true },
    { name: "Level", label: "Nível", type: "number", min: 1, max: 10, list: true, sortable: true, required: true },
    { name: "Count", label: "Membros", type: "number", list: true, sortable: true, readOnly: true },
    { name: "MaxCount", label: "Máx. membros", type: "number", min: 1 },
    { name: "Riches", label: "Fundos (Riches)", type: "number", min: 0, list: true, sortable: true },
    { name: "Honor", label: "Honra", type: "number", min: 0, list: true, sortable: true },
    { name: "StoreLevel", label: "Banco (nível)", type: "number", min: 0, max: 10, section: "Prédios" },
    { name: "ShopLevel", label: "Loja (nível)", type: "number", min: 0, max: 5, section: "Prédios" },
    { name: "SmithLevel", label: "Ferreiro (nível)", type: "number", min: 0, max: 10, section: "Prédios" },
    { name: "SkillLevel", label: "Habilidades (nível)", type: "number", min: 0, max: 10, section: "Prédios" },
    { name: "OpenApply", label: "Aceita pedidos", type: "boolean", list: true },
    { name: "Placard", label: "Aviso", type: "textarea" },
    { name: "Description", label: "Descrição", type: "textarea" },
    { name: "BadgeID", label: "Emblema", type: "number", min: 0 },
    { name: "BuildDate", label: "Criada em", type: "datetime", list: true, sortable: true, readOnly: true },
    { name: "IsExist", label: "Ativa", type: "boolean", list: true },
  ],
});

/** player."Consortia_Users" — membership rows (UserName = nickname). */
export const guildMembers = defineResource({
  name: "guild-members",
  table: 'player."Consortia_Users"',
  label: { "pt-BR": "Membros de sociedade", en: "Guild members" },
  singular: { "pt-BR": "membro", en: "member" },
  description: "Consortia_Users: cargo (DutyID), silenciado no chat da sociedade, observação.",
  icon: Users2,
  group: "players",
  idField: "ID",
  titleField: "UserName",
  defaultSort: "-ID",
  searchPlaceholder: "Apelido ou ConsortiaID…",
  capabilities: { create: false },
  fields: [
    { name: "ID", label: "ID", type: "number", list: true, sortable: true, readOnly: true },
    { name: "ConsortiaID", label: "Sociedade (ID)", type: "number", list: true, sortable: true, readOnly: true },
    { name: "UserID", label: "UserID", type: "number", list: true, readOnly: true },
    { name: "UserName", label: "Apelido", type: "text", list: true, sortable: true, readOnly: true },
    { name: "DutyID", label: "Cargo (DutyID)", type: "number", list: true },
    { name: "RatifierName", label: "Aprovado por", type: "text", readOnly: true },
    { name: "IsBanChat", label: "Silenciado", type: "boolean", list: true },
    { name: "Remark", label: "Observação", type: "textarea" },
    { name: "IsExist", label: "Ativo", type: "boolean", list: true },
  ],
});

export const guildDuties = defineResource({
  name: "guild-duties",
  table: 'player."Consortia_Duty"',
  label: { "pt-BR": "Cargos de sociedade", en: "Guild duties" },
  singular: { "pt-BR": "cargo", en: "duty" },
  description: "Consortia_Duty: nível 1 = líder; Right = bits de permissão (1 aprovar, 2 convidar, 4 silenciar, 8 aviso, 16 descrição/fundos, 32 expulsar, 64 cargos, 2048 promover).",
  icon: Crown,
  group: "players",
  idField: "DutyID",
  titleField: "DutyName",
  defaultSort: "ConsortiaID",
  capabilities: { create: false, delete: false },
  fields: [
    { name: "DutyID", label: "ID", type: "number", list: true, sortable: true, readOnly: true },
    { name: "ConsortiaID", label: "Sociedade (ID)", type: "number", list: true, sortable: true, readOnly: true },
    { name: "Level", label: "Nível", type: "number", min: 1, max: 10, list: true, sortable: true },
    { name: "DutyName", label: "Nome", type: "text", list: true, required: true },
    { name: "Right", label: "Permissões (bits)", type: "number", min: 0, list: true },
    { name: "IsExist", label: "Ativo", type: "boolean", list: true },
  ],
});

export const guildApplications = defineResource({
  name: "guild-applications",
  table: 'player."Consortia_Apply_Users"',
  label: { "pt-BR": "Pedidos de entrada", en: "Guild applications" },
  singular: { "pt-BR": "pedido", en: "application" },
  icon: UserPlus,
  group: "players",
  idField: "ID",
  titleField: "UserName",
  defaultSort: "-ApplyDate",
  capabilities: { create: false },
  fields: [
    { name: "ID", label: "ID", type: "number", list: true, readOnly: true },
    { name: "ConsortiaName", label: "Sociedade", type: "text", list: true, readOnly: true },
    { name: "UserName", label: "Jogador", type: "text", list: true, readOnly: true },
    { name: "ApplyDate", label: "Data", type: "datetime", list: true, sortable: true, readOnly: true },
    { name: "IsExist", label: "Pendente", type: "boolean", list: true },
  ],
});

export const guildEvents = defineResource({
  name: "guild-events",
  table: 'player."Consortia_Event"',
  label: { "pt-BR": "Histórico de sociedade", en: "Guild events" },
  singular: { "pt-BR": "evento", en: "event" },
  description: "Consortia_Event: 5 doação, 6 entrada, 7 expulsão, 8 saída.",
  icon: ScrollText,
  group: "players",
  idField: "ID",
  titleField: "NickName",
  defaultSort: "-Date",
  capabilities: { create: false, update: false },
  fields: [
    { name: "ID", label: "ID", type: "number", list: true, readOnly: true },
    { name: "ConsortiaID", label: "Sociedade (ID)", type: "number", list: true, sortable: true, readOnly: true },
    { name: "Date", label: "Data", type: "datetime", list: true, sortable: true, readOnly: true },
    { name: "Type", label: "Tipo", type: "select", list: true, readOnly: true, options: [{ value: 5, label: "Doação", tone: "sun" }, { value: 6, label: "Entrada", tone: "mint" }, { value: 7, label: "Expulsão", tone: "coral" }, { value: 8, label: "Saída", tone: "neutral" }] },
    { name: "NickName", label: "Jogador", type: "text", list: true, readOnly: true },
    { name: "EventValue", label: "Valor", type: "number", list: true, readOnly: true },
    { name: "ManagerName", label: "Por", type: "text", list: true, readOnly: true },
  ],
});

export const guildTasks = defineResource({
  name: "guild-tasks",
  table: 'player."Consortia_Task_Info"',
  label: { "pt-BR": "Missões de sociedade", en: "Guild missions" },
  singular: { "pt-BR": "missão", en: "mission" },
  description: "Missão ativa por sociedade (ConditionData/RankTable em JSON, como o original).",
  icon: CalendarClock,
  group: "players",
  idField: "ID",
  defaultSort: "-ID",
  capabilities: { create: false },
  fields: [
    { name: "ID", label: "ID", type: "number", list: true, readOnly: true },
    { name: "ConsortiaID", label: "Sociedade (ID)", type: "number", list: true, readOnly: true },
    { name: "Level", label: "Nível", type: "number", list: true },
    { name: "BeginTime", label: "Início", type: "datetime", list: true },
    { name: "Time", label: "Duração (min)", type: "number", list: true },
    { name: "ConditionData", label: "Condições (JSON)", type: "textarea" },
    { name: "RankTable", label: "Ranking (JSON)", type: "textarea" },
    { name: "IsExist", label: "Ativa", type: "boolean", list: true },
  ],
});

export const guildLevels = defineResource({
  name: "guild-levels",
  table: 'player."Consortia_Level"',
  label: { "pt-BR": "Níveis de sociedade", en: "Guild levels" },
  singular: { "pt-BR": "nível", en: "level" },
  description: "Consortia_Level: custo (Riches/NeedGold) e limite de membros por nível; custos dos prédios por nível.",
  icon: Building2,
  group: "content",
  idField: "Level",
  defaultSort: "Level",
  fields: [
    { name: "Level", label: "Nível", type: "number", list: true, sortable: true, required: true, min: 1 },
    { name: "Count", label: "Máx. membros", type: "number", list: true, min: 0 },
    { name: "Riches", label: "Fundos p/ subir", type: "number", list: true, min: 0 },
    { name: "NeedGold", label: "Ouro p/ subir", type: "number", list: true, min: 0 },
    { name: "Reward", label: "Bônus de fundos", type: "number", min: 0 },
    { name: "StoreRiches", label: "Banco", type: "number", list: true, min: 0 },
    { name: "ShopRiches", label: "Loja", type: "number", list: true, min: 0 },
    { name: "SmithRiches", label: "Ferreiro", type: "number", list: true, min: 0 },
    { name: "BufferRiches", label: "Habilidades", type: "number", list: true, min: 0 },
    { name: "KickMax", label: "Expulsões/dia", type: "number", min: 0 },
    { name: "Deduct", label: "Manutenção", type: "number", min: 0 },
  ],
});
