import { Ban, Bot, Gift, ShieldCheck, Users } from "lucide-react";
import { defineResource, type Row } from "@/crud/types";

const isBanned = (r: Row) => !!r.ForbidDate && new Date(String(r.ForbidDate)).getTime() > Date.now();

export const players = defineResource({
  name: "players",
  table: 'player."Sys_Users_Detail"',
  label: { "pt-BR": "Jogadores", en: "Players" },
  singular: { "pt-BR": "jogador", en: "player" },
  description: "Personagens (Sys_Users_Detail): ajuste moedas e nível, bana ou envie itens.",
  icon: Users,
  group: "players",
  idField: "UserID",
  titleField: "NickName",
  defaultSort: "-Grade",
  searchPlaceholder: "Apelido, conta ou UserID…",
  capabilities: { create: false, delete: false },
  fields: [
    { name: "UserID", label: "UserID", type: "number", list: true, sortable: true, readOnly: true },
    { name: "NickName", label: "Apelido", type: "text", list: true, sortable: true, readOnly: true },
    { name: "UserName", label: "Conta", type: "text", list: true, readOnly: true },
    { name: "State", label: "Online", type: "select", list: true, readOnly: true, options: [{ value: 0, label: "Offline", tone: "neutral" }, { value: 1, label: "Online", tone: "mint" }] },
    { name: "Grade", label: "Nível", type: "number", min: 1, max: 100, list: true, sortable: true, required: true },
    { name: "GP", label: "EXP (GP)", type: "number", min: 0 },
    { name: "Gold", label: "Ouro", type: "number", min: 0, list: true, sortable: true, required: true },
    { name: "Money", label: "Cupons", type: "number", min: 0, list: true, sortable: true, required: true },
    { name: "GiftToken", label: "Medalhas (GiftToken)", type: "number", min: 0 },
    { name: "Medal", label: "Medal", type: "number", min: 0 },
    { name: "Offer", label: "Mérito (Offer)", type: "number", min: 0 },
    { name: "FightPower", label: "Poder", type: "number", list: true, sortable: true, readOnly: true },
    { name: "ForbidDate", label: "Banido até", type: "datetime", list: true, readOnly: true },
    { name: "ForbidReason", label: "Motivo do ban", type: "text", readOnly: true },
    { name: "LastDate", label: "Último acesso", type: "datetime", list: true, sortable: true, readOnly: true },
  ],
  rowActions: [
    {
      id: "give-item",
      label: { "pt-BR": "Dar item", en: "Give item" },
      icon: Gift,
      path: "give-item",
      success: "Item enviado",
      fields: [
        { name: "templateId", label: "TemplateID", type: "number", required: true, min: 1 },
        { name: "count", label: "Quantidade", type: "number", required: true, min: 1, default: 1 },
        { name: "validDays", label: "Validade (dias)", type: "number", min: 0, default: 0, hint: "0 = permanente" },
        { name: "viaMail", label: "Enviar por correio", type: "boolean", default: true },
      ],
    },
    {
      id: "ban",
      label: { "pt-BR": "Banir", en: "Ban" },
      icon: Ban,
      tone: "danger",
      path: "ban",
      success: "Jogador banido",
      visible: (r) => !isBanned(r),
      fields: [
        { name: "reason", label: "Motivo", type: "textarea", required: true },
        { name: "hours", label: "Duração (horas)", type: "number", min: 0, default: 24, hint: "0 = permanente" },
      ],
    },
    {
      id: "unban",
      label: { "pt-BR": "Desbanir", en: "Unban" },
      icon: ShieldCheck,
      path: "unban",
      confirm: "Remover o banimento deste jogador?",
      success: "Banimento removido",
      visible: (r) => isBanned(r),
    },
  ],
});

/** New table (no equivalent in the original server): AI opponents for PvP rooms. */
export const bots = defineResource({
  name: "bots",
  table: "bots (novo)",
  label: { "pt-BR": "Bots", en: "Bots" },
  singular: { "pt-BR": "bot", en: "bot" },
  description: "Adversários controlados pela IA nas salas: nome, nível, dificuldade e equipamentos.",
  icon: Bot,
  group: "players",
  idField: "id",
  titleField: "nickname",
  defaultSort: "level",
  fields: [
    { name: "id", label: "ID", type: "number", list: true, sortable: true, form: false },
    { name: "nickname", label: "Nome exibido", type: "text", required: true, maxLength: 20, list: true, sortable: true },
    { name: "sex", label: "Sexo", type: "select", required: true, options: [{ value: "m", label: "Masculino" }, { value: "f", label: "Feminino" }] },
    { name: "level", label: "Nível", type: "number", required: true, min: 1, max: 100, default: 10, list: true, sortable: true },
    {
      name: "difficulty",
      label: "Dificuldade",
      type: "select",
      required: true,
      list: true,
      options: [
        { value: "easy", label: "Fácil", tone: "mint" },
        { value: "normal", label: "Normal", tone: "sky" },
        { value: "hard", label: "Difícil", tone: "sun" },
        { value: "expert", label: "Especialista", tone: "coral" },
      ],
      hint: "Controla a precisão de ângulo/força e o uso de itens.",
    },
    { name: "weaponTemplateId", label: "Arma (TemplateID)", type: "number", min: 0, required: true },
    { name: "equips", label: "Equipamentos (TemplateIDs)", type: "tags", list: true, hint: "Chapéu, roupa, asas…" },
    { name: "guild", label: "Guilda exibida", type: "text" },
    { name: "enabled", label: "Ativo", type: "boolean", default: true, list: true, inlineToggle: true },
  ],
});
