import { Ban, Bot, Gift, ShieldCheck, Users } from "lucide-react";
import { defineResource } from "@/crud/types";

export const players = defineResource({
  name: "players",
  label: { "pt-BR": "Jogadores", en: "Players" },
  singular: { "pt-BR": "jogador", en: "player" },
  description: "Busque personagens, ajuste moedas e nível, bana ou envie itens.",
  icon: Users,
  group: "players",
  idField: "id",
  titleField: "nickname",
  defaultSort: "-level",
  searchPlaceholder: "Apelido, usuário ou ID…",
  capabilities: { create: false, delete: false },
  fields: [
    { name: "id", label: "ID", type: "number", list: true, sortable: true, readOnly: true },
    { name: "nickname", label: "Apelido", type: "text", list: true, sortable: true, readOnly: true },
    { name: "username", label: "Conta", type: "text", list: true, readOnly: true },
    { name: "online", label: "Online", type: "boolean", list: true, readOnly: true },
    { name: "level", label: "Nível", type: "number", min: 1, max: 100, list: true, sortable: true, required: true },
    { name: "gp", label: "EXP (GP)", type: "number", min: 0 },
    { name: "gold", label: "Ouro", type: "number", min: 0, list: true, sortable: true, required: true },
    { name: "money", label: "Cupons", type: "number", min: 0, list: true, sortable: true, required: true },
    { name: "giftToken", label: "Medalhas", type: "number", min: 0 },
    { name: "banned", label: "Banido", type: "boolean", list: true, readOnly: true },
    { name: "lastLoginAt", label: "Último acesso", type: "datetime", list: true, sortable: true, readOnly: true },
  ],
  rowActions: [
    {
      id: "give-item",
      label: { "pt-BR": "Dar item", en: "Give item" },
      icon: Gift,
      path: "give-item",
      success: "Item enviado",
      fields: [
        { name: "templateId", label: "TemplateID", type: "number", required: true, min: 1 },
        { name: "count", label: "Quantidade", type: "number", required: true, min: 1, default: 1 },
        { name: "validDays", label: "Validade (dias)", type: "number", min: 0, default: 0, hint: "0 = permanente" },
        { name: "viaMail", label: "Enviar por correio", type: "boolean", default: true },
      ],
    },
    {
      id: "ban",
      label: { "pt-BR": "Banir", en: "Ban" },
      icon: Ban,
      tone: "danger",
      path: "ban",
      success: "Jogador banido",
      visible: (r) => !r.banned,
      fields: [
        { name: "reason", label: "Motivo", type: "textarea", required: true },
        { name: "hours", label: "Duração (horas)", type: "number", min: 0, default: 24, hint: "0 = permanente" },
      ],
    },
    {
      id: "unban",
      label: { "pt-BR": "Desbanir", en: "Unban" },
      icon: ShieldCheck,
      path: "unban",
      confirm: "Remover o banimento deste jogador?",
      success: "Banimento removido",
      visible: (r) => !!r.banned,
    },
  ],
});

export const bots = defineResource({
  name: "bots",
  label: { "pt-BR": "Bots", en: "Bots" },
  singular: { "pt-BR": "bot", en: "bot" },
  description: "Adversários controlados pela IA nas salas: nome, nível, dificuldade e equipamentos.",
  icon: Bot,
  group: "players",
  idField: "id",
  titleField: "nickname",
  defaultSort: "level",
  fields: [
    { name: "id", label: "ID", type: "number", list: true, sortable: true, form: false },
    { name: "nickname", label: "Nome exibido", type: "text", required: true, maxLength: 20, list: true, sortable: true },
    { name: "sex", label: "Sexo", type: "select", required: true, options: [{ value: "m", label: "Masculino" }, { value: "f", label: "Feminino" }] },
    { name: "level", label: "Nível", type: "number", required: true, min: 1, max: 100, default: 10, list: true, sortable: true },
    {
      name: "difficulty",
      label: "Dificuldade",
      type: "select",
      required: true,
      list: true,
      options: [
        { value: "easy", label: "Fácil", tone: "mint" },
        { value: "normal", label: "Normal", tone: "sky" },
        { value: "hard", label: "Difícil", tone: "sun" },
        { value: "expert", label: "Especialista", tone: "coral" },
      ],
      hint: "Controla a precisão de ângulo/força e o uso de itens.",
    },
    { name: "weaponTemplateId", label: "Arma (TemplateID)", type: "number", min: 0, required: true },
    { name: "equips", label: "Equipamentos (TemplateIDs)", type: "tags", list: true, hint: "Chapéu, roupa, asas…" },
    { name: "guild", label: "Guilda exibida", type: "text" },
    { name: "enabled", label: "Ativo", type: "boolean", default: true, list: true, inlineToggle: true },
  ],
});
