// AUTO-GENERATED by scripts/gen-schema.ts from Project_Game34 catalog.json — DO NOT EDIT.
/* eslint-disable */
import { bigint, boolean, doublePrecision, integer, numeric, primaryKey, text, timestamp, varchar } from "drizzle-orm/pg-core";
import { game } from "./schemas.js";

/** Project_Game34.dbo.Achievement — 281 rows in source; PK (ID) */
export const Achievement = game.table(
  "Achievement",
  {
    ID: integer("ID").notNull(),
    PlaceID: integer("PlaceID").notNull(),
    Title: varchar("Title", { length: 100 }).notNull(),
    Detail: varchar("Detail", { length: 500 }).notNull(),
    NeedMinLevel: integer("NeedMinLevel").notNull(),
    NeedMaxLevel: integer("NeedMaxLevel").notNull(),
    PreAchievementID: varchar("PreAchievementID", { length: 100 }).notNull(),
    IsOther: integer("IsOther").notNull(),
    AchievementType: integer("AchievementType").notNull(),
    CanHide: boolean("CanHide").notNull(),
    StartDate: timestamp("StartDate", { precision: 3, mode: "date" }).notNull(),
    EndDate: timestamp("EndDate", { precision: 3, mode: "date" }).notNull(),
    AchievementPoint: integer("AchievementPoint").notNull(),
    IsActive: integer("IsActive").notNull(),
    PicID: integer("PicID").notNull(),
    IsShare: boolean("IsShare").notNull(),
  },
  (t) => [
    primaryKey({ name: "Achievement_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Achievement_Goods — 60 rows in source; heap (no PK) */
export const Achievement_Goods = game.table(
  "Achievement_Goods",
  {
    AchievementID: integer("AchievementID").notNull(),
    RewardType: integer("RewardType").notNull(),
    RewardPara: varchar("RewardPara", { length: 500 }).notNull(),
    RewardValueId: integer("RewardValueId").notNull(),
    RewardCount: integer("RewardCount").notNull(),
  },
);

/** Project_Game34.dbo.AchievementCondition — 341 rows in source; PK (AchievementID, CondictionID) */
export const AchievementCondition = game.table(
  "AchievementCondition",
  {
    AchievementID: integer("AchievementID").notNull(),
    CondictionID: integer("CondictionID").notNull().default(0),
    CondictionType: integer("CondictionType").notNull().default(0),
    Condiction_Para1: varchar("Condiction_Para1", { length: 150 }),
    Condiction_Para2: integer("Condiction_Para2").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "AchievementCondition_pkey", columns: [t.AchievementID, t.CondictionID] }),
  ],
);

/** Project_Game34.dbo.Active — 33 rows in source; PK (ActiveID) */
export const Active = game.table(
  "Active",
  {
    ActiveID: integer("ActiveID").notNull(),
    Title: varchar("Title", { length: 200 }).notNull(),
    Description: varchar("Description", { length: 2000 }),
    Content: varchar("Content", { length: 2000 }),
    AwardContent: varchar("AwardContent", { length: 2000 }),
    HasKey: integer("HasKey").notNull().default(0),
    StartDate: timestamp("StartDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    EndDate: timestamp("EndDate", { precision: 3, mode: "date" }),
    IsOnly: integer("IsOnly").notNull().default(0),
    Type: integer("Type").notNull().default(0),
    ActionTimeContent: varchar("ActionTimeContent", { length: 50 }),
    IsAdvance: boolean("IsAdvance").notNull().default(false),
    GoodsExchangeTypes: varchar("GoodsExchangeTypes", { length: 50 }),
    GoodsExchangeNum: varchar("GoodsExchangeNum", { length: 50 }),
    limitType: varchar("limitType", { length: 50 }),
    limitValue: varchar("limitValue", { length: 50 }),
    IsShow: boolean("IsShow").notNull().default(false),
    ActiveType: integer("ActiveType").notNull().default(0),
    IconID: integer("IconID").notNull().default(0),
    CanCreateCode: boolean("CanCreateCode"),
  },
  (t) => [
    primaryKey({ name: "Active_pkey", columns: [t.ActiveID] }),
  ],
);

/** Project_Game34.dbo.Active_Award — 310 rows in source; PK (ID) */
export const Active_Award = game.table(
  "Active_Award",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ActiveID: integer("ActiveID").notNull(),
    ItemID: integer("ItemID").notNull(),
    Count: integer("Count").notNull().default(1),
    ValidDate: integer("ValidDate").notNull().default(0),
    StrengthenLevel: integer("StrengthenLevel").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    LuckCompose: integer("LuckCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull().default(0),
    Gold: integer("Gold").notNull().default(0),
    Money: integer("Money").notNull().default(0),
    Sex: integer("Sex").notNull().default(0),
    Mark: integer("Mark").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Active_Award_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Active_Convert_Item — 0 rows in source; PK (ID) */
export const Active_Convert_Item = game.table(
  "Active_Convert_Item",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ActiveID: integer("ActiveID").notNull().default(0),
    TemplateID: integer("TemplateID").notNull().default(0),
    ItemType: integer("ItemType").notNull().default(0),
    ItemCount: integer("ItemCount").notNull().default(1),
    LimitValue: integer("LimitValue").notNull().default(-1),
    IsBind: boolean("IsBind").notNull().default(true),
    ValidDate: integer("ValidDate").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Active_Convert_Item_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Activity_System_Item — 242 rows in source; PK (ID) */
export const Activity_System_Item = game.table(
  "Activity_System_Item",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ActivityType: integer("ActivityType").notNull().default(0),
    Quality: integer("Quality").notNull().default(0),
    TemplateID: integer("TemplateID").notNull().default(0),
    Count: integer("Count").notNull().default(1),
    ValidDate: integer("ValidDate").notNull().default(0),
    IsBind: boolean("IsBind").notNull().default(true),
    StrengthLevel: integer("StrengthLevel").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull().default(0),
    LuckCompose: integer("LuckCompose").notNull().default(0),
    Probability: integer("Probability").notNull().default(10000),
  },
  (t) => [
    primaryKey({ name: "Activity_System_Item_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.AreaConfig — 2 rows in source; heap (no PK) */
export const AreaConfig = game.table(
  "AreaConfig",
  {
    AreaID: integer("AreaID").notNull().default(0),
    AreaServer: varchar("AreaServer", { length: 150 }).notNull().default(""),
    AreaName: varchar("AreaName", { length: 150 }).notNull().default(""),
    DataSource: varchar("DataSource", { length: 150 }).notNull().default(""),
    Catalog: varchar("Catalog", { length: 150 }).notNull().default(""),
    UserID: varchar("UserID", { length: 150 }).notNull().default(""),
    Password: varchar("Password", { length: 150 }).notNull().default(""),
    RequestLink: varchar("RequestLink", { length: 150 }),
    ResourceLink: varchar("ResourceLink", { length: 150 }),
    Version: varchar("Version", { length: 150 }),
  },
);

/** Project_Game34.dbo.Ball — 1586 rows in source; PK (ID) */
export const Ball = game.table(
  "Ball",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 200 }),
    Power: doublePrecision("Power").notNull(),
    Radii: integer("Radii").notNull(),
    FlyingPartical: varchar("FlyingPartical", { length: 200 }),
    BombPartical: varchar("BombPartical", { length: 200 }),
    Crater: varchar("Crater", { length: 200 }),
    AttackResponse: integer("AttackResponse").notNull(),
    IsSpin: boolean("IsSpin").notNull(),
    Mass: integer("Mass").notNull(),
    SpinVA: doublePrecision("SpinVA").notNull(),
    SpinV: integer("SpinV").notNull(),
    Amount: integer("Amount").notNull(),
    Wind: integer("Wind").notNull(),
    DragIndex: integer("DragIndex").notNull(),
    Weight: integer("Weight").notNull(),
    Shake: boolean("Shake").notNull(),
    ShootSound: varchar("ShootSound", { length: 50 }),
    BombSound: varchar("BombSound", { length: 50 }),
    Delay: integer("Delay").notNull(),
    ActionType: integer("ActionType").notNull(),
    HasTunnel: boolean("HasTunnel").notNull(),
  },
  (t) => [
    primaryKey({ name: "Ball_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.BallConfig — 781 rows in source; PK (TemplateID) */
export const BallConfig = game.table(
  "BallConfig",
  {
    TemplateID: integer("TemplateID").notNull(),
    Common: integer("Common"),
    CommonAddWound: integer("CommonAddWound"),
    CommonMultiBall: integer("CommonMultiBall"),
    Special: integer("Special"),
  },
  (t) => [
    primaryKey({ name: "BallConfig_pkey", columns: [t.TemplateID] }),
  ],
);

/** Project_Game34.dbo.Card_Buff — 60 rows in source; PK (ID) */
export const Card_Buff = game.table(
  "Card_Buff",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    CardID: integer("CardID").notNull().default(0),
    condition: integer("condition").notNull().default(0),
    PropertiesDscripID: integer("PropertiesDscripID").notNull().default(0),
    value: varchar("value", { length: 50 }),
    Description: varchar("Description", { length: 1050 }),
  },
  (t) => [
    primaryKey({ name: "Card_Buff_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Card_Groove_Update — 92 rows in source; PK (ID) */
export const Card_Groove_Update = game.table(
  "Card_Groove_Update",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Level: integer("Level").notNull().default(0),
    Type: integer("Type").notNull().default(0),
    Exp: integer("Exp").notNull().default(0),
    Attack: integer("Attack").notNull().default(0),
    Defend: integer("Defend").notNull().default(0),
    Agility: integer("Agility").notNull().default(0),
    Lucky: integer("Lucky").notNull().default(0),
    Damage: integer("Damage").notNull().default(0),
    Guard: integer("Guard").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Card_Groove_Update_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Card_Group — 73 rows in source; PK (ID) */
export const Card_Group = game.table(
  "Card_Group",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    CardID: integer("CardID").notNull(),
    TemplateID: integer("TemplateID").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Card_Group_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Card_Info — 15 rows in source; PK (ID) */
export const Card_Info = game.table(
  "Card_Info",
  {
    ID: integer("ID").notNull(),
    SuitID: integer("SuitID").notNull(),
    Name: varchar("Name", { length: 250 }),
    Description: varchar("Description", { length: 1050 }),
  },
  (t) => [
    primaryKey({ name: "Card_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Card_Template_Info — 250 rows in source; PK (ID) */
export const Card_Template_Info = game.table(
  "Card_Template_Info",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    CardID: integer("CardID").notNull(),
    CardType: integer("CardType").notNull(),
    probability: integer("probability").notNull(),
    AttackRate: integer("AttackRate").notNull(),
    AddAttack: integer("AddAttack").notNull(),
    DefendRate: integer("DefendRate").notNull(),
    AddDefend: integer("AddDefend").notNull(),
    AgilityRate: integer("AgilityRate").notNull(),
    AddAgility: integer("AddAgility").notNull(),
    LuckyRate: integer("LuckyRate").notNull(),
    AddLucky: integer("AddLucky").notNull(),
    DamageRate: integer("DamageRate").notNull(),
    AddDamage: integer("AddDamage").notNull(),
    GuardRate: integer("GuardRate").notNull(),
    AddGuard: integer("AddGuard").notNull(),
  },
  (t) => [
    primaryKey({ name: "Card_Template_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.CardUpdateCondition — 31 rows in source; PK (Level) */
export const CardUpdateCondition = game.table(
  "CardUpdateCondition",
  {
    Level: integer("Level").notNull(),
    Exp: integer("Exp").notNull(),
    MinExp: integer("MinExp").notNull(),
    MaxExp: integer("MaxExp").notNull(),
    UpdateCardCount: integer("UpdateCardCount").notNull(),
    ResetCardCount: integer("ResetCardCount").notNull(),
    ResetMoney: integer("ResetMoney").notNull(),
  },
  (t) => [
    primaryKey({ name: "CardUpdateCondition_pkey", columns: [t.Level] }),
  ],
);

/** Project_Game34.dbo.CardUpdateInfo — 1470 rows in source; PK (Id, Level) */
export const CardUpdateInfo = game.table(
  "CardUpdateInfo",
  {
    Id: integer("Id").notNull(),
    Level: integer("Level").notNull(),
    Attack: integer("Attack").notNull(),
    Defend: integer("Defend").notNull(),
    Agility: integer("Agility").notNull(),
    Lucky: integer("Lucky").notNull(),
    Guard: integer("Guard").notNull(),
    Damage: integer("Damage").notNull(),
  },
  (t) => [
    primaryKey({ name: "CardUpdateInfo_pkey", columns: [t.Id, t.Level] }),
  ],
);

/** Project_Game34.dbo.ClothGroupTemplateInfo — 270 rows in source; PK (ItemID) */
export const ClothGroupTemplateInfo = game.table(
  "ClothGroupTemplateInfo",
  {
    ItemID: integer("ItemID").generatedByDefaultAsIdentity().notNull(),
    ID: integer("ID").notNull(),
    TemplateID: integer("TemplateID").notNull(),
    Sex: integer("Sex").notNull(),
    Description: integer("Description").notNull(),
    Cost: integer("Cost").notNull(),
  },
  (t) => [
    primaryKey({ name: "ClothGroupTemplateInfo_pkey", columns: [t.ItemID] }),
  ],
);

/** Project_Game34.dbo.ClothPropertyTemplateInfo — 23 rows in source; PK (ID) */
export const ClothPropertyTemplateInfo = game.table(
  "ClothPropertyTemplateInfo",
  {
    ID: integer("ID").notNull(),
    Sex: integer("Sex").notNull(),
    Name: varchar("Name", { length: 500 }).notNull(),
    Attack: integer("Attack").notNull(),
    Defend: integer("Defend").notNull(),
    Agility: integer("Agility").notNull(),
    Luck: integer("Luck").notNull(),
    Blood: integer("Blood").notNull(),
    Damage: integer("Damage").notNull(),
    Guard: integer("Guard").notNull(),
    Cost: integer("Cost").notNull(),
  },
  (t) => [
    primaryKey({ name: "ClothPropertyTemplateInfo_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Communal_Active — 4 rows in source; heap (no PK) */
export const Communal_Active = game.table(
  "Communal_Active",
  {
    ActiveID: integer("ActiveID").notNull().default(1),
    BeginTime: timestamp("BeginTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    EndTime: timestamp("EndTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    LimitGrade: integer("LimitGrade").notNull().default(0),
    DayMaxScore: integer("DayMaxScore").notNull().default(0),
    MinScore: integer("MinScore").notNull().default(0),
    AddPropertyByMoney: varchar("AddPropertyByMoney", { length: 50 }),
    AddPropertyByProp: varchar("AddPropertyByProp", { length: 50 }),
    IsReset: boolean("IsReset").notNull().default(false),
    IsSendAward: boolean("IsSendAward").notNull().default(false),
  },
);

/** Project_Game34.dbo.Communal_Active_Award — 25 rows in source; PK (ID) */
export const Communal_Active_Award = game.table(
  "Communal_Active_Award",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ActiveID: integer("ActiveID").notNull().default(0),
    IsArea: integer("IsArea").notNull().default(1),
    RandID: integer("RandID").notNull().default(0),
    TemplateID: integer("TemplateID").notNull().default(0),
    StrengthenLevel: integer("StrengthenLevel").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull().default(0),
    LuckCompose: integer("LuckCompose").notNull().default(0),
    Count: integer("Count").notNull().default(1),
    IsBind: boolean("IsBind").notNull().default(true),
    IsTime: boolean("IsTime").notNull().default(true),
    ValidDate: integer("ValidDate").notNull().default(7),
  },
  (t) => [
    primaryKey({ name: "Communal_Active_Award_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Communal_Active_Exp — 6 rows in source; PK (Grade) */
export const Communal_Active_Exp = game.table(
  "Communal_Active_Exp",
  {
    ActiveID: integer("ActiveID").notNull().default(0),
    Grade: integer("Grade").notNull().default(0),
    Exp: integer("Exp").notNull().default(0),
    AddExpPlus: integer("AddExpPlus").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Communal_Active_Exp_pkey", columns: [t.Grade] }),
  ],
);

/** Project_Game34.dbo.Consortia_Badge — 10 rows in source; PK (BadgeID) */
export const Consortia_Badge = game.table(
  "Consortia_Badge",
  {
    BadgeID: integer("BadgeID").notNull(),
    BadgeName: varchar("BadgeName", { length: 100 }).notNull(),
    Cost: integer("Cost").notNull(),
    LimitLevel: integer("LimitLevel").notNull(),
    ValidDate: integer("ValidDate").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Badge_pkey", columns: [t.BadgeID] }),
  ],
);

/** Project_Game34.dbo.Consortia_BuffTemp — 40 rows in source; PK (id) */
export const Consortia_BuffTemp = game.table(
  "Consortia_BuffTemp",
  {
    id: integer("id").notNull(),
    name: varchar("name", { length: 100 }).notNull(),
    descript: varchar("descript", { length: 500 }).notNull(),
    type: integer("type").notNull(),
    level: integer("level").notNull(),
    value: integer("value").notNull(),
    riches: integer("riches").notNull(),
    metal: integer("metal").notNull().default(0),
    pic: integer("pic").notNull(),
    group: integer("group").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_BuffTemp_pkey", columns: [t.id] }),
  ],
);

/** Project_Game34.dbo.Consortia_Level — 10 rows in source; PK (Level) */
export const Consortia_Level = game.table(
  "Consortia_Level",
  {
    Level: integer("Level").notNull(),
    Riches: integer("Riches").notNull(),
    Deduct: integer("Deduct").notNull(),
    NeedGold: integer("NeedGold").notNull(),
    NeedItem: integer("NeedItem").notNull(),
    Reward: integer("Reward").notNull(),
    Count: integer("Count").notNull(),
    StoreRiches: integer("StoreRiches").notNull().default(100),
    SmithRiches: integer("SmithRiches").notNull().default(100),
    ShopRiches: integer("ShopRiches").notNull().default(100),
    BufferRiches: integer("BufferRiches").notNull().default(0),
    KickMax: integer("KickMax").notNull().default(10),
    BossCount: integer("BossCount").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Consortia_Level_pkey", columns: [t.Level] }),
  ],
);

/** Project_Game34.dbo.Consortia_TaskAward — 4 rows in source; PK (ID) */
export const Consortia_TaskAward = game.table(
  "Consortia_TaskAward",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Lv: integer("Lv").notNull(),
    ItemID: integer("ItemID").notNull(),
    Count: integer("Count").notNull(),
    ValidDate: integer("ValidDate").notNull(),
    StrengthenLevel: integer("StrengthenLevel").notNull(),
    AttackCompose: integer("AttackCompose").notNull(),
    DefendCompose: integer("DefendCompose").notNull(),
    LuckCompose: integer("LuckCompose").notNull(),
    AgilityCompose: integer("AgilityCompose").notNull(),
    IsBind: boolean("IsBind").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_TaskAward_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Consortia_TaskConfig — 70 rows in source; PK (ID) */
export const Consortia_TaskConfig = game.table(
  "Consortia_TaskConfig",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Content: text("Content").notNull(),
    Type: integer("Type").notNull(),
    Target: integer("Target").notNull(),
    TargetCount: integer("TargetCount").notNull(),
    Para1: integer("Para1").notNull(),
    Para2: integer("Para2").notNull(),
    Level: integer("Level").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_TaskConfig_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Daily_Award — 20 rows in source; PK (ID) */
export const Daily_Award = game.table(
  "Daily_Award",
  {
    ID: integer("ID").notNull(),
    Type: integer("Type").notNull(),
    TemplateID: integer("TemplateID").notNull(),
    Count: integer("Count").notNull(),
    ValidDate: integer("ValidDate").notNull(),
    IsBinds: boolean("IsBinds").notNull(),
    Sex: integer("Sex").notNull().default(0),
    Remark: varchar("Remark", { length: 200 }),
    CountRemark: varchar("CountRemark", { length: 100 }),
    GetWay: integer("GetWay").notNull().default(0),
    AwardDays: integer("AwardDays").notNull(),
  },
  (t) => [
    primaryKey({ name: "Daily_Award_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.DailyLeagueAwardItems — 93 rows in source; PK (ID) */
export const DailyLeagueAwardItems = game.table(
  "DailyLeagueAwardItems",
  {
    ID: integer("ID").notNull(),
    Class: integer("Class").notNull(),
    TemplateID: integer("TemplateID").notNull(),
    StrengthLevel: integer("StrengthLevel").default(0),
    AttackCompose: integer("AttackCompose").default(0),
    DefendCompose: integer("DefendCompose").default(0),
    LuckCompose: integer("LuckCompose").default(0),
    AgilityCompose: integer("AgilityCompose").default(0),
    IsBind: boolean("IsBind").default(true),
    ValidDate: integer("ValidDate").default(0),
    Count: integer("Count").notNull(),
  },
  (t) => [
    primaryKey({ name: "DailyLeagueAwardItems_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.DailyLeagueAwardList — 30 rows in source; heap (no PK) */
export const DailyLeagueAwardList = game.table(
  "DailyLeagueAwardList",
  {
    Class: integer("Class").notNull(),
    Grade: integer("Grade").notNull(),
    Score: integer("Score").notNull(),
    Rank: integer("Rank").default(0),
  },
);

/** Project_Game34.dbo.DailyLeagueLevel — 14 rows in source; heap (no PK) */
export const DailyLeagueLevel = game.table(
  "DailyLeagueLevel",
  {
    Level: integer("Level").notNull(),
    Name: varchar("Name", { length: 500 }).notNull(),
    Score: integer("Score").notNull(),
  },
);

/** Project_Game34.dbo.Drop_Condiction — 112 rows in source; PK (DropID) */
export const Drop_Condiction = game.table(
  "Drop_Condiction",
  {
    DropID: integer("DropID").notNull(),
    CondictionType: integer("CondictionType").notNull(),
    Para1: varchar("Para1", { length: 500 }).notNull(),
    Para2: varchar("Para2", { length: 500 }).notNull(),
    Name: varchar("Name", { length: 150 }).notNull().default(""),
    Detail: varchar("Detail", { length: 1500 }),
  },
  (t) => [
    primaryKey({ name: "Drop_Condiction_pkey", columns: [t.DropID] }),
  ],
);

/** Project_Game34.dbo.Drop_Item — 3023 rows in source; PK (Id) */
export const Drop_Item = game.table(
  "Drop_Item",
  {
    Id: integer("Id").generatedByDefaultAsIdentity().notNull(),
    DropId: integer("DropId").notNull().default(0),
    ItemId: integer("ItemId").notNull().default(0),
    ValueDate: integer("ValueDate").notNull().default(0),
    IsBind: boolean("IsBind").notNull(),
    Random: integer("Random").notNull().default(0),
    BeginData: integer("BeginData").notNull().default(0),
    EndData: integer("EndData").notNull().default(0),
    IsTips: boolean("IsTips").notNull().default(false),
    IsLogs: boolean("IsLogs").notNull().default(false),
  },
  (t) => [
    primaryKey({ name: "Drop_Item_pkey", columns: [t.Id] }),
  ],
);

/** Project_Game34.dbo.Edictum_List — 1 rows in source; PK (ID) */
export const Edictum_List = game.table(
  "Edictum_List",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Title: varchar("Title", { length: 200 }).notNull(),
    BeginDate: timestamp("BeginDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    BeginTime: timestamp("BeginTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    EndDate: timestamp("EndDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    EndTime: timestamp("EndTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    Text: text("Text").notNull(),
    IsExist: boolean("IsExist").notNull(),
  },
  (t) => [
    primaryKey({ name: "Edictum_List_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Event_Award_Item — 432 rows in source; PK (ID) */
export const Event_Award_Item = game.table(
  "Event_Award_Item",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ActivityType: integer("ActivityType").notNull().default(0),
    TemplateID: integer("TemplateID").notNull().default(0),
    Count: integer("Count").notNull().default(1),
    ValidDate: integer("ValidDate").notNull().default(0),
    IsBinds: boolean("IsBinds").notNull().default(true),
    StrengthenLevel: integer("StrengthenLevel").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull().default(0),
    LuckCompose: integer("LuckCompose").notNull().default(0),
    Random: integer("Random").notNull().default(10000),
    IsSelect: boolean("IsSelect").notNull().default(false),
  },
  (t) => [
    primaryKey({ name: "Event_Award_Item_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Event_Live — 141 rows in source; heap (no PK) */
export const Event_Live = game.table(
  "Event_Live",
  {
    EventID: integer("EventID"),
    Description: varchar("Description", { length: 1000 }),
    CondictionType: integer("CondictionType"),
    Condiction_Para1: integer("Condiction_Para1"),
    Condiction_Para2: integer("Condiction_Para2"),
    StartDate: timestamp("StartDate", { precision: 3, mode: "date" }),
    EndDate: timestamp("EndDate", { precision: 3, mode: "date" }),
  },
);

/** Project_Game34.dbo.Event_LiveGoods — 386 rows in source; heap (no PK) */
export const Event_LiveGoods = game.table(
  "Event_LiveGoods",
  {
    EventID: integer("EventID").notNull(),
    TemplateID: integer("TemplateID").notNull(),
    ValidDate: integer("ValidDate").default(7),
    Count: integer("Count").default(1),
    StrengthenLevel: integer("StrengthenLevel").default(0),
    AttackCompose: integer("AttackCompose").default(0),
    DefendCompose: integer("DefendCompose").default(0),
    AgilityCompose: integer("AgilityCompose").default(0),
    LuckCompose: integer("LuckCompose").default(0),
    IsBind: boolean("IsBind").default(true),
  },
);

/** Project_Game34.dbo.Event_Reward_Goods — 75 rows in source; heap (no PK) */
export const Event_Reward_Goods = game.table(
  "Event_Reward_Goods",
  {
    ActivityType: integer("ActivityType").notNull(),
    SubActivityType: integer("SubActivityType").notNull(),
    TemplateId: integer("TemplateId").notNull(),
    StrengthLevel: integer("StrengthLevel").default(0),
    AttackCompose: integer("AttackCompose").default(0),
    DefendCompose: integer("DefendCompose").default(0),
    LuckCompose: integer("LuckCompose").default(0),
    AgilityCompose: integer("AgilityCompose").default(0),
    IsBind: boolean("IsBind").default(true),
    ValidDate: integer("ValidDate").default(0),
    Count: integer("Count").default(1),
  },
);

/** Project_Game34.dbo.Event_Reward_Info — 15 rows in source; heap (no PK) */
export const Event_Reward_Info = game.table(
  "Event_Reward_Info",
  {
    ActivityType: integer("ActivityType").notNull(),
    SubActivityType: integer("SubActivityType").notNull(),
    Condition: integer("Condition").notNull(),
  },
);

/** Project_Game34.dbo.ExerciseInfo — 70 rows in source; PK (Grage) */
export const ExerciseInfo = game.table(
  "ExerciseInfo",
  {
    Grage: integer("Grage").notNull(),
    GP: integer("GP").notNull().default(0),
    ExerciseA: integer("ExerciseA").notNull().default(0),
    ExerciseAG: integer("ExerciseAG").notNull().default(0),
    ExerciseD: integer("ExerciseD").notNull().default(0),
    ExerciseH: integer("ExerciseH").notNull().default(0),
    ExerciseL: integer("ExerciseL").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "ExerciseInfo_pkey", columns: [t.Grage] }),
  ],
);

/** Project_Game34.dbo.Fair_Battle_Reward_Temp — 16 rows in source; heap (no PK) */
export const Fair_Battle_Reward_Temp = game.table(
  "Fair_Battle_Reward_Temp",
  {
    Prestige: integer("Prestige").notNull(),
    Level: integer("Level").notNull(),
    Name: varchar("Name", { length: 50 }),
    PrestigeForWin: integer("PrestigeForWin").notNull(),
    PrestigeForLose: integer("PrestigeForLose").notNull(),
    Title: varchar("Title", { length: 50 }),
  },
);

/** Project_Game34.dbo.Fight_Rate — 4 rows in source; PK (ID) */
export const Fight_Rate = game.table(
  "Fight_Rate",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ServerID: integer("ServerID").notNull().default(0),
    Rate: integer("Rate").notNull().default(0),
    BeginDay: timestamp("BeginDay", { precision: 3, mode: "date" }).notNull(),
    EndDay: timestamp("EndDay", { precision: 3, mode: "date" }).notNull(),
    BeginTime: timestamp("BeginTime", { precision: 3, mode: "date" }).notNull(),
    EndTime: timestamp("EndTime", { precision: 3, mode: "date" }).notNull(),
    BoyTemplateID: integer("BoyTemplateID").notNull(),
    GirlTemplateID: integer("GirlTemplateID").notNull(),
    SelfCue: varchar("SelfCue", { length: 200 }),
    EnemyCue: varchar("EnemyCue", { length: 200 }),
    Name: varchar("Name", { length: 50 }),
  },
  (t) => [
    primaryKey({ name: "Fight_Rate_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Fight_Record — 0 rows in source; PK (ID) */
export const Fight_Record = game.table(
  "Fight_Record",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    PlayBegin: timestamp("PlayBegin", { precision: 3, mode: "date" }).notNull(),
    PlayEnd: timestamp("PlayEnd", { precision: 3, mode: "date" }).notNull(),
    ChangeTeam: integer("ChangeTeam").notNull(),
    TeamA: varchar("TeamA", { length: 50 }),
    TeamB: varchar("TeamB", { length: 50 }),
    MapID: integer("MapID").notNull(),
    RoomType: integer("RoomType").notNull(),
    FightName: varchar("FightName", { length: 50 }),
    WinTeam: integer("WinTeam").notNull(),
  },
  (t) => [
    primaryKey({ name: "Fight_Record_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Fight_Spirit_Templatelist — 30 rows in source; PK (ID) */
export const Fight_Spirit_Templatelist = game.table(
  "Fight_Spirit_Templatelist",
  {
    ID: integer("ID").notNull(),
    FightSpiritID: integer("FightSpiritID").notNull().default(0),
    FightSpiritIcon: varchar("FightSpiritIcon", { length: 50 }).notNull().default(""),
    Level: integer("Level").notNull().default(0),
    Exp: integer("Exp").notNull().default(0),
    Attack: integer("Attack").notNull().default(0),
    Defence: integer("Defence").notNull().default(0),
    Agility: integer("Agility").notNull().default(0),
    Lucky: integer("Lucky").notNull().default(0),
    Blood: integer("Blood").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Fight_Spirit_Templatelist_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Fusion — 96 rows in source; PK (FusionID) */
export const Fusion = game.table(
  "Fusion",
  {
    FusionID: integer("FusionID").notNull(),
    Item1: integer("Item1").notNull().default(0),
    Item2: integer("Item2").notNull().default(0),
    Item3: integer("Item3").notNull().default(0),
    Item4: integer("Item4").notNull().default(0),
    Item5: integer("Item5").notNull().default(0),
    Item6: integer("Item6").notNull().default(0),
    Item7: integer("Item7").notNull().default(0),
    Item8: integer("Item8").notNull().default(0),
    Item9: integer("Item9").notNull().default(0),
    Item10: integer("Item10").notNull().default(0),
    Reward1: integer("Reward1").notNull().default(0),
    Random1: integer("Random1").notNull().default(0),
    Reward2: integer("Reward2").notNull().default(0),
    Random2: integer("Random2").notNull().default(0),
    Reward3: integer("Reward3").notNull().default(0),
    Random3: integer("Random3").notNull().default(0),
    Leave: integer("Leave").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Fusion_pkey", columns: [t.FusionID] }),
  ],
);

/** Project_Game34.dbo.Game_Map — 454 rows in source; PK (ID) */
export const Game_Map = game.table(
  "Game_Map",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 50 }),
    PosX: varchar("PosX", { length: 200 }),
    PosX1: varchar("PosX1", { length: 200 }),
    Description: varchar("Description", { length: 2000 }),
    ForegroundWidth: integer("ForegroundWidth").notNull(),
    ForegroundHeight: integer("ForegroundHeight").notNull(),
    BackroundWidht: integer("BackroundWidht").notNull(),
    BackroundHeight: integer("BackroundHeight").notNull(),
    DeadWidth: integer("DeadWidth").notNull(),
    DeadHeight: integer("DeadHeight").notNull(),
    Weight: integer("Weight").notNull(),
    DragIndex: integer("DragIndex").notNull(),
    ForePic: varchar("ForePic", { length: 200 }),
    BackPic: varchar("BackPic", { length: 200 }),
    DeadPic: varchar("DeadPic", { length: 200 }),
    Pic: varchar("Pic", { length: 200 }),
    Remark: varchar("Remark", { length: 50 }),
    BackMusic: varchar("BackMusic", { length: 200 }),
    Type: integer("Type").notNull(),
  },
  (t) => [
    primaryKey({ name: "Game_Map_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.GoldEquipTemplateLoad — 277 rows in source; PK (ID) */
export const GoldEquipTemplateLoad = game.table(
  "GoldEquipTemplateLoad",
  {
    ID: integer("ID").notNull(),
    OldTemplateId: integer("OldTemplateId").notNull().default(0),
    NewTemplateId: integer("NewTemplateId").notNull().default(0),
    CategoryID: integer("CategoryID").notNull().default(0),
    Strengthen: integer("Strengthen").notNull().default(13),
    Attack: integer("Attack").notNull().default(-1),
    Defence: integer("Defence").notNull().default(-1),
    Agility: integer("Agility").notNull().default(-1),
    Luck: integer("Luck").notNull().default(-1),
    Damage: integer("Damage").notNull().default(-1),
    Guard: integer("Guard").notNull().default(-1),
    Boold: integer("Boold").notNull().default(0),
    BlessID: integer("BlessID").notNull(),
    Pic: varchar("Pic", { length: 50 }),
  },
  (t) => [
    primaryKey({ name: "GoldEquipTemplateLoad_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.HotSpringRoom — 13 rows in source; PK (roomID) */
export const HotSpringRoom = game.table(
  "HotSpringRoom",
  {
    roomNumber: integer("roomNumber").notNull(),
    roomID: integer("roomID").notNull(),
    roomName: varchar("roomName", { length: 100 }).notNull(),
    roomPassword: varchar("roomPassword", { length: 100 }),
    effectiveTime: integer("effectiveTime").notNull().default(0),
    curCount: integer("curCount").notNull().default(0),
    playerID: integer("playerID").notNull().default(0),
    playerName: varchar("playerName", { length: 500 }).notNull().default("unknown"),
    startTime: timestamp("startTime", { precision: 3, mode: "date" }),
    endTime: timestamp("endTime", { precision: 3, mode: "date" }),
    roomIntroduction: text("roomIntroduction"),
    roomType: integer("roomType").notNull().default(0),
    maxCount: integer("maxCount").notNull().default(10),
  },
  (t) => [
    primaryKey({ name: "HotSpringRoom_pkey", columns: [t.roomID] }),
  ],
);

/** Project_Game34.dbo.Item_Fusion — 326 rows in source; PK (FusionID) */
export const Item_Fusion = game.table(
  "Item_Fusion",
  {
    FusionID: integer("FusionID").generatedByDefaultAsIdentity().notNull(),
    Item1: integer("Item1").notNull().default(0),
    Item2: integer("Item2").notNull().default(0),
    Item3: integer("Item3").notNull().default(0),
    Item4: integer("Item4").notNull().default(0),
    Formula: integer("Formula").notNull().default(0),
    Reward: integer("Reward").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Item_Fusion_pkey", columns: [t.FusionID] }),
  ],
);

/** Project_Game34.dbo.Item_Record — 0 rows in source; PK (Id) */
export const Item_Record = game.table(
  "Item_Record",
  {
    Id: bigint("Id", { mode: "number" }).generatedByDefaultAsIdentity().notNull(),
    AgentsID: integer("AgentsID").notNull(),
    ServerID: integer("ServerID").notNull(),
    Timer: timestamp("Timer", { precision: 3, mode: "date" }).notNull(),
    UserID: integer("UserID").notNull(),
    UserName: varchar("UserName", { length: 50 }).notNull(),
    Operation: integer("Operation").notNull(),
    ItemName: varchar("ItemName", { length: 50 }).notNull(),
    ItemID: integer("ItemID").notNull(),
    BeginProperty: varchar("BeginProperty", { length: 200 }).notNull(),
    EndProperty: varchar("EndProperty", { length: 200 }).notNull(),
    Result: integer("Result").notNull(),
  },
  (t) => [
    primaryKey({ name: "Item_Record_pkey", columns: [t.Id] }),
  ],
);

/** Project_Game34.dbo.Item_Refinery — 0 rows in source; PK (RefineryID) */
export const Item_Refinery = game.table(
  "Item_Refinery",
  {
    RefineryID: integer("RefineryID").notNull(),
    Equip1: integer("Equip1"),
    Equip2: integer("Equip2"),
    Equip3: integer("Equip3"),
    Item1: integer("Item1"),
    Item2: integer("Item2"),
    Item3: integer("Item3"),
    Item1Count: integer("Item1Count"),
    Item2Count: integer("Item2Count"),
    Item3Count: integer("Item3Count"),
    Material1: integer("Material1"),
    Operate1: integer("Operate1"),
    Reward1: integer("Reward1"),
    Material2: integer("Material2"),
    Operate2: integer("Operate2"),
    Reward2: integer("Reward2"),
    Material3: integer("Material3"),
    Operate3: integer("Operate3"),
    Reward3: integer("Reward3"),
    Material4: integer("Material4"),
    Operate4: integer("Operate4"),
    Reward4: integer("Reward4"),
  },
  (t) => [
    primaryKey({ name: "Item_Refinery_pkey", columns: [t.RefineryID] }),
  ],
);

/** Project_Game34.dbo.Item_Refinery_Strengthen — 15 rows in source; heap (no PK) */
export const Item_Refinery_Strengthen = game.table(
  "Item_Refinery_Strengthen",
  {
    StrengthenLevel: integer("StrengthenLevel"),
    Rock: integer("Rock"),
  },
);

/** Project_Game34.dbo.Item_Strengthen — 15 rows in source; PK (StrengthenLevel) */
export const Item_Strengthen = game.table(
  "Item_Strengthen",
  {
    StrengthenLevel: integer("StrengthenLevel").notNull(),
    Rock: integer("Rock").notNull(),
    Random: integer("Random").notNull(),
    Rock1: integer("Rock1").notNull(),
    Rock2: integer("Rock2").notNull(),
    Rock3: integer("Rock3").notNull(),
    StoneLevelMin: integer("StoneLevelMin").notNull(),
  },
  (t) => [
    primaryKey({ name: "Item_Strengthen_pkey", columns: [t.StrengthenLevel] }),
  ],
);

/** Project_Game34.dbo.Item_Strengthen_Goods — 1634 rows in source; PK (ID) */
export const Item_Strengthen_Goods = game.table(
  "Item_Strengthen_Goods",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Level: integer("Level").notNull(),
    CurrentEquip: integer("CurrentEquip").notNull(),
    GainEquip: integer("GainEquip").notNull(),
    OrginEquip: integer("OrginEquip").notNull().default(7015),
  },
  (t) => [
    primaryKey({ name: "Item_Strengthen_Goods_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.ItemRecordType — 0 rows in source; PK (RecordID) */
export const ItemRecordType = game.table(
  "ItemRecordType",
  {
    RecordID: integer("RecordID").notNull(),
    Name: varchar("Name", { length: 250 }),
    Description: varchar("Description", { length: 1500 }),
  },
  (t) => [
    primaryKey({ name: "ItemRecordType_pkey", columns: [t.RecordID] }),
  ],
);

/** Project_Game34.dbo.Items_Fusion_List — 230 rows in source; PK (ID) */
export const Items_Fusion_List = game.table(
  "Items_Fusion_List",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    TemplateID: integer("TemplateID").notNull(),
    Show: integer("Show").notNull(),
    Real: integer("Real").notNull(),
  },
  (t) => [
    primaryKey({ name: "Items_Fusion_List_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.League_Info — 26 rows in source; PK (ID) */
export const League_Info = game.table(
  "League_Info",
  {
    ID: integer("ID").notNull(),
    RankName: varchar("RankName", { length: 50 }).notNull(),
    NeedPoint: integer("NeedPoint").notNull(),
  },
  (t) => [
    primaryKey({ name: "League_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.LevelInfo — 60 rows in source; PK (Grade) */
export const LevelInfo = game.table(
  "LevelInfo",
  {
    Grade: integer("Grade").notNull(),
    GP: integer("GP").notNull(),
    Blood: integer("Blood").notNull(),
  },
  (t) => [
    primaryKey({ name: "LevelInfo_pkey", columns: [t.Grade] }),
  ],
);

/** Project_Game34.dbo.LoadUserBox — 29 rows in source; PK (ID) */
export const LoadUserBox = game.table(
  "LoadUserBox",
  {
    ID: integer("ID").notNull(),
    Type: integer("Type").notNull().default(0),
    Level: integer("Level").notNull().default(1),
    Condition: integer("Condition").notNull().default(0),
    TemplateID: integer("TemplateID").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "LoadUserBox_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Login_Award_Item_Template — 23 rows in source; PK (ID) */
export const Login_Award_Item_Template = game.table(
  "Login_Award_Item_Template",
  {
    ID: integer("ID").notNull().default(0),
    Type: integer("Type").notNull().default(0),
    RewardItemID: integer("RewardItemID").notNull().default(0),
    IsSelect: boolean("IsSelect").notNull().default(false),
    IsBind: boolean("IsBind").notNull().default(false),
    RewardItemValid: integer("RewardItemValid").notNull().default(0),
    RewardItemCount: integer("RewardItemCount").notNull().default(0),
    StrengthenLevel: integer("StrengthenLevel").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull().default(0),
    LuckCompose: integer("LuckCompose").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Login_Award_Item_Template_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.LuckyStart_Topten_Award — 34 rows in source; PK (ID) */
export const LuckyStart_Topten_Award = game.table(
  "LuckyStart_Topten_Award",
  {
    ID: integer("ID").notNull(),
    Type: integer("Type").notNull().default(0),
    TemplateID: integer("TemplateID").notNull().default(0),
    Validate: integer("Validate").notNull().default(0),
    Count: integer("Count").notNull().default(1),
    StrengthenLevel: integer("StrengthenLevel").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull().default(0),
    LuckCompose: integer("LuckCompose").notNull().default(0),
    IsBind: boolean("IsBind").notNull().default(false),
  },
  (t) => [
    primaryKey({ name: "LuckyStart_Topten_Award_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Map_Server — 20 rows in source; heap (no PK) */
export const Map_Server = game.table(
  "Map_Server",
  {
    ServerID: integer("ServerID").notNull(),
    OpenMap: text("OpenMap").notNull(),
    IsSpecial: integer("IsSpecial").notNull(),
  },
);

/** Project_Game34.dbo.Map_Week — 7 rows in source; PK (WeekID) */
export const Map_Week = game.table(
  "Map_Week",
  {
    WeekID: integer("WeekID").notNull(),
    OpenMap: varchar("OpenMap", { length: 1000 }),
  },
  (t) => [
    primaryKey({ name: "Map_Week_pkey", columns: [t.WeekID] }),
  ],
);

/** Project_Game34.dbo.Mission_Info — 170 rows in source; PK (Id) */
export const Mission_Info = game.table(
  "Mission_Info",
  {
    Id: integer("Id").notNull(),
    Name: varchar("Name", { length: 100 }).notNull(),
    TotalCount: integer("TotalCount").notNull(),
    TotalTurn: integer("TotalTurn").notNull(),
    Script: varchar("Script", { length: 100 }),
    Success: varchar("Success", { length: 100 }),
    Failure: varchar("Failure", { length: 100 }),
    Description: varchar("Description", { length: 1000 }),
    IncrementDelay: integer("IncrementDelay"),
    Delay: integer("Delay"),
    Title: varchar("Title", { length: 50 }),
    Param1: integer("Param1"),
    Param2: integer("Param2"),
    TakeCard: integer("TakeCard"),
    TryAgain: boolean("TryAgain").notNull().default(false),
    TryAgainCost: integer("TryAgainCost").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Mission_Info_pkey", columns: [t.Id] }),
  ],
);

/** Project_Game34.dbo.Mission_Info_Backup — 128 rows in source; PK (Id) */
export const Mission_Info_Backup = game.table(
  "Mission_Info_Backup",
  {
    Id: integer("Id").notNull(),
    Name: varchar("Name", { length: 100 }).notNull(),
    TotalCount: integer("TotalCount").notNull(),
    TotalTurn: integer("TotalTurn").notNull(),
    Script: varchar("Script", { length: 100 }),
    Success: varchar("Success", { length: 100 }),
    Failure: varchar("Failure", { length: 100 }),
    Description: varchar("Description", { length: 1000 }),
    IncrementDelay: integer("IncrementDelay"),
    Delay: integer("Delay"),
    Title: varchar("Title", { length: 50 }),
    Param1: integer("Param1"),
    Param2: integer("Param2"),
    TakeCard: integer("TakeCard"),
    TryAgain: boolean("TryAgain").notNull(),
    TryAgainCost: integer("TryAgainCost").notNull(),
  },
  (t) => [
    primaryKey({ name: "Mission_Info_Backup_pkey", columns: [t.Id] }),
  ],
);

/** Project_Game34.dbo.New_Title — 325 rows in source; PK (ID) */
export const New_Title = game.table(
  "New_Title",
  {
    ID: integer("ID").notNull().default(0),
    Order: integer("Order").notNull(),
    Show: integer("Show").notNull().default(0),
    Name: varchar("Name", { length: 150 }).notNull().default(""),
    Pic: integer("Pic").notNull().default(0),
    Att: integer("Att").notNull().default(0),
    Def: integer("Def").notNull().default(0),
    Agi: integer("Agi").notNull().default(0),
    Luck: integer("Luck").notNull().default(0),
    Desc: varchar("Desc", { length: 200 }).notNull(),
  },
  (t) => [
    primaryKey({ name: "New_Title_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.NPC_Info — 1005 rows in source; PK (ID) */
export const NPC_Info = game.table(
  "NPC_Info",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 50 }).notNull(),
    Level: integer("Level").notNull(),
    Camp: integer("Camp").notNull(),
    Type: integer("Type").notNull(),
    X: integer("X").notNull(),
    Y: integer("Y").notNull(),
    Width: integer("Width").notNull(),
    Height: integer("Height").notNull(),
    Blood: integer("Blood").notNull(),
    MoveMin: integer("MoveMin").notNull(),
    MoveMax: integer("MoveMax").notNull(),
    BaseDamage: integer("BaseDamage").notNull(),
    BaseGuard: integer("BaseGuard").notNull(),
    Defence: integer("Defence").notNull(),
    Agility: integer("Agility").notNull(),
    Lucky: integer("Lucky").notNull(),
    Attack: integer("Attack").notNull(),
    ModelID: varchar("ModelID", { length: 1000 }).notNull(),
    ResourcesPath: varchar("ResourcesPath", { length: 1000 }).notNull(),
    DropRate: varchar("DropRate", { length: 50 }),
    Experience: integer("Experience").notNull(),
    Delay: integer("Delay").notNull(),
    Immunity: integer("Immunity").notNull(),
    Alert: integer("Alert"),
    Range: integer("Range"),
    Preserve: integer("Preserve"),
    Script: varchar("Script", { length: 250 }),
    FireX: integer("FireX").notNull(),
    FireY: integer("FireY").notNull(),
    DropId: integer("DropId").notNull(),
    CurrentBallId: integer("CurrentBallId").notNull(),
    speed: integer("speed").notNull(),
    MagicAttack: integer("MagicAttack").notNull().default(0),
    MagicDefence: integer("MagicDefence").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "NPC_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Old_Player_Award_Info — 27 rows in source; PK (ID) */
export const Old_Player_Award_Info = game.table(
  "Old_Player_Award_Info",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    RewardItemID: integer("RewardItemID").notNull(),
    RewardItemValid: integer("RewardItemValid").notNull(),
    RewardItemCount: integer("RewardItemCount").notNull(),
    StrengthenLevel: integer("StrengthenLevel").notNull(),
    AttackCompose: integer("AttackCompose").notNull(),
    DefendCompose: integer("DefendCompose").notNull(),
    AgilityCompose: integer("AgilityCompose").notNull(),
    LuckCompose: integer("LuckCompose").notNull(),
    IsBind: boolean("IsBind").notNull(),
  },
  (t) => [
    primaryKey({ name: "Old_Player_Award_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Pet_Config — 56 rows in source; PK (Name) */
export const Pet_Config = game.table(
  "Pet_Config",
  {
    Name: varchar("Name", { length: 50 }).notNull(),
    Value: varchar("Value", { length: 2000 }),
  },
  (t) => [
    primaryKey({ name: "Pet_Config_pkey", columns: [t.Name] }),
  ],
);

/** Project_Game34.dbo.Pet_Exp_Item_Price — 20 rows in source; PK (ID) */
export const Pet_Exp_Item_Price = game.table(
  "Pet_Exp_Item_Price",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Count: integer("Count").notNull(),
    Money: integer("Money").notNull(),
    ItemCount: integer("ItemCount").notNull(),
  },
  (t) => [
    primaryKey({ name: "Pet_Exp_Item_Price_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Pet_Fight_Property — 70 rows in source; PK (ID) */
export const Pet_Fight_Property = game.table(
  "Pet_Fight_Property",
  {
    ID: integer("ID").notNull(),
    Exp: integer("Exp").notNull().default(0),
    Attack: integer("Attack").notNull().default(0),
    Agility: integer("Agility").notNull().default(0),
    Defence: integer("Defence").notNull().default(0),
    Lucky: integer("Lucky").notNull().default(0),
    Blood: integer("Blood").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Pet_Fight_Property_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Pet_Level — 70 rows in source; PK (Level) */
export const Pet_Level = game.table(
  "Pet_Level",
  {
    Level: integer("Level").notNull(),
    GP: integer("GP").notNull(),
  },
  (t) => [
    primaryKey({ name: "Pet_Level_pkey", columns: [t.Level] }),
  ],
);

/** Project_Game34.dbo.Pet_Moe_Property — 50 rows in source; PK (Level) */
export const Pet_Moe_Property = game.table(
  "Pet_Moe_Property",
  {
    Level: integer("Level").notNull().default(0),
    Attack: integer("Attack").notNull().default(0),
    Lucky: integer("Lucky").notNull().default(0),
    Agility: integer("Agility").notNull().default(0),
    Blood: integer("Blood").notNull().default(0),
    Defence: integer("Defence").notNull().default(0),
    Guard: integer("Guard").notNull().default(0),
    Exp: integer("Exp").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Pet_Moe_Property_pkey", columns: [t.Level] }),
  ],
);

/** Project_Game34.dbo.Pet_Skill_Element_Info — 2084 rows in source; PK (ID) */
export const Pet_Skill_Element_Info = game.table(
  "Pet_Skill_Element_Info",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 200 }),
    EffectPic: varchar("EffectPic", { length: 100 }),
    Description: varchar("Description", { length: 1000 }),
    Pic: integer("Pic").notNull(),
  },
  (t) => [
    primaryKey({ name: "Pet_Skill_Element_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Pet_Skill_Info — 1653 rows in source; PK (ID) */
export const Pet_Skill_Info = game.table(
  "Pet_Skill_Info",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 250 }).default(""),
    Damage: integer("Damage").notNull().default(0),
    DamageCrit: integer("DamageCrit").notNull().default(0),
    ElementIDs: varchar("ElementIDs", { length: 50 }).default(""),
    Description: varchar("Description", { length: 1050 }).default(""),
    BallType: integer("BallType").notNull(),
    NewBallID: integer("NewBallID").notNull(),
    CostMP: integer("CostMP").notNull(),
    Pic: integer("Pic").notNull(),
    Action: varchar("Action", { length: 50 }).default(""),
    EffectPic: varchar("EffectPic", { length: 50 }).default(""),
    Delay: integer("Delay").notNull(),
    ColdDown: integer("ColdDown").notNull(),
    GameType: integer("GameType").notNull(),
    Probability: integer("Probability").notNull(),
  },
  (t) => [
    primaryKey({ name: "Pet_Skill_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Pet_Skill_Template_Info — 380 rows in source; PK (SkillID) */
export const Pet_Skill_Template_Info = game.table(
  "Pet_Skill_Template_Info",
  {
    PetTemplateID: integer("PetTemplateID").notNull(),
    KindID: integer("KindID").notNull(),
    GetType: integer("GetType").notNull(),
    SkillID: integer("SkillID").notNull(),
    SkillBookID: integer("SkillBookID").notNull(),
    MinLevel: integer("MinLevel").notNull(),
    DeleteSkillIDs: varchar("DeleteSkillIDs", { length: 100 }),
  },
  (t) => [
    primaryKey({ name: "Pet_Skill_Template_Info_pkey", columns: [t.SkillID] }),
  ],
);

/** Project_Game34.dbo.Pet_Star_Exp — 67 rows in source; PK (OldID) */
export const Pet_Star_Exp = game.table(
  "Pet_Star_Exp",
  {
    Exp: integer("Exp").notNull().default(0),
    OldID: integer("OldID").notNull().default(0),
    NewID: integer("NewID").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Pet_Star_Exp_pkey", columns: [t.OldID] }),
  ],
);

/** Project_Game34.dbo.Pet_Template_Info — 199 rows in source; PK (TemplateID) */
export const Pet_Template_Info = game.table(
  "Pet_Template_Info",
  {
    TemplateID: integer("TemplateID").notNull().default(0),
    Name: varchar("Name", { length: 250 }).notNull(),
    KindID: integer("KindID").notNull().default(0),
    Description: varchar("Description", { length: 1000 }).notNull(),
    Pic: varchar("Pic", { length: 100 }).notNull(),
    RareLevel: integer("RareLevel").notNull().default(0),
    MP: integer("MP").notNull().default(100),
    StarLevel: integer("StarLevel").notNull().default(1),
    GameAssetUrl: varchar("GameAssetUrl", { length: 100 }).notNull(),
    EvolutionID: integer("EvolutionID").notNull().default(1),
    HighAgility: integer("HighAgility").notNull().default(0),
    HighAgilityGrow: integer("HighAgilityGrow").notNull().default(0),
    HighAttack: integer("HighAttack").notNull().default(0),
    HighAttackGrow: integer("HighAttackGrow").notNull().default(0),
    HighBlood: integer("HighBlood").notNull().default(0),
    HighBloodGrow: integer("HighBloodGrow").notNull().default(0),
    HighDamage: integer("HighDamage").notNull().default(0),
    HighDamageGrow: integer("HighDamageGrow").notNull().default(0),
    HighDefence: integer("HighDefence").notNull().default(0),
    HighDefenceGrow: integer("HighDefenceGrow").notNull().default(0),
    HighGuard: integer("HighGuard").notNull().default(0),
    HighGuardGrow: integer("HighGuardGrow").notNull().default(0),
    HighLuck: integer("HighLuck").notNull().default(0),
    HighLuckGrow: integer("HighLuckGrow").notNull().default(0),
    WashGetCount: integer("WashGetCount").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Pet_Template_Info_pkey", columns: [t.TemplateID] }),
  ],
);

/** Project_Game34.dbo.Pve_Info — 33 rows in source; PK (ID) */
export const Pve_Info = game.table(
  "Pve_Info",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 100 }),
    Type: integer("Type"),
    LevelLimits: integer("LevelLimits"),
    SimpleTemplateIds: varchar("SimpleTemplateIds", { length: 1024 }),
    NormalTemplateIds: varchar("NormalTemplateIds", { length: 1024 }),
    HardTemplateIds: varchar("HardTemplateIds", { length: 1024 }),
    TerrorTemplateIds: varchar("TerrorTemplateIds", { length: 1024 }),
    Pic: varchar("Pic", { length: 100 }),
    Description: text("Description"),
    SimpleGameScript: varchar("SimpleGameScript", { length: 100 }),
    NormalGameScript: varchar("NormalGameScript", { length: 100 }),
    HardGameScript: varchar("HardGameScript", { length: 100 }),
    TerrorGameScript: varchar("TerrorGameScript", { length: 100 }),
    Ordering: integer("Ordering").notNull().default(0),
    AdviceTips: varchar("AdviceTips", { length: 100 }),
    BossFightNeedMoney: varchar("BossFightNeedMoney", { length: 50 }),
    LastFloor: varchar("LastFloor", { length: 50 }),
  },
  (t) => [
    primaryKey({ name: "Pve_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.QQtips_Messages — 1 rows in source; PK (ID) */
export const QQtips_Messages = game.table(
  "QQtips_Messages",
  {
    ID: integer("ID").notNull().default(0),
    title: varchar("title", { length: 250 }),
    content: varchar("content", { length: 2500 }),
    maxLevel: integer("maxLevel").notNull().default(65),
    minLevel: integer("minLevel").notNull().default(5),
    outInType: integer("outInType").notNull().default(1),
    moduleType: integer("moduleType").notNull().default(0),
    inItemID: integer("inItemID").notNull().default(0),
    url: varchar("url", { length: 250 }).notNull().default("http://gunny.zing.vn"),
  },
  (t) => [
    primaryKey({ name: "QQtips_Messages_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Quest — 728 rows in source; PK (ID) */
export const Quest = game.table(
  "Quest",
  {
    ID: integer("ID").notNull(),
    QuestID: integer("QuestID").notNull(),
    Title: varchar("Title", { length: 300 }),
    Detail: varchar("Detail", { length: 1500 }),
    Objective: varchar("Objective", { length: 50 }),
    NeedMinLevel: integer("NeedMinLevel").notNull(),
    NeedMaxLevel: integer("NeedMaxLevel").notNull(),
    PreQuestID: varchar("PreQuestID", { length: 40 }).notNull(),
    NextQuestID: varchar("NextQuestID", { length: 40 }).notNull(),
    IsOther: integer("IsOther").notNull(),
    CanRepeat: boolean("CanRepeat").notNull(),
    RepeatInterval: integer("RepeatInterval").notNull(),
    RepeatMax: integer("RepeatMax").notNull(),
    RewardGP: integer("RewardGP").notNull(),
    RewardGold: integer("RewardGold").notNull(),
    RewardGiftToken: integer("RewardGiftToken").notNull(),
    RewardOffer: integer("RewardOffer").notNull(),
    RewardRiches: integer("RewardRiches").notNull(),
    RewardBuffID: integer("RewardBuffID").notNull(),
    RewardBuffDate: integer("RewardBuffDate").notNull(),
    RewardMoney: integer("RewardMoney").notNull(),
    RewardMedal: integer("RewardMedal").notNull().default(0),
    Rands: numeric("Rands", { precision: 18, scale: 2 }).notNull(),
    StartDate: timestamp("StartDate", { precision: 3, mode: "date" }).notNull(),
    EndDate: timestamp("EndDate", { precision: 3, mode: "date" }).notNull(),
    RandDouble: integer("RandDouble").notNull(),
    TimeMode: boolean("TimeMode").notNull(),
    MapID: integer("MapID").notNull().default(0),
    AutoEquip: boolean("AutoEquip").notNull().default(false),
    Rank: varchar("Rank", { length: 500 }),
    StarLev: integer("StarLev").notNull().default(0),
    NotMustCount: integer("NotMustCount").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Quest_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Quest_Condiction — 853 rows in source; heap (no PK) */
export const Quest_Condiction = game.table(
  "Quest_Condiction",
  {
    QuestID: integer("QuestID").notNull(),
    CondictionID: integer("CondictionID").notNull(),
    CondictionType: integer("CondictionType").notNull(),
    CondictionTitle: varchar("CondictionTitle", { length: 200 }).notNull(),
    Para1: integer("Para1").notNull(),
    Para2: integer("Para2").notNull(),
    isOpitional: boolean("isOpitional").notNull().default(false),
  },
);

/** Project_Game34.dbo.Quest_Goods — 1006 rows in source; heap (no PK) */
export const Quest_Goods = game.table(
  "Quest_Goods",
  {
    QuestID: integer("QuestID").notNull(),
    RewardItemID: integer("RewardItemID").notNull(),
    IsSelect: boolean("IsSelect").notNull(),
    RewardItemValid: integer("RewardItemValid").notNull(),
    RewardItemCount: integer("RewardItemCount").notNull(),
    StrengthenLevel: integer("StrengthenLevel").default(0),
    AttackCompose: integer("AttackCompose").default(0),
    DefendCompose: integer("DefendCompose").default(0),
    AgilityCompose: integer("AgilityCompose").default(0),
    LuckCompose: integer("LuckCompose").default(0),
    IsCount: boolean("IsCount").default(true),
    IsBind: boolean("IsBind").default(true),
  },
);

/** Project_Game34.dbo.Quest_Rate — 0 rows in source; heap (no PK) */
export const Quest_Rate = game.table(
  "Quest_Rate",
  {
    BindMoneyRate: varchar("BindMoneyRate", { length: 50 }).notNull(),
    ExpRate: varchar("ExpRate", { length: 50 }).notNull(),
    GoldRate: varchar("GoldRate", { length: 50 }).notNull(),
    ExploitRate: varchar("ExploitRate", { length: 50 }).notNull(),
    CanOneKeyFinishTime: integer("CanOneKeyFinishTime").notNull(),
  },
);

/** Project_Game34.dbo.Rate — 19 rows in source; heap (no PK) */
export const Rate = game.table(
  "Rate",
  {
    ServerID: integer("ServerID").notNull(),
    Rate: numeric("Rate", { precision: 6, scale: 2 }).notNull(),
    BeginDay: timestamp("BeginDay", { precision: 3, mode: "date" }).notNull(),
    EndDay: timestamp("EndDay", { precision: 3, mode: "date" }).notNull(),
    BeginTime: timestamp("BeginTime", { precision: 3, mode: "date" }).notNull(),
    EndTime: timestamp("EndTime", { precision: 3, mode: "date" }).notNull(),
    Type: integer("Type").notNull().default(0),
  },
);

/** Project_Game34.dbo.Rune_Template — 456 rows in source; PK (TemplateID) */
export const Rune_Template = game.table(
  "Rune_Template",
  {
    TemplateID: integer("TemplateID").notNull(),
    NextTemplateID: integer("NextTemplateID").notNull().default(0),
    Name: varchar("Name", { length: 50 }),
    BaseLevel: integer("BaseLevel").notNull().default(1),
    MaxLevel: integer("MaxLevel").notNull().default(2),
    Type1: integer("Type1").notNull().default(1),
    Attribute1: varchar("Attribute1", { length: 50 }).notNull().default("1|2"),
    Turn1: integer("Turn1").notNull().default(0),
    Rate1: integer("Rate1").notNull().default(0),
    Type2: integer("Type2").notNull().default(0),
    Attribute2: varchar("Attribute2", { length: 50 }).notNull().default("1|2"),
    Turn2: integer("Turn2").notNull().default(0),
    Rate2: integer("Rate2").notNull().default(0),
    Type3: integer("Type3").notNull().default(0),
    Attribute3: varchar("Attribute3", { length: 50 }).notNull().default("1|2"),
    Turn3: integer("Turn3").notNull().default(0),
    Rate3: integer("Rate3").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Rune_Template_pkey", columns: [t.TemplateID] }),
  ],
);

/** Project_Game34.dbo.Search_Goods_Temp — 5 rows in source; PK (StarID) */
export const Search_Goods_Temp = game.table(
  "Search_Goods_Temp",
  {
    StarID: integer("StarID").notNull(),
    NeedMoney: integer("NeedMoney").notNull().default(0),
    DestinationReward: integer("DestinationReward").notNull().default(0),
    VIPLevel: integer("VIPLevel").notNull().default(-1),
    ExtractNumber: varchar("ExtractNumber", { length: 50 }).notNull().default("10,2,3,1"),
  },
  (t) => [
    primaryKey({ name: "Search_Goods_Temp_pkey", columns: [t.StarID] }),
  ],
);

/** Project_Game34.dbo.Server_Config — 489 rows in source; PK (ID) */
export const Server_Config = game.table(
  "Server_Config",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 50 }).notNull(),
    Value: varchar("Value", { length: 2000 }).notNull(),
  },
  (t) => [
    primaryKey({ name: "Server_Config_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Sets_Build_Temp — 70 rows in source; PK (Level) */
export const Sets_Build_Temp = game.table(
  "Sets_Build_Temp",
  {
    Level: integer("Level").notNull(),
    SetsType: integer("SetsType").notNull(),
    UseItemTemplate: integer("UseItemTemplate").notNull(),
    Exp: integer("Exp").notNull(),
    DefenceGrow: integer("DefenceGrow").notNull(),
    BloodGrow: integer("BloodGrow").notNull(),
    LuckGrow: integer("LuckGrow").notNull(),
    AgilityGrow: integer("AgilityGrow").notNull(),
    DamageGrow: integer("DamageGrow").notNull(),
    GuardGrow: integer("GuardGrow").notNull(),
  },
  (t) => [
    primaryKey({ name: "Sets_Build_Temp_pkey", columns: [t.Level] }),
  ],
);

/** Project_Game34.dbo.Shop — 5025 rows in source; heap (no PK) */
export const Shop = game.table(
  "Shop",
  {
    ID: doublePrecision("ID"),
    ShopID: doublePrecision("ShopID"),
    GroupID: doublePrecision("GroupID"),
    TemplateID: doublePrecision("TemplateID"),
    BuyType: doublePrecision("BuyType"),
    IsContinue: boolean("IsContinue").notNull(),
    IsBind: doublePrecision("IsBind"),
    IsVouch: doublePrecision("IsVouch").default(0),
    Label: doublePrecision("Label"),
    Beat: doublePrecision("Beat"),
    AUnit: doublePrecision("AUnit"),
    APrice1: doublePrecision("APrice1"),
    AValue1: doublePrecision("AValue1"),
    APrice2: doublePrecision("APrice2"),
    AValue2: doublePrecision("AValue2"),
    APrice3: doublePrecision("APrice3"),
    AValue3: doublePrecision("AValue3"),
    BUnit: doublePrecision("BUnit"),
    BPrice1: doublePrecision("BPrice1"),
    BValue1: doublePrecision("BValue1"),
    BPrice2: doublePrecision("BPrice2"),
    BValue2: doublePrecision("BValue2"),
    BPrice3: doublePrecision("BPrice3"),
    BValue3: doublePrecision("BValue3"),
    CUnit: doublePrecision("CUnit"),
    CPrice1: doublePrecision("CPrice1"),
    CValue1: doublePrecision("CValue1"),
    CPrice2: doublePrecision("CPrice2"),
    CValue2: doublePrecision("CValue2"),
    CPrice3: doublePrecision("CPrice3"),
    Sort: doublePrecision("Sort").default(0),
    CValue3: doublePrecision("CValue3"),
    IsCheap: boolean("IsCheap").notNull(),
    LimitCount: doublePrecision("LimitCount"),
    StartDate: timestamp("StartDate", { precision: 3, mode: "date" }),
    EndDate: timestamp("EndDate", { precision: 3, mode: "date" }),
    LimitGrade: integer("LimitGrade").default(0),
    CanBuy: boolean("CanBuy").notNull().default(false),
  },
);

/** Project_Game34.dbo.Shop_Goods — 7640 rows in source; PK (TemplateID) */
export const Shop_Goods = game.table(
  "Shop_Goods",
  {
    TemplateID: integer("TemplateID").notNull(),
    CanRecycle: integer("CanRecycle").notNull(),
    Name: varchar("Name", { length: 50 }),
    Remark: varchar("Remark", { length: 200 }),
    CategoryID: integer("CategoryID").notNull(),
    Description: text("Description"),
    Attack: integer("Attack").notNull(),
    Defence: integer("Defence").notNull(),
    Agility: integer("Agility").notNull(),
    Luck: integer("Luck").notNull(),
    Level: integer("Level").notNull(),
    Quality: integer("Quality").notNull(),
    Pic: varchar("Pic", { length: 200 }),
    MaxCount: integer("MaxCount").notNull(),
    NeedSex: integer("NeedSex").notNull(),
    NeedLevel: integer("NeedLevel").notNull(),
    CanStrengthen: boolean("CanStrengthen").notNull(),
    CanCompose: boolean("CanCompose").notNull(),
    CanDrop: boolean("CanDrop").notNull(),
    CanEquip: boolean("CanEquip").notNull(),
    CanUse: boolean("CanUse").notNull(),
    CanDelete: boolean("CanDelete").notNull(),
    Script: varchar("Script", { length: 200 }),
    Data: varchar("Data", { length: 1000 }),
    Colors: varchar("Colors", { length: 1000 }),
    Property1: integer("Property1").notNull(),
    Property2: integer("Property2").notNull(),
    Property3: integer("Property3").notNull(),
    Property4: integer("Property4").notNull(),
    Property5: integer("Property5").notNull(),
    Property6: integer("Property6").notNull(),
    Property7: integer("Property7").notNull(),
    Property8: integer("Property8").notNull(),
    Valid: integer("Valid").notNull().default(0),
    Count: integer("Count").notNull().default(1),
    AddTime: timestamp("AddTime", { precision: 3, mode: "date" }),
    BindType: integer("BindType").notNull(),
    FusionType: integer("FusionType").notNull(),
    FusionRate: integer("FusionRate").notNull(),
    FusionNeedRate: integer("FusionNeedRate").notNull(),
    Hole: varchar("Hole", { length: 50 }),
    RefineryLevel: integer("RefineryLevel").notNull(),
    ReclaimValue: integer("ReclaimValue").notNull(),
    ReclaimType: integer("ReclaimType").notNull(),
    FloorPrice: integer("FloorPrice").notNull().default(0),
    SuitId: integer("SuitId").notNull().default(0),
    CanTransfer: integer("CanTransfer").notNull().default(1),
    Price: integer("Price"),
    FineSuitType: integer("FineSuitType").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Shop_Goods_pkey", columns: [t.TemplateID] }),
  ],
);

/** Project_Game34.dbo.Shop_Goods_Box — 4043 rows in source; heap (no PK) */
export const Shop_Goods_Box = game.table(
  "Shop_Goods_Box",
  {
    ID: integer("ID").notNull(),
    TemplateId: integer("TemplateId").notNull(),
    IsSelect: boolean("IsSelect").notNull(),
    IsBind: boolean("IsBind").notNull(),
    ItemValid: integer("ItemValid").notNull(),
    ItemCount: integer("ItemCount").notNull(),
    StrengthenLevel: integer("StrengthenLevel").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull().default(0),
    LuckCompose: integer("LuckCompose").notNull().default(0),
    Random: integer("Random").notNull(),
    IsTips: integer("IsTips").notNull().default(0),
    IsLogs: boolean("IsLogs").notNull().default(false),
  },
);

/** Project_Game34.dbo.Shop_Goods_Categorys — 34 rows in source; PK (ID) */
export const Shop_Goods_Categorys = game.table(
  "Shop_Goods_Categorys",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 50 }),
    Place: integer("Place").default(0),
    Remark: varchar("Remark", { length: 200 }),
  },
  (t) => [
    primaryKey({ name: "Shop_Goods_Categorys_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.ShopGoodsShowList — 5093 rows in source; PK (TempID) */
export const ShopGoodsShowList = game.table(
  "ShopGoodsShowList",
  {
    Type: integer("Type").notNull(),
    ShopId: integer("ShopId").notNull(),
    TempID: integer("TempID").generatedByDefaultAsIdentity().notNull(),
  },
  (t) => [
    primaryKey({ name: "ShopGoodsShowList_pkey", columns: [t.TempID] }),
  ],
);

/** Project_Game34.dbo.ShopGoodsShowList_BK — 4090 rows in source; PK (TempID) */
export const ShopGoodsShowList_BK = game.table(
  "ShopGoodsShowList_BK",
  {
    Type: integer("Type").notNull(),
    ShopId: integer("ShopId").notNull(),
    TempID: integer("TempID").generatedByDefaultAsIdentity().notNull(),
  },
  (t) => [
    primaryKey({ name: "ShopGoodsShowList_BK_pkey", columns: [t.TempID] }),
  ],
);

/** Project_Game34.dbo.StrengThenExp — 16 rows in source; PK (ID) */
export const StrengThenExp = game.table(
  "StrengThenExp",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Level: integer("Level").notNull().default(0),
    Exp: integer("Exp").notNull().default(0),
    NecklaceStrengthExp: integer("NecklaceStrengthExp").notNull().default(0),
    NecklaceStrengthPlus: integer("NecklaceStrengthPlus").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "StrengThenExp_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Sub_Active_Condition — 11 rows in source; PK (ID) */
export const Sub_Active_Condition = game.table(
  "Sub_Active_Condition",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ActiveID: integer("ActiveID").notNull().default(0),
    SubID: integer("SubID").notNull().default(0),
    ConditionID: integer("ConditionID").notNull().default(0),
    Type: integer("Type").notNull().default(-1),
    Value: varchar("Value", { length: 150 }).notNull().default("1-50-2-50-3-50-4-50-5-1500-6-100-7-100-8-Bao tay venus+5-9-不限-10-+1-11-0-12-28"),
    AwardType: integer("AwardType").notNull().default(1),
    AwardValue: varchar("AwardValue", { length: 250 }),
    IsValid: boolean("IsValid").notNull().default(false),
  },
  (t) => [
    primaryKey({ name: "Sub_Active_Condition_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Sub_Active_List — 1 rows in source; PK (ID) */
export const Sub_Active_List = game.table(
  "Sub_Active_List",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ActiveID: integer("ActiveID").notNull().default(0),
    SubID: integer("SubID").notNull().default(0),
    IsOpen: boolean("IsOpen").notNull().default(false),
    StartDate: timestamp("StartDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    StartTime: timestamp("StartTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    EndDate: timestamp("EndDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    EndTime: timestamp("EndTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    IsContinued: boolean("IsContinued").notNull().default(true),
    ActiveInfo: varchar("ActiveInfo", { length: 500 }),
  },
  (t) => [
    primaryKey({ name: "Sub_Active_List_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Suit_TemplateID — 111 rows in source; heap (no PK) */
export const Suit_TemplateID = game.table(
  "Suit_TemplateID",
  {
    ID: integer("ID"),
    ContainEquip: varchar("ContainEquip", { length: 500 }),
    PartName: varchar("PartName", { length: 500 }),
  },
);

/** Project_Game34.dbo.SuitTemplateInfo — 46 rows in source; heap (no PK) */
export const SuitTemplateInfo = game.table(
  "SuitTemplateInfo",
  {
    SuitId: integer("SuitId").notNull(),
    SuitName: varchar("SuitName", { length: 500 }).notNull(),
    EqipCount1: integer("EqipCount1"),
    SkillDescribe1: varchar("SkillDescribe1", { length: 500 }),
    Skill1: varchar("Skill1", { length: 200 }),
    EqipCount2: integer("EqipCount2"),
    SkillDescribe2: varchar("SkillDescribe2", { length: 500 }),
    Skill2: varchar("Skill2", { length: 200 }),
    EqipCount3: integer("EqipCount3"),
    SkillDescribe3: varchar("SkillDescribe3", { length: 500 }),
    Skill3: varchar("Skill3", { length: 200 }),
    EqipCount4: integer("EqipCount4"),
    SkillDescribe4: varchar("SkillDescribe4", { length: 500 }),
    Skill4: varchar("Skill4", { length: 200 }),
    EqipCount5: integer("EqipCount5"),
    SkillDescribe5: varchar("SkillDescribe5", { length: 500 }),
    Skill5: varchar("Skill5", { length: 200 }),
  },
);

/** Project_Game34.dbo.TempTable — 34 rows in source; heap (no PK) */
export const TempTable = game.table(
  "TempTable",
  {
    id: integer("id"),
    value: varchar("value", { length: 50 }),
  },
);

/** Project_Game34.dbo.Totem_Honor_Template — 20 rows in source; PK (ID) */
export const Totem_Honor_Template = game.table(
  "Totem_Honor_Template",
  {
    ID: integer("ID").notNull(),
    Type: integer("Type").notNull().default(1),
    NeedMoney: integer("NeedMoney").notNull().default(0),
    AddHonor: integer("AddHonor").notNull().default(200),
  },
  (t) => [
    primaryKey({ name: "Totem_Honor_Template_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.Totem_Info — 350 rows in source; PK (ID) */
export const Totem_Info = game.table(
  "Totem_Info",
  {
    ID: integer("ID").notNull(),
    ConsumeExp: integer("ConsumeExp").notNull().default(0),
    ConsumeHonor: integer("ConsumeHonor").notNull().default(0),
    AddAttack: integer("AddAttack").notNull().default(0),
    AddDefence: integer("AddDefence").notNull().default(0),
    AddAgility: integer("AddAgility").notNull().default(0),
    AddLuck: integer("AddLuck").notNull().default(0),
    AddBlood: integer("AddBlood").notNull().default(0),
    AddDamage: integer("AddDamage").notNull().default(0),
    AddGuard: integer("AddGuard").notNull().default(0),
    Random: integer("Random").notNull().default(0),
    Page: integer("Page").notNull().default(0),
    Layers: integer("Layers").notNull().default(0),
    Location: integer("Location").notNull().default(0),
    Point: integer("Point").notNull().default(0),
    DiscountMoney: integer("DiscountMoney").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Totem_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Game34.dbo.User_Box — 29 rows in source; PK (ID) */
export const User_Box = game.table(
  "User_Box",
  {
    ID: integer("ID").notNull(),
    Type: integer("Type").notNull(),
    Level: integer("Level").notNull(),
    Condition: integer("Condition").notNull(),
    TemplateID: integer("TemplateID").notNull(),
  },
  (t) => [
    primaryKey({ name: "User_Box_pkey", columns: [t.ID] }),
  ],
);
