// AUTO-GENERATED by scripts/gen-schema.ts from Db_Membership catalog.json — DO NOT EDIT.
/* eslint-disable */
import { bigint, boolean, integer, numeric, primaryKey, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { member } from "./schemas.js";

/** Db_Membership.dbo.Mem_ActiveCode — 20200 rows in source; PK (ActiveCode) */
export const Mem_ActiveCode = member.table(
  "Mem_ActiveCode",
  {
    ApplicationId: varchar("ApplicationId", { length: 256 }),
    ActiveCode: varchar("ActiveCode", { length: 50 }).notNull(),
    BeginActivityDate: timestamp("BeginActivityDate", { precision: 3, mode: "date" }),
    EndActivityDate: timestamp("EndActivityDate", { precision: 3, mode: "date" }),
    IsOpen: integer("IsOpen"),
    Company: varchar("Company", { length: 50 }),
  },
  (t) => [
    primaryKey({ name: "Mem_ActiveCode_pkey", columns: [t.ActiveCode] }),
  ],
);

/** Db_Membership.dbo.Mem_Application — 6 rows in source; PK (ApplicationId) */
export const Mem_Application = member.table(
  "Mem_Application",
  {
    ApplicationName: varchar("ApplicationName", { length: 256 }),
    LowerApplicationName: varchar("LowerApplicationName", { length: 256 }),
    ApplicationId: varchar("ApplicationId", { length: 20 }).notNull(),
    Description: varchar("Description", { length: 256 }),
    IsOpen: boolean("IsOpen").default(false),
  },
  (t) => [
    primaryKey({ name: "Mem_Application_pkey", columns: [t.ApplicationId] }),
  ],
);

/** Db_Membership.dbo.Mem_Application_Sub — 6 rows in source; heap (no PK) */
export const Mem_Application_Sub = member.table(
  "Mem_Application_Sub",
  {
    id: integer("id").generatedByDefaultAsIdentity().notNull(),
    ApplicationId: varchar("ApplicationId", { length: 50 }),
    SubName: varchar("SubName", { length: 256 }),
    SubId: varchar("SubId", { length: 50 }),
    IsOpen: boolean("IsOpen"),
    Description: varchar("Description", { length: 50 }),
  },
);

/** Db_Membership.dbo.Mem_Code — 3 rows in source; heap (no PK) */
export const Mem_Code = member.table(
  "Mem_Code",
  {
    id: integer("id").generatedByDefaultAsIdentity().notNull(),
    code: varchar("code", { length: 50 }).notNull(),
    codenumber: bigint("codenumber", { mode: "number" }),
    info: varchar("info", { length: 50 }),
  },
);

/** Db_Membership.dbo.Mem_Module — 117 rows in source; PK (ModuleId) */
export const Mem_Module = member.table(
  "Mem_Module",
  {
    Id: integer("Id").generatedByDefaultAsIdentity().notNull(),
    ApplicationId: varchar("ApplicationId", { length: 20 }),
    ModuleId: integer("ModuleId").notNull(),
    ModuleName: varchar("ModuleName", { length: 256 }),
    ParModuleId: integer("ParModuleId"),
    AddTime: timestamp("AddTime", { precision: 3, mode: "date" }).defaultNow(),
    Description: varchar("Description", { length: 256 }),
  },
  (t) => [
    primaryKey({ name: "Mem_Module_pkey", columns: [t.ModuleId] }),
  ],
);

/** Db_Membership.dbo.Mem_Paths — 0 rows in source; PK (PathId) */
export const Mem_Paths = member.table(
  "Mem_Paths",
  {
    ApplicationId: varchar("ApplicationId", { length: 20 }),
    PathId: varchar("PathId", { length: 256 }).notNull(),
    Path: varchar("Path", { length: 256 }),
    LoweredPath: varchar("LoweredPath", { length: 256 }),
  },
  (t) => [
    primaryKey({ name: "Mem_Paths_pkey", columns: [t.PathId] }),
  ],
);

/** Db_Membership.dbo.Mem_ResetPwd — 0 rows in source; heap (no PK) */
export const Mem_ResetPwd = member.table(
  "Mem_ResetPwd",
  {
    UserId: integer("UserId").notNull(),
    SaleEntry: uuid("SaleEntry"),
    GetTime: timestamp("GetTime", { precision: 3, mode: "date" }).defaultNow(),
    IsActived: boolean("IsActived").default(false),
    ApplicationId: integer("ApplicationId"),
  },
);

/** Db_Membership.dbo.Mem_Right — 153 rows in source; heap (no PK) */
export const Mem_Right = member.table(
  "Mem_Right",
  {
    Id: integer("Id").generatedByDefaultAsIdentity().notNull(),
    ApplicationId: varchar("ApplicationId", { length: 256 }),
    ModuleId: integer("ModuleId"),
    RightsName: varchar("RightsName", { length: 256 }),
    RightsId: integer("RightsId"),
    RightsDes: varchar("RightsDes", { length: 256 }),
    AddTime: timestamp("AddTime", { precision: 3, mode: "date" }).defaultNow(),
  },
);

/** Db_Membership.dbo.Mem_Roles — 12 rows in source; heap (no PK) */
export const Mem_Roles = member.table(
  "Mem_Roles",
  {
    ApplicationId: varchar("ApplicationId", { length: 50 }),
    RoleId: integer("RoleId"),
    RoleName: varchar("RoleName", { length: 256 }),
    LowerRoleName: varchar("LowerRoleName", { length: 256 }),
    Description: varchar("Description", { length: 256 }),
  },
);

/** Db_Membership.dbo.Mem_UserInfo — 6 rows in source; heap (no PK) */
export const Mem_UserInfo = member.table(
  "Mem_UserInfo",
  {
    ApplicationId: varchar("ApplicationId", { length: 20 }),
    UserId: varchar("UserId", { length: 256 }),
    Password: varchar("Password", { length: 128 }),
    PasswordFormat: integer("PasswordFormat"),
    PasswordSalt: varchar("PasswordSalt", { length: 128 }),
    MobilePIN: varchar("MobilePIN", { length: 16 }),
    Email: varchar("Email", { length: 256 }),
    LowerEmail: varchar("LowerEmail", { length: 256 }),
    PasswordQuestion: varchar("PasswordQuestion", { length: 256 }),
    PasswordAnswer: varchar("PasswordAnswer", { length: 128 }),
    IsApproved: boolean("IsApproved"),
    IsLockedOut: boolean("IsLockedOut"),
    CreateDate: timestamp("CreateDate", { precision: 3, mode: "date" }),
    LastLoginDate: timestamp("LastLoginDate", { precision: 3, mode: "date" }),
    LastPasswordChangeDate: timestamp("LastPasswordChangeDate", { precision: 3, mode: "date" }),
    LastLockoutDate: timestamp("LastLockoutDate", { precision: 3, mode: "date" }),
    FailedPasswordAttemptCount: integer("FailedPasswordAttemptCount"),
    FailedPasswordAttemptWindowStart: timestamp("FailedPasswordAttemptWindowStart", { precision: 3, mode: "date" }),
    FailedPasswordAnswerAttemptCount: integer("FailedPasswordAnswerAttemptCount"),
    FailedPasswordAnswerAttemptWindowstart: timestamp("FailedPasswordAnswerAttemptWindowstart", { precision: 3, mode: "date" }),
    Comment: text("Comment"),
    UserSex: boolean("UserSex"),
  },
);

/** Db_Membership.dbo.Mem_UserRight — 0 rows in source; PK (Id) */
export const Mem_UserRight = member.table(
  "Mem_UserRight",
  {
    Id: integer("Id").generatedByDefaultAsIdentity().notNull(),
    ApplicationId: varchar("ApplicationId", { length: 256 }),
    UserID: varchar("UserID", { length: 256 }),
    RightsId: integer("RightsId"),
    AddTime: timestamp("AddTime", { precision: 3, mode: "date" }),
  },
  (t) => [
    primaryKey({ name: "Mem_UserRight_pkey", columns: [t.Id] }),
  ],
);

/** Db_Membership.dbo.Mem_Users — 6 rows in source; heap (no PK) */
export const Mem_Users = member.table(
  "Mem_Users",
  {
    ApplicationId: varchar("ApplicationId", { length: 20 }),
    UserId: varchar("UserId", { length: 256 }),
    UserName: varchar("UserName", { length: 256 }),
    LowerName: varchar("LowerName", { length: 256 }),
    MobileAlias: varchar("MobileAlias", { length: 200 }),
    IsAnonymous: boolean("IsAnonymous"),
    LastActivityDate: timestamp("LastActivityDate", { precision: 3, mode: "date" }),
    LoginTime: integer("LoginTime"),
  },
);

/** Db_Membership.dbo.Mem_Users_Save — 3 rows in source; heap (no PK) */
export const Mem_Users_Save = member.table(
  "Mem_Users_Save",
  {
    id: integer("id").generatedByDefaultAsIdentity().notNull(),
    User_Type: varchar("User_Type", { length: 50 }),
  },
);

/** Db_Membership.dbo.Mem_UsersInRoles — 0 rows in source; heap (no PK) */
export const Mem_UsersInRoles = member.table(
  "Mem_UsersInRoles",
  {
    UserID: integer("UserID"),
    RoleID: integer("RoleID"),
  },
);

/** Db_Membership.dbo.Pay_Card — 2694 rows in source; heap (no PK) */
export const Pay_Card = member.table(
  "Pay_Card",
  {
    id: integer("id").generatedByDefaultAsIdentity().notNull(),
    CardId: varchar("CardId", { length: 20 }),
    IsValues: integer("IsValues"),
    IsOpen: integer("IsOpen"),
    MustMoney: numeric("MustMoney", { precision: 18, scale: 0 }),
    GamePoint: integer("GamePoint"),
    ApplicationId: varchar("ApplicationId", { length: 10 }),
    CardPassword: varchar("CardPassword", { length: 20 }),
    BeginDay: timestamp("BeginDay", { precision: 3, mode: "date" }),
    EndDay: timestamp("EndDay", { precision: 3, mode: "date" }),
    OrderId: varchar("OrderId", { length: 20 }),
    PayId: varchar("PayId", { length: 50 }),
    PayDateTime: timestamp("PayDateTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("IX_Pay_Card").on(t.CardId),
  ],
);

/** Db_Membership.dbo.Pay_Exchange — 0 rows in source; heap (no PK) */
export const Pay_Exchange = member.table(
  "Pay_Exchange",
  {
    Id: integer("Id"),
    OrderId: varchar("OrderId", { length: 100 }),
    UserId: varchar("UserId", { length: 50 }),
    LastMoney: integer("LastMoney"),
    OutPoint: integer("OutPoint"),
    ResultPoint: integer("ResultPoint"),
    EnterIp: varchar("EnterIp", { length: 50 }),
    EnterTime: timestamp("EnterTime", { precision: 3, mode: "date" }),
    EnterServer: varchar("EnterServer", { length: 50 }),
    EnterUserId: varchar("EnterUserId", { length: 50 }),
    Remark: varchar("Remark", { length: 200 }),
  },
);

/** Db_Membership.dbo.Pay_History — 0 rows in source; heap (no PK) */
export const Pay_History = member.table(
  "Pay_History",
  {
    Id: integer("Id"),
    Order_Id: varchar("Order_Id", { length: 20 }),
    Money: numeric("Money", { precision: 18, scale: 2 }),
    User_Id: varchar("User_Id", { length: 50 }),
    Enter_Ip: varchar("Enter_Ip", { length: 20 }),
    Enter_Time: timestamp("Enter_Time", { precision: 3, mode: "date" }),
    Pay_Info: varchar("Pay_Info", { length: 100 }),
  },
);

/** Db_Membership.dbo.Pay_Info — 45 rows in source; PK (OrderId) */
export const Pay_Info = member.table(
  "Pay_Info",
  {
    id: integer("id").generatedByDefaultAsIdentity().notNull(),
    OrderId: varchar("OrderId", { length: 20 }).notNull(),
    OrderNumbers: integer("OrderNumbers"),
    OrderMoney: numeric("OrderMoney", { precision: 18, scale: 0 }),
    PayUserId: varchar("PayUserId", { length: 50 }),
    EnterIp: varchar("EnterIp", { length: 50 }),
    EnterDate: timestamp("EnterDate", { precision: 3, mode: "date" }),
    BuyInfo: varchar("BuyInfo", { length: 200 }),
    IsPass: integer("IsPass"),
    UserId: varchar("UserId", { length: 50 }),
    LastDateTime: timestamp("LastDateTime", { precision: 3, mode: "date" }),
    PayWay: varchar("PayWay", { length: 20 }),
  },
  (t) => [
    primaryKey({ name: "Pay_Info_pkey", columns: [t.OrderId] }),
  ],
);

/** Db_Membership.dbo.Pay_Select — 0 rows in source; heap (no PK) */
export const Pay_Select = member.table(
  "Pay_Select",
  {
    id: integer("id"),
    PaywayId: varchar("PaywayId", { length: 20 }),
    PayName: varchar("PayName", { length: 200 }),
    IsOpen: boolean("IsOpen"),
  },
);

/** Db_Membership.dbo.Pay_Way — 4 rows in source; heap (no PK) */
export const Pay_Way = member.table(
  "Pay_Way",
  {
    Id: integer("Id").generatedByDefaultAsIdentity().notNull(),
    WayId: varchar("WayId", { length: 10 }),
    WayName: varchar("WayName", { length: 20 }),
    IsOpen: boolean("IsOpen").default(true),
  },
);
