// AUTO-GENERATED by scripts/gen-schema.ts from Project_Player34 catalog.json — DO NOT EDIT.
/* eslint-disable */
import { boolean, doublePrecision, index, integer, numeric, primaryKey, text, timestamp, varchar } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { player, bytea } from "./schemas.js";

/** Project_Player34.dbo.AASInfo — 0 rows in source; PK (UserID) */
export const AASInfo = player.table(
  "AASInfo",
  {
    UserID: integer("UserID").notNull(),
    Name: varchar("Name", { length: 50 }).notNull(),
    IDNumber: varchar("IDNumber", { length: 50 }).notNull(),
    State: integer("State").notNull(),
  },
  (t) => [
    primaryKey({ name: "AASInfo_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.AchievementData — 0 rows in source; PK (UserID, AchievementID) */
export const AchievementData = player.table(
  "AchievementData",
  {
    UserID: integer("UserID").notNull(),
    AchievementID: integer("AchievementID").notNull(),
    IsComplete: boolean("IsComplete").notNull(),
    CompletedDate: timestamp("CompletedDate", { precision: 3, mode: "date" }).notNull(),
  },
  (t) => [
    primaryKey({ name: "AchievementData_pkey", columns: [t.UserID, t.AchievementID] }),
  ],
);

/** Project_Player34.dbo.Active_Number — 0 rows in source; PK (AwardID) */
export const Active_Number = player.table(
  "Active_Number",
  {
    AwardID: varchar("AwardID", { length: 50 }).notNull(),
    ActiveID: integer("ActiveID").notNull(),
    PullDown: boolean("PullDown").notNull().default(false),
    GetDate: timestamp("GetDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    UserID: integer("UserID").notNull().default(0),
    Mark: integer("Mark").notNull().default(0),
    GetByBot: boolean("GetByBot"),
  },
  (t) => [
    primaryKey({ name: "Active_Number_pkey", columns: [t.AwardID] }),
  ],
);

/** Project_Player34.dbo.AdoptPetList — 0 rows in source; PK (ID) */
export const AdoptPetList = player.table(
  "AdoptPetList",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    PetID: integer("PetID").notNull().default(0),
    TemplateID: integer("TemplateID").notNull().default(0),
    Name: varchar("Name", { length: 2000 }),
    UserID: integer("UserID").notNull().default(0),
    Attack: integer("Attack").notNull().default(0),
    Defence: integer("Defence").notNull().default(0),
    Luck: integer("Luck").notNull().default(0),
    Agility: integer("Agility").notNull().default(0),
    Blood: integer("Blood").notNull().default(0),
    Damage: integer("Damage").notNull().default(0),
    Guard: integer("Guard").notNull().default(0),
    AttackGrow: integer("AttackGrow").notNull().default(0),
    DefenceGrow: integer("DefenceGrow").notNull().default(0),
    LuckGrow: integer("LuckGrow").notNull().default(0),
    AgilityGrow: integer("AgilityGrow").notNull().default(0),
    BloodGrow: integer("BloodGrow").notNull().default(0),
    DamageGrow: integer("DamageGrow").notNull().default(0),
    GuardGrow: integer("GuardGrow").notNull().default(0),
    Level: integer("Level").notNull().default(1),
    GP: integer("GP").notNull().default(0),
    MaxGP: integer("MaxGP").notNull().default(0),
    Hunger: integer("Hunger").notNull().default(10000),
    PetHappyStar: integer("PetHappyStar").notNull().default(3),
    MP: integer("MP").notNull().default(0),
    IsEquip: boolean("IsEquip").notNull().default(false),
    Place: integer("Place").notNull().default(-1),
    IsExit: boolean("IsExit").notNull().default(true),
    IsUse: boolean("IsUse").notNull().default(false),
    Skill: varchar("Skill", { length: 50 }).notNull().default(""),
    SkillEquip: varchar("SkillEquip", { length: 50 }).notNull().default(""),
  },
  (t) => [
    primaryKey({ name: "AdoptPetList_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Auction — 0 rows in source; PK (AuctionID) */
export const Auction = player.table(
  "Auction",
  {
    AuctionID: integer("AuctionID").generatedByDefaultAsIdentity().notNull(),
    Name: varchar("Name", { length: 50 }).notNull(),
    Category: integer("Category").notNull(),
    AuctioneerID: integer("AuctioneerID").notNull(),
    AuctioneerName: varchar("AuctioneerName", { length: 50 }).notNull(),
    ItemID: integer("ItemID").notNull(),
    PayType: integer("PayType").notNull(),
    Price: integer("Price").notNull(),
    Rise: integer("Rise").notNull(),
    Mouthful: integer("Mouthful").notNull(),
    BeginDate: timestamp("BeginDate", { precision: 3, mode: "date" }).notNull(),
    ValidDate: integer("ValidDate").notNull(),
    BuyerID: integer("BuyerID").notNull(),
    BuyerName: varchar("BuyerName", { length: 50 }).notNull(),
    IsExist: boolean("IsExist").notNull(),
    TemplateID: integer("TemplateID").notNull().default(0),
    Random: integer("Random").notNull().default(0),
    goodsCount: integer("goodsCount").default(0),
  },
  (t) => [
    primaryKey({ name: "Auction_pkey", columns: [t.AuctionID] }),
    index("IX_Auction_AuctioneerID").on(t.AuctioneerID) /* added, not in original */,
  ],
);

/** Project_Player34.dbo.Bag_Init — 0 rows in source; PK (ID) */
export const Bag_Init = player.table(
  "Bag_Init",
  {
    ID: integer("ID").notNull(),
    Sex: integer("Sex").notNull().default(2),
    TemplateID: integer("TemplateID").notNull(),
    Count: integer("Count").notNull().default(1),
    ValidDate: integer("ValidDate").notNull().default(0),
    StrengthenLevel: integer("StrengthenLevel").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    LuckCompose: integer("LuckCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull().default(0),
    IsBinds: boolean("IsBinds").notNull().default(false),
    BagType: integer("BagType").notNull().default(-1),
    place: integer("place").notNull().default(-1),
  },
  (t) => [
    primaryKey({ name: "Bag_Init_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Charge_Money — 0 rows in source; PK (ChargeID) */
export const Charge_Money = player.table(
  "Charge_Money",
  {
    ChargeID: varchar("ChargeID", { length: 50 }).notNull(),
    UserName: varchar("UserName", { length: 200 }).notNull(),
    Money: integer("Money").notNull(),
    Date: timestamp("Date", { precision: 3, mode: "date" }).notNull().defaultNow(),
    CanUse: boolean("CanUse").notNull(),
    PayWay: varchar("PayWay", { length: 200 }).notNull().default("0"),
    NeedMoney: numeric("NeedMoney", { precision: 10, scale: 2 }).notNull().default("0"),
    IP: varchar("IP", { length: 50 }),
    NickName: varchar("NickName", { length: 200 }),
  },
  (t) => [
    primaryKey({ name: "Charge_Money_pkey", columns: [t.ChargeID] }),
  ],
);

/** Project_Player34.dbo.ChickActive_Number — 0 rows in source; PK (ActiveCode) */
export const ChickActive_Number = player.table(
  "ChickActive_Number",
  {
    ActiveCode: varchar("ActiveCode", { length: 100 }).notNull(),
    UserID: integer("UserID").notNull().default(0),
    GetDate: timestamp("GetDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ name: "ChickActive_Number_pkey", columns: [t.ActiveCode] }),
  ],
);

/** Project_Player34.dbo.Consortia — 0 rows in source; PK (ConsortiaID) */
export const Consortia = player.table(
  "Consortia",
  {
    ConsortiaID: integer("ConsortiaID").generatedByDefaultAsIdentity().notNull(),
    ConsortiaName: varchar("ConsortiaName", { length: 200 }).notNull(),
    Honor: integer("Honor").notNull(),
    CreatorID: integer("CreatorID").notNull(),
    CreatorName: varchar("CreatorName", { length: 200 }).notNull(),
    ChairmanID: integer("ChairmanID").notNull(),
    ChairmanName: varchar("ChairmanName", { length: 200 }).notNull(),
    Description: varchar("Description", { length: 1000 }),
    Placard: varchar("Placard", { length: 1000 }),
    Level: integer("Level").notNull(),
    MaxCount: integer("MaxCount").notNull(),
    CelebCount: integer("CelebCount").notNull(),
    BuildDate: timestamp("BuildDate", { precision: 3, mode: "date" }).notNull(),
    Repute: integer("Repute").notNull().default(999999999),
    Count: integer("Count").notNull().default(0),
    IP: varchar("IP", { length: 50 }).notNull(),
    Port: integer("Port").notNull(),
    IsExist: boolean("IsExist").notNull(),
    Riches: integer("Riches").notNull().default(0),
    DeductDate: timestamp("DeductDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    WarnDate: timestamp("WarnDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    LastDayRiches: integer("LastDayRiches").notNull().default(0),
    AddDayRiches: integer("AddDayRiches").notNull().default(0),
    LastWeekRiches: integer("LastWeekRiches").notNull().default(0),
    AddWeekRiches: integer("AddWeekRiches").notNull().default(0),
    LastDayHonor: integer("LastDayHonor").notNull().default(0),
    AddDayHonor: integer("AddDayHonor").notNull().default(0),
    LastWeekHonor: integer("LastWeekHonor").notNull().default(0),
    AddWeekHonor: integer("AddWeekHonor").notNull().default(0),
    OpenApply: boolean("OpenApply").notNull().default(true),
    StoreLevel: integer("StoreLevel").notNull().default(0),
    SmithLevel: integer("SmithLevel").notNull().default(0),
    ShopLevel: integer("ShopLevel").notNull().default(0),
    SkillLevel: integer("SkillLevel").notNull().default(0),
    Rename: boolean("Rename").notNull().default(false),
    KickDate: timestamp("KickDate", { precision: 3, mode: "date" }).notNull().default(sql`'1905-07-01 00:00:00'::timestamp`),
    KickCount: integer("KickCount").notNull().default(0),
    FightPower: integer("FightPower").notNull().default(0),
    BadgeType: integer("BadgeType").notNull().default(0),
    BadgeName: varchar("BadgeName", { length: 50 }).default(""),
    BadgeID: integer("BadgeID").notNull().default(0),
    BadgeBuyTime: varchar("BadgeBuyTime", { length: 50 }),
    ValidDate: integer("ValidDate").notNull().default(0),
    consortiaPower: integer("consortiaPower").notNull().default(0),
    DateOpenTask: timestamp("DateOpenTask", { precision: 3, mode: "date" }).default(sql`'2016-07-07 00:00:00'::timestamp`),
  },
  (t) => [
    primaryKey({ name: "Consortia_pkey", columns: [t.ConsortiaID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Ally — 0 rows in source; PK (ID) */
export const Consortia_Ally = player.table(
  "Consortia_Ally",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Consortia1ID: integer("Consortia1ID").notNull(),
    Consortia2ID: integer("Consortia2ID").notNull(),
    State: integer("State").notNull(),
    Date: timestamp("Date", { precision: 3, mode: "date" }).notNull().defaultNow(),
    ValidDate: integer("ValidDate").notNull(),
    IsExist: boolean("IsExist").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Ally_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Apply_Ally — 0 rows in source; PK (ID) */
export const Consortia_Apply_Ally = player.table(
  "Consortia_Apply_Ally",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Consortia1ID: integer("Consortia1ID").notNull(),
    Consortia2ID: integer("Consortia2ID").notNull(),
    Date: timestamp("Date", { precision: 3, mode: "date" }).notNull().defaultNow(),
    Remark: varchar("Remark", { length: 200 }),
    IsExist: boolean("IsExist").notNull(),
    State: integer("State").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Consortia_Apply_Ally_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Apply_Users — 0 rows in source; PK (ID) */
export const Consortia_Apply_Users = player.table(
  "Consortia_Apply_Users",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ConsortiaID: integer("ConsortiaID").notNull(),
    ConsortiaName: varchar("ConsortiaName", { length: 200 }),
    UserID: integer("UserID").notNull(),
    UserName: varchar("UserName", { length: 200 }).notNull(),
    ApplyDate: timestamp("ApplyDate", { precision: 3, mode: "date" }).notNull(),
    Remark: varchar("Remark", { length: 200 }),
    IsExist: boolean("IsExist").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Apply_Users_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Boss — 0 rows in source; PK (ConsortiaID) */
export const Consortia_Boss = player.table(
  "Consortia_Boss",
  {
    ConsortiaID: integer("ConsortiaID").notNull(),
    typeBoss: integer("typeBoss").notNull(),
    callBossCount: integer("callBossCount").notNull(),
    BossLevel: integer("BossLevel").notNull(),
    Blood: integer("Blood").notNull(),
    LastOpenBoss: timestamp("LastOpenBoss", { precision: 3, mode: "date" }).notNull(),
    BossOpenTime: timestamp("BossOpenTime", { precision: 3, mode: "date" }).notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Boss_pkey", columns: [t.ConsortiaID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Boss_Config — 0 rows in source; PK (Level) */
export const Consortia_Boss_Config = player.table(
  "Consortia_Boss_Config",
  {
    Level: integer("Level").notNull(),
    NpcID: integer("NpcID").notNull(),
    MissionID: integer("MissionID").notNull(),
    AwardID: integer("AwardID").notNull(),
    CostRich: integer("CostRich").notNull(),
    ProlongRich: integer("ProlongRich").notNull(),
    BossLevel: integer("BossLevel").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Boss_Config_pkey", columns: [t.Level] }),
  ],
);

/** Project_Player34.dbo.Consortia_Buff_Temp — 34 rows in source; PK (id) */
export const Consortia_Buff_Temp = player.table(
  "Consortia_Buff_Temp",
  {
    id: integer("id").notNull().default(0),
    name: varchar("name", { length: 50 }),
    descript: varchar("descript", { length: 250 }),
    type: integer("type").notNull().default(1),
    level: integer("level").notNull().default(1),
    value: integer("value").notNull().default(1),
    riches: integer("riches").notNull().default(0),
    metal: integer("metal").notNull().default(0),
    pic: integer("pic").notNull().default(0),
    group: integer("group").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Consortia_Buff_Temp_pkey", columns: [t.id] }),
  ],
);

/** Project_Player34.dbo.Consortia_Buffer — 0 rows in source; PK (ID) */
export const Consortia_Buffer = player.table(
  "Consortia_Buffer",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ConsortiaID: integer("ConsortiaID"),
    BufferID: integer("BufferID"),
    IsOpen: boolean("IsOpen"),
    BeginDate: timestamp("BeginDate", { precision: 3, mode: "date" }),
    ValidDate: integer("ValidDate"),
    Type: integer("Type"),
    Value: integer("Value"),
  },
  (t) => [
    primaryKey({ name: "Consortia_Buffer_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Duty — 0 rows in source; PK (DutyID) */
export const Consortia_Duty = player.table(
  "Consortia_Duty",
  {
    DutyID: integer("DutyID").generatedByDefaultAsIdentity().notNull(),
    ConsortiaID: integer("ConsortiaID").notNull(),
    Level: integer("Level").notNull(),
    DutyName: varchar("DutyName", { length: 200 }).notNull(),
    Right: integer("Right").notNull().default(0),
    IsExist: boolean("IsExist").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Duty_pkey", columns: [t.DutyID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Equip_Control — 0 rows in source; PK (ConsortiaID, Type, Level) */
export const Consortia_Equip_Control = player.table(
  "Consortia_Equip_Control",
  {
    ConsortiaID: integer("ConsortiaID").notNull(),
    Type: integer("Type").notNull(),
    Level: integer("Level").notNull(),
    Riches: integer("Riches").notNull(),
    IsExist: boolean("IsExist").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Equip_Control_pkey", columns: [t.ConsortiaID, t.Type, t.Level] }),
  ],
);

/** Project_Player34.dbo.Consortia_Event — 0 rows in source; PK (ID) */
export const Consortia_Event = player.table(
  "Consortia_Event",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ConsortiaID: integer("ConsortiaID").notNull(),
    Date: timestamp("Date", { precision: 3, mode: "date" }).notNull(),
    Type: integer("Type").notNull().default(0),
    NickName: varchar("NickName", { length: 50 }).notNull(),
    EventValue: integer("EventValue").notNull(),
    ManagerName: varchar("ManagerName", { length: 100 }),
    IsExist: boolean("IsExist").notNull(),
    Remark: varchar("Remark", { length: 1000 }).notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Event_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Invite_Users — 0 rows in source; PK (ID) */
export const Consortia_Invite_Users = player.table(
  "Consortia_Invite_Users",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ConsortiaID: integer("ConsortiaID").notNull(),
    ConsortiaName: varchar("ConsortiaName", { length: 200 }).notNull(),
    UserID: integer("UserID").notNull(),
    UserName: varchar("UserName", { length: 200 }).notNull(),
    InviteID: integer("InviteID").notNull(),
    InviteName: varchar("InviteName", { length: 200 }).notNull(),
    InviteDate: timestamp("InviteDate", { precision: 3, mode: "date" }).notNull(),
    Remark: varchar("Remark", { length: 200 }),
    IsExist: boolean("IsExist").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Invite_Users_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Level — 10 rows in source; PK (Level) */
export const Consortia_Level = player.table(
  "Consortia_Level",
  {
    Level: integer("Level").notNull(),
    Riches: integer("Riches").notNull(),
    Deduct: integer("Deduct").notNull(),
    NeedGold: integer("NeedGold").notNull(),
    NeedItem: integer("NeedItem").notNull(),
    Reward: integer("Reward").notNull(),
    Count: integer("Count").notNull(),
    StoreRiches: integer("StoreRiches").notNull().default(100),
    SmithRiches: integer("SmithRiches").notNull().default(100),
    ShopRiches: integer("ShopRiches").notNull().default(100),
    BufferRiches: integer("BufferRiches").notNull().default(0),
    KickMax: integer("KickMax").notNull().default(10),
    BossCount: integer("BossCount").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Consortia_Level_pkey", columns: [t.Level] }),
  ],
);

/** Project_Player34.dbo.Consortia_Task_Info — 0 rows in source; PK (ID) */
export const Consortia_Task_Info = player.table(
  "Consortia_Task_Info",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ConsortiaID: integer("ConsortiaID"),
    BeginTime: timestamp("BeginTime", { precision: 3, mode: "date" }),
    Contribution: integer("Contribution"),
    Expirience: integer("Expirience"),
    Offer: integer("Offer"),
    BuffID: integer("BuffID"),
    Level: integer("Level"),
    Riches: integer("Riches"),
    Time: integer("Time"),
    ConditionData: text("ConditionData"),
    RankTable: text("RankTable"),
    IsExist: boolean("IsExist").default(true),
  },
  (t) => [
    primaryKey({ name: "Consortia_Task_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Consortia_Users — 0 rows in source; PK (ID) */
export const Consortia_Users = player.table(
  "Consortia_Users",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ConsortiaID: integer("ConsortiaID").notNull(),
    UserID: integer("UserID").notNull(),
    UserName: varchar("UserName", { length: 200 }).notNull(),
    RatifierID: integer("RatifierID"),
    RatifierName: varchar("RatifierName", { length: 200 }),
    DutyID: integer("DutyID").notNull(),
    Remark: varchar("Remark", { length: 2000 }),
    IsBanChat: boolean("IsBanChat").notNull().default(false),
    IsExist: boolean("IsExist").notNull(),
  },
  (t) => [
    primaryKey({ name: "Consortia_Users_pkey", columns: [t.ID] }),
    index("IX_Consortia_Users_ConsortiaID").on(t.ConsortiaID) /* added, not in original */,
    index("IX_Consortia_Users_UserID").on(t.UserID) /* added, not in original */,
  ],
);

/** Project_Player34.dbo.DailyLogList — 0 rows in source; PK (ID) */
export const DailyLogList = player.table(
  "DailyLogList",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull(),
    UserAwardLog: integer("UserAwardLog").notNull().default(0),
    DayLog: varchar("DayLog", { length: 2000 }).default(""),
    LastDate: timestamp("LastDate", { precision: 3, mode: "date" }).notNull().default(sql`'1753-01-01 00:00:00'::timestamp`),
  },
  (t) => [
    primaryKey({ name: "DailyLogList_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.DailyRecordInfo — 0 rows in source; heap (no PK) */
export const DailyRecordInfo = player.table(
  "DailyRecordInfo",
  {
    UserID: integer("UserID").notNull(),
    Type: integer("Type").notNull(),
    Value: varchar("Value", { length: 500 }).notNull(),
  },
);

/** Project_Player34.dbo.Fight_Rate — 4 rows in source; PK (ID) */
export const Fight_Rate = player.table(
  "Fight_Rate",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ServerID: integer("ServerID").notNull().default(0),
    Rate: integer("Rate").notNull().default(0),
    BeginDay: timestamp("BeginDay", { precision: 3, mode: "date" }).notNull(),
    EndDay: timestamp("EndDay", { precision: 3, mode: "date" }).notNull(),
    BeginTime: timestamp("BeginTime", { precision: 3, mode: "date" }).notNull(),
    EndTime: timestamp("EndTime", { precision: 3, mode: "date" }).notNull(),
    BoyTemplateID: integer("BoyTemplateID").notNull(),
    GirlTemplateID: integer("GirlTemplateID").notNull(),
    SelfCue: varchar("SelfCue", { length: 200 }),
    EnemyCue: varchar("EnemyCue", { length: 200 }),
    Name: varchar("Name", { length: 50 }),
  },
  (t) => [
    primaryKey({ name: "Fight_Rate_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Fight_Record — 0 rows in source; PK (ID) */
export const Fight_Record = player.table(
  "Fight_Record",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    PlayBegin: timestamp("PlayBegin", { precision: 3, mode: "date" }).notNull(),
    PlayEnd: timestamp("PlayEnd", { precision: 3, mode: "date" }).notNull(),
    ChangeTeam: integer("ChangeTeam").notNull(),
    TeamA: varchar("TeamA", { length: 50 }),
    TeamB: varchar("TeamB", { length: 50 }),
    MapID: integer("MapID").notNull(),
    RoomType: integer("RoomType").notNull(),
    FightName: varchar("FightName", { length: 50 }),
    WinTeam: integer("WinTeam").notNull(),
  },
  (t) => [
    primaryKey({ name: "Fight_Record_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Game_Commands — 0 rows in source; PK (UserID) */
export const Game_Commands = player.table(
  "Game_Commands",
  {
    UserID: integer("UserID").notNull(),
    Commands: varchar("Commands", { length: 255 }).notNull(),
  },
  (t) => [
    primaryKey({ name: "Game_Commands_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.Item_Fusion — 157 rows in source; PK (FusionID) */
export const Item_Fusion = player.table(
  "Item_Fusion",
  {
    FusionID: integer("FusionID").generatedByDefaultAsIdentity().notNull(),
    Item1: integer("Item1").notNull().default(0),
    Item2: integer("Item2").notNull().default(0),
    Item3: integer("Item3").notNull().default(0),
    Item4: integer("Item4").notNull().default(0),
    Formula: integer("Formula").notNull().default(0),
    Reward: integer("Reward").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Item_Fusion_pkey", columns: [t.FusionID] }),
  ],
);

/** Project_Player34.dbo.Items_Fusion_List — 30 rows in source; PK (ID) */
export const Items_Fusion_List = player.table(
  "Items_Fusion_List",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    TemplateID: integer("TemplateID").notNull(),
    Show: integer("Show").notNull(),
    Real: integer("Real").notNull(),
  },
  (t) => [
    primaryKey({ name: "Items_Fusion_List_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.LuckStarRankInfo — 0 rows in source; PK (ID) */
export const LuckStarRankInfo = player.table(
  "LuckStarRankInfo",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull().default(0),
    useStarNum: integer("useStarNum").notNull().default(0),
    nickName: varchar("nickName", { length: 150 }),
    isVip: integer("isVip").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "LuckStarRankInfo_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Marry_Apply — 0 rows in source; PK (ID) */
export const Marry_Apply = player.table(
  "Marry_Apply",
  {
    UserID: integer("UserID").notNull(),
    ApplyUserID: integer("ApplyUserID").notNull(),
    ApplyUserName: varchar("ApplyUserName", { length: 50 }).notNull(),
    ApplyType: integer("ApplyType").notNull(),
    LoveProclamation: varchar("LoveProclamation", { length: 300 }),
    ApplyResult: boolean("ApplyResult"),
    isExist: boolean("isExist").notNull().default(true),
    isDeal: boolean("isDeal").notNull().default(false),
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ApplyDate: timestamp("ApplyDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ name: "Marry_Apply_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Marry_Info — 0 rows in source; PK (ID) */
export const Marry_Info = player.table(
  "Marry_Info",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull(),
    IsPublishEquip: boolean("IsPublishEquip").notNull(),
    Introduction: varchar("Introduction", { length: 120 }),
    RegistTime: timestamp("RegistTime", { precision: 3, mode: "date" }).notNull(),
    IsExist: boolean("IsExist").notNull().default(true),
  },
  (t) => [
    primaryKey({ name: "Marry_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Marry_Room_Info — 0 rows in source; PK (ID) */
export const Marry_Room_Info = player.table(
  "Marry_Room_Info",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Name: varchar("Name", { length: 50 }).notNull(),
    PlayerID: integer("PlayerID").notNull(),
    PlayerName: varchar("PlayerName", { length: 50 }),
    GroomID: integer("GroomID").notNull(),
    GroomName: varchar("GroomName", { length: 50 }),
    BrideID: integer("BrideID").notNull(),
    BrideName: varchar("BrideName", { length: 50 }),
    Pwd: varchar("Pwd", { length: 15 }).notNull(),
    AvailTime: integer("AvailTime").notNull(),
    MaxCount: integer("MaxCount").notNull(),
    GuestInvite: boolean("GuestInvite").notNull(),
    MapIndex: integer("MapIndex").notNull(),
    BeginTime: timestamp("BeginTime", { precision: 3, mode: "date" }).notNull(),
    BreakTime: timestamp("BreakTime", { precision: 3, mode: "date" }).notNull(),
    RoomIntroduction: varchar("RoomIntroduction", { length: 300 }),
    ServerID: integer("ServerID").notNull(),
    IsHymeneal: boolean("IsHymeneal").notNull(),
    isExist: boolean("isExist").notNull().default(true),
    IsGunsaluteUsed: boolean("IsGunsaluteUsed").notNull().default(false),
  },
  (t) => [
    primaryKey({ name: "Marry_Room_Info_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.New_ChickenBox_Data — 0 rows in source; PK (ID) */
export const New_ChickenBox_Data = player.table(
  "New_ChickenBox_Data",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull().default(0),
    TemplateID: integer("TemplateID").notNull().default(0),
    Count: integer("Count").notNull().default(0),
    ValidDate: integer("ValidDate").notNull().default(0),
    StrengthenLevel: integer("StrengthenLevel").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull(),
    LuckCompose: integer("LuckCompose").notNull(),
    Position: integer("Position").notNull().default(0),
    IsSelected: boolean("IsSelected").notNull().default(false),
    IsSeeded: boolean("IsSeeded").notNull().default(false),
    IsBinds: boolean("IsBinds").notNull().default(true),
  },
  (t) => [
    primaryKey({ name: "New_ChickenBox_Data_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.QuestData — 0 rows in source; PK (UserID, QuestID) */
export const QuestData = player.table(
  "QuestData",
  {
    UserID: integer("UserID").notNull(),
    QuestID: integer("QuestID").notNull(),
    IsComplete: boolean("IsComplete").notNull(),
    CompletedDate: timestamp("CompletedDate", { precision: 3, mode: "date" }),
    Condition1: integer("Condition1").notNull().default(0),
    Condition2: integer("Condition2").notNull().default(0),
    Condition3: integer("Condition3").notNull().default(0),
    Condition4: integer("Condition4").notNull().default(0),
    IsExist: boolean("IsExist").notNull().default(true),
    RepeatFinish: integer("RepeatFinish").notNull().default(0),
    RandDobule: integer("RandDobule").notNull().default(1),
  },
  (t) => [
    primaryKey({ name: "QuestData_pkey", columns: [t.UserID, t.QuestID] }),
  ],
);

/** Project_Player34.dbo.Rate — 0 rows in source; heap (no PK) */
export const Rate = player.table(
  "Rate",
  {
    ServerID: integer("ServerID").notNull(),
    Rate: numeric("Rate", { precision: 6, scale: 2 }).notNull(),
    BeginDay: timestamp("BeginDay", { precision: 3, mode: "date" }).notNull(),
    EndDay: timestamp("EndDay", { precision: 3, mode: "date" }).notNull(),
    BeginTime: timestamp("BeginTime", { precision: 3, mode: "date" }).notNull(),
    EndTime: timestamp("EndTime", { precision: 3, mode: "date" }).notNull(),
    Type: integer("Type").notNull().default(0),
  },
);

/** Project_Player34.dbo.Rename_Consortia — 0 rows in source; PK (ID) */
export const Rename_Consortia = player.table(
  "Rename_Consortia",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    ConsortiaID: integer("ConsortiaID").notNull(),
    ConsortiaName: varchar("ConsortiaName", { length: 200 }).notNull(),
    NickName: varchar("NickName", { length: 200 }).notNull(),
    Date: timestamp("Date", { precision: 3, mode: "date" }).notNull(),
    IsExist: boolean("IsExist").notNull(),
  },
  (t) => [
    primaryKey({ name: "Rename_Consortia_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Rename_Nick — 0 rows in source; PK (ID) */
export const Rename_Nick = player.table(
  "Rename_Nick",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull(),
    UserName: varchar("UserName", { length: 200 }).notNull(),
    NickName: varchar("NickName", { length: 200 }).notNull(),
    Date: timestamp("Date", { precision: 3, mode: "date" }).notNull(),
    IsExist: boolean("IsExist").notNull(),
    OldNickName: varchar("OldNickName", { length: 200 }),
  },
  (t) => [
    primaryKey({ name: "Rename_Nick_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Server_Config — 514 rows in source; PK (ID) */
export const Server_Config = player.table(
  "Server_Config",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 50 }).notNull(),
    Value: varchar("Value", { length: 2000 }).notNull(),
  },
  (t) => [
    primaryKey({ name: "Server_Config_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Server_Event — 3 rows in source; PK (ID) */
export const Server_Event = player.table(
  "Server_Event",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    Name: varchar("Name", { length: 200 }).notNull(),
    Value: varchar("Value", { length: 500 }),
  },
  (t) => [
    primaryKey({ name: "Server_Event_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Server_List — 1 rows in source; PK (ID) */
export const Server_List = player.table(
  "Server_List",
  {
    ID: integer("ID").notNull(),
    Name: varchar("Name", { length: 50 }),
    IP: varchar("IP", { length: 50 }),
    Port: integer("Port").default(0),
    State: integer("State").notNull().default(0),
    Online: integer("Online").notNull().default(0),
    Total: integer("Total").notNull().default(1000),
    Room: integer("Room").notNull().default(200),
    Remark: varchar("Remark", { length: 200 }),
    RSA: varchar("RSA", { length: 1000 }),
    MustLevel: integer("MustLevel").notNull().default(0),
    LowestLevel: integer("LowestLevel").notNull().default(0),
    NewerServer: boolean("NewerServer").notNull().default(false),
    ZoneId: integer("ZoneId").notNull().default(1),
    ZoneName: varchar("ZoneName", { length: 50 }).notNull().default("Server S1"),
  },
  (t) => [
    primaryKey({ name: "Server_List_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Suit_Manager — 0 rows in source; heap (no PK) */
export const Suit_Manager = player.table(
  "Suit_Manager",
  {
    UserID: integer("UserID"),
    Kill_List: varchar("Kill_List", { length: 200 }),
  },
);

/** Project_Player34.dbo.Sys_Active_System_Data — 0 rows in source; PK (ID) */
export const Sys_Active_System_Data = player.table(
  "Sys_Active_System_Data",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull().default(0),
    canOpenCounts: integer("canOpenCounts").notNull().default(5),
    canEagleEyeCounts: integer("canEagleEyeCounts").notNull().default(3),
    lastFlushTime: timestamp("lastFlushTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    isShowAll: boolean("isShowAll").notNull().default(true),
    ChickActiveData: text("ChickActiveData").notNull().default("0"),
    LuckystarCoins: integer("LuckystarCoins").notNull().default(0),
    ActiveMoney: integer("ActiveMoney").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_Active_System_Data_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Sys_Eat_Pets — 0 rows in source; PK (ID) */
export const Sys_Eat_Pets = player.table(
  "Sys_Eat_Pets",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull().default(0),
    weaponExp: integer("weaponExp").notNull().default(0),
    weaponLevel: integer("weaponLevel").notNull().default(0),
    clothesExp: integer("clothesExp").notNull().default(0),
    clothesLevel: integer("clothesLevel").notNull().default(0),
    hatExp: integer("hatExp").notNull().default(0),
    hatLevel: integer("hatLevel").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_Eat_Pets_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Sys_User_Farm — 0 rows in source; PK (ID) */
export const Sys_User_Farm = player.table(
  "Sys_User_Farm",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    FarmID: integer("FarmID").notNull(),
    PayFieldMoney: varchar("PayFieldMoney", { length: 50 }),
    PayAutoMoney: varchar("PayAutoMoney", { length: 50 }),
    AutoPayTime: timestamp("AutoPayTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    AutoValidDate: integer("AutoValidDate").notNull().default(1),
    VipLimitLevel: integer("VipLimitLevel").notNull().default(0),
    FarmerName: varchar("FarmerName", { length: 50 }),
    GainFieldId: integer("GainFieldId").notNull().default(0),
    MatureId: integer("MatureId").notNull().default(0),
    KillCropId: integer("KillCropId").notNull().default(0),
    isAutoId: integer("isAutoId").notNull().default(0),
    isFarmHelper: boolean("isFarmHelper").notNull().default(false),
    buyExpRemainNum: integer("buyExpRemainNum").notNull().default(20),
    isArrange: boolean("isArrange").notNull().default(false),
    FriendCrop: varchar("FriendCrop", { length: 1000 }),
    TreeLevel: integer("TreeLevel").notNull().default(0),
    TreeExp: integer("TreeExp").notNull().default(0),
    LoveScore: integer("LoveScore").notNull().default(0),
    MonsterExp: integer("MonsterExp").notNull().default(0),
    PoultryState: integer("PoultryState").notNull().default(0),
    CountDownTime: timestamp("CountDownTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    TreeCostExp: integer("TreeCostExp").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_User_Farm_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Sys_User_Field — 0 rows in source; PK (ID) */
export const Sys_User_Field = player.table(
  "Sys_User_Field",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    FarmID: integer("FarmID").notNull().default(0),
    FieldID: integer("FieldID").notNull().default(0),
    SeedID: integer("SeedID").notNull().default(0),
    PlantTime: timestamp("PlantTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    AccelerateTime: integer("AccelerateTime").notNull().default(0),
    FieldValidDate: integer("FieldValidDate").notNull().default(0),
    PayTime: timestamp("PayTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    GainCount: integer("GainCount").notNull().default(10),
    AutoSeedID: integer("AutoSeedID").notNull().default(0),
    AutoFertilizerID: integer("AutoFertilizerID").notNull().default(0),
    AutoSeedIDCount: integer("AutoSeedIDCount").notNull().default(0),
    AutoFertilizerCount: integer("AutoFertilizerCount").notNull().default(0),
    isAutomatic: boolean("isAutomatic").notNull().default(false),
    AutomaticTime: timestamp("AutomaticTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    IsExit: boolean("IsExit").notNull().default(false),
    payFieldTime: integer("payFieldTime").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_User_Field_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Sys_User_Gemstone — 0 rows in source; PK (ID) */
export const Sys_User_Gemstone = player.table(
  "Sys_User_Gemstone",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull(),
    FigSpiritId: integer("FigSpiritId").notNull().default(0),
    FigSpiritIdValue: varchar("FigSpiritIdValue", { length: 50 }).notNull().default("0,0,0|0,0,1|0,0,2"),
    EquipPlace: integer("EquipPlace").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_User_Gemstone_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Sys_User_Info — 0 rows in source; PK (UserID) */
export const Sys_User_Info = player.table(
  "Sys_User_Info",
  {
    UserID: integer("UserID").notNull(),
    UserEmail: varchar("UserEmail", { length: 255 }),
    UserPhone: varchar("UserPhone", { length: 50 }),
    UserOther1: varchar("UserOther1", { length: 50 }),
    UserOther2: varchar("UserOther2", { length: 50 }),
    UserOther3: varchar("UserOther3", { length: 50 }),
  },
  (t) => [
    primaryKey({ name: "Sys_User_Info_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.Sys_User_Match_Info — 0 rows in source; PK (UserID) */
export const Sys_User_Match_Info = player.table(
  "Sys_User_Match_Info",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull(),
    dailyScore: integer("dailyScore").notNull(),
    dailyWinCount: integer("dailyWinCount").notNull(),
    dailyGameCount: integer("dailyGameCount").notNull(),
    weeklyScore: integer("weeklyScore").notNull(),
    weeklyRanking: integer("weeklyRanking").notNull(),
    weeklyGameCount: integer("weeklyGameCount").notNull(),
    DailyLeagueFirst: boolean("DailyLeagueFirst").notNull().default(false),
    DailyLeagueLastScore: integer("DailyLeagueLastScore").notNull().default(0),
    addDayPrestge: integer("addDayPrestge").notNull().default(0),
    totalPrestige: integer("totalPrestige").notNull().default(0),
    restCount: integer("restCount").notNull().default(0),
    leagueItemsGet: integer("leagueItemsGet").notNull().default(0),
    leagueGrade: integer("leagueGrade").notNull().default(0),
    eliteScore: integer("eliteScore").notNull().default(0),
    eliteRank: integer("eliteRank").notNull().default(0),
    WeeklyWinCount: integer("WeeklyWinCount").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_User_Match_Info_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.Sys_User_Rank — 0 rows in source; PK (ID) */
export const Sys_User_Rank = player.table(
  "Sys_User_Rank",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull().default(0),
    UserRank: varchar("UserRank", { length: 500 }),
    Attack: integer("Attack").notNull().default(0),
    Defence: integer("Defence").notNull().default(0),
    Luck: integer("Luck").notNull().default(0),
    Agility: integer("Agility").notNull().default(0),
    HP: integer("HP").notNull().default(0),
    Damage: integer("Damage").notNull().default(0),
    Guard: integer("Guard").notNull().default(0),
    BeginDate: timestamp("BeginDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    Validate: integer("Validate").notNull().default(0),
    IsExit: boolean("IsExit").notNull().default(false),
    NewTitleID: integer("NewTitleID").notNull().default(0),
    EndDate: timestamp("EndDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    Name: varchar("Name", { length: 500 }),
  },
  (t) => [
    primaryKey({ name: "Sys_User_Rank_pkey", columns: [t.ID] }),
    index("IX_Sys_User_Rank_UserID").on(t.UserID) /* added, not in original */,
  ],
);

/** Project_Player34.dbo.Sys_Users_AvatarCollection — 0 rows in source; PK (ID) */
export const Sys_Users_AvatarCollection = player.table(
  "Sys_Users_AvatarCollection",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    AvatarID: integer("AvatarID").notNull(),
    UserID: integer("UserID").notNull(),
    Sex: integer("Sex").notNull(),
    IsActive: boolean("IsActive").notNull().default(false),
    Data: varchar("Data", { length: 500 }),
    TimeStart: timestamp("TimeStart", { precision: 3, mode: "date" }).defaultNow(),
    TimeEnd: timestamp("TimeEnd", { precision: 3, mode: "date" }).defaultNow(),
    IsExit: boolean("IsExit").notNull().default(true),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_AvatarCollection_pkey", columns: [t.ID] }),
    index("IX_Sys_Users_AvatarCollection_UserID").on(t.UserID) /* added, not in original */,
  ],
);

/** Project_Player34.dbo.Sys_Users_Card — 0 rows in source; PK (CardID) */
export const Sys_Users_Card = player.table(
  "Sys_Users_Card",
  {
    CardID: integer("CardID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull(),
    TemplateID: integer("TemplateID").notNull(),
    Place: integer("Place").notNull().default(0),
    Count: integer("Count").notNull().default(0),
    Attack: integer("Attack").notNull().default(0),
    Defence: integer("Defence").notNull().default(0),
    Agility: integer("Agility").notNull().default(0),
    Luck: integer("Luck").notNull().default(0),
    Guard: integer("Guard").notNull().default(0),
    AttackReset: integer("AttackReset").notNull().default(0),
    DefenceReset: integer("DefenceReset").notNull().default(0),
    AgilityReset: integer("AgilityReset").notNull().default(0),
    LuckReset: integer("LuckReset").notNull().default(0),
    Damage: integer("Damage").notNull().default(0),
    Level: integer("Level").notNull().default(0),
    CardGP: integer("CardGP").notNull().default(0),
    isFirstGet: boolean("isFirstGet").notNull().default(false),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Card_pkey", columns: [t.CardID] }),
    index("IX_Sys_Users_Card_UserID").on(t.UserID) /* added, not in original */,
  ],
);

/** Project_Player34.dbo.Sys_Users_DanhHieu — 0 rows in source; PK (Id) */
export const Sys_Users_DanhHieu = player.table(
  "Sys_Users_DanhHieu",
  {
    Id: integer("Id").generatedByDefaultAsIdentity().notNull(),
    Template: integer("Template"),
    UserRank: varchar("UserRank", { length: 250 }),
    Attack: integer("Attack").default(0),
    Defence: integer("Defence").default(0),
    Luck: integer("Luck"),
    Agility: integer("Agility").default(0),
    HP: integer("HP").default(0),
    Damage: integer("Damage").default(0),
    Guard: integer("Guard").default(0),
    Validate: integer("Validate").default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_DanhHieu_pkey", columns: [t.Id] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_Detail — 0 rows in source; PK (UserID) */
export const Sys_Users_Detail = player.table(
  "Sys_Users_Detail",
  {
    UserID: integer("UserID").generatedByDefaultAsIdentity().notNull(),
    UserName: varchar("UserName", { length: 200 }),
    Password: varchar("Password", { length: 200 }),
    NickName: varchar("NickName", { length: 50 }),
    Date: timestamp("Date", { precision: 3, mode: "date" }).notNull().defaultNow(),
    IsConsortia: boolean("IsConsortia").notNull().default(false),
    ConsortiaID: integer("ConsortiaID").notNull().default(0),
    Sex: boolean("Sex").notNull().default(true),
    Win: integer("Win").notNull().default(0),
    Total: integer("Total").notNull().default(0),
    Escape: integer("Escape").notNull().default(0),
    GP: integer("GP").notNull().default(0),
    Honor: varchar("Honor", { length: 50 }).notNull().default("Guerreiro"),
    Gold: integer("Gold").notNull().default(0),
    Money: integer("Money").notNull().default(0),
    MoneyLock: integer("MoneyLock").notNull().default(0),
    Style: varchar("Style", { length: 200 }).notNull().default(",,,,,,"),
    Colors: varchar("Colors", { length: 200 }).notNull().default(",,,,,,"),
    Hide: integer("Hide").notNull().default(1111111111),
    Grade: integer("Grade").notNull().default(1),
    State: integer("State").notNull().default(0),
    IsFirst: integer("IsFirst").notNull(),
    Repute: integer("Repute").notNull().default(0),
    LastDate: timestamp("LastDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    ChargeDate: timestamp("ChargeDate", { precision: 3, mode: "date" }),
    ExpendDate: timestamp("ExpendDate", { precision: 3, mode: "date" }),
    ActiveIP: varchar("ActiveIP", { length: 50 }),
    ForbidDate: timestamp("ForbidDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    Skin: varchar("Skin", { length: 50 }).notNull().default(""),
    Offer: integer("Offer").notNull().default(0),
    IsExist: boolean("IsExist").notNull().default(true),
    ReputeOffer: integer("ReputeOffer").notNull().default(0),
    LastDateSecond: timestamp("LastDateSecond", { precision: 3, mode: "date" }),
    LastDateThird: timestamp("LastDateThird", { precision: 3, mode: "date" }),
    LoginCount: integer("LoginCount").notNull().default(0),
    OnlineTime: integer("OnlineTime").notNull().default(0),
    AntiAddiction: integer("AntiAddiction").notNull().default(0),
    AntiDate: timestamp("AntiDate", { precision: 3, mode: "date" }),
    RichesOffer: integer("RichesOffer").notNull().default(0),
    RichesRob: integer("RichesRob").notNull().default(0),
    UseOffer: integer("UseOffer").notNull().default(0),
    LastDayGP: integer("LastDayGP").notNull().default(0),
    AddDayGP: integer("AddDayGP").notNull().default(0),
    LastWeekGP: integer("LastWeekGP").notNull().default(0),
    AddWeekGP: integer("AddWeekGP").notNull().default(0),
    LastDayOffer: integer("LastDayOffer").notNull().default(0),
    AddDayOffer: integer("AddDayOffer").notNull().default(0),
    LastWeekOffer: integer("LastWeekOffer").notNull().default(0),
    AddWeekOffer: integer("AddWeekOffer").notNull().default(0),
    CheckCount: integer("CheckCount").notNull().default(0),
    Site: varchar("Site", { length: 200 }),
    IsMarried: boolean("IsMarried").notNull().default(false),
    SpouseID: integer("SpouseID").notNull().default(0),
    SpouseName: varchar("SpouseName", { length: 50 }),
    MarryInfoID: integer("MarryInfoID").notNull().default(0),
    DayLoginCount: integer("DayLoginCount").notNull().default(0),
    ForbidReason: varchar("ForbidReason", { length: 1000 }),
    IsCreatedMarryRoom: boolean("IsCreatedMarryRoom").notNull().default(false),
    PasswordTwo: varchar("PasswordTwo", { length: 200 }),
    SelfMarryRoomID: integer("SelfMarryRoomID").notNull().default(0),
    IsGotRing: boolean("IsGotRing").notNull().default(false),
    ServerName: varchar("ServerName", { length: 50 }),
    Rename: boolean("Rename").notNull().default(false),
    Nimbus: integer("Nimbus").notNull().default(0),
    LastAward: timestamp("LastAward", { precision: 3, mode: "date" }).notNull().default(sql`'1905-07-01 00:00:00'::timestamp`),
    GiftToken: integer("GiftToken").notNull().default(0),
    QuestSite: bytea("QuestSite").notNull().default(sql`decode('', 'hex')`),
    PvePermission: varchar("PvePermission", { length: 50 }),
    FightLabPermission: varchar("FightLabPermission", { length: 50 }).default("10000000000"),
    FightPower: integer("FightPower").notNull().default(0),
    AnswerSite: integer("AnswerSite").notNull().default(0),
    LastAuncherAward: timestamp("LastAuncherAward", { precision: 3, mode: "date" }).notNull().default(sql`'1905-07-01 00:00:00'::timestamp`),
    WeaklessGuildProgressStr: text("WeaklessGuildProgressStr").notNull().default("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="),
    AchievementPoint: integer("AchievementPoint").notNull().default(0),
    IsShowConsortia: boolean("IsShowConsortia").notNull().default(false),
    OptionOnOff: integer("OptionOnOff").notNull().default(0),
    badgeID: integer("badgeID").notNull().default(0),
    IsRecharged: boolean("IsRecharged").default(false),
    IsGetAward: boolean("IsGetAward").default(false),
    MoneyPlus: integer("MoneyPlus").default(0),
    evolutionGrade: integer("evolutionGrade").notNull().default(0),
    evolutionExp: integer("evolutionExp").notNull().default(0),
    hardCurrency: integer("hardCurrency").notNull().default(0),
    EliteScore: integer("EliteScore").notNull().default(0),
    CanSentMoney: boolean("CanSentMoney").notNull().default(false),
    apprenticeshipState: integer("apprenticeshipState").notNull().default(0),
    masterID: integer("masterID").notNull().default(0),
    masterOrApprentices: varchar("masterOrApprentices", { length: 500 }).default(""),
    graduatesCount: integer("graduatesCount").notNull().default(0),
    honourOfMaster: varchar("honourOfMaster", { length: 500 }).default(""),
    freezesDate: timestamp("freezesDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    ShopFinallyGottenTime: timestamp("ShopFinallyGottenTime", { precision: 3, mode: "date" }).default(sql`'2016-08-07 00:00:00'::timestamp`),
    charmGP: integer("charmGP").notNull().default(0),
    Medal: integer("Medal").notNull().default(0),
    ChatCount: integer("ChatCount").notNull().default(0),
    SpaPubGoldRoomLimit: integer("SpaPubGoldRoomLimit").notNull().default(0),
    LastSpaDate: timestamp("LastSpaDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    IsInSpaPubGoldToday: boolean("IsInSpaPubGoldToday").notNull().default(false),
    IsInSpaPubMoneyToday: boolean("IsInSpaPubMoneyToday").notNull().default(false),
    LastWeekly: timestamp("LastWeekly", { precision: 3, mode: "date" }).notNull().defaultNow(),
    LastWeeklyVersion: integer("LastWeeklyVersion").notNull().default(0),
    IsOldPlayer: boolean("IsOldPlayer").notNull().default(false),
    Score: integer("Score").notNull().default(0),
    isOldPlayerHasValidEquitAtLogin: boolean("isOldPlayerHasValidEquitAtLogin").notNull().default(false),
    badLuckNumber: integer("badLuckNumber").notNull().default(0),
    luckyNum: integer("luckyNum").notNull().default(0),
    lastLuckyNumDate: timestamp("lastLuckyNumDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    lastLuckNum: integer("lastLuckNum").notNull().default(0),
    NewDay: timestamp("NewDay", { precision: 3, mode: "date" }).notNull().defaultNow(),
    BoxGetDate: timestamp("BoxGetDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    AlreadyGetBox: integer("AlreadyGetBox").notNull().default(0),
    BoxProgression: integer("BoxProgression").notNull().default(0),
    GetBoxLevel: integer("GetBoxLevel").notNull().default(0),
    AddWeekLeagueScore: integer("AddWeekLeagueScore").notNull().default(0),
    WeekLeagueRanking: integer("WeekLeagueRanking").notNull().default(0),
    SpaPubMoneyRoomLimit: integer("SpaPubMoneyRoomLimit").notNull().default(0),
    LastGetEgg: timestamp("LastGetEgg", { precision: 3, mode: "date" }).notNull().default(sql`'1905-07-01 00:00:00'::timestamp`),
    IsFistGetPet: boolean("IsFistGetPet").notNull().default(true),
    LastRefreshPet: timestamp("LastRefreshPet", { precision: 3, mode: "date" }).notNull().defaultNow(),
    petScore: integer("petScore").notNull().default(0),
    accumulativeLoginDays: integer("accumulativeLoginDays").notNull().default(0),
    accumulativeAwardDays: integer("accumulativeAwardDays").notNull().default(0),
    honorId: integer("honorId").notNull().default(0),
    damageScores: integer("damageScores").notNull().default(0),
    totemId: integer("totemId").notNull().default(0),
    myHonor: integer("myHonor").notNull().default(0),
    MaxBuyHonor: integer("MaxBuyHonor").notNull().default(0),
    necklaceExp: integer("necklaceExp").notNull().default(0),
    necklaceExpAdd: integer("necklaceExpAdd").notNull().default(0),
    GhostEquipList: text("GhostEquipList"),
    fineSuitExp: integer("fineSuitExp").notNull().default(0),
    CountPVP: integer("CountPVP").notNull().default(1),
    IsSMG: boolean("IsSMG").notNull().default(false),
    FightLimit: integer("FightLimit").notNull().default(1),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Detail_pkey", columns: [t.UserID] }),
    index("IX_Sys_Users_Detail_UserName").on(t.UserName) /* added, not in original */,
    index("IX_Sys_Users_Detail_NickName").on(t.NickName) /* added, not in original */,
    index("IX_Sys_Users_Detail_ConsortiaID").on(t.ConsortiaID) /* added, not in original */,
  ],
);

/** Project_Player34.dbo.Sys_Users_EventProcess — 0 rows in source; PK (UserID, ActiveType) */
export const Sys_Users_EventProcess = player.table(
  "Sys_Users_EventProcess",
  {
    UserID: integer("UserID").notNull(),
    ActiveType: integer("ActiveType").notNull(),
    Conditions: integer("Conditions").notNull().default(0),
    AwardGot: integer("AwardGot").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_EventProcess_pkey", columns: [t.UserID, t.ActiveType] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_Extra — 0 rows in source; PK (UserID) */
export const Sys_Users_Extra = player.table(
  "Sys_Users_Extra",
  {
    UserID: integer("UserID").notNull(),
    LastTimeHotSpring: timestamp("LastTimeHotSpring", { precision: 3, mode: "date" }).notNull().defaultNow(),
    LastFreeTimeHotSpring: timestamp("LastFreeTimeHotSpring", { precision: 3, mode: "date" }).notNull().defaultNow(),
    MinHotSpring: integer("MinHotSpring").notNull().default(60),
    LastTimeConsortiaPower: timestamp("LastTimeConsortiaPower", { precision: 3, mode: "date" }).notNull().defaultNow(),
    coupleBossEnterNum: integer("coupleBossEnterNum").notNull().default(0),
    coupleBossHurt: integer("coupleBossHurt").notNull().default(0),
    coupleBossBoxNum: integer("coupleBossBoxNum").notNull().default(0),
    TotalCaddyOpen: integer("TotalCaddyOpen").notNull().default(0),
    isGetAwardMarry: boolean("isGetAwardMarry").notNull().default(false),
    isFirstAwardMarry: boolean("isFirstAwardMarry").notNull().default(false),
    LastGetEgg: timestamp("LastGetEgg", { precision: 3, mode: "date" }),
    PassWarriorArena: integer("PassWarriorArena").notNull().default(0),
    LeftRoutteCount: integer("LeftRoutteCount"),
    LeftRoutteRate: doublePrecision("LeftRoutteRate"),
    FreeSendMailCount: integer("FreeSendMailCount").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Extra_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_Fight — 0 rows in source; PK (UserID) */
export const Sys_Users_Fight = player.table(
  "Sys_Users_Fight",
  {
    UserID: integer("UserID").notNull(),
    Attack: integer("Attack").notNull().default(0),
    Defence: integer("Defence").notNull().default(0),
    Luck: integer("Luck").notNull().default(0),
    Agility: integer("Agility").notNull().default(0),
    HP: integer("HP").notNull().default(0),
    Delay: integer("Delay").notNull().default(0),
    Honor: varchar("Honor", { length: 200 }),
    Map: varchar("Map", { length: 50 }),
    Directory: varchar("Directory", { length: 50 }),
    IsExist: boolean("IsExist").notNull().default(true),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Fight_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_Friends — 0 rows in source; PK (ID) */
export const Sys_Users_Friends = player.table(
  "Sys_Users_Friends",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull(),
    FriendID: integer("FriendID").notNull(),
    AddDate: timestamp("AddDate", { precision: 3, mode: "date" }).defaultNow(),
    Remark: varchar("Remark", { length: 200 }),
    IsExist: boolean("IsExist").notNull().default(true),
    Relation: integer("Relation").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Friends_pkey", columns: [t.ID] }),
    index("IX_Sys_Users_Friends_UserID").on(t.UserID) /* added, not in original */,
  ],
);

/** Project_Player34.dbo.Sys_Users_Gift — 0 rows in source; PK (ID) */
export const Sys_Users_Gift = player.table(
  "Sys_Users_Gift",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    SenderID: integer("SenderID").notNull(),
    ReceiverID: integer("ReceiverID").notNull(),
    TemplateID: integer("TemplateID").notNull(),
    Count: integer("Count").notNull(),
    CreateDate: timestamp("CreateDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    LastUpdate: timestamp("LastUpdate", { precision: 3, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Gift_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_Goods — 0 rows in source; PK (ItemID) */
export const Sys_Users_Goods = player.table(
  "Sys_Users_Goods",
  {
    ItemID: integer("ItemID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull().default(0),
    BagType: integer("BagType").notNull().default(0),
    TemplateID: integer("TemplateID").notNull().default(0),
    Place: integer("Place").notNull().default(100),
    Count: integer("Count").notNull().default(1),
    IsJudge: boolean("IsJudge").notNull().default(true),
    Color: varchar("Color", { length: 50 }),
    IsExist: boolean("IsExist").notNull().default(true),
    StrengthenLevel: integer("StrengthenLevel").notNull().default(0),
    StrengthenExp: integer("StrengthenExp").notNull().default(0),
    AttackCompose: integer("AttackCompose").notNull().default(0),
    DefendCompose: integer("DefendCompose").notNull().default(0),
    LuckCompose: integer("LuckCompose").notNull().default(0),
    AgilityCompose: integer("AgilityCompose").notNull().default(0),
    Skin: varchar("Skin", { length: 50 }).notNull().default(""),
    IsBinds: boolean("IsBinds").notNull().default(false),
    IsUsed: boolean("IsUsed").notNull().default(false),
    BeginDate: timestamp("BeginDate", { precision: 3, mode: "date" }).notNull().default(sql`'1905-06-11 00:00:00'::timestamp`),
    ValidDate: integer("ValidDate").notNull().default(10),
    RemoveDate: timestamp("RemoveDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    RemoveType: integer("RemoveType").notNull().default(0),
    Hole1: integer("Hole1").notNull().default(-1),
    Hole2: integer("Hole2").notNull().default(-1),
    Hole3: integer("Hole3").notNull().default(-1),
    Hole4: integer("Hole4").notNull().default(-1),
    Hole5: integer("Hole5").notNull().default(-1),
    Hole6: integer("Hole6").notNull().default(-1),
    Hole5Level: integer("Hole5Level").notNull().default(0),
    Hole5Exp: integer("Hole5Exp").notNull().default(0),
    Hole6Level: integer("Hole6Level").notNull().default(0),
    Hole6Exp: integer("Hole6Exp").notNull().default(0),
    StrengthenTimes: integer("StrengthenTimes").notNull().default(0),
    StrengthenRefineryLevel: integer("StrengthenRefineryLevel").notNull().default(0),
    isGold: boolean("isGold").notNull().default(false),
    goldValidDate: integer("goldValidDate").notNull().default(0),
    goldBeginTime: timestamp("goldBeginTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    Blood: integer("Blood").notNull().default(0),
    latentEnergyCurStr: varchar("latentEnergyCurStr", { length: 50 }).notNull().default("0,0,0,0"),
    latentEnergyNewStr: varchar("latentEnergyNewStr", { length: 50 }).notNull().default("0,0,0,0"),
    latentEnergyEndTime: timestamp("latentEnergyEndTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    curExp: integer("curExp").notNull().default(0),
    cellLocked: boolean("cellLocked").notNull().default(false),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Goods_pkey", columns: [t.ItemID] }),
    index("IX_Sys_Users_Goods_UserID_BagType").on(t.UserID, t.BagType) /* added, not in original */,
  ],
);

/** Project_Player34.dbo.Sys_Users_Labyrinth — 0 rows in source; PK (UserID) */
export const Sys_Users_Labyrinth = player.table(
  "Sys_Users_Labyrinth",
  {
    UserID: integer("UserID").notNull(),
    myProgress: integer("myProgress").notNull().default(0),
    myRanking: integer("myRanking").notNull().default(0),
    completeChallenge: boolean("completeChallenge").notNull().default(false),
    isDoubleAward: boolean("isDoubleAward").notNull().default(true),
    currentFloor: integer("currentFloor").notNull().default(0),
    accumulateExp: integer("accumulateExp").notNull().default(0),
    remainTime: integer("remainTime").notNull().default(0),
    currentRemainTime: integer("currentRemainTime").notNull().default(0),
    cleanOutAllTime: integer("cleanOutAllTime").notNull().default(0),
    cleanOutGold: integer("cleanOutGold").notNull().default(0),
    tryAgainComplete: boolean("tryAgainComplete").notNull().default(false),
    isInGame: boolean("isInGame").notNull().default(false),
    isCleanOut: boolean("isCleanOut").notNull().default(false),
    serverMultiplyingPower: boolean("serverMultiplyingPower").notNull().default(false),
    LastDate: timestamp("LastDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    ProcessAward: varchar("ProcessAward", { length: 2000 }).notNull().default("-1"),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Labyrinth_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_League — 0 rows in source; PK (ID) */
export const Sys_Users_League = player.table(
  "Sys_Users_League",
  {
    UserID: integer("UserID").notNull(),
    RankID: integer("RankID").notNull().default(1),
    Point: integer("Point").notNull().default(0),
    Win: integer("Win").notNull().default(0),
    Lose: integer("Lose").notNull().default(0),
    IsBanned: boolean("IsBanned").notNull().default(false),
    ForbidDate: timestamp("ForbidDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    ForbidReason: varchar("ForbidReason", { length: 500 }).notNull().default("Không Có"),
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_League_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_Log — 0 rows in source; PK (ID) */
export const Sys_Users_Log = player.table(
  "Sys_Users_Log",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    UserID: integer("UserID").notNull(),
    UserName: varchar("UserName", { length: 100 }).notNull(),
    NickName: varchar("NickName", { length: 100 }).notNull(),
    Type: varchar("Type", { length: 50 }),
    Content: varchar("Content", { length: 500 }),
    TimeCreate: timestamp("TimeCreate", { precision: 3, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Log_pkey", columns: [t.ID] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_Order — 0 rows in source; PK (UserID) */
export const Sys_Users_Order = player.table(
  "Sys_Users_Order",
  {
    UserID: integer("UserID").notNull(),
    Repute: integer("Repute").notNull().default(0),
    ReputeOffer: integer("ReputeOffer").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Order_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_Password — 0 rows in source; PK (UserID) */
export const Sys_Users_Password = player.table(
  "Sys_Users_Password",
  {
    UserID: integer("UserID").notNull(),
    PasswordQuestion1: varchar("PasswordQuestion1", { length: 50 }),
    PasswordAnswer1: varchar("PasswordAnswer1", { length: 50 }),
    PasswordQuestion2: varchar("PasswordQuestion2", { length: 50 }),
    PasswordAnswer2: varchar("PasswordAnswer2", { length: 50 }),
    LastFindDate: timestamp("LastFindDate", { precision: 3, mode: "date" }),
    FailedPasswordAttemptCount: integer("FailedPasswordAttemptCount").default(5),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Password_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.Sys_Users_Pet — 0 rows in source; PK (ID) */
export const Sys_Users_Pet = player.table(
  "Sys_Users_Pet",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    TemplateID: integer("TemplateID").notNull().default(0),
    Name: varchar("Name", { length: 2000 }),
    UserID: integer("UserID").notNull().default(0),
    Attack: integer("Attack").notNull().default(0),
    Defence: integer("Defence").notNull().default(0),
    Luck: integer("Luck").notNull().default(0),
    Agility: integer("Agility").notNull().default(0),
    Blood: integer("Blood").notNull().default(0),
    Damage: integer("Damage").notNull().default(0),
    Guard: integer("Guard").notNull().default(0),
    AttackGrow: integer("AttackGrow").notNull().default(0),
    DefenceGrow: integer("DefenceGrow").notNull().default(0),
    LuckGrow: integer("LuckGrow").notNull().default(0),
    AgilityGrow: integer("AgilityGrow").notNull().default(0),
    BloodGrow: integer("BloodGrow").notNull().default(0),
    DamageGrow: integer("DamageGrow").notNull().default(0),
    GuardGrow: integer("GuardGrow").notNull().default(0),
    Level: integer("Level").notNull().default(1),
    GP: integer("GP").notNull().default(0),
    MaxGP: integer("MaxGP").notNull().default(55),
    Hunger: integer("Hunger").notNull().default(10000),
    PetHappyStar: integer("PetHappyStar").notNull().default(3),
    MP: integer("MP").notNull().default(0),
    IsEquip: boolean("IsEquip").notNull().default(false),
    Place: integer("Place").notNull().default(-1),
    IsExit: boolean("IsExit").notNull().default(false),
    Skill: text("Skill"),
    SkillEquip: text("SkillEquip"),
    currentStarExp: integer("currentStarExp").notNull().default(0),
    breakGrade: integer("breakGrade").notNull().default(-1),
    breakAttack: integer("breakAttack").notNull().default(0),
    breakDefence: integer("breakDefence").notNull().default(0),
    breakAgility: integer("breakAgility").notNull().default(0),
    breakLuck: integer("breakLuck").notNull().default(0),
    breakBlood: integer("breakBlood").notNull().default(0),
    eQPets: text("eQPets").notNull().default("[]"),
    BaseProp: text("BaseProp").notNull().default(""),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Pet_pkey", columns: [t.ID] }),
    index("IX_Sys_Users_Pet_UserID").on(t.UserID) /* added, not in original */,
  ],
);

/** Project_Player34.dbo.Sys_Users_Rank_Date — 0 rows in source; heap (no PK) */
export const Sys_Users_Rank_Date = player.table(
  "Sys_Users_Rank_Date",
  {
    UserID: integer("UserID").notNull().default(0),
    ConsortiaID: integer("ConsortiaID").notNull().default(0),
    FightPower: integer("FightPower").notNull().default(0),
    PrevFightPower: integer("PrevFightPower").notNull().default(0),
    GP: integer("GP").notNull().default(0),
    PrevGP: integer("PrevGP").notNull().default(0),
    AchievementPoint: integer("AchievementPoint").notNull().default(0),
    PrevAchievementPoint: integer("PrevAchievementPoint").notNull().default(0),
    charmGP: integer("charmGP").notNull().default(0),
    PrecharmGP: integer("PrecharmGP").notNull().default(0),
    LeagueAddWeek: integer("LeagueAddWeek").notNull().default(0),
    PrevLeagueAddWeek: integer("PrevLeagueAddWeek").notNull().default(0),
    ConsortiaFightPower: integer("ConsortiaFightPower").notNull().default(0),
    ConsortiaPrevFightPower: integer("ConsortiaPrevFightPower").notNull().default(0),
    ConsortiaLevel: integer("ConsortiaLevel").notNull().default(0),
    ConsortiaPrevLevel: integer("ConsortiaPrevLevel").notNull().default(0),
    ConsortiaRiches: integer("ConsortiaRiches").notNull().default(0),
    ConsortiaPrevRiches: integer("ConsortiaPrevRiches").notNull().default(0),
    ConsortiacharmGP: integer("ConsortiacharmGP").notNull().default(0),
    ConsortiaPrevcharmGP: integer("ConsortiaPrevcharmGP").notNull().default(0),
  },
);

/** Project_Player34.dbo.Sys_Users_Record — 0 rows in source; heap (no PK) */
export const Sys_Users_Record = player.table(
  "Sys_Users_Record",
  {
    UserID: integer("UserID").notNull(),
    RecordID: integer("RecordID").notNull().default(0),
    Total: integer("Total").notNull().default(0),
  },
);

/** Project_Player34.dbo.Sys_Users_Texp — 0 rows in source; PK (UserID) */
export const Sys_Users_Texp = player.table(
  "Sys_Users_Texp",
  {
    UserID: integer("UserID").notNull(),
    spdTexpExp: integer("spdTexpExp").notNull().default(0),
    attTexpExp: integer("attTexpExp").notNull().default(0),
    defTexpExp: integer("defTexpExp").notNull().default(0),
    hpTexpExp: integer("hpTexpExp").notNull().default(0),
    lukTexpExp: integer("lukTexpExp").notNull().default(0),
    texpTaskCount: integer("texpTaskCount").notNull().default(0),
    texpCount: integer("texpCount").notNull().default(0),
    texpTaskDate: timestamp("texpTaskDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ name: "Sys_Users_Texp_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.Sys_VIP_Info — 0 rows in source; PK (UserID) */
export const Sys_VIP_Info = player.table(
  "Sys_VIP_Info",
  {
    UserID: integer("UserID").generatedByDefaultAsIdentity().notNull(),
    typeVIP: integer("typeVIP").notNull().default(0),
    VIPLevel: integer("VIPLevel").notNull().default(0),
    VIPExp: integer("VIPExp").notNull().default(0),
    VIPOnlineDays: integer("VIPOnlineDays").notNull().default(0),
    VIPOfflineDays: integer("VIPOfflineDays").notNull().default(0),
    VIPExpireDay: timestamp("VIPExpireDay", { precision: 3, mode: "date" }).notNull().defaultNow(),
    LastVIPPackTime: timestamp("LastVIPPackTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    VIPLastdate: timestamp("VIPLastdate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    VIPNextLevelDaysNeeded: integer("VIPNextLevelDaysNeeded").notNull().default(0),
    CanTakeVipReward: boolean("CanTakeVipReward").notNull().default(false),
  },
  (t) => [
    primaryKey({ name: "Sys_VIP_Info_pkey", columns: [t.UserID] }),
  ],
);

/** Project_Player34.dbo.User_Buff — 0 rows in source; PK (UserID, Type) */
export const User_Buff = player.table(
  "User_Buff",
  {
    UserID: integer("UserID").notNull(),
    Type: integer("Type").notNull(),
    Value: integer("Value").notNull(),
    BeginDate: timestamp("BeginDate", { precision: 3, mode: "date" }).notNull(),
    ValidDate: integer("ValidDate").notNull(),
    TemplateID: integer("TemplateID").notNull().default(0),
    ValidCount: integer("ValidCount").notNull().default(0),
    Data: varchar("Data", { length: 200 }),
    IsExist: boolean("IsExist").notNull(),
  },
  (t) => [
    primaryKey({ name: "User_Buff_pkey", columns: [t.UserID, t.Type] }),
  ],
);

/** Project_Player34.dbo.User_Messages — 0 rows in source; PK (ID) */
export const User_Messages = player.table(
  "User_Messages",
  {
    ID: integer("ID").generatedByDefaultAsIdentity().notNull(),
    SenderID: integer("SenderID").notNull().default(0),
    Sender: varchar("Sender", { length: 50 }),
    ReceiverID: integer("ReceiverID").notNull().default(0),
    Receiver: varchar("Receiver", { length: 50 }),
    Title: varchar("Title", { length: 500 }),
    Content: varchar("Content", { length: 2000 }),
    SendTime: timestamp("SendTime", { precision: 3, mode: "date" }).notNull().defaultNow(),
    IsRead: boolean("IsRead").notNull().default(false),
    IsDelR: boolean("IsDelR").notNull().default(false),
    IfDelS: boolean("IfDelS").notNull().default(false),
    IsDelete: boolean("IsDelete").notNull().default(false),
    Annex1: varchar("Annex1", { length: 50 }),
    Annex2: varchar("Annex2", { length: 50 }),
    Gold: integer("Gold").notNull().default(0),
    Money: integer("Money").notNull().default(0),
    IsExist: boolean("IsExist").notNull().default(true),
    Type: integer("Type").notNull().default(0),
    Remark: varchar("Remark", { length: 200 }),
    ValidDate: integer("ValidDate").notNull().default(240),
    Annex1Name: varchar("Annex1Name", { length: 50 }),
    Annex2Name: varchar("Annex2Name", { length: 50 }),
    SendDate: timestamp("SendDate", { precision: 3, mode: "date" }).notNull().defaultNow(),
    Annex3: varchar("Annex3", { length: 50 }),
    Annex4: varchar("Annex4", { length: 50 }),
    Annex5: varchar("Annex5", { length: 50 }),
    Annex3Name: varchar("Annex3Name", { length: 50 }),
    Annex4Name: varchar("Annex4Name", { length: 50 }),
    Annex5Name: varchar("Annex5Name", { length: 50 }),
    AnnexRemark: varchar("AnnexRemark", { length: 200 }),
    GiftToken: integer("GiftToken").notNull().default(0),
  },
  (t) => [
    primaryKey({ name: "User_Messages_pkey", columns: [t.ID] }),
    index("IX_User_Messages_ReceiverID").on(t.ReceiverID) /* added, not in original */,
    index("IX_User_Messages_SenderID").on(t.SenderID) /* added, not in original */,
  ],
);
