// AUTO-GENERATED by scripts/gen-schema.ts — DO NOT EDIT.
import { customType, pgSchema } from "drizzle-orm/pg-core";

/** Project_Game34 (templates) */
export const game = pgSchema("game");
/** Project_Player34 (player data + a few config tables) */
export const player = pgSchema("player");
/** Db_Membership (web accounts; schema only) + the new "Accounts" table */
export const member = pgSchema("member");

/** SQL Server varbinary/image -> bytea */
export const bytea = customType<{ data: Uint8Array; driverData: Uint8Array }>({
  dataType: () => "bytea",
});
