-- Project_Game34: 104 tables. Generated by vendor/_tools/export.mjs from sys.* catalog (SQL Server dialect).

-- rows: 281
CREATE TABLE [dbo].[Achievement] (
  [ID] int NOT NULL,
  [PlaceID] int NOT NULL,
  [Title] nvarchar(100) NOT NULL,
  [Detail] nvarchar(500) NOT NULL,
  [NeedMinLevel] int NOT NULL,
  [NeedMaxLevel] int NOT NULL,
  [PreAchievementID] nvarchar(100) NOT NULL,
  [IsOther] int NOT NULL,
  [AchievementType] int NOT NULL,
  [CanHide] bit NOT NULL,
  [StartDate] datetime NOT NULL,
  [EndDate] datetime NOT NULL,
  [AchievementPoint] int NOT NULL,
  [IsActive] int NOT NULL,
  [PicID] int NOT NULL,
  [IsShare] bit NOT NULL
);

-- rows: 60
CREATE TABLE [dbo].[Achievement_Goods] (
  [AchievementID] int NOT NULL,
  [RewardType] int NOT NULL,
  [RewardPara] nvarchar(500) NOT NULL,
  [RewardValueId] int NOT NULL,
  [RewardCount] int NOT NULL
);

-- rows: 341
CREATE TABLE [dbo].[AchievementCondition] (
  [AchievementID] int NOT NULL,
  [CondictionID] int NOT NULL CONSTRAINT [DF_AchievementCondition_CondictionID] DEFAULT ((0)),
  [CondictionType] int NOT NULL CONSTRAINT [DF_AchievementCondition_CondictionType] DEFAULT ((0)),
  [Condiction_Para1] nvarchar(150) NULL,
  [Condiction_Para2] int NOT NULL CONSTRAINT [DF_AchievementCondition_Condiction_Para2] DEFAULT ((0)),
  CONSTRAINT [PK_AchievementCondition] PRIMARY KEY CLUSTERED ([AchievementID], [CondictionID])
);

-- rows: 33
CREATE TABLE [dbo].[Active] (
  [ActiveID] int NOT NULL,
  [Title] nvarchar(200) NOT NULL,
  [Description] nvarchar(2000) NULL,
  [Content] nvarchar(2000) NULL,
  [AwardContent] nvarchar(2000) NULL,
  [HasKey] int NOT NULL CONSTRAINT [DF_Active_HasKey] DEFAULT ((0)),
  [StartDate] datetime NOT NULL CONSTRAINT [DF_Active_StartDate] DEFAULT (getdate()),
  [EndDate] datetime NULL,
  [IsOnly] int NOT NULL CONSTRAINT [DF_Active_IsOnly] DEFAULT ((0)),
  [Type] int NOT NULL CONSTRAINT [DF_Active_Type] DEFAULT ((0)),
  [ActionTimeContent] nvarchar(50) NULL,
  [IsAdvance] bit NOT NULL CONSTRAINT [DF_Active_IsAdvance] DEFAULT ((0)),
  [GoodsExchangeTypes] nvarchar(50) NULL,
  [GoodsExchangeNum] nvarchar(50) NULL,
  [limitType] nvarchar(50) NULL,
  [limitValue] nvarchar(50) NULL,
  [IsShow] bit NOT NULL CONSTRAINT [DF_Active_IsShow] DEFAULT ((0)),
  [ActiveType] int NOT NULL CONSTRAINT [DF_Active_ActiveType] DEFAULT ((0)),
  [IconID] int NOT NULL CONSTRAINT [DF_Active_IconID] DEFAULT ((0)),
  [CanCreateCode] bit NULL,
  CONSTRAINT [PK_Active] PRIMARY KEY CLUSTERED ([ActiveID])
);

-- rows: 310
CREATE TABLE [dbo].[Active_Award] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ActiveID] int NOT NULL,
  [ItemID] int NOT NULL,
  [Count] int NOT NULL CONSTRAINT [DF_Active_Award_Count] DEFAULT ((1)),
  [ValidDate] int NOT NULL CONSTRAINT [DF_Active_Award_ValidDate] DEFAULT ((0)),
  [StrengthenLevel] int NOT NULL CONSTRAINT [DF_Active_Award_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_Active_Award_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_Active_Award_DefendCompose] DEFAULT ((0)),
  [LuckCompose] int NOT NULL CONSTRAINT [DF_Active_Award_LuckCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL CONSTRAINT [DF_Active_Award_AgilityCompose] DEFAULT ((0)),
  [Gold] int NOT NULL CONSTRAINT [DF_Active_Award_Gold] DEFAULT ((0)),
  [Money] int NOT NULL CONSTRAINT [DF_Active_Award_Money] DEFAULT ((0)),
  [Sex] int NOT NULL CONSTRAINT [DF_Active_Award_Sex] DEFAULT ((0)),
  [Mark] int NOT NULL CONSTRAINT [DF_Active_Award_Mark] DEFAULT ((0)),
  CONSTRAINT [PK_Active_Award] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Active_Convert_Item] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ActiveID] int NOT NULL CONSTRAINT [DF_Active_Convert_Item_ActiveID] DEFAULT ((0)),
  [TemplateID] int NOT NULL CONSTRAINT [DF_Active_Convert_Item_TemplateID] DEFAULT ((0)),
  [ItemType] int NOT NULL CONSTRAINT [DF_Active_Convert_Item_ItemType] DEFAULT ((0)),
  [ItemCount] int NOT NULL CONSTRAINT [DF_Active_Convert_Item_ItemCount] DEFAULT ((1)),
  [LimitValue] int NOT NULL CONSTRAINT [DF_Active_Convert_Item_LimitValue] DEFAULT ((-1)),
  [IsBind] bit NOT NULL CONSTRAINT [DF_Active_Convert_Item_IsBind] DEFAULT ((1)),
  [ValidDate] int NOT NULL CONSTRAINT [DF_Active_Convert_Item_ValidDate] DEFAULT ((0)),
  CONSTRAINT [PK_Active_Convert_Item] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 242
CREATE TABLE [dbo].[Activity_System_Item] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ActivityType] int NOT NULL CONSTRAINT [DF_Activity_System_Item_UserID] DEFAULT ((0)),
  [Quality] int NOT NULL CONSTRAINT [DF_Activity_System_Item_Position] DEFAULT ((0)),
  [TemplateID] int NOT NULL CONSTRAINT [DF_Activity_System_Item_TemplateID] DEFAULT ((0)),
  [Count] int NOT NULL CONSTRAINT [DF_Activity_System_Item_Count] DEFAULT ((1)),
  [ValidDate] int NOT NULL CONSTRAINT [DF_Activity_System_Item_ValidDate] DEFAULT ((0)),
  [IsBind] bit NOT NULL CONSTRAINT [DF_Activity_System_Item_IsBinds_1] DEFAULT ((1)),
  [StrengthLevel] int NOT NULL CONSTRAINT [DF_Activity_System_Item_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_Activity_System_Item_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_Activity_System_Item_DefendCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL CONSTRAINT [DF_Activity_System_Item_AgilityCompose] DEFAULT ((0)),
  [LuckCompose] int NOT NULL CONSTRAINT [DF_Activity_System_Item_LuckCompose] DEFAULT ((0)),
  [Probability] int NOT NULL CONSTRAINT [DF_Activity_System_Item_Random] DEFAULT ((10000)),
  CONSTRAINT [PK_Activity_System_Item] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 2
CREATE TABLE [dbo].[AreaConfig] (
  [AreaID] int NOT NULL CONSTRAINT [DF_AreaConfig_AreaID] DEFAULT ((0)),
  [AreaServer] nvarchar(150) NOT NULL CONSTRAINT [DF_AreaConfig_AreaServer] DEFAULT (N''),
  [AreaName] nvarchar(150) NOT NULL CONSTRAINT [DF_AreaConfig_AreaName] DEFAULT (N''),
  [DataSource] nvarchar(150) NOT NULL CONSTRAINT [DF_AreaConfig_DataSource] DEFAULT (N''),
  [Catalog] nvarchar(150) NOT NULL CONSTRAINT [DF_AreaConfig_Catalog] DEFAULT (N''),
  [UserID] nvarchar(150) NOT NULL CONSTRAINT [DF_AreaConfig_UserID] DEFAULT (N''),
  [Password] nvarchar(150) NOT NULL CONSTRAINT [DF_AreaConfig_Password] DEFAULT (N''),
  [RequestLink] nvarchar(150) NULL,
  [ResourceLink] nvarchar(150) NULL,
  [Version] nvarchar(150) NULL
);

-- rows: 1586
CREATE TABLE [dbo].[Ball] (
  [ID] int NOT NULL,
  [Name] nvarchar(200) NULL,
  [Power] float NOT NULL,
  [Radii] int NOT NULL,
  [FlyingPartical] nvarchar(200) NULL,
  [BombPartical] nvarchar(200) NULL,
  [Crater] nvarchar(200) NULL,
  [AttackResponse] int NOT NULL,
  [IsSpin] bit NOT NULL,
  [Mass] int NOT NULL,
  [SpinVA] float NOT NULL,
  [SpinV] int NOT NULL,
  [Amount] int NOT NULL,
  [Wind] int NOT NULL,
  [DragIndex] int NOT NULL,
  [Weight] int NOT NULL,
  [Shake] bit NOT NULL,
  [ShootSound] nvarchar(50) NULL,
  [BombSound] nvarchar(50) NULL,
  [Delay] int NOT NULL,
  [ActionType] int NOT NULL,
  [HasTunnel] bit NOT NULL
);

-- rows: 781
CREATE TABLE [dbo].[BallConfig] (
  [TemplateID] int NOT NULL,
  [Common] int NULL,
  [CommonAddWound] int NULL,
  [CommonMultiBall] int NULL,
  [Special] int NULL
);

-- rows: 60
CREATE TABLE [dbo].[Card_Buff] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [CardID] int NOT NULL CONSTRAINT [DF_Card_Buff_CardID] DEFAULT ((0)),
  [condition] int NOT NULL CONSTRAINT [DF_Card_Buff_condition] DEFAULT ((0)),
  [PropertiesDscripID] int NOT NULL CONSTRAINT [DF_Card_Buff_PropertiesDscripID] DEFAULT ((0)),
  [value] nvarchar(50) NULL,
  [Description] nvarchar(1050) NULL,
  CONSTRAINT [PK_Card_Buff] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 92
CREATE TABLE [dbo].[Card_Groove_Update] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Level] int NOT NULL CONSTRAINT [DF_Card_Groove_Update_Level] DEFAULT ((0)),
  [Type] int NOT NULL CONSTRAINT [DF_Card_Groove_Update_Type] DEFAULT ((0)),
  [Exp] int NOT NULL CONSTRAINT [DF_Card_Groove_Update_Exp] DEFAULT ((0)),
  [Attack] int NOT NULL CONSTRAINT [DF_Card_Groove_Update_Attack] DEFAULT ((0)),
  [Defend] int NOT NULL CONSTRAINT [DF_Card_Groove_Update_Defend] DEFAULT ((0)),
  [Agility] int NOT NULL CONSTRAINT [DF_Card_Groove_Update_Agility] DEFAULT ((0)),
  [Lucky] int NOT NULL CONSTRAINT [DF_Card_Groove_Update_Lucky] DEFAULT ((0)),
  [Damage] int NOT NULL CONSTRAINT [DF_Card_Groove_Update_Damage] DEFAULT ((0)),
  [Guard] int NOT NULL CONSTRAINT [DF_Card_Groove_Update_Guard] DEFAULT ((0)),
  CONSTRAINT [PK_Card_Groove_Update] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 73
CREATE TABLE [dbo].[Card_Group] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [CardID] int NOT NULL,
  [TemplateID] int NOT NULL CONSTRAINT [DF_Card_Group_TemplateID] DEFAULT ((0)),
  CONSTRAINT [PK_Card_Group] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 15
CREATE TABLE [dbo].[Card_Info] (
  [ID] int NOT NULL,
  [SuitID] int NOT NULL,
  [Name] nvarchar(250) NULL,
  [Description] nvarchar(1050) NULL,
  CONSTRAINT [PK_CardInfo] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 250
CREATE TABLE [dbo].[Card_Template_Info] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [CardID] int NOT NULL,
  [CardType] int NOT NULL,
  [probability] int NOT NULL,
  [AttackRate] int NOT NULL,
  [AddAttack] int NOT NULL,
  [DefendRate] int NOT NULL,
  [AddDefend] int NOT NULL,
  [AgilityRate] int NOT NULL,
  [AddAgility] int NOT NULL,
  [LuckyRate] int NOT NULL,
  [AddLucky] int NOT NULL,
  [DamageRate] int NOT NULL,
  [AddDamage] int NOT NULL,
  [GuardRate] int NOT NULL,
  [AddGuard] int NOT NULL,
  CONSTRAINT [PK_Card_Template_Info] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 31
CREATE TABLE [dbo].[CardUpdateCondition] (
  [Level] int NOT NULL,
  [Exp] int NOT NULL,
  [MinExp] int NOT NULL,
  [MaxExp] int NOT NULL,
  [UpdateCardCount] int NOT NULL,
  [ResetCardCount] int NOT NULL,
  [ResetMoney] int NOT NULL,
  CONSTRAINT [PK_CardUpdateCondition] PRIMARY KEY CLUSTERED ([Level])
);

-- rows: 1470
CREATE TABLE [dbo].[CardUpdateInfo] (
  [Id] int NOT NULL,
  [Level] int NOT NULL,
  [Attack] int NOT NULL,
  [Defend] int NOT NULL,
  [Agility] int NOT NULL,
  [Lucky] int NOT NULL,
  [Guard] int NOT NULL,
  [Damage] int NOT NULL,
  CONSTRAINT [PK_CardUpdateInfo] PRIMARY KEY CLUSTERED ([Id], [Level])
);

-- rows: 270
CREATE TABLE [dbo].[ClothGroupTemplateInfo] (
  [ItemID] int IDENTITY(1,1) NOT NULL,
  [ID] int NOT NULL,
  [TemplateID] int NOT NULL,
  [Sex] int NOT NULL,
  [Description] int NOT NULL,
  [Cost] int NOT NULL,
  CONSTRAINT [PK_ClothGroupTemplateInfo] PRIMARY KEY CLUSTERED ([ItemID])
);

-- rows: 23
CREATE TABLE [dbo].[ClothPropertyTemplateInfo] (
  [ID] int NOT NULL,
  [Sex] int NOT NULL,
  [Name] nvarchar(500) NOT NULL,
  [Attack] int NOT NULL,
  [Defend] int NOT NULL,
  [Agility] int NOT NULL,
  [Luck] int NOT NULL,
  [Blood] int NOT NULL,
  [Damage] int NOT NULL,
  [Guard] int NOT NULL,
  [Cost] int NOT NULL,
  CONSTRAINT [PK_ClothPropertyTemplateInfo] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 4
CREATE TABLE [dbo].[Communal_Active] (
  [ActiveID] int NOT NULL CONSTRAINT [DF_Communal_Active_ActiveID] DEFAULT ((1)),
  [BeginTime] datetime NOT NULL CONSTRAINT [DF_Communal_Active_BeginTime] DEFAULT (getdate()),
  [EndTime] datetime NOT NULL CONSTRAINT [DF_Communal_Active_EndTime] DEFAULT (getdate()),
  [LimitGrade] int NOT NULL CONSTRAINT [DF_Communal_Active_LimitGrade] DEFAULT ((0)),
  [DayMaxScore] int NOT NULL CONSTRAINT [DF_Communal_Active_DayMaxScore] DEFAULT ((0)),
  [MinScore] int NOT NULL CONSTRAINT [DF_Communal_Active_MinScore] DEFAULT ((0)),
  [AddPropertyByMoney] nvarchar(50) NULL,
  [AddPropertyByProp] nvarchar(50) NULL,
  [IsReset] bit NOT NULL CONSTRAINT [DF_Communal_Active_IsReset] DEFAULT ((0)),
  [IsSendAward] bit NOT NULL CONSTRAINT [DF_Communal_Active_IsSendAward] DEFAULT ((0))
);

-- rows: 25
CREATE TABLE [dbo].[Communal_Active_Award] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ActiveID] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_ActiveID] DEFAULT ((0)),
  [IsArea] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_IsArea] DEFAULT ((1)),
  [RandID] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_RandID] DEFAULT ((0)),
  [TemplateID] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_TemplateID] DEFAULT ((0)),
  [StrengthenLevel] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_DefendCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_AgilityCompose] DEFAULT ((0)),
  [LuckCompose] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_LuckCompose] DEFAULT ((0)),
  [Count] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_Count] DEFAULT ((1)),
  [IsBind] bit NOT NULL CONSTRAINT [DF_Communal_Active_Award_IsBind] DEFAULT ((1)),
  [IsTime] bit NOT NULL CONSTRAINT [DF_Communal_Active_Award_IsTime] DEFAULT ((1)),
  [ValidDate] int NOT NULL CONSTRAINT [DF_Communal_Active_Award_ValidDate] DEFAULT ((7))
);

-- rows: 6
CREATE TABLE [dbo].[Communal_Active_Exp] (
  [ActiveID] int NOT NULL CONSTRAINT [DF_Communal_Active_Exp_ActiveID] DEFAULT ((0)),
  [Grade] int NOT NULL CONSTRAINT [DF_Communal_Active_Exp_Grade] DEFAULT ((0)),
  [Exp] int NOT NULL CONSTRAINT [DF_Communal_Active_Exp_Exp] DEFAULT ((0)),
  [AddExpPlus] int NOT NULL CONSTRAINT [DF_Communal_Active_Exp_AddExpPlus] DEFAULT ((0)),
  CONSTRAINT [PK_Communal_Active_Exp] PRIMARY KEY CLUSTERED ([Grade])
);

-- rows: 10
CREATE TABLE [dbo].[Consortia_Badge] (
  [BadgeID] int NOT NULL,
  [BadgeName] nvarchar(100) NOT NULL,
  [Cost] int NOT NULL,
  [LimitLevel] int NOT NULL,
  [ValidDate] int NOT NULL,
  CONSTRAINT [PK_Consortia_Badge] PRIMARY KEY CLUSTERED ([BadgeID])
);

-- rows: 40
CREATE TABLE [dbo].[Consortia_BuffTemp] (
  [id] int NOT NULL,
  [name] nvarchar(100) NOT NULL,
  [descript] nvarchar(500) NOT NULL,
  [type] int NOT NULL,
  [level] int NOT NULL,
  [value] int NOT NULL,
  [riches] int NOT NULL,
  [metal] int NOT NULL CONSTRAINT [DF_Consortia_BuffTemp_metal] DEFAULT ((0)),
  [pic] int NOT NULL,
  [group] int NOT NULL,
  CONSTRAINT [PK_Consortia_BuffTemp] PRIMARY KEY CLUSTERED ([id])
);

-- rows: 10
CREATE TABLE [dbo].[Consortia_Level] (
  [Level] int NOT NULL,
  [Riches] int NOT NULL,
  [Deduct] int NOT NULL,
  [NeedGold] int NOT NULL,
  [NeedItem] int NOT NULL,
  [Reward] int NOT NULL,
  [Count] int NOT NULL,
  [StoreRiches] int NOT NULL CONSTRAINT [DF_Consortia_Level_StoreRiches] DEFAULT ((100)),
  [SmithRiches] int NOT NULL CONSTRAINT [DF_Consortia_Level_SmithRiches] DEFAULT ((100)),
  [ShopRiches] int NOT NULL CONSTRAINT [DF_Consortia_Level_ShopRiches] DEFAULT ((100)),
  [BufferRiches] int NOT NULL CONSTRAINT [DF_Consortia_Level_BufferRiches] DEFAULT ((0)),
  [KickMax] int NOT NULL CONSTRAINT [DF_Consortia_Level_KickCount] DEFAULT ((10)),
  [BossCount] int NOT NULL CONSTRAINT [DF_Consortia_Level_BossCount] DEFAULT ((0)),
  CONSTRAINT [PK_Consortia_Level] PRIMARY KEY CLUSTERED ([Level])
);

-- rows: 4
CREATE TABLE [dbo].[Consortia_TaskAward] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Lv] int NOT NULL,
  [ItemID] int NOT NULL,
  [Count] int NOT NULL,
  [ValidDate] int NOT NULL,
  [StrengthenLevel] int NOT NULL,
  [AttackCompose] int NOT NULL,
  [DefendCompose] int NOT NULL,
  [LuckCompose] int NOT NULL,
  [AgilityCompose] int NOT NULL,
  [IsBind] bit NOT NULL,
  CONSTRAINT [PK_Consortia_TaskAward] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 70
CREATE TABLE [dbo].[Consortia_TaskConfig] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Content] nvarchar(max) NOT NULL,
  [Type] int NOT NULL,
  [Target] int NOT NULL,
  [TargetCount] int NOT NULL,
  [Para1] int NOT NULL,
  [Para2] int NOT NULL,
  [Level] int NOT NULL,
  CONSTRAINT [PK_Consortia_Task_Condition] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 20
CREATE TABLE [dbo].[Daily_Award] (
  [ID] int NOT NULL,
  [Type] int NOT NULL,
  [TemplateID] int NOT NULL,
  [Count] int NOT NULL,
  [ValidDate] int NOT NULL,
  [IsBinds] bit NOT NULL,
  [Sex] int NOT NULL CONSTRAINT [DF_Daily_Award_Sex] DEFAULT ((0)),
  [Remark] nvarchar(200) NULL,
  [CountRemark] nvarchar(100) NULL,
  [GetWay] int NOT NULL CONSTRAINT [DF_Daily_Award_GetWay] DEFAULT ((0)),
  [AwardDays] int NOT NULL,
  CONSTRAINT [PK_Daily_Award] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 93
CREATE TABLE [dbo].[DailyLeagueAwardItems] (
  [ID] int NOT NULL,
  [Class] int NOT NULL,
  [TemplateID] int NOT NULL,
  [StrengthLevel] int NULL CONSTRAINT [DF_DailyLeagueAwardItems_StrengthLevel] DEFAULT ((0)),
  [AttackCompose] int NULL CONSTRAINT [DF_DailyLeagueAwardItems_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NULL CONSTRAINT [DF_DailyLeagueAwardItems_DefendCompose] DEFAULT ((0)),
  [LuckCompose] int NULL CONSTRAINT [DF_DailyLeagueAwardItems_LuckCompose] DEFAULT ((0)),
  [AgilityCompose] int NULL CONSTRAINT [DF_DailyLeagueAwardItems_AgilityCompose] DEFAULT ((0)),
  [IsBind] bit NULL CONSTRAINT [DF_DailyLeagueAwardItems_IsBind] DEFAULT ((1)),
  [ValidDate] int NULL CONSTRAINT [DF_DailyLeagueAwardItems_ValidDate] DEFAULT ((0)),
  [Count] int NOT NULL
);

-- rows: 30
CREATE TABLE [dbo].[DailyLeagueAwardList] (
  [Class] int NOT NULL,
  [Grade] int NOT NULL,
  [Score] int NOT NULL,
  [Rank] int NULL CONSTRAINT [DF_DailyLeagueAwardList_Rank] DEFAULT ((0))
);

-- rows: 14
CREATE TABLE [dbo].[DailyLeagueLevel] (
  [Level] int NOT NULL,
  [Name] nvarchar(500) NOT NULL,
  [Score] int NOT NULL
);

-- rows: 112
CREATE TABLE [dbo].[Drop_Condiction] (
  [DropID] int NOT NULL,
  [CondictionType] int NOT NULL,
  [Para1] nvarchar(500) NOT NULL,
  [Para2] nvarchar(500) NOT NULL,
  [Name] nvarchar(150) NOT NULL CONSTRAINT [DF_Drop_Condiction_Name_1] DEFAULT (N''),
  [Detail] nvarchar(1500) NULL,
  CONSTRAINT [PK_Drop_Condiction] PRIMARY KEY CLUSTERED ([DropID])
);

-- rows: 3023
CREATE TABLE [dbo].[Drop_Item] (
  [Id] int IDENTITY(1,1) NOT NULL,
  [DropId] int NOT NULL CONSTRAINT [DF_Drop_Item_DropId] DEFAULT ((0)),
  [ItemId] int NOT NULL CONSTRAINT [DF_Drop_Item_ItemId] DEFAULT ((0)),
  [ValueDate] int NOT NULL CONSTRAINT [DF_Drop_Item_ValueDate] DEFAULT ((0)),
  [IsBind] bit NOT NULL,
  [Random] int NOT NULL CONSTRAINT [DF_Drop_Item_Random] DEFAULT ((0)),
  [BeginData] int NOT NULL CONSTRAINT [DF_Drop_Item_BeginData] DEFAULT ((0)),
  [EndData] int NOT NULL CONSTRAINT [DF_Drop_Item_EndData] DEFAULT ((0)),
  [IsTips] bit NOT NULL CONSTRAINT [DF_Drop_Item_IsTips] DEFAULT ((0)),
  [IsLogs] bit NOT NULL CONSTRAINT [DF_Drop_Item_IsLogs] DEFAULT ((0)),
  CONSTRAINT [PK_Drop_Item] PRIMARY KEY CLUSTERED ([Id])
);

-- rows: 1
CREATE TABLE [dbo].[Edictum_List] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Title] nvarchar(200) NOT NULL,
  [BeginDate] datetime NOT NULL CONSTRAINT [DF_Edictum_List_BeginDate] DEFAULT (getdate()),
  [BeginTime] datetime NOT NULL CONSTRAINT [DF_Edictum_List_BeginTime] DEFAULT (getdate()),
  [EndDate] datetime NOT NULL CONSTRAINT [DF_Edictum_List_EndDate] DEFAULT (getdate()),
  [EndTime] datetime NOT NULL CONSTRAINT [DF_Edictum_List_EndTime] DEFAULT (getdate()),
  [Text] nvarchar(max) NOT NULL,
  [IsExist] bit NOT NULL,
  CONSTRAINT [PK_Edictum_List] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 432
CREATE TABLE [dbo].[Event_Award_Item] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ActivityType] int NOT NULL CONSTRAINT [DF_Event_Award_Item_ActivityType] DEFAULT ((0)),
  [TemplateID] int NOT NULL CONSTRAINT [DF_Event_Award_Item_TemplateID] DEFAULT ((0)),
  [Count] int NOT NULL CONSTRAINT [DF_Event_Award_Item_Count] DEFAULT ((1)),
  [ValidDate] int NOT NULL CONSTRAINT [DF_Event_Award_Item_ValidDate] DEFAULT ((0)),
  [IsBinds] bit NOT NULL CONSTRAINT [DF_Event_Award_Item_IsBinds_1] DEFAULT ((1)),
  [StrengthenLevel] int NOT NULL CONSTRAINT [DF_Event_Award_Item_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_Event_Award_Item_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_Event_Award_Item_DefendCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL CONSTRAINT [DF_Event_Award_Item_AgilityCompose] DEFAULT ((0)),
  [LuckCompose] int NOT NULL CONSTRAINT [DF_Event_Award_Item_LuckCompose] DEFAULT ((0)),
  [Random] int NOT NULL CONSTRAINT [DF_Event_Award_Item_Random] DEFAULT ((10000)),
  [IsSelect] bit NOT NULL CONSTRAINT [DF_Event_Award_Item_IsSelect] DEFAULT ((0)),
  CONSTRAINT [PK_Event_Award_Item] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 141
CREATE TABLE [dbo].[Event_Live] (
  [EventID] int NULL,
  [Description] nvarchar(1000) NULL,
  [CondictionType] int NULL,
  [Condiction_Para1] int NULL,
  [Condiction_Para2] int NULL,
  [StartDate] datetime NULL,
  [EndDate] datetime NULL
);

-- rows: 386
CREATE TABLE [dbo].[Event_LiveGoods] (
  [EventID] int NOT NULL,
  [TemplateID] int NOT NULL,
  [ValidDate] int NULL CONSTRAINT [DF_Event_LiveGoods_ValidDate] DEFAULT ((7)),
  [Count] int NULL CONSTRAINT [DF_Event_LiveGoods_Count] DEFAULT ((1)),
  [StrengthenLevel] int NULL CONSTRAINT [DF_Event_LiveGoods_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NULL CONSTRAINT [DF_Event_LiveGoods_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NULL CONSTRAINT [DF_Event_LiveGoods_DefendCompose] DEFAULT ((0)),
  [AgilityCompose] int NULL CONSTRAINT [DF_Event_LiveGoods_AgilityCompose] DEFAULT ((0)),
  [LuckCompose] int NULL CONSTRAINT [DF_Event_LiveGoods_LuckCompose] DEFAULT ((0)),
  [IsBind] bit NULL CONSTRAINT [DF_Event_LiveGoods_IsBind] DEFAULT ((1))
);

-- rows: 75
CREATE TABLE [dbo].[Event_Reward_Goods] (
  [ActivityType] int NOT NULL,
  [SubActivityType] int NOT NULL,
  [TemplateId] int NOT NULL,
  [StrengthLevel] int NULL CONSTRAINT [DF_Event_Reward_Goods_StrengthLevel] DEFAULT ((0)),
  [AttackCompose] int NULL CONSTRAINT [DF_Event_Reward_Goods_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NULL CONSTRAINT [DF_Event_Reward_Goods_DefendCompose] DEFAULT ((0)),
  [LuckCompose] int NULL CONSTRAINT [DF_Event_Reward_Goods_LuckCompose] DEFAULT ((0)),
  [AgilityCompose] int NULL CONSTRAINT [DF_Event_Reward_Goods_AgilityCompose] DEFAULT ((0)),
  [IsBind] bit NULL CONSTRAINT [DF_Event_Reward_Goods_IsBind] DEFAULT ((1)),
  [ValidDate] int NULL CONSTRAINT [DF_Event_Reward_Goods_ValidDate] DEFAULT ((0)),
  [Count] int NULL CONSTRAINT [DF_Event_Reward_Goods_Count] DEFAULT ((1))
);

-- rows: 15
CREATE TABLE [dbo].[Event_Reward_Info] (
  [ActivityType] int NOT NULL,
  [SubActivityType] int NOT NULL,
  [Condition] int NOT NULL
);

-- rows: 70
CREATE TABLE [dbo].[ExerciseInfo] (
  [Grage] int NOT NULL,
  [GP] int NOT NULL CONSTRAINT [DF_ExerciseInfo_GP] DEFAULT ((0)),
  [ExerciseA] int NOT NULL CONSTRAINT [DF_ExerciseInfo_ExerciseA] DEFAULT ((0)),
  [ExerciseAG] int NOT NULL CONSTRAINT [DF_ExerciseInfo_ExerciseAG] DEFAULT ((0)),
  [ExerciseD] int NOT NULL CONSTRAINT [DF_ExerciseInfo_ExerciseD] DEFAULT ((0)),
  [ExerciseH] int NOT NULL CONSTRAINT [DF_ExerciseInfo_ExerciseH] DEFAULT ((0)),
  [ExerciseL] int NOT NULL CONSTRAINT [DF_ExerciseInfo_ExerciseL] DEFAULT ((0)),
  CONSTRAINT [PK_ExerciseInfo] PRIMARY KEY CLUSTERED ([Grage])
);

-- rows: 16
CREATE TABLE [dbo].[Fair_Battle_Reward_Temp] (
  [Prestige] int NOT NULL,
  [Level] int NOT NULL,
  [Name] nvarchar(50) NULL,
  [PrestigeForWin] int NOT NULL,
  [PrestigeForLose] int NOT NULL,
  [Title] nvarchar(50) NULL
);

-- rows: 4
CREATE TABLE [dbo].[Fight_Rate] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ServerID] int NOT NULL CONSTRAINT [DF_Fight_Change_Rate_ServerID] DEFAULT ((0)),
  [Rate] int NOT NULL CONSTRAINT [DF_Fight_Change_Rate_Rate] DEFAULT ((0)),
  [BeginDay] datetime NOT NULL,
  [EndDay] datetime NOT NULL,
  [BeginTime] datetime NOT NULL,
  [EndTime] datetime NOT NULL,
  [BoyTemplateID] int NOT NULL,
  [GirlTemplateID] int NOT NULL,
  [SelfCue] nvarchar(200) NULL,
  [EnemyCue] nvarchar(200) NULL,
  [Name] nvarchar(50) NULL,
  CONSTRAINT [PK_Fight_Change_Rate] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[Fight_Record] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [PlayBegin] datetime NOT NULL,
  [PlayEnd] datetime NOT NULL,
  [ChangeTeam] int NOT NULL,
  [TeamA] nvarchar(50) NULL,
  [TeamB] nvarchar(50) NULL,
  [MapID] int NOT NULL,
  [RoomType] int NOT NULL,
  [FightName] nvarchar(50) NULL,
  [WinTeam] int NOT NULL,
  CONSTRAINT [PK_Fight_Record] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 30
CREATE TABLE [dbo].[Fight_Spirit_Templatelist] (
  [ID] int NOT NULL,
  [FightSpiritID] int NOT NULL CONSTRAINT [DF_Fight_Spirit_Templatelist_FightSpiritID] DEFAULT ((0)),
  [FightSpiritIcon] nvarchar(50) NOT NULL CONSTRAINT [DF_Fight_Spirit_Templatelist_FightSpiritIcon] DEFAULT (''),
  [Level] int NOT NULL CONSTRAINT [DF_Fight_Spirit_Templatelist_Level] DEFAULT ((0)),
  [Exp] int NOT NULL CONSTRAINT [DF_Fight_Spirit_Templatelist_Exp] DEFAULT ((0)),
  [Attack] int NOT NULL CONSTRAINT [DF_Fight_Spirit_Templatelist_Attack] DEFAULT ((0)),
  [Defence] int NOT NULL CONSTRAINT [DF_Fight_Spirit_Templatelist_Defence] DEFAULT ((0)),
  [Agility] int NOT NULL CONSTRAINT [DF_Fight_Spirit_Templatelist_Agility] DEFAULT ((0)),
  [Lucky] int NOT NULL CONSTRAINT [DF_Fight_Spirit_Templatelist_Lucky] DEFAULT ((0)),
  [Blood] int NOT NULL CONSTRAINT [DF_Fight_Spirit_Templatelist_Blood] DEFAULT ((0)),
  CONSTRAINT [PK_Fight_Spirit_Templatelist] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 96
CREATE TABLE [dbo].[Fusion] (
  [FusionID] int NOT NULL,
  [Item1] int NOT NULL CONSTRAINT [DF_Fusion_Item1] DEFAULT ((0)),
  [Item2] int NOT NULL CONSTRAINT [DF_Fusion_Item2] DEFAULT ((0)),
  [Item3] int NOT NULL CONSTRAINT [DF_Fusion_Item3] DEFAULT ((0)),
  [Item4] int NOT NULL CONSTRAINT [DF_Fusion_Item4] DEFAULT ((0)),
  [Item5] int NOT NULL CONSTRAINT [DF_Fusion_Item5] DEFAULT ((0)),
  [Item6] int NOT NULL CONSTRAINT [DF_Fusion_Item6] DEFAULT ((0)),
  [Item7] int NOT NULL CONSTRAINT [DF_Fusion_Item7] DEFAULT ((0)),
  [Item8] int NOT NULL CONSTRAINT [DF_Fusion_Item8] DEFAULT ((0)),
  [Item9] int NOT NULL CONSTRAINT [DF_Fusion_Item9] DEFAULT ((0)),
  [Item10] int NOT NULL CONSTRAINT [DF_Fusion_Item10] DEFAULT ((0)),
  [Reward1] int NOT NULL CONSTRAINT [DF_Fusion_Reward1] DEFAULT ((0)),
  [Random1] int NOT NULL CONSTRAINT [DF_Fusion_Random1] DEFAULT ((0)),
  [Reward2] int NOT NULL CONSTRAINT [DF_Fusion_Reward2] DEFAULT ((0)),
  [Random2] int NOT NULL CONSTRAINT [DF_Fusion_Random2] DEFAULT ((0)),
  [Reward3] int NOT NULL CONSTRAINT [DF_Fusion_Reward3] DEFAULT ((0)),
  [Random3] int NOT NULL CONSTRAINT [DF_Fusion_Random3] DEFAULT ((0)),
  [Leave] int NOT NULL CONSTRAINT [DF_Fusion_Leave] DEFAULT ((0)),
  CONSTRAINT [PK_Fusion] PRIMARY KEY CLUSTERED ([FusionID])
);

-- rows: 454
CREATE TABLE [dbo].[Game_Map] (
  [ID] int NOT NULL,
  [Name] nvarchar(50) NULL,
  [PosX] nvarchar(200) NULL,
  [PosX1] nvarchar(200) NULL,
  [Description] nvarchar(2000) NULL,
  [ForegroundWidth] int NOT NULL,
  [ForegroundHeight] int NOT NULL,
  [BackroundWidht] int NOT NULL,
  [BackroundHeight] int NOT NULL,
  [DeadWidth] int NOT NULL,
  [DeadHeight] int NOT NULL,
  [Weight] int NOT NULL,
  [DragIndex] int NOT NULL,
  [ForePic] nvarchar(200) NULL,
  [BackPic] nvarchar(200) NULL,
  [DeadPic] nvarchar(200) NULL,
  [Pic] nvarchar(200) NULL,
  [Remark] nvarchar(50) NULL,
  [BackMusic] nvarchar(200) NULL,
  [Type] int NOT NULL
);

-- rows: 277
CREATE TABLE [dbo].[GoldEquipTemplateLoad] (
  [ID] int NOT NULL,
  [OldTemplateId] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_OldTemplateId] DEFAULT ((0)),
  [NewTemplateId] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_NewTemplateId] DEFAULT ((0)),
  [CategoryID] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_CategoryID] DEFAULT ((0)),
  [Strengthen] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_Strengthen] DEFAULT ((13)),
  [Attack] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_Attack] DEFAULT ((-1)),
  [Defence] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_Defence] DEFAULT ((-1)),
  [Agility] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_Agility] DEFAULT ((-1)),
  [Luck] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_Luck] DEFAULT ((-1)),
  [Damage] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_Damage] DEFAULT ((-1)),
  [Guard] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_Guard] DEFAULT ((-1)),
  [Boold] int NOT NULL CONSTRAINT [DF_GoldEquipTemplateLoad_Boold] DEFAULT ((0)),
  [BlessID] int NOT NULL,
  [Pic] nvarchar(50) NULL,
  CONSTRAINT [PK_GoldEquipTemplateLoad_1] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 13
CREATE TABLE [dbo].[HotSpringRoom] (
  [roomNumber] int NOT NULL,
  [roomID] int NOT NULL,
  [roomName] nvarchar(100) NOT NULL,
  [roomPassword] nvarchar(100) NULL,
  [effectiveTime] int NOT NULL CONSTRAINT [DF_HotSpringRoom_effectiveTime] DEFAULT ((0)),
  [curCount] int NOT NULL CONSTRAINT [DF_HotSpringRoom_curCount] DEFAULT ((0)),
  [playerID] int NOT NULL CONSTRAINT [DF_HotSpringRoom_playerID] DEFAULT ((0)),
  [playerName] nvarchar(500) NOT NULL CONSTRAINT [DF_HotSpringRoom_playerName] DEFAULT (N'unknown'),
  [startTime] datetime NULL,
  [endTime] datetime NULL,
  [roomIntroduction] nvarchar(max) NULL,
  [roomType] int NOT NULL CONSTRAINT [DF_HotSpringRoom_roomType] DEFAULT ((0)),
  [maxCount] int NOT NULL CONSTRAINT [DF_HotSpringRoom_maxCount] DEFAULT ((10)),
  CONSTRAINT [PK_HotSpringRoom] PRIMARY KEY CLUSTERED ([roomID])
);

-- rows: 326
CREATE TABLE [dbo].[Item_Fusion] (
  [FusionID] int IDENTITY(1,1) NOT NULL,
  [Item1] int NOT NULL CONSTRAINT [DF_Item_Fusion_Item1] DEFAULT ((0)),
  [Item2] int NOT NULL CONSTRAINT [DF_Item_Fusion_Item2] DEFAULT ((0)),
  [Item3] int NOT NULL CONSTRAINT [DF_Item_Fusion_Item3] DEFAULT ((0)),
  [Item4] int NOT NULL CONSTRAINT [DF_Item_Fusion_Item4] DEFAULT ((0)),
  [Formula] int NOT NULL CONSTRAINT [DF_Item_Fusion_Formula] DEFAULT ((0)),
  [Reward] int NOT NULL CONSTRAINT [DF_Item_Fusion_Reward] DEFAULT ((0)),
  CONSTRAINT [PK_Item_Fusion] PRIMARY KEY CLUSTERED ([FusionID])
);

-- rows: 0
CREATE TABLE [dbo].[Item_Record] (
  [Id] bigint IDENTITY(1,1) NOT NULL,
  [AgentsID] int NOT NULL,
  [ServerID] int NOT NULL,
  [Timer] datetime NOT NULL,
  [UserID] int NOT NULL,
  [UserName] nvarchar(50) NOT NULL,
  [Operation] int NOT NULL,
  [ItemName] nvarchar(50) NOT NULL,
  [ItemID] int NOT NULL,
  [BeginProperty] nvarchar(200) NOT NULL,
  [EndProperty] nvarchar(200) NOT NULL,
  [Result] int NOT NULL
);

-- rows: 0
CREATE TABLE [dbo].[Item_Refinery] (
  [RefineryID] int NOT NULL,
  [Equip1] int NULL,
  [Equip2] int NULL,
  [Equip3] int NULL,
  [Item1] int NULL,
  [Item2] int NULL,
  [Item3] int NULL,
  [Item1Count] int NULL,
  [Item2Count] int NULL,
  [Item3Count] int NULL,
  [Material1] int NULL,
  [Operate1] int NULL,
  [Reward1] int NULL,
  [Material2] int NULL,
  [Operate2] int NULL,
  [Reward2] int NULL,
  [Material3] int NULL,
  [Operate3] int NULL,
  [Reward3] int NULL,
  [Material4] int NULL,
  [Operate4] int NULL,
  [Reward4] int NULL,
  CONSTRAINT [PK_Item_Refinery] PRIMARY KEY CLUSTERED ([RefineryID])
);

-- rows: 15
CREATE TABLE [dbo].[Item_Refinery_Strengthen] (
  [StrengthenLevel] int NULL,
  [Rock] int NULL
);

-- rows: 15
CREATE TABLE [dbo].[Item_Strengthen] (
  [StrengthenLevel] int NOT NULL,
  [Rock] int NOT NULL,
  [Random] int NOT NULL,
  [Rock1] int NOT NULL,
  [Rock2] int NOT NULL,
  [Rock3] int NOT NULL,
  [StoneLevelMin] int NOT NULL,
  CONSTRAINT [PK_Item_Strengthen] PRIMARY KEY CLUSTERED ([StrengthenLevel])
);

-- rows: 1634
CREATE TABLE [dbo].[Item_Strengthen_Goods] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Level] int NOT NULL,
  [CurrentEquip] int NOT NULL,
  [GainEquip] int NOT NULL,
  [OrginEquip] int NOT NULL CONSTRAINT [DF_Item_Strengthen_Goods_OrginEquip] DEFAULT ((7015)),
  CONSTRAINT [PK_Item_Strengthen_Goods] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 0
CREATE TABLE [dbo].[ItemRecordType] (
  [RecordID] int NOT NULL,
  [Name] nvarchar(250) NULL,
  [Description] nvarchar(1500) NULL,
  CONSTRAINT [PK_ItemRecordType] PRIMARY KEY CLUSTERED ([RecordID])
);

-- rows: 230
CREATE TABLE [dbo].[Items_Fusion_List] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [TemplateID] int NOT NULL,
  [Show] int NOT NULL,
  [Real] int NOT NULL,
  CONSTRAINT [PK_Items_Fusion_List] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 26
CREATE TABLE [dbo].[League_Info] (
  [ID] int NOT NULL,
  [RankName] nvarchar(50) NOT NULL,
  [NeedPoint] int NOT NULL,
  CONSTRAINT [PK_League_Info] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 60
CREATE TABLE [dbo].[LevelInfo] (
  [Grade] int NOT NULL,
  [GP] int NOT NULL,
  [Blood] int NOT NULL,
  CONSTRAINT [PK_Level] PRIMARY KEY CLUSTERED ([Grade])
);

-- rows: 29
CREATE TABLE [dbo].[LoadUserBox] (
  [ID] int NOT NULL,
  [Type] int NOT NULL CONSTRAINT [DF_LoadUserBox_Type] DEFAULT ((0)),
  [Level] int NOT NULL CONSTRAINT [DF_LoadUserBox_Level] DEFAULT ((1)),
  [Condition] int NOT NULL CONSTRAINT [DF_LoadUserBox_Condition] DEFAULT ((0)),
  [TemplateID] int NOT NULL CONSTRAINT [DF_LoadUserBox_TemplateID] DEFAULT ((0)),
  CONSTRAINT [PK_LoadUserBox] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 23
CREATE TABLE [dbo].[Login_Award_Item_Template] (
  [ID] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_ID] DEFAULT ((0)),
  [Type] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_Count] DEFAULT ((0)),
  [RewardItemID] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_RewardItemID] DEFAULT ((0)),
  [IsSelect] bit NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_IsSelect] DEFAULT ((0)),
  [IsBind] bit NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_IsBind] DEFAULT ((0)),
  [RewardItemValid] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_RewardItemValid] DEFAULT ((0)),
  [RewardItemCount] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_RewardItemCount] DEFAULT ((0)),
  [StrengthenLevel] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_DefendCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_AgilityCompose] DEFAULT ((0)),
  [LuckCompose] int NOT NULL CONSTRAINT [DF_Login_Award_Item_Template_LuckCompose] DEFAULT ((0))
);

-- rows: 34
CREATE TABLE [dbo].[LuckyStart_Topten_Award] (
  [ID] int NOT NULL,
  [Type] int NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_Type] DEFAULT ((0)),
  [TemplateID] int NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_TemplateID] DEFAULT ((0)),
  [Validate] int NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_Validate] DEFAULT ((0)),
  [Count] int NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_Count] DEFAULT ((1)),
  [StrengthenLevel] int NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_DefendCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_AgilityCompose] DEFAULT ((0)),
  [LuckCompose] int NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_LuckCompose] DEFAULT ((0)),
  [IsBind] bit NOT NULL CONSTRAINT [DF_LuckyStart_Topten_Award_IsBind] DEFAULT ((0)),
  CONSTRAINT [PK_LuckyStart_Topten_Award] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 20
CREATE TABLE [dbo].[Map_Server] (
  [ServerID] int NOT NULL,
  [OpenMap] nvarchar(max) NOT NULL,
  [IsSpecial] int NOT NULL
);

-- rows: 7
CREATE TABLE [dbo].[Map_Week] (
  [WeekID] int NOT NULL,
  [OpenMap] nvarchar(1000) NULL,
  CONSTRAINT [PK_Map_Week] PRIMARY KEY CLUSTERED ([WeekID])
);

-- rows: 170
CREATE TABLE [dbo].[Mission_Info] (
  [Id] int NOT NULL,
  [Name] nvarchar(100) NOT NULL,
  [TotalCount] int NOT NULL,
  [TotalTurn] int NOT NULL,
  [Script] nvarchar(100) NULL,
  [Success] nvarchar(100) NULL,
  [Failure] nvarchar(100) NULL,
  [Description] nvarchar(1000) NULL,
  [IncrementDelay] int NULL,
  [Delay] int NULL,
  [Title] nvarchar(50) NULL,
  [Param1] int NULL,
  [Param2] int NULL,
  [TakeCard] int NULL,
  [TryAgain] bit NOT NULL CONSTRAINT [DF_Mission_Info_TryAgain] DEFAULT ((0)),
  [TryAgainCost] int NOT NULL CONSTRAINT [DF_Mission_Info_TryAgainCost] DEFAULT ((0)),
  CONSTRAINT [PK_Mission_Info] PRIMARY KEY CLUSTERED ([Id])
);

-- rows: 128
CREATE TABLE [dbo].[Mission_Info_Backup] (
  [Id] int NOT NULL,
  [Name] nvarchar(100) NOT NULL,
  [TotalCount] int NOT NULL,
  [TotalTurn] int NOT NULL,
  [Script] nvarchar(100) NULL,
  [Success] nvarchar(100) NULL,
  [Failure] nvarchar(100) NULL,
  [Description] nvarchar(1000) NULL,
  [IncrementDelay] int NULL,
  [Delay] int NULL,
  [Title] nvarchar(50) NULL,
  [Param1] int NULL,
  [Param2] int NULL,
  [TakeCard] int NULL,
  [TryAgain] bit NOT NULL,
  [TryAgainCost] int NOT NULL
);

-- rows: 325
CREATE TABLE [dbo].[New_Title] (
  [ID] int NOT NULL CONSTRAINT [DF_New_Title_ID] DEFAULT ((0)),
  [Order] int NOT NULL,
  [Show] int NOT NULL CONSTRAINT [DF_New_Title_Show] DEFAULT ((0)),
  [Name] nvarchar(150) NOT NULL CONSTRAINT [DF_New_Title_Name] DEFAULT (N''),
  [Pic] int NOT NULL CONSTRAINT [DF_New_Title_Pic] DEFAULT ((0)),
  [Att] int NOT NULL CONSTRAINT [DF_New_Title_Att] DEFAULT ((0)),
  [Def] int NOT NULL CONSTRAINT [DF_New_Title_Def] DEFAULT ((0)),
  [Agi] int NOT NULL CONSTRAINT [DF_New_Title_Agi] DEFAULT ((0)),
  [Luck] int NOT NULL CONSTRAINT [DF_New_Title_Luck] DEFAULT ((0)),
  [Desc] nvarchar(200) NOT NULL,
  CONSTRAINT [PK_New_Title] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 1005
CREATE TABLE [dbo].[NPC_Info] (
  [ID] int NOT NULL,
  [Name] nvarchar(50) NOT NULL,
  [Level] int NOT NULL,
  [Camp] int NOT NULL,
  [Type] int NOT NULL,
  [X] int NOT NULL,
  [Y] int NOT NULL,
  [Width] int NOT NULL,
  [Height] int NOT NULL,
  [Blood] int NOT NULL,
  [MoveMin] int NOT NULL,
  [MoveMax] int NOT NULL,
  [BaseDamage] int NOT NULL,
  [BaseGuard] int NOT NULL,
  [Defence] int NOT NULL,
  [Agility] int NOT NULL,
  [Lucky] int NOT NULL,
  [Attack] int NOT NULL,
  [ModelID] nvarchar(1000) NOT NULL,
  [ResourcesPath] nvarchar(1000) NOT NULL,
  [DropRate] nvarchar(50) NULL,
  [Experience] int NOT NULL,
  [Delay] int NOT NULL,
  [Immunity] int NOT NULL,
  [Alert] int NULL,
  [Range] int NULL,
  [Preserve] int NULL,
  [Script] nvarchar(250) NULL,
  [FireX] int NOT NULL,
  [FireY] int NOT NULL,
  [DropId] int NOT NULL,
  [CurrentBallId] int NOT NULL,
  [speed] int NOT NULL,
  [MagicAttack] int NOT NULL CONSTRAINT [DF_NPC_Info_MagicAttack] DEFAULT ((0)),
  [MagicDefence] int NOT NULL CONSTRAINT [DF_NPC_Info_MagicDefence] DEFAULT ((0))
);

-- rows: 27
CREATE TABLE [dbo].[Old_Player_Award_Info] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [RewardItemID] int NOT NULL,
  [RewardItemValid] int NOT NULL,
  [RewardItemCount] int NOT NULL,
  [StrengthenLevel] int NOT NULL,
  [AttackCompose] int NOT NULL,
  [DefendCompose] int NOT NULL,
  [AgilityCompose] int NOT NULL,
  [LuckCompose] int NOT NULL,
  [IsBind] bit NOT NULL,
  CONSTRAINT [PK_Old_Player_Award_Info] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 56
CREATE TABLE [dbo].[Pet_Config] (
  [Name] nvarchar(50) NOT NULL,
  [Value] nvarchar(2000) NULL,
  CONSTRAINT [PK_Pet_Config_1] PRIMARY KEY CLUSTERED ([Name])
);

-- rows: 20
CREATE TABLE [dbo].[Pet_Exp_Item_Price] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Count] int NOT NULL,
  [Money] int NOT NULL,
  [ItemCount] int NOT NULL
);

-- rows: 70
CREATE TABLE [dbo].[Pet_Fight_Property] (
  [ID] int NOT NULL,
  [Exp] int NOT NULL CONSTRAINT [DF_Pet_Fight_Property_Exp] DEFAULT ((0)),
  [Attack] int NOT NULL CONSTRAINT [DF_Pet_Fight_Property_Attack] DEFAULT ((0)),
  [Agility] int NOT NULL CONSTRAINT [DF_Pet_Fight_Property_Agility] DEFAULT ((0)),
  [Defence] int NOT NULL CONSTRAINT [DF_Pet_Fight_Property_Defence] DEFAULT ((0)),
  [Lucky] int NOT NULL CONSTRAINT [DF_Pet_Fight_Property_Lucky] DEFAULT ((0)),
  [Blood] int NOT NULL CONSTRAINT [DF_Pet_Fight_Property_Blood] DEFAULT ((0)),
  CONSTRAINT [PK_Pet_Fight_Property] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 70
CREATE TABLE [dbo].[Pet_Level] (
  [Level] int NOT NULL,
  [GP] int NOT NULL,
  CONSTRAINT [PK_PetLevel] PRIMARY KEY CLUSTERED ([Level])
);

-- rows: 50
CREATE TABLE [dbo].[Pet_Moe_Property] (
  [Level] int NOT NULL CONSTRAINT [DF_Pet_Moe_Property_Level] DEFAULT ((0)),
  [Attack] int NOT NULL CONSTRAINT [DF_Pet_Moe_Property_Attack] DEFAULT ((0)),
  [Lucky] int NOT NULL CONSTRAINT [DF_Pet_Moe_Property_Lucky] DEFAULT ((0)),
  [Agility] int NOT NULL CONSTRAINT [DF_Pet_Moe_Property_Agility] DEFAULT ((0)),
  [Blood] int NOT NULL CONSTRAINT [DF_Pet_Moe_Property_Blood] DEFAULT ((0)),
  [Defence] int NOT NULL CONSTRAINT [DF_Pet_Moe_Property_Defence] DEFAULT ((0)),
  [Guard] int NOT NULL CONSTRAINT [DF_Pet_Moe_Property_Guard] DEFAULT ((0)),
  [Exp] int NOT NULL CONSTRAINT [DF_Pet_Moe_Property_Exp] DEFAULT ((0)),
  CONSTRAINT [PK_Pet_Moe_Property] PRIMARY KEY CLUSTERED ([Level])
);

-- rows: 2084
CREATE TABLE [dbo].[Pet_Skill_Element_Info] (
  [ID] int NOT NULL,
  [Name] nvarchar(200) NULL,
  [EffectPic] nvarchar(100) NULL,
  [Description] nvarchar(1000) NULL,
  [Pic] int NOT NULL,
  CONSTRAINT [PK_PetSkillElementInfo] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 1653
CREATE TABLE [dbo].[Pet_Skill_Info] (
  [ID] int NOT NULL,
  [Name] nvarchar(250) NULL CONSTRAINT [DF_Pet_Skill_Info_Name] DEFAULT (''),
  [Damage] int NOT NULL CONSTRAINT [DF_Pet_Skill_Info_Effect1] DEFAULT ((0)),
  [DamageCrit] int NOT NULL CONSTRAINT [DF_Pet_Skill_Info_DamageCrit] DEFAULT ((0)),
  [ElementIDs] nvarchar(50) NULL CONSTRAINT [DF_Pet_Skill_Info_ElementIDs] DEFAULT (''),
  [Description] nvarchar(1050) NULL CONSTRAINT [DF_Pet_Skill_Info_Description] DEFAULT (''),
  [BallType] int NOT NULL,
  [NewBallID] int NOT NULL,
  [CostMP] int NOT NULL,
  [Pic] int NOT NULL,
  [Action] nvarchar(50) NULL CONSTRAINT [DF_Pet_Skill_Info_Action] DEFAULT (''),
  [EffectPic] nvarchar(50) NULL CONSTRAINT [DF_Pet_Skill_Info_EffectPic] DEFAULT (''),
  [Delay] int NOT NULL,
  [ColdDown] int NOT NULL,
  [GameType] int NOT NULL,
  [Probability] int NOT NULL,
  CONSTRAINT [PK_Pet_Skill_Info] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 380
CREATE TABLE [dbo].[Pet_Skill_Template_Info] (
  [PetTemplateID] int NOT NULL,
  [KindID] int NOT NULL,
  [GetType] int NOT NULL,
  [SkillID] int NOT NULL,
  [SkillBookID] int NOT NULL,
  [MinLevel] int NOT NULL,
  [DeleteSkillIDs] nvarchar(100) NULL,
  CONSTRAINT [PK_Pet_Skill_Template_Info_1] PRIMARY KEY CLUSTERED ([SkillID])
);

-- rows: 67
CREATE TABLE [dbo].[Pet_Star_Exp] (
  [Exp] int NOT NULL CONSTRAINT [DF_Pet_Star_Exp_Exp] DEFAULT ((0)),
  [OldID] int NOT NULL CONSTRAINT [DF_Pet_Star_Exp_OldID] DEFAULT ((0)),
  [NewID] int NOT NULL CONSTRAINT [DF_Pet_Star_Exp_NewID] DEFAULT ((0)),
  CONSTRAINT [PK_Pet_Star_Exp] PRIMARY KEY CLUSTERED ([OldID])
);

-- rows: 199
CREATE TABLE [dbo].[Pet_Template_Info] (
  [TemplateID] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_TemplateID] DEFAULT ((0)),
  [Name] nvarchar(250) NOT NULL,
  [KindID] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_KindID] DEFAULT ((0)),
  [Description] nvarchar(1000) NOT NULL,
  [Pic] nvarchar(100) NOT NULL,
  [RareLevel] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_RareLevel] DEFAULT ((0)),
  [MP] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_MP] DEFAULT ((100)),
  [StarLevel] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_StarLevel] DEFAULT ((1)),
  [GameAssetUrl] nvarchar(100) NOT NULL,
  [EvolutionID] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_EvolutionID] DEFAULT ((1)),
  [HighAgility] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighAgility] DEFAULT ((0)),
  [HighAgilityGrow] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighAgilityGrow] DEFAULT ((0)),
  [HighAttack] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighAttack] DEFAULT ((0)),
  [HighAttackGrow] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighAttackGrow] DEFAULT ((0)),
  [HighBlood] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighBlood] DEFAULT ((0)),
  [HighBloodGrow] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighBloodGrow] DEFAULT ((0)),
  [HighDamage] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighDamage] DEFAULT ((0)),
  [HighDamageGrow] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighDamageGrow] DEFAULT ((0)),
  [HighDefence] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighDefence] DEFAULT ((0)),
  [HighDefenceGrow] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighDefenceGrow] DEFAULT ((0)),
  [HighGuard] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighGuard] DEFAULT ((0)),
  [HighGuardGrow] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighGuardGrow] DEFAULT ((0)),
  [HighLuck] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighLuck] DEFAULT ((0)),
  [HighLuckGrow] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_HighLuckGrow] DEFAULT ((0)),
  [WashGetCount] int NOT NULL CONSTRAINT [DF_Pet_Template_Info_WashGetCount] DEFAULT ((0)),
  CONSTRAINT [PK_Pet_Template_Info] PRIMARY KEY CLUSTERED ([TemplateID])
);

-- rows: 33
CREATE TABLE [dbo].[Pve_Info] (
  [ID] int NOT NULL,
  [Name] nvarchar(100) NULL,
  [Type] int NULL,
  [LevelLimits] int NULL,
  [SimpleTemplateIds] nvarchar(1024) NULL,
  [NormalTemplateIds] nvarchar(1024) NULL,
  [HardTemplateIds] nvarchar(1024) NULL,
  [TerrorTemplateIds] nvarchar(1024) NULL,
  [Pic] nvarchar(100) NULL,
  [Description] nvarchar(max) NULL,
  [SimpleGameScript] nvarchar(100) NULL,
  [NormalGameScript] nvarchar(100) NULL,
  [HardGameScript] nvarchar(100) NULL,
  [TerrorGameScript] nvarchar(100) NULL,
  [Ordering] int NOT NULL CONSTRAINT [DF_Pve_Info_Ordering] DEFAULT ((0)),
  [AdviceTips] nvarchar(100) NULL,
  [BossFightNeedMoney] nvarchar(50) NULL,
  [LastFloor] nvarchar(50) NULL,
  CONSTRAINT [PK_PveInfo] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 1
CREATE TABLE [dbo].[QQtips_Messages] (
  [ID] int NOT NULL CONSTRAINT [DF_QQtips_Messages_ID] DEFAULT ((0)),
  [title] nvarchar(250) NULL,
  [content] nvarchar(2500) NULL,
  [maxLevel] int NOT NULL CONSTRAINT [DF_QQtips_Messages_maxLevel] DEFAULT ((65)),
  [minLevel] int NOT NULL CONSTRAINT [DF_QQtips_Messages_minLevel] DEFAULT ((5)),
  [outInType] int NOT NULL CONSTRAINT [DF_QQtips_Messages_outInType] DEFAULT ((1)),
  [moduleType] int NOT NULL CONSTRAINT [DF_QQtips_Messages_moduleType] DEFAULT ((0)),
  [inItemID] int NOT NULL CONSTRAINT [DF_QQtips_Messages_inItemID] DEFAULT ((0)),
  [url] nvarchar(250) NOT NULL CONSTRAINT [DF_QQtips_Messages_url] DEFAULT (N'http://gunny.zing.vn'),
  CONSTRAINT [PK_QQtips_Messages] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 728
CREATE TABLE [dbo].[Quest] (
  [ID] int NOT NULL,
  [QuestID] int NOT NULL,
  [Title] nvarchar(300) NULL,
  [Detail] nvarchar(1500) NULL,
  [Objective] nvarchar(50) NULL,
  [NeedMinLevel] int NOT NULL,
  [NeedMaxLevel] int NOT NULL,
  [PreQuestID] nvarchar(40) NOT NULL,
  [NextQuestID] nvarchar(40) NOT NULL,
  [IsOther] int NOT NULL,
  [CanRepeat] bit NOT NULL,
  [RepeatInterval] int NOT NULL,
  [RepeatMax] int NOT NULL,
  [RewardGP] int NOT NULL,
  [RewardGold] int NOT NULL,
  [RewardGiftToken] int NOT NULL,
  [RewardOffer] int NOT NULL,
  [RewardRiches] int NOT NULL,
  [RewardBuffID] int NOT NULL,
  [RewardBuffDate] int NOT NULL,
  [RewardMoney] int NOT NULL,
  [RewardMedal] int NOT NULL CONSTRAINT [DF_Quest_RewardMedal] DEFAULT ((0)),
  [Rands] numeric(18,2) NOT NULL,
  [StartDate] datetime NOT NULL,
  [EndDate] datetime NOT NULL,
  [RandDouble] int NOT NULL,
  [TimeMode] bit NOT NULL,
  [MapID] int NOT NULL CONSTRAINT [DF_Quest_MapID] DEFAULT ((0)),
  [AutoEquip] bit NOT NULL CONSTRAINT [DF_Quest_AutoEquip] DEFAULT ((0)),
  [Rank] nvarchar(500) NULL,
  [StarLev] int NOT NULL CONSTRAINT [DF_Quest_StarLev] DEFAULT ((0)),
  [NotMustCount] int NOT NULL CONSTRAINT [DF_Quest_NotMustCount] DEFAULT ((0))
);

-- rows: 853
CREATE TABLE [dbo].[Quest_Condiction] (
  [QuestID] int NOT NULL,
  [CondictionID] int NOT NULL,
  [CondictionType] int NOT NULL,
  [CondictionTitle] nvarchar(200) NOT NULL,
  [Para1] int NOT NULL,
  [Para2] int NOT NULL,
  [isOpitional] bit NOT NULL CONSTRAINT [DF_Quest_Condiction_isOpitional] DEFAULT ((0))
);

-- rows: 1006
CREATE TABLE [dbo].[Quest_Goods] (
  [QuestID] int NOT NULL,
  [RewardItemID] int NOT NULL,
  [IsSelect] bit NOT NULL,
  [RewardItemValid] int NOT NULL,
  [RewardItemCount] int NOT NULL,
  [StrengthenLevel] int NULL CONSTRAINT [DF_Quest_Goods_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NULL CONSTRAINT [DF_Quest_Goods_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NULL CONSTRAINT [DF_Quest_Goods_DefendCompose] DEFAULT ((0)),
  [AgilityCompose] int NULL CONSTRAINT [DF_Quest_Goods_AgilityCompose] DEFAULT ((0)),
  [LuckCompose] int NULL CONSTRAINT [DF_Quest_Goods_LuckCompose] DEFAULT ((0)),
  [IsCount] bit NULL CONSTRAINT [DF_Quest_Goods_IsCount] DEFAULT ((1)),
  [IsBind] bit NULL CONSTRAINT [DF_Quest_Goods_IsBind] DEFAULT ((1))
);

-- rows: 0
CREATE TABLE [dbo].[Quest_Rate] (
  [BindMoneyRate] nvarchar(50) NOT NULL,
  [ExpRate] nvarchar(50) NOT NULL,
  [GoldRate] nvarchar(50) NOT NULL,
  [ExploitRate] nvarchar(50) NOT NULL,
  [CanOneKeyFinishTime] int NOT NULL
);

-- rows: 19
CREATE TABLE [dbo].[Rate] (
  [ServerID] int NOT NULL,
  [Rate] decimal(6,2) NOT NULL,
  [BeginDay] datetime NOT NULL,
  [EndDay] datetime NOT NULL,
  [BeginTime] datetime NOT NULL,
  [EndTime] datetime NOT NULL,
  [Type] int NOT NULL CONSTRAINT [DF_Experience_Rate_Type] DEFAULT ((0))
);

-- rows: 456
CREATE TABLE [dbo].[Rune_Template] (
  [TemplateID] int NOT NULL,
  [NextTemplateID] int NOT NULL CONSTRAINT [DF_Rune_Template_NextTemplateID] DEFAULT ((0)),
  [Name] nvarchar(50) NULL,
  [BaseLevel] int NOT NULL CONSTRAINT [DF_Rune_Template_BaseLevel] DEFAULT ((1)),
  [MaxLevel] int NOT NULL CONSTRAINT [DF_Rune_Template_MaxLevel] DEFAULT ((2)),
  [Type1] int NOT NULL CONSTRAINT [DF_Rune_Template_Type1] DEFAULT ((1)),
  [Attribute1] nvarchar(50) NOT NULL CONSTRAINT [DF_Rune_Template_Attribute1] DEFAULT ('1|2'),
  [Turn1] int NOT NULL CONSTRAINT [DF_Rune_Template_Turn1] DEFAULT ((0)),
  [Rate1] int NOT NULL CONSTRAINT [DF_Rune_Template_Rate1] DEFAULT ((0)),
  [Type2] int NOT NULL CONSTRAINT [DF_Rune_Template_Type2] DEFAULT ((0)),
  [Attribute2] nvarchar(50) NOT NULL CONSTRAINT [DF_Rune_Template_Attribute2] DEFAULT ('1|2'),
  [Turn2] int NOT NULL CONSTRAINT [DF_Rune_Template_Turn2] DEFAULT ((0)),
  [Rate2] int NOT NULL CONSTRAINT [DF_Rune_Template_Rate2] DEFAULT ((0)),
  [Type3] int NOT NULL CONSTRAINT [DF_Rune_Template_Type3] DEFAULT ((0)),
  [Attribute3] nvarchar(50) NOT NULL CONSTRAINT [DF_Rune_Template_Attribute3] DEFAULT ('1|2'),
  [Turn3] int NOT NULL CONSTRAINT [DF_Rune_Template_Turn3] DEFAULT ((0)),
  [Rate3] int NOT NULL CONSTRAINT [DF_Rune_Template_Rate3] DEFAULT ((0)),
  CONSTRAINT [PK_Rune_Template] PRIMARY KEY CLUSTERED ([TemplateID])
);

-- rows: 5
CREATE TABLE [dbo].[Search_Goods_Temp] (
  [StarID] int NOT NULL,
  [NeedMoney] int NOT NULL CONSTRAINT [DF_Search_Goods_Temp_NeedMoney] DEFAULT ((0)),
  [DestinationReward] int NOT NULL CONSTRAINT [DF_Search_Goods_Temp_DestinationReward] DEFAULT ((0)),
  [VIPLevel] int NOT NULL CONSTRAINT [DF_Search_Goods_Temp_VIPLevel] DEFAULT ((-1)),
  [ExtractNumber] nvarchar(50) NOT NULL CONSTRAINT [DF_Search_Goods_Temp_ExtractNumber] DEFAULT (N'10,2,3,1'),
  CONSTRAINT [PK_Search_Goods_Temp] PRIMARY KEY CLUSTERED ([StarID])
);

-- rows: 489
CREATE TABLE [dbo].[Server_Config] (
  [ID] int NOT NULL,
  [Name] nvarchar(50) NOT NULL,
  [Value] nvarchar(2000) NOT NULL,
  CONSTRAINT [PK_Server_Config] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 70
CREATE TABLE [dbo].[Sets_Build_Temp] (
  [Level] int NOT NULL,
  [SetsType] int NOT NULL,
  [UseItemTemplate] int NOT NULL,
  [Exp] int NOT NULL,
  [DefenceGrow] int NOT NULL,
  [BloodGrow] int NOT NULL,
  [LuckGrow] int NOT NULL,
  [AgilityGrow] int NOT NULL,
  [DamageGrow] int NOT NULL,
  [GuardGrow] int NOT NULL,
  CONSTRAINT [PK_Sets_Build_Temp] PRIMARY KEY CLUSTERED ([Level])
);

-- rows: 5025
CREATE TABLE [dbo].[Shop] (
  [ID] float NULL,
  [ShopID] float NULL,
  [GroupID] float NULL,
  [TemplateID] float NULL,
  [BuyType] float NULL,
  [IsContinue] bit NOT NULL,
  [IsBind] float NULL,
  [IsVouch] float NULL CONSTRAINT [DF_Shop_IsVouch] DEFAULT ((0)),
  [Label] float NULL,
  [Beat] float NULL,
  [AUnit] float NULL,
  [APrice1] float NULL,
  [AValue1] float NULL,
  [APrice2] float NULL,
  [AValue2] float NULL,
  [APrice3] float NULL,
  [AValue3] float NULL,
  [BUnit] float NULL,
  [BPrice1] float NULL,
  [BValue1] float NULL,
  [BPrice2] float NULL,
  [BValue2] float NULL,
  [BPrice3] float NULL,
  [BValue3] float NULL,
  [CUnit] float NULL,
  [CPrice1] float NULL,
  [CValue1] float NULL,
  [CPrice2] float NULL,
  [CValue2] float NULL,
  [CPrice3] float NULL,
  [Sort] float NULL CONSTRAINT [DF_Shop_Sort] DEFAULT ((0)),
  [CValue3] float NULL,
  [IsCheap] bit NOT NULL,
  [LimitCount] float NULL,
  [StartDate] datetime NULL,
  [EndDate] datetime NULL,
  [LimitGrade] int NULL CONSTRAINT [DF_Shop_LimitGrade] DEFAULT ((0)),
  [CanBuy] bit NOT NULL CONSTRAINT [DF_Shop_CanBuy] DEFAULT ((0))
);

-- rows: 7640
CREATE TABLE [dbo].[Shop_Goods] (
  [TemplateID] int NOT NULL,
  [CanRecycle] int NOT NULL,
  [Name] nvarchar(50) NULL,
  [Remark] nvarchar(200) NULL,
  [CategoryID] int NOT NULL,
  [Description] nvarchar(max) NULL,
  [Attack] int NOT NULL,
  [Defence] int NOT NULL,
  [Agility] int NOT NULL,
  [Luck] int NOT NULL,
  [Level] int NOT NULL,
  [Quality] int NOT NULL,
  [Pic] nvarchar(200) NULL,
  [MaxCount] int NOT NULL,
  [NeedSex] int NOT NULL,
  [NeedLevel] int NOT NULL,
  [CanStrengthen] bit NOT NULL,
  [CanCompose] bit NOT NULL,
  [CanDrop] bit NOT NULL,
  [CanEquip] bit NOT NULL,
  [CanUse] bit NOT NULL,
  [CanDelete] bit NOT NULL,
  [Script] nvarchar(200) NULL,
  [Data] nvarchar(1000) NULL,
  [Colors] nvarchar(1000) NULL,
  [Property1] int NOT NULL,
  [Property2] int NOT NULL,
  [Property3] int NOT NULL,
  [Property4] int NOT NULL,
  [Property5] int NOT NULL,
  [Property6] int NOT NULL,
  [Property7] int NOT NULL,
  [Property8] int NOT NULL,
  [Valid] int NOT NULL CONSTRAINT [DF_Shop_Goods_Valid] DEFAULT ((0)),
  [Count] int NOT NULL CONSTRAINT [DF_Shop_Goods_Count] DEFAULT ((1)),
  [AddTime] datetime NULL,
  [BindType] int NOT NULL,
  [FusionType] int NOT NULL,
  [FusionRate] int NOT NULL,
  [FusionNeedRate] int NOT NULL,
  [Hole] nvarchar(50) NULL,
  [RefineryLevel] int NOT NULL,
  [ReclaimValue] int NOT NULL,
  [ReclaimType] int NOT NULL,
  [FloorPrice] int NOT NULL CONSTRAINT [DF_Shop_Goods_FloorPrice] DEFAULT ((0)),
  [SuitId] int NOT NULL CONSTRAINT [DF_Shop_Goods_SuitId] DEFAULT ((0)),
  [CanTransfer] int NOT NULL CONSTRAINT [DF_Shop_Goods_CanTransfer] DEFAULT ((1)),
  [Price] int NULL,
  [FineSuitType] int NOT NULL CONSTRAINT [DF_Shop_Goods_FineSuitType] DEFAULT ((0)),
  CONSTRAINT [PK_Shop_Goods] PRIMARY KEY CLUSTERED ([TemplateID])
);

-- rows: 4043
CREATE TABLE [dbo].[Shop_Goods_Box] (
  [ID] int NOT NULL,
  [TemplateId] int NOT NULL,
  [IsSelect] bit NOT NULL,
  [IsBind] bit NOT NULL,
  [ItemValid] int NOT NULL,
  [ItemCount] int NOT NULL,
  [StrengthenLevel] int NOT NULL CONSTRAINT [DF_Shop_Goods_Box_StrengthenLevel] DEFAULT ((0)),
  [AttackCompose] int NOT NULL CONSTRAINT [DF_Shop_Goods_Box_AttackCompose] DEFAULT ((0)),
  [DefendCompose] int NOT NULL CONSTRAINT [DF_Shop_Goods_Box_DefendCompose] DEFAULT ((0)),
  [AgilityCompose] int NOT NULL CONSTRAINT [DF_Shop_Goods_Box_AgilityCompose] DEFAULT ((0)),
  [LuckCompose] int NOT NULL CONSTRAINT [DF_Shop_Goods_Box_LuckCompose] DEFAULT ((0)),
  [Random] int NOT NULL,
  [IsTips] int NOT NULL CONSTRAINT [DF_Shop_Goods_Box_IsTips] DEFAULT ((0)),
  [IsLogs] bit NOT NULL CONSTRAINT [DF_Shop_Goods_Box_IsLogs] DEFAULT ((0))
);

-- rows: 34
CREATE TABLE [dbo].[Shop_Goods_Categorys] (
  [ID] int NOT NULL,
  [Name] nvarchar(50) NULL,
  [Place] int NULL CONSTRAINT [DF_Shop_Goods_Categorys_Place] DEFAULT ((0)),
  [Remark] nvarchar(200) NULL,
  CONSTRAINT [PK_TABLE1] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 5093
CREATE TABLE [dbo].[ShopGoodsShowList] (
  [Type] int NOT NULL,
  [ShopId] int NOT NULL,
  [TempID] int IDENTITY(1,1) NOT NULL
);

-- rows: 4090
CREATE TABLE [dbo].[ShopGoodsShowList_BK] (
  [Type] int NOT NULL,
  [ShopId] int NOT NULL,
  [TempID] int IDENTITY(1,1) NOT NULL
);

-- rows: 16
CREATE TABLE [dbo].[StrengThenExp] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [Level] int NOT NULL CONSTRAINT [DF_StrengThenExp_Lv] DEFAULT ((0)),
  [Exp] int NOT NULL CONSTRAINT [DF_StrengThenExp_Exp] DEFAULT ((0)),
  [NecklaceStrengthExp] int NOT NULL CONSTRAINT [DF_StrengThenExp_NecklaceStrengthExp] DEFAULT ((0)),
  [NecklaceStrengthPlus] int NOT NULL CONSTRAINT [DF_StrengThenExp_NecklaceStrengthPlus] DEFAULT ((0)),
  CONSTRAINT [PK_StrengThenExp] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 11
CREATE TABLE [dbo].[Sub_Active_Condition] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ActiveID] int NOT NULL CONSTRAINT [DF_Sub_Active_Condition_ActiveID] DEFAULT ((0)),
  [SubID] int NOT NULL CONSTRAINT [DF_Sub_Active_Condition_SubID] DEFAULT ((0)),
  [ConditionID] int NOT NULL CONSTRAINT [DF_Sub_Active_Condition_ConditionID] DEFAULT ((0)),
  [Type] int NOT NULL CONSTRAINT [DF_Sub_Active_Condition_Type] DEFAULT ((-1)),
  [Value] nvarchar(150) NOT NULL CONSTRAINT [DF_Sub_Active_Condition_Value] DEFAULT (N'1-50-2-50-3-50-4-50-5-1500-6-100-7-100-8-Bao tay venus+5-9-不限-10-+1-11-0-12-28'),
  [AwardType] int NOT NULL CONSTRAINT [DF_Sub_Active_Condition_AwardType] DEFAULT ((1)),
  [AwardValue] nvarchar(250) NULL,
  [IsValid] bit NOT NULL CONSTRAINT [DF_Sub_Active_Condition_IsValid] DEFAULT ((0)),
  CONSTRAINT [PK_Sub_Active_Condition] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 1
CREATE TABLE [dbo].[Sub_Active_List] (
  [ID] int IDENTITY(1,1) NOT NULL,
  [ActiveID] int NOT NULL CONSTRAINT [DF_Sub_Active_List_ActiveID] DEFAULT ((0)),
  [SubID] int NOT NULL CONSTRAINT [DF_Sub_Active_List_SubID] DEFAULT ((0)),
  [IsOpen] bit NOT NULL CONSTRAINT [DF_Sub_Active_List_IsOpen] DEFAULT ((0)),
  [StartDate] datetime NOT NULL CONSTRAINT [DF_Sub_Active_List_StartDate] DEFAULT (getdate()),
  [StartTime] datetime NOT NULL CONSTRAINT [DF_Sub_Active_List_StartTime] DEFAULT (getdate()),
  [EndDate] datetime NOT NULL CONSTRAINT [DF_Sub_Active_List_EndDate] DEFAULT (getdate()),
  [EndTime] datetime NOT NULL CONSTRAINT [DF_Sub_Active_List_EndTime] DEFAULT (getdate()),
  [IsContinued] bit NOT NULL CONSTRAINT [DF_Sub_Active_List_IsContinued] DEFAULT ((1)),
  [ActiveInfo] nvarchar(500) NULL,
  CONSTRAINT [PK_Sub_Active_List] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 111
CREATE TABLE [dbo].[Suit_TemplateID] (
  [ID] int NULL,
  [ContainEquip] nvarchar(500) NULL,
  [PartName] nvarchar(500) NULL
);

-- rows: 46
CREATE TABLE [dbo].[SuitTemplateInfo] (
  [SuitId] int NOT NULL,
  [SuitName] nvarchar(500) NOT NULL,
  [EqipCount1] int NULL,
  [SkillDescribe1] nvarchar(500) NULL,
  [Skill1] nvarchar(200) NULL,
  [EqipCount2] int NULL,
  [SkillDescribe2] nvarchar(500) NULL,
  [Skill2] nvarchar(200) NULL,
  [EqipCount3] int NULL,
  [SkillDescribe3] nvarchar(500) NULL,
  [Skill3] nvarchar(200) NULL,
  [EqipCount4] int NULL,
  [SkillDescribe4] nvarchar(500) NULL,
  [Skill4] nvarchar(200) NULL,
  [EqipCount5] int NULL,
  [SkillDescribe5] nvarchar(500) NULL,
  [Skill5] nvarchar(200) NULL
);

-- rows: 34
CREATE TABLE [dbo].[TempTable] (
  [id] int NULL,
  [value] nvarchar(50) NULL
);

-- rows: 20
CREATE TABLE [dbo].[Totem_Honor_Template] (
  [ID] int NOT NULL,
  [Type] int NOT NULL CONSTRAINT [DF_Totem_Honor_Template_Type] DEFAULT ((1)),
  [NeedMoney] int NOT NULL CONSTRAINT [DF_Totem_Honor_Template_NeedMoney] DEFAULT ((0)),
  [AddHonor] int NOT NULL CONSTRAINT [DF_Totem_Honor_Template_AddHonor] DEFAULT ((200)),
  CONSTRAINT [PK_Totem_Honor_Template] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 350
CREATE TABLE [dbo].[Totem_Info] (
  [ID] int NOT NULL,
  [ConsumeExp] int NOT NULL CONSTRAINT [DF_Totem_Info_ConsumeExp] DEFAULT ((0)),
  [ConsumeHonor] int NOT NULL CONSTRAINT [DF_Totem_Info_ConsumeHonor] DEFAULT ((0)),
  [AddAttack] int NOT NULL CONSTRAINT [DF_Totem_Info_AddAttack] DEFAULT ((0)),
  [AddDefence] int NOT NULL CONSTRAINT [DF_Totem_Info_AddDefence] DEFAULT ((0)),
  [AddAgility] int NOT NULL CONSTRAINT [DF_Totem_Info_AddAgility] DEFAULT ((0)),
  [AddLuck] int NOT NULL CONSTRAINT [DF_Totem_Info_AddLuck] DEFAULT ((0)),
  [AddBlood] int NOT NULL CONSTRAINT [DF_Totem_Info_AddBlood] DEFAULT ((0)),
  [AddDamage] int NOT NULL CONSTRAINT [DF_Totem_Info_AddDamage] DEFAULT ((0)),
  [AddGuard] int NOT NULL CONSTRAINT [DF_Totem_Info_AddGuard] DEFAULT ((0)),
  [Random] int NOT NULL CONSTRAINT [DF_Totem_Info_Random] DEFAULT ((0)),
  [Page] int NOT NULL CONSTRAINT [DF_Totem_Info_Page] DEFAULT ((0)),
  [Layers] int NOT NULL CONSTRAINT [DF_Totem_Info_Layers] DEFAULT ((0)),
  [Location] int NOT NULL CONSTRAINT [DF_Totem_Info_Location] DEFAULT ((0)),
  [Point] int NOT NULL CONSTRAINT [DF_Totem_Info_Point] DEFAULT ((0)),
  [DiscountMoney] int NOT NULL CONSTRAINT [DF_Totem_Info_DiscountMoney] DEFAULT ((0)),
  CONSTRAINT [PK_Totem_Info] PRIMARY KEY CLUSTERED ([ID])
);

-- rows: 29
CREATE TABLE [dbo].[User_Box] (
  [ID] int NOT NULL,
  [Type] int NOT NULL,
  [Level] int NOT NULL,
  [Condition] int NOT NULL,
  [TemplateID] int NOT NULL,
  CONSTRAINT [PK_User_Box] PRIMARY KEY CLUSTERED ([ID])
);

