// AUTO-GENERATED by scripts/extract-codes.ts from vendor/DDTank41 (C# project Bussiness). DO NOT EDIT.
// Regenerate: pnpm --filter @ddt/protocol extract-codes
/* eslint-disable */

/**
 * Bussiness.Protocol.eEventPacket — Bussiness/Protocol/eEventPacket.cs:8
 */
export const eEventPacket = {
  RANKING_LIGHTRIDDLE: 1,
  UPDATE_RANKING_LIGHTRIDDLE: 2,
  SEND_LIGHTRIDDLE_AWARD: 3,
  LUCKSTAR_REWARD_RECORD: 4,
  HALLOWEEN_RANK_RECORD: 5,
} as const;
export type eEventPacket = (typeof eEventPacket)[keyof typeof eEventPacket];

