// AUTO-GENERATED by scripts/extract-codes.ts from vendor/DDTank41 (C# project Game.Server). DO NOT EDIT.
// Regenerate: pnpm --filter @ddt/protocol extract-codes
/* eslint-disable */

/**
 * eChatServerPacket — Game.Server/ChatServer/eChatServerPacket.cs
 * Duplicate values (aliases): KITOFF_USER = GET_LIGHTRIDDLE_INFO (2); LOGIN = LIGHTRIDDLE_INFO (1); RANKING_LIGHTRIDDLE = LIGHTRIDDLE_INFO (1); SEND_LIGHTRIDDLE_AWARD = ALLOW_USER_LOGIN (3); UPDATE_RANKING_LIGHTRIDDLE = GET_LIGHTRIDDLE_INFO (2); USER_OFFLINE = LUCKSTAR_REWARD_RECORD (4)
 */
export const eChatServerPacket = {
  ALLOW_USER_LOGIN: 3,
  B_BUGLE: 72,
  BATTLE_GOUND_OPEN_CLOSE: 88,
  CONSORTIA_ALLY_ADD: 147,
  CONSORTIA_BOSS_AWARD: 185,
  CONSORTIA_BOSS_CLOSE: 187,
  CONSORTIA_BOSS_CREATE_BOSS: 183,
  CONSORTIA_BOSS_DIE: 188,
  CONSORTIA_BOSS_EXTEND_AVAILABLE: 182,
  CONSORTIA_BOSS_INFO: 180,
  CONSORTIA_BOSS_RELOAD: 184,
  CONSORTIA_BOSS_UPDATE_BLOOD: 186,
  CONSORTIA_BOSS_UPDATE_RANK: 181,
  CONSORTIA_CREATE: 130,
  CONSORTIA_CHAT: 155,
  CONSORTIA_DELETE: 131,
  CONSORTIA_FIGHT: 158,
  CONSORTIA_OFFER: 156,
  CONSORTIA_RESPONSE: 128,
  CONSORTIA_RICHES: 157,
  CONSORTIA_UPGRADE: 159,
  CHARGE_MONEY: 9,
  CHAT_PERSONAL: 37,
  DISPATCHES: 123,
  EVENT_RANKING: 90,
  FIGHTFOOT_BALL_TIME: 89,
  FRIEND_RESPONSE: 166,
  FRIEND_STATE: 165,
  GET_LIGHTRIDDLE_INFO: 2,
  IM_CMD: 160,
  IP_PORT: 240,
  KIT_OFF_PLAYER: 242,
  KITOFF_USER: 2,
  LEAGUE_OPEN_CLOSE: 87,
  LIGHTRIDDLE_INFO: 1,
  LOGIN: 1,
  LUCKSTAR_REWARD_RECORD: 4,
  MACRO_DROP: 178,
  MAIL_RESPONSE: 117,
  MARRY_ROOM_DISPOSE: 241,
  MARRY_ROOM_INFO_TO_PLAYER: 14,
  MESSAGE: 118,
  PING: 12,
  RANKING_LIGHTRIDDLE: 1,
  RATE: 177,
  RSAKey: 0,
  SCENE_CHAT: 19,
  SEND_LIGHTRIDDLE_AWARD: 3,
  SHUTDOWN: 15,
  SYS_CMD: 11,
  SYS_MESS: 38,
  SYS_NOTICE: 10,
  UPDATE_ASS: 7,
  UPDATE_CONFIG_STATE: 8,
  UPDATE_PLAYER_MARRIED_STATE: 13,
  UPDATE_RANKING_LIGHTRIDDLE: 2,
  USER_OFFLINE: 4,
  USER_ONLINE: 5,
  USER_STATE: 6,
  WORLD_BOSS_FIGHTOVER: 82,
  WORLD_BOSS_RANK: 81,
  WORLD_BOSS_ROOMCLOSE: 83,
  WORLD_BOSS_START: 80,
  WORLD_BOSS_UPDATE_BLOOD: 79,
  WORLD_BOSS_UPDATEBLOOD: 84,
  WORLD_BOSS_VIEW_RANK: 86,
  WORLD_EVENT: 91,
  WORLDBOSS_PRIVATE_INFO: 85,
} as const;
export type eChatServerPacket = (typeof eChatServerPacket)[keyof typeof eChatServerPacket];

/**
 * Game.Server.HotSpringRooms.HotSpringCmdType — Game.Server/HotSpringRooms/HotSpringCmdType.cs:3
 */
export const HotSpringCmdType = {
  CONTINU_BY_MONEY: 11,
  CONTINU_BY_MONEY_SUCCESS: 12,
  HOTSPRING_ROOM_ADMIN_REMOVE_PLAYER: 9,
  HOTSPRING_ROOM_EDIT: 6,
  HOTSPRING_ROOM_INVITE: 4,
  HOTSPRING_ROOM_PLAYER_CONTINUE: 10,
  HOTSPRING_ROOM_RENEWAL_FEE: 3,
  HOTSPRING_ROOM_TIME_UPDATE: 7,
  TARGET_POINT: 1,
} as const;
export type HotSpringCmdType = (typeof HotSpringCmdType)[keyof typeof HotSpringCmdType];

/**
 * Game.Server.Packets.BaglockedPackageType — Game.Server/Packets/BaglockedPackageType.cs:3
 */
export const BaglockedPackageType = {
  CHECK_PHONE_BINDING: 5,
  DELETE_PWD_BY_PHONE: 4,
  DELETE_QUESTION: 3,
  GET_BACK_BY_PHONE: 1,
  GET_BACK_BY_QUESTION: 2,
} as const;
export type BaglockedPackageType = (typeof BaglockedPackageType)[keyof typeof BaglockedPackageType];

/**
 * Game.Server.Packets.ChargePackageType — Game.Server/Packets/ChargePackageType.cs:3
 */
export const ChargePackageType = {
  Handle_For_Divorce: 2,
  Handle_For_Shop: 4,
  Pay_For_Auction: 7,
  Pay_For_Auction_Email: 6,
  Request_For_Auction: 5,
  Request_For_Divorce: 1,
  Request_For_Shop: 3,
} as const;
export type ChargePackageType = (typeof ChargePackageType)[keyof typeof ChargePackageType];

/**
 * Game.Server.Packets.ChickActivationType — Game.Server/Packets/ChickActivationType.cs:3
 * Duplicate values (aliases): CHICKACTIVATION_UPDATE = CHICKACTIVATION (2); CHICKACTIVATION_OPENKEY = CHICKACTIVATION_LOGIN (1); CHICKACTIVATION_GETAWARD = CHICKACTIVATION (2)
 */
export const ChickActivationType = {
  CHICKACTIVATION: 2,
  CHICKACTIVATION_LOGIN: 1,
  CHICKACTIVATION_UPDATE: 2,
  CHICKACTIVATION_OPENKEY: 1,
  CHICKACTIVATION_GETAWARD: 2,
  CHICKACTIVATION_QUERY: 3,
} as const;
export type ChickActivationType = (typeof ChickActivationType)[keyof typeof ChickActivationType];

/**
 * Game.Server.Packets.ConsBatPackageType — Game.Server/Packets/ConsBatPackageType.cs:3
 */
export const ConsBatPackageType = {
  START_OR_CLOSE: 1,
  ENTER_SELF_INFO: 2,
  ADD_PLAYER: 3,
  PLAYER_MOVE: 4,
  DELETE_PLAYER: 5,
  CHALLENGE: 6,
  PLAYER_STATUS: 7,
  SPLIT_MERGE: 8,
  UPDATE_SCENE_INFO: 9,
  UPDATE_SCORE: 16,
  CONSUME: 17,
  BROADCAST: 19,
  CONFIRM_ENTER: 21,
} as const;
export type ConsBatPackageType = (typeof ConsBatPackageType)[keyof typeof ConsBatPackageType];

/**
 * ConsortiaPackageType — Game.Server/Packets/ConsortiaPackageType.cs
 */
export const ConsortiaPackageType = {
  CONSORTIA_TRYIN: 0,
  CONSORTIA_CREATE: 1,
  CONSORTIA_DISBAND: 2,
  CONSORTIA_RENEGADE: 3,
  CONSORTIA_TRYIN_PASS: 4,
  CONSORTIA_TRYIN_DEL: 5,
  CONSORTIA_RICHES_OFFER: 6,
  CONSORTIA_APPLY_STATE: 7,
  CONSORTIA_DUTY_DELETE: 9,
  CONSORTIA_DUTY_UPDATE: 10,
  CONSORTIA_INVITE: 11,
  CONSORTIA_INVITE_PASS: 12,
  CONSORTIA_INVITE_DELETE: 13,
  CONSORTIA_DESCRIPTION_UPDATE: 14,
  CONSORTIA_PLACARD_UPDATE: 15,
  CONSORTIA_BANCHAT_UPDATE: 16,
  CONSORTIA_USER_REMARK_UPDATE: 17,
  CONSORTIA_USER_GRADE_UPDATE: 18,
  CONSORTIA_CHAIRMAN_CHAHGE: 19,
  CONSORTIA_CHAT: 20,
  CONSORTIA_LEVEL_UP: 21,
  CONSORTIA_TASK_RELEASE: 22,
  DONATE: 23,
  CONSORTIA_EQUIP_CONTROL: 24,
  POLL_CANDIDATE: 25,
  SKILL_SOCKET: 26,
  CONSORTION_MAIL: 29,
  BUY_BADGE: 28,
  BOSS_OPEN_CLOSE: 31,
  CONSORTIA_BOSS_INFO: 30,
} as const;
export type ConsortiaPackageType = (typeof ConsortiaPackageType)[keyof typeof ConsortiaPackageType];

/**
 * Game.Server.Packets.EquipType — Game.Server/Packets/EquipType.cs:3
 * Duplicate values (aliases): CONSORTIA_REWORK_NAME = CONSORTIA_CHANGE_NAME_CARD (11993); CHANGE_COLOR_SHELL = COLORCARD (11999); GOLD_CADDY = Gold_Caddy (112101); MEDAL = GIFT (-300); REWORK_NAME = CHANGE_NAME_CARD (11994); SILVER_CADDY = Silver_Caddy (112100); STRENGTH_STONE_NEW = Qiang_SHI (11025)
 */
export const EquipType = {
  ADD_ONE_ATTACK: 10002,
  ADD_TWO_ATTACK: 10001,
  Agility_Get: 11909,
  Angle: 17001,
  AttackBeadLv1: 311199,
  AttackBeadLv2: 311299,
  AttackBeadLv3: 311399,
  AttackBeadLv4: 311499,
  AttributeBeadLv1: 313199,
  AttributeBeadLv2: 313299,
  AttributeBeadLv3: 313399,
  AttributeBeadLv4: 313499,
  BADLUCK_STONE: 11550,
  BATTLE_COMPANION: 112262,
  BEAD_ATTACK: 311500,
  BEAD_ATTACK_IV: 311599,
  BEAD_ATTRIBUTE: 313500,
  BEAD_ATTRIBUTE_IV: 313599,
  BEAD_DEFENSE: 312500,
  BEAD_DEFENSE_IV: 312599,
  BOMB_KING_BLESS: 112222,
  CADDY: 112047,
  CADDY_BAGI: 112054,
  CADDY_BAGII: 112055,
  CADDY_BAGIII: 112056,
  Caddy_Good: 11907,
  CADDY_KEY: 11456,
  Card_Get: 11913,
  CardMaxLv: 30,
  CARDSOUL_BOX: 20150,
  CELEBRATION_BOX: 112255,
  COLORCARD: 11999,
  CONSORTIA_CHANGE_NAME_CARD: 11993,
  CONSORTIA_REWORK_NAME: 11993,
  CHANGE_COLOR_SHELL: 11999,
  CHANGE_NAME_CARD: 11994,
  CHANGE_SEX: 11569,
  CHRISTMAS_TIMER: 201145,
  DefenceBeadLv1: 312199,
  DefenceBeadLv2: 312299,
  DefenceBeadLv3: 312399,
  DefenceBeadLv4: 312499,
  DOUBLE_EXP_CARD: 11998,
  DOUBLE_GESTE_CARD: 11997,
  DOUBLE_PRESTIGE: 11955,
  EASY_TICKET_ID: 200619,
  ExcellentShield: 17004,
  ExllenceAngle: 17005,
  EXP: 11107,
  FLY: 10006,
  FLY_CD: 2,
  FLY_ENERGY: 150,
  FlyAngle: 17000,
  FlyAngleOne: 17100,
  FREE_PROP_CARD: 11995,
  Freeze: 10015,
  GEMSTONE: 100100,
  GND_OPENHOLE_STONE: 11035,
  GOLD_BLESS: 112224,
  GOLD_BOX: 11233,
  Gold_Caddy: 112101,
  GOLD_CADDY: 112101,
  GuildBomb: 10017,
  GIFT: -300,
  HARD_TICKET_ID: 200621,
  Health: 10012,
  HealthGroup: 10009,
  HERO_TICKET_ID: 200622,
  Hiding: 10010,
  HidingGroup: 10011,
  LABYINTH_DOBLE_AWARD: 11916,
  LABYINTH_DOBLE_AWARD_GOODS_ID: 1191601,
  LaserBomdID: 87,
  Level_Try: 11912,
  LUCKY: 11018,
  LUCKYSTAR_ID: 201192,
  MagicBook: 17006,
  MEDAL: -300,
  MY_CARDBOX: 112108,
  MYSTICAL_CARDBOX: 112150,
  NECKLACE_PTETROCHEM_STONE: 11160,
  NORMAL_TICKET_ID: 200620,
  OFFER_PACK_I: 11252,
  OFFER_PACK_II: 11257,
  OFFER_PACK_III: 11258,
  OFFER_PACK_IV: 11259,
  OFFER_PACK_V: 11260,
  Pay_Buff: -1,
  PCELEBRATION_KEY: 11658,
  PIAN_OPENHOLE_STONE: 11034,
  PREVENT_KICK: 11996,
  Qiang_SHI: 11025,
  ReHealth: 11910,
  REWORK_NAME: 11994,
  ROULETTE_BOX: 112019,
  ROULETTE_KEY: 11444,
  Save_Life: 11908,
  SILVER_BLESS: 112223,
  Silver_Caddy: 112100,
  SILVER_CADDY: 112100,
  SKY_OPENHOLE_STONE: 11036,
  STRENGTH_GIFT_BAG: 112051100,
  STRENGTH_STONE_NEW: 11025,
  STRENGTH_STONE4: 11023,
  SURPRISE_ROULETTE_BOX: 190000,
  SURPRISE_ROULETTE_KEY: 190001,
  SYMBLE: 11020,
  T_ALL_PROP: 10200,
  T_BBUGLE: 11102,
  T_CBUGLE: 11100,
  T_SBUGLE: 11101,
  TEXP_LV_II: 40002,
  THREEKILL: 10003,
  Train_Good: 11911,
  TRANSFER_PROP: 34101,
  TrueAngle: 17002,
  TrueAngle2: 17102,
  TrueShield: 17003,
  VIP_COIN: 112109,
  VIP_GIFT_BAG: 112164,
  VIPCARD: 11992,
  VIPCARD_TEST: 11991,
  VIPCARD_TEST3: 11914,
  WEDDING_RING: 9022,
  WISHBEAD_AGILE: 11562,
  WISHBEAD_ATTACK: 11560,
  WISHBEAD_DEFENSE: 11561,
  WishKingBlessing: 17200,
  EXALT_ROCK: 11150,
} as const;
export type EquipType = (typeof EquipType)[keyof typeof EquipType];

/**
 * Game.Server.Packets.FarmPackageType — Game.Server/Packets/FarmPackageType.cs:3
 */
export const FarmPackageType = {
  ENTER_FARM: 1,
  GROW_FIELD: 2,
  ACCELERATE_FIELD: 3,
  GAIN_FIELD: 4,
  PAY_FIELD: 6,
  COMPOSE_FOOD: 5,
  FRUSH_FIELD: 0,
  KILLCROP_FIELD: 7,
  HELPER_PAY_FIELD: 8,
  HELPER_SWITCH_FIELD: 9,
  EXIT_FARM: 16,
  FARM_LAND_INFO: 17,
  FRAM_GROP_FASTFORWARD: 18,
  BUY_PET_EXP_ITEM: 19,
  FARM_GIFTPACKS: 20,
  FARM_POULTYRLEVEL: 21,
  FARM_UPGRADEINITTREE: 22,
  FARM_CALLPOULTYR: 23,
  FARM_POULTYWAKE: 24,
  FARM_CONDENSER: 25,
  FARM_WATER: 32,
  FARM_POULTYRFEED: 33,
} as const;
export type FarmPackageType = (typeof FarmPackageType)[keyof typeof FarmPackageType];

/**
 * Game.Server.Packets.FightSpiritPackageType — Game.Server/Packets/FightSpiritPackageType.cs:3
 */
export const FightSpiritPackageType = {
  FIGHT_SPIRIT_INIT: 1,
  PLAYER_FIGHT_SPIRIT_UP: 2,
  FIGHT_SPIRIT_LEVELUP: 3,
  REFIGHTSPIRITNUM_CHANGE: 4,
} as const;
export type FightSpiritPackageType = (typeof FightSpiritPackageType)[keyof typeof FightSpiritPackageType];

/**
 * Game.Server.Packets.GameRoomPackageType — Game.Server/Packets/GameRoomPackageType.cs:3
 */
export const GameRoomPackageType = {
  GAME_ROOM_CREATE: 0,
  GAME_ROOM_LOGIN: 1,
  GAME_ROOM_SETUP_CHANGE: 2,
  GAME_ROOM_KICK: 3,
  GAME_ROOM_ADDPLAYER: 4,
  GAME_ROOM_REMOVEPLAYER: 5,
  GAME_TEAM: 6,
  GAME_START: 7,
  ROOMLIST_UPDATE: 9,
  GAME_ROOM_UPDATE_PLACE: 10,
  GAME_PICKUP_CANCEL: 11,
  GAME_PICKUP_STYLE: 12,
  GAME_PICKUP_WAIT: 13,
  ROOM_PASS: 14,
  GAME_PLAYER_STATE_CHANGE: 15,
  GAME_ROOM_FULL: 17,
  PASSED_WARRIORSARENA_10: 34,
  No_WARRIORSARENA_TICKET: 35,
  LAST_MISSION_FOR_WARRIORSARENA: 33,
  SINGLE_ROOM_BEGIN: 18,
  FAST_INVITE_CALL: 19,
  GAME_ENERGY_NOT_ENOUGH: 20,
} as const;
export type GameRoomPackageType = (typeof GameRoomPackageType)[keyof typeof GameRoomPackageType];

/**
 * GuildMemberWeekPackageType — Game.Server/Packets/GuildMemberWeekPackageType.cs
 * Duplicate values (aliases): ENTER_GAME = PLAYERTOP10 (8); CLOSE = ADDPOINTBOOK10 (9); SEND_ADDRUNKING = ADDPOINTBOOKRECORD (10)
 */
export const GuildMemberWeekPackageType = {
  OPEN: 7,
  PLAYERTOP10: 8,
  ADDPOINTBOOK10: 9,
  GET_MYRUNKING: 11,
  ADDPOINTBOOKRECORD: 10,
  UPADDPOINTBOOK: 12,
  SHOWACTIVITYEND: 13,
  ENTER_GAME: 8,
  CLOSE: 9,
  SEND_ADDRUNKING: 10,
  FINISHACTIVITY: 53,
  SHOWRUNKING: 54,
} as const;
export type GuildMemberWeekPackageType = (typeof GuildMemberWeekPackageType)[keyof typeof GuildMemberWeekPackageType];

/**
 * Game.Server.Packets.IMPackageType — Game.Server/Packets/IMPackageType.cs:3
 */
export const IMPackageType = {
  ADD_CUSTOM_FRIENDS: 208,
  FRIEND_ADD: 160,
  FRIEND_REMOVE: 161,
  FRIEND_RESPONSE: 166,
  FRIEND_STATE: 165,
  FRIEND_UPDATE: 162,
  ONE_ON_ONE_TALK: 51,
  ONS_EQUIP: 45,
  SAME_CITY_FRIEND: 164,
} as const;
export type IMPackageType = (typeof IMPackageType)[keyof typeof IMPackageType];

/**
 * Game.Server.Packets.LabyrinthPackageType — Game.Server/Packets/LabyrinthPackageType.cs:3
 */
export const LabyrinthPackageType = {
  DOUBLE_REWARD: 1,
  REQUEST_UPDATE: 2,
  CLEAN_OUT: 3,
  SPEEDED_UP_CLEAN_OUT: 4,
  STOP_CLEAN_OUT: 5,
  RESET_LABYRINTH: 6,
  PUSH_CLEAN_OUT_INFO: 7,
  CLEAN_OUT_COMPLETE: 8,
  TRY_AGAIN: 9,
} as const;
export type LabyrinthPackageType = (typeof LabyrinthPackageType)[keyof typeof LabyrinthPackageType];

/**
 * Game.Server.Packets.LightRoadPackageType — Game.Server/Packets/LightRoadPackageType.cs:3
 * Duplicate values (aliases): ENTER_GAME = ACTIVATIONTYPE (64); BECHOOSE_POINT = UPTHINGSMESSAGE (66)
 */
export const LightRoadPackageType = {
  CLOSEMAINFRAME: 1,
  OPENHELPRAME: 2,
  UPMAINFRAMEDATA: 3,
  ACTIVATIONTYPE: 64,
  INACVATION: 65,
  UPTHINGSMESSAGE: 66,
  ENTER_GAME: 64,
  BECHOOSE_POINT: 66,
} as const;
export type LightRoadPackageType = (typeof LightRoadPackageType)[keyof typeof LightRoadPackageType];

/**
 * Game.Server.Packets.NewChickenBoxPackageType — Game.Server/Packets/NewChickenBoxPackageType.cs:3
 */
export const NewChickenBoxPackageType = {
  ENTERCHICKENVIEW: 10,
  USEEAGLEEYE: 11,
  TAKEOVERCARD: 13,
  FLUSHCHICKENVIEW: 14,
  CLICKSTARTBNT: 15,
  AllITEMSHOW: 12,
  CHICKENBOXOPEN: 1,
  CHICKENBOXCLOSE: 2,
  GETITEMLIST: 3,
  CANCLICKCARD: 5,
  TACKOVERCARD: 4,
  EAGLEEYE: 7,
  OVERSHOWITEMS: 6,
  ALL_GOODS_INFO: 21,
  REWARD_RECORD: 22,
  GOODS_INFO: 23,
  PLAY_REWARD_INFO: 24,
  ACTIVITY_OPEN: 25,
  ACTIVITY_END: 26,
  AWARD_RANK: 27,
  ENTER_GAME: 31,
  CLOSE_GAME: 32,
  START_TURN: 33,
  TURN_COMPLETE: 34,
} as const;
export type NewChickenBoxPackageType = (typeof NewChickenBoxPackageType)[keyof typeof NewChickenBoxPackageType];

/**
 * Game.Server.Packets.NoviceActiveType — Game.Server/Packets/NoviceActiveType.cs:3
 */
export const NoviceActiveType = {
  GRADE_UP_ACTIVE: 1,
  STRENGTHEN_WEAPON_ACTIVE: 2,
  USE_MONEY_ACTIVE: 3,
  RECHANGE_MONEY_ACTIVE: 4,
  UPGRADE_VIP_ACTIVE: 8,
  UPDATE_FIGHTPOWER: 9,
  USE_MONEY_ACTIVE_OFWEEK: 5,
  RECHANGE_MONEY_ACTIVE_OFWEEK: 6,
} as const;
export type NoviceActiveType = (typeof NoviceActiveType)[keyof typeof NoviceActiveType];

/**
 * PetPackageType — Game.Server/Packets/PetPackageType.cs
 */
export const PetPackageType = {
  UPDATE_PET: 1,
  MOVE_PETBAG: 3,
  FEED_PET: 4,
  EQUIP_PET_SKILL: 7,
  RENAME_PET: 9,
  RELEASE_PET: 8,
  ADOPT_PET: 6,
  REFRESH_PET: 5,
  PAY_SKILL: 16,
  FIGHT_PET: 17,
  ADD_PET: 2,
  REVER_PET: 18,
  ADD_PET_EQUIP: 20,
  DEL_PET_EQUIP: 21,
  PET_RISINGSTAR: 22,
  PET_EVOLUTION: 23,
  PET_FORMINFO: 24,
  PET_FOLLOW: 25,
  PET_BREAK: 31,
  PET_WAKE: 32,
  EAT_PETS: 33,
  PET_BREAK_INFO: 34,
  PET_TEMPORARY_CARD: 35,
  PET_FOLD_EQUIPS: 36,
  PET_AWAKEN: 37,
  PET_EQUIP_AWAKENINFO: 38,
  PET_PURIFICAR: 40,
  PET_SELAR: 46,
  PET_DESSELAR: 47,
  PET_SELAR_FLASH: 48,
  PET_DESSELAR_FLASH: 49,
} as const;
export type PetPackageType = (typeof PetPackageType)[keyof typeof PetPackageType];

/**
 * Game.Server.Packets.RuneType — Game.Server/Packets/RuneType.cs:3
 */
export const RuneType = {
  RUNE_LOCK: 4,
  RUNE_MOVEPLACE: 1,
  RUNE_OPEN_HOLE: 5,
  RUNE_OPENPACKAGE: 3,
  RUNE_SENDINFO_TOCLIENT: 6,
  RUNE_UPGRADE: 2,
} as const;
export type RuneType = (typeof RuneType)[keyof typeof RuneType];

/**
 * Game.Server.Packets.WorldBossGamePackageType — Game.Server/Packets/WorldBossGamePackageType.cs:6
 */
export const WorldBossGamePackageType = {
  ENTER_WORLDBOSSROOM: 32,
  MOVE: 35,
  LEAVE_ROOM: 33,
  STAUTS: 36,
  ADDPLAYERS: 34,
  REQUEST_REVIVE: 37,
  BUFF_BUY: 38,
} as const;
export type WorldBossGamePackageType = (typeof WorldBossGamePackageType)[keyof typeof WorldBossGamePackageType];

/**
 * WorldBossPackageType — Game.Server/Packets/WorldBossPackageType.cs
 */
export const WorldBossPackageType = {
  OPEN: 0,
  OVER: 1,
  CANENTER: 2,
  MOVE: 6,
  ENTER: 3,
  WORLDBOSS_EXIT: 4,
  WORLDBOSS_PLAYERSTAUTSUPDATE: 7,
  WORLDBOSS_FIGHTOVER: 8,
  WORLDBOSS_ROOM_CLOSE: 9,
  WORLDBOSS_BLOOD_UPDATE: 5,
  WORLDBOSS_RANKING: 10,
  WORLDBOSS_PLAYER_REVIVE: 11,
  WORLDBOSS_BUYBUFF: 12,
  WORLDBOSS_PRIVATE_INFO: 22,
} as const;
export type WorldBossPackageType = (typeof WorldBossPackageType)[keyof typeof WorldBossPackageType];

/**
 * Game.Server.Packets.eDutyRightType — Game.Server/Packets/eDutyRightType.cs:3
 */
export const eDutyRightType = {
  _1_Ratify: 1,
  _10_ChangeMan: 512,
  _11_Disband: 1024,
  _12_UpGrade: 2048,
  _13_Exit: 4096,
  _2_Invite: 2,
  _3_BanChat: 4,
  _4_Notice: 8,
  _5_Enounce: 16,
  _6_Expel: 32,
  _7_Diplomatism: 64,
  _8_Manage: 128,
  _9_ConsortiaUp: 256,
} as const;
export type eDutyRightType = (typeof eDutyRightType)[keyof typeof eDutyRightType];

/**
 * Game.Server.Packets.eLittleGamePackageInType — Game.Server/Packets/eLittleGamePackageInType.cs:3
 */
export const eLittleGamePackageInType = {
  WORLD_LIST: 1,
  START_LOAD: 2,
  GAME_START: 3,
  SETCLOCK: 5,
  PONG: 6,
  NET_DELAY: 7,
  ADD_SPRITE: 16,
  REMOVE_SPRITE: 17,
  KICK_PLAYE: 18,
  MOVE: 32,
  UPDATE_POS: 33,
  GETSCORE: 49,
  ADD_OBJECT: 64,
  REMOVE_OBJECT: 65,
  INVOKE_OBJECT: 66,
  UPDATELIVINGSPROPERTY: 80,
  DoMovie: 81,
  DoAction: 96,
} as const;
export type eLittleGamePackageInType = (typeof eLittleGamePackageInType)[keyof typeof eLittleGamePackageInType];

/**
 * Game.Server.Packets.eMailRespose — Game.Server/Packets/eMailRespose.cs:3
 */
export const eMailRespose = {
  Receiver: 1,
  Send: 2,
  ReceAndSend: 3,
  Gift: 4,
} as const;
export type eMailRespose = (typeof eMailRespose)[keyof typeof eMailRespose];

/**
 * Game.Server.Packets.eMailType — Game.Server/Packets/eMailType.cs:3
 */
export const eMailType = {
  Active: 52,
  AdvertMail: 58,
  AuctionFail: 3,
  AuctionSuccess: 2,
  BidFail: 5,
  BidSuccess: 4,
  BuyItem: 8,
  Common: 1,
  ConsortionEmail: 59,
  ConsortionSkillMail: 62,
  DailyAward: 15,
  Default: 0,
  FriendBrithday: 60,
  GiftGuide: 55,
  ItemOverdue: 9,
  Manage: 51,
  Marry: 14,
  MyseftBrithday: 61,
  OpenUpArk: 12,
  Payment: 101,
  PaymentCancel: 7,
  PaymentFinish: 11,
  PresentItem: 10,
  ReturnPayment: 6,
  StoreCanel: 13,
} as const;
export type eMailType = (typeof eMailType)[keyof typeof eMailType];

/**
 * Game.Server.Packets.eMarryApplyType — Game.Server/Packets/eMarryApplyType.cs:3
 */
export const eMarryApplyType = {
  Default: 0,
  Courtship: 1,
  Accept: 2,
  Divorce: 3,
} as const;
export type eMarryApplyType = (typeof eMarryApplyType)[keyof typeof eMarryApplyType];

/**
 * eMessageType — Game.Server/Packets/eMessageType.cs
 * Duplicate values (aliases): ERROR = BIGBUGLE_NOTICE (1); Normal = GM_NOTICE (0); SYS_NOTICE = ChatERROR (3); SYS_TIP_NOTICE = ChatNormal (2)
 */
export const eMessageType = {
  ALERT: 4,
  BIGBUGLE_NOTICE: 1,
  CONSORTIA_NOTICE: 8,
  CROSS_NOTICE: 12,
  ChatERROR: 3,
  ChatNormal: 2,
  DailyAward: 5,
  Defence: 6,
  ERROR: 1,
  GM_NOTICE: 0,
  Normal: 0,
  SYS_NOTICE: 3,
  SYS_TIP_NOTICE: 2,
} as const;
export type eMessageType = (typeof eMessageType)[keyof typeof eMessageType];

/**
 * Game.Server.Packets.ePackageType — Game.Server/Packets/ePackageType.cs:3
 * Duplicate values (aliases): SCENE_STATE = LOTTERY_AWARD (251); QQTIPS_GET_INFO = TEXP (99); MARRY_ROOM_STATE = USE_CHANGE_SEX (252); CLIENT_LOG = VIP_LEVELUP_AWARDS (8); CHANGE_STATE = COLLECTINFO (32); GET_DYNAMIC = UPDATE_HOTPOINT (39); DELETE_GOODS = LEAGUE_START_NOTICE (42); ROOM_SAVE_OBJECT = LEFT_GUN_ROULETTE_SOCKET (128); SCENE_ADD_USER = GET_PLAYER_CARD (18); GAME_CHANGE_MAP = CARD_LOTTERY (104); BUY_GIFTBAG = UPDATE_COUPONS (46); UNCHAIN_EQUIP = SYSTEM_LUCKYNUM (47); GRID_GOODS = OPTION_UPDATE (64); GAME_TAKE_OUT = WISHBEADEQUIP (106); EQUIP_CHANGE = PROP_USE (66); ITEM_OBTAIN = C_BUGLE (73); ITEM_REFINERY = GAME_CAPTAIN_CHOICE (110); ITEM_REFINERY_PREVIEW = GAME_CAPTAIN_AFFIRM (111); CONSORTIA_RESPONSE = LEFT_GUN_ROULETTE_SOCKET (128); CID_CHECK = GAME_VISITOR_DATA (224); AMARRYINFO_REFRESH = GOTO_CARD_LOTTERY (239); HOTSPRING_CMD_B = EDITION_ERROR (12); GET_TIME_BOX = REPAIR_GOODS (53); LOTTERY_GET_ITEM = PICC (30); ANSWERBOX_QUESTIN = GOODS_EXCHANGE (31); REQUEST_UPDATE = ENTHRALL_SWITCH (225); USE_LOG = FEEDBACK_REPLY (213); LOAD_RESOURCE = FRIEND_BRITHDAY (223); ACTIVITY_SYSTEM = LIGHTROAD_SYSTEM (145)
 */
export const ePackageType = {
  LABYRINTH: 131,
  ITEM_ADVANCE: 138,
  USE_CHANGE_SEX: 252,
  OPTION_CHANGE: 158,
  PET: 68,
  INVITE_FRIEND: 107,
  FIRSTRECHARGE: 259,
  NOVICEACTIVITY: 258,
  VIP_LEVELUP_AWARDS: 8,
  GOTO_CARD_LOTTERY: 239,
  CAN_CARD_LOTTERY: 93,
  LOTTERY_AWARD: 251,
  LUCK_LOTTERY: 105,
  CARD_LOTTERY: 104,
  UPDATE_SHOP: 109,
  WISHBEADEQUIP: 106,
  LEFT_GUN_ROULETTE_COMPLETTE: 130,
  LEFT_GUN_ROULETTE_SOCKET: 128,
  LEFT_GUN_ROULETTE_START: 163,
  LEFT_GUN_ROULETTE: 137,
  ELITEGAME: 162,
  PICC: 30,
  FARM: 81,
  OPEN_ALL_CARDBOX: 204,
  LITTLEGAME_ACTIVED: 80,
  IM_CMD: 160,
  TEXP: 99,
  GOODS_EXCHANGE: 31,
  COLLECTINFO: 32,
  DAILYRECORD: 103,
  FRIEND_BRITHDAY: 223,
  CHAT_FILTERING_FRIENDS_SHARE: 17,
  GET_PLAYER_CARD: 18,
  OPTION_UPDATE: 64,
  CARD_RESET: 196,
  CARDS_DATA: 216,
  PROP_USE: 66,
  LEAGUE_START_NOTICE: 42,
  SYSTEM_LUCKYNUM: 47,
  USER_LUCKYNUM: 161,
  WEEKLY_CLICK_CNT: 219,
  USER_ANSWER: 15,
  BAG_LOCKED: 25,
  MARRY_ROOM_CREATE: 241,
  MARRY_ROOM_LOGIN: 242,
  MARRY_SCENE_LOGIN: 240,
  PLAYER_ENTER_MARRY_ROOM: 243,
  PLAYER_EXIT_MARRY_ROOM: 244,
  MARRY_APPLY: 247,
  MARRY_APPLY_REPLY: 250,
  DIVORCE_APPLY: 248,
  MARRY_STATUS: 246,
  SCENE_STATE: 251,
  QQTIPS_GET_INFO: 99,
  EDICTUM_GET_SERVION: 75,
  MARRY_ROOM_STATE: 252,
  MARRY_ROOM_INFO_UPDATE: 253,
  MARRYPROP_GET: 234,
  MARRY_ROOM_UPDATE: 255,
  MARRY_ROOM_DISPOSE: 254,
  MARRY_CMD: 249,
  CHURCH_MOVIE_OVER: 167,
  MARRY_SCENE_CHANGE: 233,
  CLIENT_LOG: 8,
  SCENE_CHAT: 19,
  SCENE_FACE: 20,
  SCENE_CHANNEL_CHANGE: 24,
  CHANGE_STATE: 32,
  CHANGE_NICKNAME: 33,
  AC_ACTION: 35,
  SYNCH_ACTION: 36,
  CHAT_PERSONAL: 37,
  UPDATE_PRIVATE_INFO: 38,
  UPDATE_HOTPOINT: 39,
  GET_DYNAMIC: 39,
  SNS_MSG_RECEIVE: 40,
  SAVE_STYLE: 41,
  DELETE_GOODS: 42,
  CONSORTIA_MAIL_MESSAGE: 43,
  ROOM_SAVE_OBJECT: 128,
  GAME_VISITOR_DATA: 224,
  LOGIN: 1,
  DAILY_AWARD: 13,
  GET_SIGNAWARD: 90,
  GAME_ROOM: 94,
  SCENE_ADD_USER: 18,
  KIT_USER: 2,
  SCENE_LOGIN: 16,
  GAME_CMD: 91,
  GAME_CHANGE_MAP: 104,
  SCENE_REMOVE_USER: 21,
  CHANGE_PLACE_GOODS: 49,
  REClAIM_GOODS: 127,
  CHANGE_PLACE_GOODS_ALL: 124,
  SEll_GOODS: 48,
  USER_RANK: 34,
  FIGHT_NPC: 50,
  UPDATE_GOODS: 51,
  UPDATE_COUPONS: 46,
  ITEM_STORE: 79,
  BUY_GOODS: 44,
  BUY_QUICK_GOLDBOX: 126,
  BUY_GIFTBAG: 46,
  CHAIN_EQUIP: 52,
  UNCHAIN_EQUIP: 47,
  REPAIR_GOODS: 53,
  DELETE_MAIL: 112,
  GET_MAIL_ATTACHMENT: 113,
  UPDATE_MAIL: 114,
  UPDATE_NEW_MAIL: 115,
  SEND_MAIL: 116,
  MAIL_RESPONSE: 117,
  MAIL_CANCEL: 118,
  PROP_BUY: 54,
  PROP_SELL: 55,
  PROP_CHAIN: 56,
  GOODS_PRESENT: 57,
  GOODS_COUNT: 168,
  GRID_GOODS: 64,
  GRID_PROP: 65,
  UPDATE_PLAYER_INFO: 67,
  GAME_TAKE_OUT: 106,
  EQUIP_CHANGE: 66,
  PING: 4,
  NETWORK: 6,
  GAME_TAKE_TEMP: 108,
  RSAKEY: 7,
  SYS_MESSAGE: 3,
  ITEM_COMPOSE: 58,
  ITEM_STRENGTHEN: 59,
  ITEM_TRANSFER: 61,
  GAME_CAPTAIN_CHOICE: 110,
  GAME_CAPTAIN_AFFIRM: 111,
  SCENE_USERS_LIST: 69,
  GAME_INVITE: 70,
  S_BUGLE: 71,
  B_BUGLE: 72,
  C_BUGLE: 73,
  DEFY_AFFICHE: 123,
  ITEM_HIDE: 60,
  ITEM_OBTAIN: 73,
  QUEST_ADD: 176,
  QUEST_REMOVE: 177,
  QUEST_UPDATE: 178,
  QUEST_FINISH: 179,
  QUSET_OBTAIN: 180,
  QUEST_CHECK: 181,
  ITEM_CONTINUE: 62,
  SYS_DATE: 5,
  ITEM_EQUIP: 74,
  MATE_ONLINE_TIME: 85,
  SYS_NOTICE: 10,
  ITEM_OPENUP: 63,
  ACTIVE_PULLDOWN: 11,
  EDITION_ERROR: 12,
  ITEM_FUSION: 78,
  EQUIP_RECYCLE_ITEM: 222,
  ITEM_FUSION_PREVIEW: 76,
  ITEM_REFINERY: 110,
  ITEM_REFINERY_PREVIEW: 111,
  ITEM_INLAY: 121,
  ITEM_EMBED_BACKOUT: 125,
  OPEN_FIVE_SIX_HOLE: 217,
  ITEM_TREND: 120,
  CLEAR_STORE_BAG: 122,
  ITEM_OVERDUE: 77,
  AUCTION_ADD: 192,
  AUCTION_UPDATE: 193,
  AUCTION_DELETE: 194,
  AUCTION_REFRESH: 195,
  CHECK_CODE: 200,
  CONSORTIA_CMD: 129,
  CONSORTIA_RESPONSE: 128,
  CID_CHECK: 224,
  ENTHRALL_LIGHT: 227,
  ENTHRALL_SWITCH: 225,
  CID_INFO_VALID: 226,
  BUFF_INFO: 0,
  USE_COLOR_CARD: 182,
  CARD_USE: 183,
  USE_CHANGE_COLOR_SHELL: 205,
  CHANGE_COLOR_OVER_DUE: 206,
  USE_REWORK_NAME: 171,
  USE_CONSORTIA_REWORK_NAME: 188,
  BUFF_ADD: 184,
  BUFF_UPDATE: 185,
  BUFF_OBTAIN: 186,
  MARRYINFO_GET: 235,
  MARRYINFO_ADD: 236,
  MARRYINFO_UPDATE: 237,
  MARRYINFO_DELETE: 238,
  AMARRYINFO_REFRESH: 239,
  LINKREQUEST_GOODS: 119,
  GET_ITEM_MESS: 14,
  SAVE_DB: 172,
  LITTLEGAME_COMMAND: 166,
  HOTSPRING_CMD: 191,
  HOTSPRING_CMD_B: 12,
  HOTSPRING_ENTER: 187,
  HOTSPRING_ROOM_CREATE: 175,
  HOTSPRING_ROOM_REMOVE: 174,
  HOTSPRING_ROOM_ADD_OR_UPDATE: 173,
  HOTSPRING_ROOM_LIST_GET: 197,
  HOTSPRING_ROOM_QUICK_ENTER: 190,
  HOTSPRING_ROOM_ENTER: 202,
  HOTSPRING_ROOM_ENTER_VIEW: 201,
  HOTSPRING_ROOM_PLAYER_ADD: 198,
  HOTSPRING_ROOM_PLAYER_REMOVE: 169,
  HOTSPRING_ROOM_PLAYER_REMOVE_NOTICE: 199,
  HOTSPRING_ROOM_ENTER_CONFIRM: 212,
  GET_TIME_BOX: 53,
  ACHIEVEMENT_FINISH: 230,
  ACHIEVEMENT_UPDATE: 229,
  ACHIEVEMENT_INIT: 228,
  ACHIEVEMENTDATA_INIT: 231,
  USER_CHANGE_RANK: 189,
  LOOKUP_EFFORT: 203,
  LOTTERY_OPEN_BOX: 26,
  LOTTERY_RANDOM_SELECT: 27,
  LOTTERY_FINISH: 28,
  LOTTERY_ALTERNATE_LIST: 29,
  LOTTERY_GET_ITEM: 30,
  CADDY_SELL_ALL_GOODS: 232,
  CADDY_GET_AWARDS: 245,
  CADDY_GET_BADLUCK: 45,
  FEEDBACK_REPLY: 213,
  QUESTION_REPLY: 89,
  ANSWERBOX_QUESTIN: 31,
  REQUEST_UPDATE: 225,
  VIP_RENEWAL: 92,
  USE_LOG: 213,
  LOAD_RESOURCE: 223,
  USER_GET_GIFTS: 218,
  USER_SEND_GIFTS: 221,
  USER_UPDATE_GIFT: 220,
  USER_RELOAD_GIFT: 214,
  NEWCHICKENBOX_SYS: 87,
  WORLDBOSS_CMD: 102,
  RING_STATION: 404,
  ACTIVITY_PACKAGE: 84,
  LATENT_ENERGY: 133,
  FIGHT_SPIRIT: 209,
  LIGHTROAD_SYSTEM: 145,
  ACCUMULATIVELOGIN_AWARD: 338,
  AVATAR_COLLECTION: 402,
  ACTIVITY_SYSTEM: 145,
  BAGLOCK_PWD: 403,
  TOTEM: 136,
  NECKLACE_STRENGTH: 95,
  HONOR_UP_COUNT: 96,
  NEWTITLE_CARD: 265,
} as const;
export type ePackageType = (typeof ePackageType)[keyof typeof ePackageType];

/**
 * Game.Server.Packets.ePlayerState — Game.Server/Packets/ePlayerState.cs:3
 * Duplicate values (aliases): Dungeon = Away (2); Offline = Auto (0); Online = Manual (1); RoomList = Manual (1)
 */
export const ePlayerState = {
  Auto: 0,
  Away: 2,
  Busy: 3,
  CompleteLoad: 13,
  Dungeon: 2,
  Manual: 1,
  No_Distrub: 5,
  Offline: 0,
  Online: 1,
  RoomList: 1,
  Shoping: 4,
} as const;
export type ePlayerState = (typeof ePlayerState)[keyof typeof ePlayerState];

/**
 * Game.Server.Packets.eRoomPackageType — Game.Server/Packets/eRoomPackageType.cs:3
 */
export const eRoomPackageType = {
  GAME_ROOM_CREATE: 0,
  GAME_ROOM_LOGIN: 1,
  GAME_ROOM_SETUP_CHANGE: 2,
  GAME_ROOM_KICK: 3,
  GAME_ROOM_ADDPLAYER: 4,
  GAME_ROOM_REMOVEPLAYER: 5,
  GAME_TEAM: 6,
  GAME_START: 7,
  ROOMLIST_UPDATE: 9,
  GAME_ROOM_UPDATE_PLACE: 10,
  GAME_PICKUP_CANCEL: 11,
  GAME_PICKUP_STYLE: 12,
  GAME_PICKUP_WAIT: 13,
  ROOM_PASS: 14,
  GAME_PLAYER_STATE_CHANGE: 15,
} as const;
export type eRoomPackageType = (typeof eRoomPackageType)[keyof typeof eRoomPackageType];

/**
 * Game.Server.Packets.eSocketType — Game.Server/Packets/eSocketType.cs:3
 */
export const eSocketType = {
  SAP_XEP: 124,
  GIFT_STRENGTHEN: 46,
  VIP: 92,
} as const;
export type eSocketType = (typeof eSocketType)[keyof typeof eSocketType];

/**
 * Game.Server.Packets.RingStationPackageType — Game.Server/RingStation/RingStationPackageType.cs:3
 */
export const RingStationPackageType = {
  RINGSTATION_VIEWINFO: 1,
  RINGSTATION_BUYCOUNTORTIME: 2,
  RINGSTATION_ARMORY: 3,
  RINGSTATION_NEWBATTLEFIELD: 4,
  RINGSTATION_CHALLENGE: 5,
  RINGSTATION_FIGHTFLAG: 6,
  RINGSTATION_SENDSIGNMSG: 7,
  RINGSTATION_GETREWARD: 8,
  LANDERSAWARD_RECEIVE: 48,
  LANDERSAWARD_GET: 49,
  DUNGEON_UPDATEEXP: 64,
} as const;
export type RingStationPackageType = (typeof RingStationPackageType)[keyof typeof RingStationPackageType];

/**
 * Game.Server.RingStation.RoomGamePkg.GameCmdType — Game.Server/RingStation/RoomGamePkg/GameCmdType.cs:3
 */
export const GameCmdType = {
  GAME_CMD: 91,
  SYS_MESSAGE: 3,
  GAME_ROOM_REMOVEPLAYER: 5,
  GAME_ROOM: 94,
  GAME_MISSION_START: 82,
  BUFF_OBTAIN: 186,
  DISCONNECT: 83,
  CHAT_MSG: 19,
} as const;
export type GameCmdType = (typeof GameCmdType)[keyof typeof GameCmdType];

/**
 * Game.Server.SceneMarryRooms.MarryCmdType — Game.Server/SceneMarryRooms/MarryCmdType.cs:3
 * Duplicate values (aliases): INVITE = CLIENTCONFIRM (4); MOVE = BEGINSENDGIFT (1)
 */
export const MarryCmdType = {
  BEGINSENDGIFT: 1,
  CLIENTCONFIRM: 4,
  CONTINUATION: 3,
  FORBID: 8,
  GUNSALUTE: 11,
  HYMENEAL: 2,
  HYMENEAL_STOP: 9,
  INVITE: 4,
  KICK: 7,
  LARGESS: 5,
  MARRYROOMSENDGIFT: 12,
  MOVE: 1,
  POSITION: 10,
  USEFIRECRACKERS: 6,
} as const;
export type MarryCmdType = (typeof MarryCmdType)[keyof typeof MarryCmdType];

