// AUTO-GENERATED by scripts/extract-codes.ts from vendor/DDTank41 (index). DO NOT EDIT.
// Regenerate: pnpm --filter @ddt/protocol extract-codes
/* eslint-disable */

export * as Bussiness from "./bussiness.js";
export * as CenterServer from "./center-server.js";
export * as GameLogic from "./game-logic.js";
export * as GameServer from "./game-server.js";
export * as Client from "./client.js";

/** All names that map to `value` in a generated code object (several when the C# enum has aliases). */
export function codeNames(codes: Readonly<Record<string, number>>, value: number): string[] {
  return Object.keys(codes).filter((k) => codes[k] === value);
}

/** First name for `value`, or `undefined`. */
export function codeName(codes: Readonly<Record<string, number>>, value: number): string | undefined {
  for (const k in codes) if (codes[k] === value) return k;
  return undefined;
}
